### ISSUE TITLE
Allow NPOT textures in webgl2 renderer

### ISSUE THREAD

**Issue by geNAZt** [melonjs/melonJS#1001]
Accordig to WebGL 2 spec: https://www.khronos.org/registry/webgl/specs/latest/2.0/#4.1.3 NPOT textures are allowed inside the renderer. Unlike WebGL 1 where they are forbidden.

It seems that currently all NPOT textures are not used in the renderer for patterns. Would it make sense to change that behaviour for WebGL 2?

**Comment by obiot** [comment]
👍 WebGL2 support has been added to the latest 8.x branch. It's currently not enabled by default as there are still some minor issues to iron out with complex shape drawing, but if don't need/use that (which I assume is your case based on your example),  you can use the link to the build I gave you in the other ticket, just be sure to add `preferWebGL1 : false` to the video options to enable WebGL2.

Let me know if it works

**Comment by obiot** [comment]
after double-checking, I did indeed forgot one thing here :
https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L263-L269

**Comment by obiot** [comment]
the first check should be replace by :
```javascript
if (me.video.renderer.WebGLVersion === 1 && (!me.Math.isPowerOfTwo(width) || !me.Math.isPowerOfTwo(height))) {
```

**Comment by geNAZt** [comment]
No its fine, the other issue is far more important for me. I will try this feature out when its built in :) Take your time

**Comment by obiot** [comment]
this one is done, tested by resizing the background in the platformer example to a random NPOT size, and fully working ! thanks for the tip/reminder on this one :)

**Comment by obiot** [comment]
as a final reminder, WebGL2 is still as of today (8.0 version) disabled by default, `preferWebGL1 : false` can be used to manually force it.
