### ISSUE TITLE
Animations in TMX files are mapped to the wrong tile id

### ISSUE THREAD

**Issue by alcor** [melonjs/melonJS#1005]
#### OS platform / Browser  
Mac OS 10.14 / Chrome 83
 
#### melonJS version 
7.1.1 and top of tree

#### Bug description  
When animations are parsed in the latest version of Tiled files, they are assigned to an index based on their position in the "tiles" array, and not to the ID that is specified in their definition.

#### Steps to reproduce the bug
Render the attached map and sprites to see this
[MapSample.zip](https://github.com/melonjs/melonJS/files/4888775/MapSample.zip)

The bug appears to be related to part of me.TMXTileset:
https://github.com/melonjs/melonJS/blob/7131fd98e3a245688156303077dab23d55abf2ef/src/level/tiled/TMXTileset.js#L90

Map in Tiled:

<img width="540" alt="Map as rendered by Tiled" src="https://user-images.githubusercontent.com/563095/86882019-6206be00-c0a4-11ea-8e4a-40ecf51438e1.png">

Map in MelonJS
<img width="610" alt="Screen Shot 2020-07-07 at 10 50 52 PM" src="https://user-images.githubusercontent.com/563095/86882543-44862400-c0a5-11ea-8a25-3c76ee96d7e8.png">

In this case Tile ID 4, which is a white corner tile, is overwritten by what should be animation associated with Tile ID 66
If you correct this line to `this.animations.set(**tiles[i].id** + this.firstgid`, it behaves correctly with regard to the tiles.

<img width="610" alt="Map as rendered by Melonjs - After Fix" src="https://user-images.githubusercontent.com/563095/86882587-5798f400-c0a5-11ea-943e-cc3a8abbcc00.png">

Note that the corner, white assets are correct now. There is a second, related behavior visible above where items rotated 90deg clockwise are incorrectly offset, but I wanted to look into this first :) 

[related issue](https://github.com/melonjs/melonJS/issues/1006)

**Comment by obiot** [comment]
Hi Alcor, thank you very much for the report, investigation and even solution ! I was busy with other things these last days but I will look at it this weekend ! thank again !

**Comment by obiot** [comment]
so its not as easy as we thought, as if the current changes there are still some issues with the rendering in Tiled, including animation not playing, and some tile still being misplaced, or wrong tile id being used. but at least with #1006 fixed now it will help ruling out potential cause, so back to it ! :)

**Comment by obiot** [comment]
and there it is !
![Screen-Recording-2020-07-11-at-4](https://user-images.githubusercontent.com/4033090/87220421-1ac74880-c396-11ea-8fc9-4898397d1549.gif)

**Comment by obiot** [comment]
one thing, I'm gonna keep your map as one of the example in the tiled loader example, if I can :)

**Comment by alcor** [comment]
Please do!

**Comment by obiot** [comment]
Thanks !
