### ISSUE TITLE
Rotation in TMX files renders incorrectly

### ISSUE THREAD

**Issue by alcor** [melonjs/melonJS#1006]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser 
Mac OS 10.14 / Chrome 83
 
#### melonJS version 
7.1.1 and top of tree

#### Bug description  
When rotation is specified in TMX files, the tiles are not offset and rotated correctly

#### Steps to reproduce the bug

The following map is a simplified version of the bug
[RotationBug.zip](https://github.com/melonjs/melonJS/files/4891140/RotationBug.zip)
In it, the same tile is used 4 times at 4 different rotations.

It appears that:
Vertical and horizontal flips work
180 degree rotation works
90 and -90 rotations offset the tile, but then don't rotate it about an anchor back into place.

It is possible there is a bug in:
https://github.com/melonjs/melonJS/blob/2094bcd6ac96e67e3c7a73ff7ad73d4d800a021a/src/level/tiled/TMXTile.js#L114

Map in Tiled
<img width="317" alt="Screen Shot 2020-07-08 at 7 12 49 AM" src="https://user-images.githubusercontent.com/563095/86929229-753c7c80-c0ea-11ea-8061-9ac1e3fa3ce0.png">

Map in MelonJS
<img width="136" alt="Screen Shot 2020-07-08 at 7 12 23 AM" src="https://user-images.githubusercontent.com/563095/86929232-766da980-c0ea-11ea-88a4-8a5e00fe3e64.png">

**Comment by obiot** [comment]
same here, thanks !

**Comment by obiot** [comment]
with the last fix it seems that AD rotation is correct now, here is below a screenshot of the map (improved version) :
<img width="129" alt="Screenshot 2020-07-11 at 3 54 05 PM" src="https://user-images.githubusercontent.com/4033090/87219659-ab4e5a80-c38f-11ea-92c5-c81444a45c11.png">

first one use only X & Y rotation to create the mini island,
second one only use AD rotation, 
and the last one use a combination of X, Y & AD.

All looks  right and exactly the same as in Tiled (if you notice they don't exactly all look the same).

**Comment by obiot** [comment]
closing this ticket (I'll let you reopen it if you think there is still an issue).
