### ISSUE TITLE
src/video/video.js calling getParentElement is wrong and creates problems with mouse events

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#1010]
I experienced a problem with my game wherein the canvas was not receiving mouse events.

I discovered that in api.init in video.js, it is calling

`me.video.parent = me.device.getParentElement(settings.parent);`

This results in the canvas being placed in the parent element of the wrapper rather than in the wrapper which causes problems with mouse event capturing.

If this line is changed to

`me.video.parent = me.device.getElement(settings.parent);`

the mouse events in my game work perfectly.

I suggest making this change.

**Comment by obiot** [comment]
wow, very good finding, so obvious and yet we missed it (did not even break our own examples) ! This is indeed a regression introduced in the 8.0 version when rewriting some portion of this code, I'll properly test it and push the fix tomorrow.

**Comment by obiot** [comment]
here is the fix, now it should properly work as intended :
- when the canvas is created it is added to the container specified by the `parent` property, or `document.body` if none was specified
- when detecting pointer input, the elements bounds of the canvas container is used
- when resizing, melonJS try to use the space available within the parent container of the canvas div container (so the parent of the parent of the canvas, maybe the initial `me.video.parent` property is not such a good choice, but at the end this is the actual parent container of the canvas)

**Comment by obiot** [comment]
thanks again for investigating on this one, can you pull the last change from the master branch, or do you want me to upload a build here ?

**Comment by siauderman** [comment]
I'll pull.
