### ISSUE TITLE
Better tutorials + HTTPS website

### ISSUE THREAD

**Issue by nekromoff** [melonjs/melonJS#1014]
![image](https://user-images.githubusercontent.com/8550349/97787848-e4b40b80-1bb4-11eb-8720-e56ad3af0012.png)

+better tutorials are needed for isometric world etc. There is really very little information on starting with MelonJS. And the documentation lacks examples (sample code) of function use.

**Comment by obiot** [comment]
still working on the https certificate :) dunno why, but ending up longer than expected :)
