### ISSUE TITLE
Gravitional acceleration

### ISSUE THREAD

**Issue by neilsf** [melonjs/melonJS#1017]
Firstly, I don't know if physics in MelonJS are expected to be realistic, but here is my suggestion:

In the real world, the gravitional acceleration of an object is the same regardless of the object's mass. If you let two things fall at the same time from the same height, they'll reach the ground at the same time. In our evreyday world (e. g. on Earth) G is constant.

In melonJS, a lighter body falls slower while the heavier one falls faster. This is wrong.

I think it is calculated here: https://github.com/melonjs/melonJS/blob/e0281e7d35c80085715430d863c588eb9b4c100c/src/physics/body.js#L671

I think the solution would be to exclude `this.mass` from the above formula and acceleration will be constant.

PS. MelonJS is great btw! Thanks for your great work!

**Comment by obiot** [comment]
hi @neilsf, thanks for the suggestion, I will definitely look into it, but maybe for the next 10.x version though as I'm trying to avoid more api break of behaviour break for the current 9.x branch.

have you done any nice project you can share with melonjs ?

thanks again!

**Comment by neilsf** [comment]
> have you done any nice project you can share with melonjs ?

Oh, I started but gave up eventually :-( I might get back to it when I have some more time.

**Comment by obiot** [comment]
this one done, as part of other changes linked to Physic implementation in the coming 10.0 (melonJS 2) release, see the here above commit for more details
