### ISSUE TITLE
Support proper fix for types

### ISSUE THREAD

**Issue by Coder2195Text** [melonjs/melonJS#1071]
Im using TypeScript

And this happens

![image](https://user-images.githubusercontent.com/63069499/154762101-bff7640e-10d1-4b7c-ae15-0b82ac4faed5.png)

And looking at the d.ts file results in 10+ errors

![image](https://user-images.githubusercontent.com/63069499/154762175-544264dd-93e7-45d9-8a99-c12730bb88ee.png)

As well as the ANY types here
![image](https://user-images.githubusercontent.com/63069499/154762288-03a5e5f1-a6b5-408a-b6b6-7fd88373da02.png)

**Comment by parasyte** [comment]
I'm not an active maintainer on this project anymore, but recently with my other JS projects I have been using vanilla JS with jsdoc type annotations for TypeScript linting in IDEs. melonJS is already well-documented with jsdoc style comments, and adding types is a big commitment. But it less work than translating the whole project to TypeScript.

It's pretty easy to get started. Create a new file in the root called `tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "strict": true,
    "target": "es2015"
  },
  "include": [
    "dist/**/*.ts",
    "src/**/*.js"
  ]
}
```

(If you have increased your ECMAScript level to a more recent version, just change the `target` field.)

And then install the TypeScript addon for your IDE, that's it! You can also configure the addon to show type errors in various ways, depending on the IDE. For example, I use Sublime Text, and this is how I have it configured:

![melonjs-typescript](https://user-images.githubusercontent.com/456942/154765224-d511809f-c013-4709-9e63-83f3c7a5c1a1.png)

And you can run `tsc` in your shell (assuming `npm install -g typescript`) to get all the same info:

![melonjs-tsc](https://user-images.githubusercontent.com/456942/154766605-c578a1ea-1d3f-4afa-9a95-ab827b1ab767.png)

The best part about this setup, IMHO, is there is no need to run any build commands. Import the source code directly as a module and away you go!

Just thought I would throw that out there. melonJS still isn't 100% TypeScript compatible, as far as I know. Adding the TypeScript config and using it as a lint will go a long way to improving that, though! The biggest challenge that I can see for this is replacing the antiquated `me` namespace with proper es2015 modules. Most of the work was completed as of #1021, but this legacy namespace thing persists.

**Comment by obiot** [comment]
the TS Definition file is indeed built based on the JSDoc Tags, but yes it still needs more reworking to output a clean definition. In the latest commits, most (if not all in theory) object constructor now have proper typings, see here :
https://github.com/melonjs/melonJS/blob/master/dist/melonjs.module.d.ts#L1819

but we still have that me namespace to indeed be removed from jsdoc, it's almost there, especially again with those last commits where most of the documentation was properly update to document es2015 classes.

**Comment by obiot** [comment]
Hi Guys,

so in the last commits, I updated the documentation and removed all traces of the legacy me namespace (only remaining now is in the examples). this greatly help with TypeScript in removing most of the errors we had previously.

@Coder2195Text  if you have any time to give it a look, the latest distribution file is up to date here : https://github.com/melonjs/melonJS/blob/master/dist/melonjs.module.d.ts

only few errors now are some missing namespace and some warning, but I think it should be much more easy to use TS with melonJS now, let me know !

**Comment by obiot** [comment]
with the few last commits today, we have now `0` warnings and `0` errors on the typescript definition file 🥳 🎈 🍺 

![Screenshot 2022-02-23 at 3 57 34 PM](https://user-images.githubusercontent.com/4033090/155280231-547b4e23-baf7-47d1-9fc6-0411d3ec0e62.png)

For testing, same as yesterday, while waiting for the 10.4 version to be published, I updated the distribution files on Github:
https://github.com/melonjs/melonJS/blob/master/dist/melonjs.module.d.ts

would be great to get some feedback/confirmation, but in the mean time I will therefore close this ticket !
