### ISSUE TITLE
npm run serve states "missing script: serve"

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1072]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Windows 10x64
 
#### melonJS version 
10

#### Bug description 
npm run serve states "missing script: serve"

#### Steps to reproduce the bug
install boilerplate and type npm run serve

#### Console log Extract 
C:\projectx>npm run serve
npm ERR! Missing script: "serve"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-21T15_59_31_609Z-debug.log

**Comment by obiot** [comment]
thanks for the notification/help, the tutorial does need a bit of love following the recent changes/update on the boilerplate :)

https://github.com/melonjs/tutorial-platformer/commit/fc6e1d63dffb049e12a4f7cea80a7bbf00876140
