### ISSUE TITLE
Platformer tutorial based on old boilerplate

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1073]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
10

#### Bug description  
Platformer tutorial located at https://melonjs.github.io/tutorial-platformer/ contains numerous omissions and errors.  Initial game directory is entirely different.  Missing instructions on usage of resources.js.  References to outdated procedures and methods.

#### Steps to reproduce the bug
View tutorial at link above.

#### Console log Extract 
N/A

**Comment by obiot** [comment]
https://github.com/melonjs/tutorial-platformer/commit/514b48200716c7b83d7a2408d5622134c4686929

**Comment by obiot** [comment]
https://github.com/melonjs/tutorial-platformer/commit/09eb1804b84b0a8bf6007020f664e64d96fd7c23

**Comment by obiot** [comment]
Tutorial has been updated, might not be perfect yet, but at least they are no mentions anymore of the old boilerplate. If you find more issues, please (kindly) rather open a ticket directly on the Platformer GitHub : https://github.com/melonjs/tutorial-platformer

**Comment by obiot** [comment]
thanks for your time on providing feedback on what is broken, much appreciated !
