### ISSUE TITLE
Numerous missing links/linkdead in Details & Usage and third party tools section

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1074]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
N/A

#### Bug description  
From this page:
https://github.com/melonjs/melonJS/wiki#details--usage
Select "core engine explained", then select the details on how to use are in the [tutorial](http://melonjs.org/tutorial). - this link is 404

[Building for production using the boilerplate](https://github.com/melonjs/melonJS/wiki/Building)
(empty page)

Linkdead
[melonJS Particle Studio Editor](http://melonjs.github.io/melonJS/examples/particles/) : Visual Particle Editor for melonJS

[Using sprite sheets in melonJS](https://www.codeandweb.com/blog/2015/11/08/using-sprite-sheets-with-melonjs-tutorial) (by [codeandweb](https://www.codeandweb.com/))

#### Steps to reproduce the bug
Visit link above

#### Console log Extract 
N/A

**Comment by obiot** [comment]
thanks, pages move, change, disappear,  not always easy to keep track of everything ! All links have been updated, thanks again !
