### ISSUE TITLE
Conflicting/missing docs on how to properly create resources.js and/or manifest.js

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1075]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
10

#### Bug description  
Conflicting/missing docs on how to properly create resources.js and/or manifest.js

https://melonjs.github.io/tutorial-platformer/
Platformer tutorial states:
_The boilerplate automatically builds the resources list and exposes it to your app as game.resources (build/js/resources.js) when using the npm run serve task.
WARNING: If you are not using the boilerplate, you will have to manage the resources.js manually (it is time-consuming, and error-prone). If managing resources.js manually, you can see an [example on the git repo](https://github.com/melonjs/tutorial-platformer/blob/gh-pages/tutorial_step9/js/resources.js)._

> npm run serve doesn't exist
> no docs anywhere on how to build or include resources.js

https://melonjs.github.io/tutorial-space-invaders/
Space invader tutorial contains conflicting instructions:
_The first thing to add is images to the resources.js file._

> resources.js is not listed in the file list (manifest.js is)
> resources.js is not included in the index.js (DataManifest is)
> code snippet below this line shows DataManifest, not Resources
> example is contrary to Platformer statement that this file should be created automatically and that manual maintenance is error prone

Documentation should clearly state if resources.js or manifest.js should be used and if so, if they need to be manually maintained or if they are automatically built.  If automatically built, documentation should detail steps on proper way to build and include.

#### Steps to reproduce the bug
Access links above

#### Console log Extract 
NA

**Comment by obiot** [comment]
the Platformer tutorial has been fixed, will close this ticket one the space invaders one is done too.

thanks !

**Comment by obiot** [comment]
finally found the time to fix the space invaders tutorial (see https://github.com/melonjs/tutorial-space-invaders/commit/eaceb91d1f950e342cf543f4d7748994adc6e11b), so closing this one !
