### ISSUE TITLE
Incorrect rendering of background from TileD

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1076]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Windows 10/64, Chrome
 
#### melonJS version 
10

#### Bug description  
Rendering of a background inserted into tileD is truncated at the bottom of the image (see attached).  Tried several different image sizes with same result.

#### Steps to reproduce the bug
Create a TileD level with a background image, export level and load into project

#### Console log Extract 
No errors in console
<img width="678" alt="in_browser" src="https://user-images.githubusercontent.com/81651363/155739098-2363e7d4-a16b-4a4a-83b9-0881cb12bca6.PNG">
<img width="707" alt="in_tiled" src="https://user-images.githubusercontent.com/81651363/155739104-41dc0139-78ce-4ac0-a842-f609e12c1a5a.PNG">
<img width="297" alt="layers" src="https://user-images.githubusercontent.com/81651363/155739105-e2087478-7b58-41a0-b501-18ac421a8a98.PNG">
<img width="247" alt="settings" src="https://user-images.githubusercontent.com/81651363/155739107-0a861a2f-ca38-4b84-8255-ffbcf837282e.PNG">
![background1-0](https://user-images.githubusercontent.com/81651363/155739150-c9d15536-b115-45c9-a96d-e8447dc29199.png)

**Comment by obiot** [comment]
any way you can share maybe the tmx map so that I can test on my side ? I haven't notice any issue on my side, so maybe it's happening with certain size of map or background or something.

thanks for reporting this !

**Comment by obiot** [comment]
@dynamo-foundation hi, can yo also share the `level25-Tileset.png` file ? thanks!

**Comment by obiot** [comment]
this one done too, pity that I published 10.5.0 yesterday, even though this one was a tricky one, the fix is actually pretty simple..... (not to mention it's a pretty stupid bug in the first place)
