### ISSUE TITLE
linkdead in wiki

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1077]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
Any

#### Bug description  
In wiki under Core, 404 link on tiled tutorial
https://github.com/melonjs/melonJS/wiki/MelonJS-Core
here:
There is a near complete [Tiled Map](https://www.mapeditor.org/) integration with melonJS, the details on how to use are in the [tutorial](http://melonjs.org/tutorial).

Would be nice to have step by step on using TileD especially given the numerous issues I am encountering using it as trial and error is wasting alot of time.

#### Steps to reproduce the bug
click link above

#### Console log Extract 
N/A

**Comment by obiot** [comment]
good catch, I updated the link to point to https://github.com/melonjs/melonJS/wiki#tutorial !

**Comment by obiot** [comment]
this page is also worth reading for beginner :
https://doc.mapeditor.org/en/stable/manual/introduction/
