### ISSUE TITLE
Support for Spine2D

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1081]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
10

#### Bug description  
Add support for Spine2D

#### Steps to reproduce the bug
I'm ready to start development on this - how do you want to organize / coordinate?

#### Console log Extract 
to show possible exception/errors raised by the engine or the browser

##### How to enable/use the console log
* Webkit (Chrome, Safari) : https://developer.chrome.com/devtools
* Opera : http://www.opera.com/dragonfly/documentation/
* FireFox : http://getfirebug.com/enable
* MS (Edge) : https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/debugger

**Comment by obiot** [comment]
I suggest you start working on it on your side until you feel you have something ready to share that we can work on together if needed.

my suggestion would be to do a plugin, like for the older version. I would love to directly add it to melonJS, but the spine framework is actually quite big, and beside that I'm not how it would work in terms of license agreement, so maybe keeping it separated is easier.

also as you suggested, yes definitely go directly for the latest 4.0 runtime,

thanks for that !!!!! that would huge & awesome to have proper support for Spine in melonJS :)

**Comment by obiot** [comment]
closing this one in favour of #1114, that better describe what to do !

**Comment by obiot** [comment]
FYI, here it is : https://github.com/melonjs/spine-plugin
