### ISSUE TITLE
npm run build fails due to unknown dependencies

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1085]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
10

#### Bug description  
npm run build fails

building appears to require some version of eslint
readme does not include any directions on dependencies aside from node and npm

#### Steps to reproduce the bug
run npm run build
see error
/////////////////////////////////////////////////////
> melonjs@10.3.0 lint
> eslint --config .eslintrc.json src rollup.config.js

'eslint' is not recognized as an internal or external command,
operable program or batch file.
/////////////////////////////////////////////////////

#### Console log Extract 
NA

##### How to enable/use the console log
* Webkit (Chrome, Safari) : https://developer.chrome.com/devtools
* Opera : http://www.opera.com/dragonfly/documentation/
* FireFox : http://getfirebug.com/enable
* MS (Edge) : https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/debugger

**Comment by dynamo-foundation** [comment]
after manual install of eslint, got this:

> melonjs@10.3.0 lint
> eslint --config .eslintrc.json src rollup.config.js


Oops! Something went wrong! :(

ESLint: 8.10.0

Failed to read JSON file at C:\project1\node_modules\melonjs\.eslintrc.json:

Cannot read config file: C:\project1\node_modules\melonjs\.eslintrc.json
Error: ENOENT: no such file or directory, open 'C:\project1\node_modules\melonjs\.eslintrc.json'

**Comment by obiot** [comment]
this does not make any sense.... (at least to me 😵‍💫)

from the look of it, it seems like a path issue on windows ? also why is `.eslintrc.json` being transformed to `melonjs.eslintrc.json` ? that files does not indeed exist

**Comment by obiot** [comment]
can you try to modify the command to remove the `--config .eslintrc.json` part ? eslintrc.json is the default name for the configuration file, so `--config .eslintrc.json` is kind of useless here

**Comment by obiot** [comment]
I went ahead and remove `--config .eslintrc.json` from the command line, let me know if it works now for you
