### ISSUE TITLE
Replace JSDoc as it is not maintained and is legacy software

### ISSUE THREAD

**Issue by ShukantPal** [melonjs/melonJS#1089]
Hi folks, JSDoc is [no longer being actively maintained](https://github.com/jsdoc/jsdoc/commits/main) and that's why I built a better, maintainable toolset called [webdoc](https://www.webdoclabs.com?utm_campaign=melonjs&utm_source=ni&utm_medium=GitHub). webdoc has a more [modern theme](https://webdoc-labs.github.io/example-documentation/index.html) that's fully customizable! I would be down to helping you move your documentation to webdoc, the choice is up to you.

I think webdoc will bring a lot of clarity to your existing documentation, and it is pretty good for this use case. See the PixiJS (also a renderer) documentation site: https://api.pixijs.io

**Comment by obiot** [comment]
hi, thanks for reaching out ! 

we have been discussing this actually for years (literally #497) but nobody never took on the task, as honestly it does look like a big one, maybe not anymore in "converting" the tags, but especially in recreating a specific template/theme and all.... but definitely, If you are willing to help, I could hardly say now :)

**Comment by ShukantPal** [comment]
Ok will take a look next weekend.

**Comment by obiot** [comment]
Hi @ShukantPal, I went ahead and add some first npm task to generate webdoc documentation, it's as straightforward as you were implying though.

So first comments and related questions :
- I literally have a billions of `[...] does not have a "-" token preceeding description [...]` errors  : is there a way to configure this ? this was not an issue with jsdoc, and I really don't feel like going through all the source code to add a `-` between each function parameter and their description

- is it possible to output the line number where the tag parsing error is coming from ?

- I use this "trick" (https://github.com/melonjs/melonJS/blob/master/src/geometries/line.js#L15-L31) to generate different doc entry for the same function when the function takes different parameters, but webdoc does not seem to like it (e.g. `"x" is not a parameter & cannot come after the last parameter "`), is there a way to disable warning or force it, similarly to eslint for example ?

- what are the `[DepsChain] xxxx is a member of xxxx` output for ?

- every time I run webdoc it creates an `example.api.json` file at root level ?

thanks !

Note: I'm using the default template for now ("@webdoc/default-template"), config file is here : https://github.com/melonjs/melonJS/blob/master/webdoc.conf.json

**Comment by ShukantPal** [comment]
* I'll create an option to disable these warnings & try to release this weekend. I don't think there's a way to disable it immediately.
* Can you post which error you're seeing in this case?
* Hmm I didn't think of this use case when I added that guard. I can create an option to disable all of these checks.

---
* Unlike JSDoc, webdoc uses a tree structure to model your symbolic relations. This means if C is a member of B and B is a member of A, you can't declare A to be a member of C (a cyclical child-parent relationship).
* Yes, you can set the `opts.export` option to rename it to `melon.api.json`


```json
"opts": {
  "export": "melon.api.json" // or false if you don't like it, but please don't :)
}
```

This `api.json` manifest is a serialization of webdoc's model for your symbol tree. At the moment, it can be used to import a project's API documentation in another place. For example, if someone created a MelonJS plugin and wanted to document a class that extends a class in Melon - they could import your `api.json` manifest by it's URL and webdoc would be able to correctly link references to MelonJS symbols on their website to the MelonJS documentation website.

**Comment by obiot** [comment]
for the error report, for example when running the eslint jsdoc plugin, it gives me this :
`ERROR: The @publiec tag is not a known tag. File: deprecated.js, line: 62`

**Comment by obiot** [comment]
and here is the full log :[webdoc_error.log](https://github.com/melonjs/melonJS/files/8811806/webdoc_error.log)

**Comment by obiot** [comment]
for the record, and for future discussion about template, I moved the jsdoc one we currerntly use into its own repo here: https://github.com/melonjs/jsdoc-template

**Comment by ShukantPal** [comment]
I cloned melonJS locally. The [DepsChain] errors are because webdoc doesn't understand `@memberof Renderer.prototype` - it expects `@memberof Renderer`. I think JSDoc also supports this syntax, is it okay if I make a PR on melonJS for this specific issue? (still fixing the other stuff in webdoc :))

**Comment by obiot** [comment]
Definitely! Please do 🙏🙏🙏

**Comment by ShukantPal** [comment]
@obiot I've released webdoc 1.6.0 with some fixes for your codebase: https://github.com/webdoc-labs/webdoc/releases/tag/v1.6.0. You can pass the `--quiet` option to suppress the unwanted tag parser warnings!

There are some parsing failures - some because of webdoc, and some because of melonJS incorrectly documenting symbols. The documentation site is still getting generate, just with those omissions.

Examples of the latter are where you're declaring members above if statements. webdoc doesn't know what you're documenting and there isn't any `@member` / `@name` tag, neither is it above a `this.` property assignment.
<img width="393" alt="Screen Shot 2022-06-05 at 8 34 19 PM" src="https://user-images.githubusercontent.com/22450567/172077178-2c405249-52bb-4c0b-b601-4458ac97be0c.png">

I can fix this with either option. I can make a PR for these errors (they're not that frequent).

| Option 1 | Option 2 |
|---------|----------|
| <img width="466" alt="Screen Shot 2022-06-05 at 8 36 28 PM" src="https://user-images.githubusercontent.com/22450567/172077258-fcff9ceb-43bd-440e-8b6d-f31118180940.png"> | <img width="360" alt="Screen Shot 2022-06-05 at 8 37 28 PM" src="https://user-images.githubusercontent.com/22450567/172077297-a6d525ae-7a3f-4ca5-8c84-ba6c6c6f8327.png"> |

---

Here are the problems on webdoc's side I'll be working on this week:
1. Parsing the enum in `keyboard.js` from the source. For some reason, it's not parsing the enum properties correctly.
2. Method overloads. They work in TypeScript but not with the JSDoc notation - I'll look into why.
3. Displaying the parameter table for standalone function pages.

You can generate the doc site locally and see if there's anything that needs to be corrected and I'll add them to this list (feel free to create issues at [webdoc-labs/webdoc](https://github.com/webdoc-labs/webdoc))

**Comment by obiot** [comment]
Hi @ShukantPal, that's awesome ! I'll update and work on it as well this week; also definitely you spotted them, there are some quirky jsdoc tags that need to be fixed. I already spent some times few months ago cleaning/unifying everything and moving to a more jsdoc es6 class approach (for the melonJS 2 release), but we still do have some weird stuff here and there.

**Comment by obiot** [comment]
by the way, did you already added the possibility to have a different delimiter between argument names and descriptions ?  I was looking at your commits this weekend, but I don't think I saw it.

I mean the one for : 
`[TagParser]:{@TMXRenderer.drawTile} Parameter "renderer" does not have a "-" token preceeding description <a renderer object>`

**Comment by ShukantPal** [comment]
@obiot 
You just need to pass `--quiet` here :): https://github.com/melonjs/melonJS/blob/927b12db132873feb53fed5e54fc42c4c89483fb/package.json#L98

**Comment by obiot** [comment]
oh ok, it's just a warning actually, I thought the parser was then "ignoring" those lines because of the missing "-". Got it !

**Comment by obiot** [comment]
wow, already much more less scary now to see the parsing log 👍

**Comment by ShukantPal** [comment]
Published 1.6.1 to fix all of these issues. https://github.com/webdoc-labs/webdoc/releases/tag/v1.6.1


There's another problem in this codebase. It uses @function to describe class methods. webdoc makes a distinction between functions and methods; methods are members of a class whereas functions are considered "independent".

I think we could just get rid of the verbose @function tags in most of the codebase since webdoc infers it's a method by default.

<img width="869" alt="Screen Shot 2022-06-06 at 10 22 24 PM" src="https://user-images.githubusercontent.com/22450567/172282125-ca1e328a-071f-45c4-be6b-c7b9eab8e450.png">

**Comment by obiot** [comment]
hi @ShukantPal  thanks !

on the @function and @method, yeah definitely, actually I wanted to even completely remove @function from the es6 class, as it you look at the jsdoc documentation it's not required for es6 :
https://jsdoc.app/howto-es2015-classes.html

what happen if you follow the same logic in webdoc ?

**Comment by ShukantPal** [comment]
I'm working on a PR atm to remove of em!

**Comment by obiot** [comment]
by the way I noticed that when I generate the doc, the landing page is actually the readme, and it does not include the class explorer on the left side, is there something I'm missing, or is it the normal behaviour for the default template and something to rather add in a future "melonjs" template ?

**Comment by ShukantPal** [comment]
@obiot Do you have JavaScript enabled? It has the sidebar for me:

<img width="1436" alt="Screen Shot 2022-06-06 at 10 37 22 PM" src="https://user-images.githubusercontent.com/22450567/172283809-a4b52fc0-47be-4822-aa86-ce69436d0799.png">

**Comment by obiot** [comment]
of course, same browser I use for testing ... and I'm also on macOS... wtf....  😵‍💫

**Comment by ShukantPal** [comment]
Make sure you're serving it using a server and the server root is `dist/docs`.

**Comment by obiot** [comment]
oh boy ! 😄

**Comment by ShukantPal** [comment]
@obiot Ok - last PR and then all webdoc should generate a clean output: https://github.com/melonjs/melonJS/pull/1101/files

Now it's up to you  - how you want to skin the template (would recommend reskinning instead of creating a new template tbh; that way any design improvements will come your way in the future!).

Also, if you ever decide to move to TypeScript - webdoc will just work! :)

**Comment by obiot** [comment]
hi, so I'm now serving the doc folder from a web server (`https://192.168.0.220/docs/`), and put the docs directory at the server root folder, but I still have the same issue :

<img width="1680" alt="Screenshot 2022-06-08 at 8 37 12 AM" src="https://user-images.githubusercontent.com/4033090/172506927-01251682-54cc-4b03-a043-3d0fa3e8c903.png">

is there a way to modify the template so that the javascript is executed without the need for a web server ? (you know on Mac OS , Safari is much more permissive than Chrome of Firefox, which why is very often my to-go first choice when doing testing)

bonus question: what is the complexity in converting an existing JSDoc template to Webdoc (we use this one for now : https://github.com/melonjs/jsdoc-template) ?

**Comment by ShukantPal** [comment]
@obiot webdoc uses absolute URLs so you need to `cd docs` before running the server. The URL should be `192.168.0.220` for the homepage. Otherwise you'd need to pass `--site-root /docs`

To convert an existing JSDoc template, you usually have to just rewrite the `publish.js` script. Most of the template code can be reused, apart from some minor differences between the document model in webdoc / JSDoc. webdoc has a template library so the new publish script should be smaller, since you're not reimplementing the things the template library already provides. Here's the publish script for the default template (which is really flexible).

https://github.com/webdoc-labs/webdoc/blob/master/packages/webdoc-default-template/publish.js

---

Another thing you could do is reskin the default template to your theme using a custom stylesheet. The layout would still be new but the branding / themeing would be of melonJS.

**Comment by obiot** [comment]
by the way I have those errors in the console:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (index.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (default-template.js, line 0)

interestingly it expects everything to be served directly form the root folder itself : 
`http://192.168.0.220/scripts/default-template.js` instead of `http://192.168.0.220/docs/scripts/default-template.js`

**Comment by obiot** [comment]
> @obiot webdoc uses absolute URLs so you need to `cd docs` before running the server. The URL should be `192.168.0.220` for the homepage. Otherwise you'd need to pass `--site-root /docs`

thanks, that was what I was missing ! why can't it use relative path though ? would make it so much easier to test especially when working on the template update (right now I then need to copy everything to my web server to test it).

**Comment by ShukantPal** [comment]
It was designed like that to let you have different URL layouts. Not sure why you need to copy files to a separate web server tho. If you're on a mac:
```
cd $MELON_PROJECT/dist/docs
python3 -m http.server
```
That should setup a server in the docs folder.

**Comment by ShukantPal** [comment]
@obiot Is there a specific reason you want to port the old JSDoc template instead of retheming webdoc's default template? The default template has lots of good features like an available Algolia DocSearch integration! The default template should also be faster since it caches the document model in a JSON instead of producing large HTML files (for the sidebar). The default template will continue to be maintained & will also get better design in the future (like mobile support).

<img width="558" alt="Screen Shot 2022-06-07 at 10 03 04 PM" src="https://user-images.githubusercontent.com/22450567/172515407-a6afa42d-176e-413c-a8bd-4475eb9007c6.png">

**Comment by obiot** [comment]
> 



> It was designed like that to let you have different URL layouts. Not sure why you need to copy files to a separate web server tho. If you're on a mac:
> 
> ```
> cd $MELON_PROJECT/dist/docs
> python3 -m http.server
> ```
> 
> That should setup a server in the docs folder.

whaaaat ??? man I never though about doing this.... you just blew my mind!

**Comment by obiot** [comment]
> Is there a specific reason you want to port the old JSDoc templat

no specific reason really, I was just trying to understand what was the best route with the template . I noticed that a few were ported from their original JSDoc equivalent (jaguar, pixi??), and I thought that if it was a "simple" conversion I might do the same. Now if not yeah definitely going with the default one + reskining/theming.

what do you recommend by the way, shall I close your repo into a `@melonjs/webdoc-template` and modify my own, or is there a "better" proper way to do it ?

thanks again for all your support, really appreciate it ! be sure I'll do a big shout out for Webdoc once its all completed :):):)

**Comment by ShukantPal** [comment]
@obiot If you just want to retheme the default template, there's no copying involved. The right way to do it is just updating the webdoc config. There are a few steps involved:

1. Change the `applicationName` in the config: https://github.com/webdoc-labs/pixijs/blob/df56af7614d7e1d68b588dd0f2ceebf8d7e74021/webdoc.conf.json#L40

2. Add stylesheets: https://github.com/webdoc-labs/pixijs/blob/df56af7614d7e1d68b588dd0f2ceebf8d7e74021/webdoc.conf.json#L56. If you need help for anything specific here, I can help you once you've setup the CSS files in this repo. 

You can view the classnames for different UI elements in the default template in the source code here: https://github.com/webdoc-labs/webdoc/tree/master/packages/webdoc-default-template/src/styles

3. Setup the OpenGraph meta tags: https://github.com/webdoc-labs/pixijs/blob/df56af7614d7e1d68b588dd0f2ceebf8d7e74021/webdoc.conf.json#L61. These are for the website previews
<img width="385" alt="Screen Shot 2022-06-07 at 10 44 48 PM" src="https://user-images.githubusercontent.com/22450567/172520397-a92e8622-5314-48ed-bf15-b70e513e849e.png">

**Comment by ShukantPal** [comment]
Yeah def retheming is the way to go IMO.

> thanks again for all your support, really appreciate it ! be sure I'll do a big shout out for Webdoc once its all completed :):):)

Much appreciated! Happy to see webdoc getting used!

**Comment by obiot** [comment]
> 2\. Add stylesheets: https://github.com/webdoc-labs/pixijs/blob/df56af7614d7e1d68b588dd0f2ceebf8d7e74021/webdoc.conf.json#L56. If you need help for anything specific here, I can help you once you've setup the CSS files in this repo.

oh well If I need to add specific files in the melonJS repo for the docs, I'd rather then copy the template in his own repo and modify it from there to be honest. I've been trying to "unclutter" things by removing as much as possible and I have no "place" to put those stylesheets

**Comment by ShukantPal** [comment]
@obiot In this case, you're not actually copying webdoc's code - these are your theme's stylesheets. I think you'd need at most 1 or 2 CSS files.

You could make a separate repo with the stylesheets and use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to import them in this repo too. Or just publish the CSS files to npm and then pull them from inside `node_modules`, e.g. `./node_modules/@melon/webdoc-template/melon-theme.css`

**Comment by obiot** [comment]
@ShukantPal  sorry about all the questions, but one more : what about all the images I'm using with the current jsdoc template: https://github.com/melonjs/jsdoc-template/tree/main/static/images

**Comment by ShukantPal** [comment]
@obiot Ideally, they should be put in a CDN and you can use the absolute URL. webdoc will eventually support in-repo assets but not atm.

**Comment by ShukantPal** [comment]
Nevermind, I'm adding support for copying assets over in the upcoming release.

**Comment by ShukantPal** [comment]
@obiot Can you upgrade to webdoc [1.6.2](https://github.com/webdoc-labs/webdoc/releases/tag/v1.6.2) and set `template.assets` to the directory `static` in the jsdoc-template repo? This should make all images work in your documentation.

```json
{
  "template": {
    "assets": ["./path/to/static"]
  }
}
```

**Comment by obiot** [comment]
wow so fast ! will it work if I add both the stylesheets and static images to a `@melonjs/webdoc-theme` repository that I would publish to npm so that i can do :

```javascript
 "template": {
    "assets": ["./node_modules/@melon/webdoc-theme/static"]
    "stylesheets": [
      "./node_modules/@melon/webdoc-theme/stylesheets/index.css",
      "./node_modules/@melon/webdoc-theme/stylesheets/header.css",
      "./node_modules/@melon/webdoc-theme/stylesheets/md.css"
    ],
```

**Comment by ShukantPal** [comment]
@obiot Yes.

**Comment by obiot** [comment]
awesome, will try all that this afternoon, create the repo and populate it, thanks again for your super fast support !

funny to see how 2 somehow similar project like pixie and melonjs (I mean 2 javacript or typescript framework) have some many different use cases when it comes to documentation ! this will for sure (hopefully) benefit all future framework that will migrate to webdoc too !

**Comment by ShukantPal** [comment]
@obiot I was browsing through the MelonJS docs locally and saw that `Light2d` isn't documented in the current website: https://github.com/melonjs/melonJS/blob/ae6d3a3cf08d77e045eeaf461c176421e3ec841f/src/renderable/light2d.js#L22

Bug in JSDoc?

**Comment by obiot** [comment]
No I just did not publish the latest doc actually ☺️ and since its more of an experimental feature anyway for now i’d figure it can wait for webdoc to be ready.

by the way do you know how to automatically publish to gh-pages? I tried to do it for the doc in the past but never succeeded

**Comment by ShukantPal** [comment]
I would recommend you setup a GitHub workflow with a [Deploy to GitHub pages](https://github.com/marketplace/actions/deploy-to-github-pages).

**Comment by obiot** [comment]
@ShukantPal I just updated to the latest 1.6.2 version and modified the conf file as follow :
```javascript
    "template": {
        "applicationName": "melonJS",
        "repository": "@webdoc/default-template",
        "outputSourceFiles": false,
        "readme": "./README.md",
        "repository": "https://github.com/melonjs/melonJS/",
        "assets": ["./node_modules/@melonjs/jsdoc-template/static"]
    }
```

however the path to the assets is not correct, as you can see below it properly fetch the html, but when it comes to the images the base `docs` folder is ignored: ` /assets/images/convex_polygon.png` should be `docs/ /assets/images/convex_polygon.png`

````
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::1 - - [09/Jun/2022 15:18:21] "GET /docs/melonjs/Polygon.html HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] code 404, message File not found
::1 - - [09/Jun/2022 15:18:21] "GET /assets/images/convex_polygon.png HTTP/1.1" 404 -
::1 - - [09/Jun/2022 15:18:21] "GET /docs/styles/index.css HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] "GET /docs/icons/link.svg HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] "GET /docs/icons/chevron-up.svg HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] "GET /docs/icons/chevron-down.svg HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] "GET /docs/scripts/default-template.js HTTP/1.1" 200 -
::1 - - [09/Jun/2022 15:18:21] code 404, message File not found
::1 - - [09/Jun/2022 15:18:21] "GET /assets/images/convex_polygon.png HTTP/1.1" 404 -
::1 - - [09/Jun/2022 15:18:22] "GET /docs/explorer/reference.json HTTP/1.1" 200 -
````

**Comment by obiot** [comment]
latest update :

* new repository for the melonJS theme : https://github.com/melonjs/webdoc-theme
* conf file updated accordingly: https://github.com/melonjs/melonJS/blob/master/webdoc.conf.json#L14-L26

colors are not yet fully right (I'd like to have the banner in a dark gray color, and then use the melonJS green for main text and highlight), and the image assets are not yet there (as per my last feedback), but we are almost there !

**Comment by ShukantPal** [comment]
I'll fix the image linking problem later today then!

**Comment by ShukantPal** [comment]
I didn't realize the PixiJS theme was that good 😂.

**Comment by obiot** [comment]
ahahahaha thanks 😂 I've been struggling yesterday to make the webdoc one looks like the former jsdoc really

**Comment by ShukantPal** [comment]
Made a PR with the changes: https://github.com/melonjs/webdoc-theme/pull/1

**Comment by obiot** [comment]
you are the best ! Looking at your changes in the css, I would have never figured it out :P but I suck at web/css design, thanks a bunch, really ! I think that's ready now for publishing now, can't see right what is still missing honestly. I'll review the doc carefully for anything missing and then will go ahead !

**Comment by obiot** [comment]
Hi @ShukantPal, 

I was trying to to put the final touch at the documentation before publishing, but I could not find how to add a footer in the template, is it something I missing, or is not possible in the current version (which is ok, just want to add something similar to jsdoc: copyright + generated by webdoc)

also I tried to Look at Algolia, create an account and everything, but I'm not sure what benefit it brings; I mean the filter/search field in the explorer is already good enough no ? and Algolia is not so simple to put in place.

I created an account, got my key and all, but when I tried to update the record and upload the json manifest file (which I assume is the one to use) I got the below error :
`Upload error: Record at the position 0 objectID=97ef94bd024c5_dashboard_generated_id is too big size=1767006/100000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits`

**Comment by ShukantPal** [comment]
Hi @obiot,

I pushed a PR to upgrade your webdoc installation to 1.6.5; that version lets you configure the footer without having to re-add “Powered by webdoc!”

You can set the “template.alias.footer” property to a HTML fragment file (*.tmpl). You would basically be overriding this template file:

https://github.com/webdoc-labs/webdoc/blob/master/packages/webdoc-default-template/tmpl/components/footer/index.tmpl

In regards to Algolia,
1. I think you have to deploy your site first since Algolia will crawl through it.
2. You also have to set the “template.siteDomain” config in webdoc.conf.json to “http://melonjs.github.io<http://melonjs.github.io/>”. That will make webdoc generate a sitemap. Algolia uses the sitemap to find each page.
3. Make sure you’re using the DocSearch (legacy) Docker image: https://docsearch.algolia.com/docs/legacy/run-your-own. Then your Algolia command should look something like:

[cid:68DF5987-B34A-46A7-9D26-775027306E99]

If you invite me to your Algolia account, I might be able to give more help. The benefit of Algolia is that it is full-text search so people can search by keywords in class descriptions and members too.

On Jun 11, 2022, at 11:40 PM, Olivier Biot ***@***.******@***.***>> wrote:



Hi @ShukantPal<https://github.com/ShukantPal>,

I was trying to to put the final touch at the documentation before publishing, but I could not find how to add a footer in the template, is it something I missing, or is not possible in the current version (which is ok, just want to add something similar to jsdoc: copyright + generated by webdoc)

also I tried to Look at Algolia, create an account and everything, but I'm not sure what benefit it brings; I mean the filter/search field in the explorer is already good enough no ? and Algolia is not so simple to put in place.

I created an account, got my key and all, but when I tried to update the record and upload the json manifest file (which I assume is the one to use) I got the below error :
Upload error: Record at the position 0 objectID=97ef94bd024c5_dashboard_generated_id is too big size=1767006/100000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits

**Comment by obiot** [comment]
fantastic, thanks !

for Algolia I will wait next release then, plublish this version first, and indeed then let it crawl the online doc.

thanks again :)

**Comment by obiot** [comment]
I'm gonna close this ticket too, we are done here I believe :) we can still come back here for discussion of course.
