### ISSUE TITLE
Melon.js, TypeScript and Parcel

### ISSUE THREAD

**Issue by 8Observer8** [melonjs/melonJS#1111]
- Install Melon.js 10.12.0
- Install Parcel 2.6.2 globally
- Install TypeScript 4.6.3 globally
- Add these commands to package.json:

```
"scripts": {
    "start": "parcel src/index.html --dist-dir public --open",
    "build": "parcel build src/index.html"
  },
```

- Add this dependency to package.json:

```
  "dependencies": {
    "melonjs": "^10.12.0"
  }
```

- Create `src/index.html`:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script  type="module" src="main.ts"></script>
</body>

</html>
```

- Create `src/main.ts`:

```
import * as me from "melonjs";

console.log(me.version);
```

- Run the command: `npm run start`
- You will see this error in the browser console:

![image](https://user-images.githubusercontent.com/3908473/175218558-774aa0fe-db46-484e-859f-255c3ce54448.png)

**Comment by obiot** [comment]
interesting, that line 28787 points to here:
https://github.com/melonjs/melonJS/blob/master/src/system/device.js#L421
looks like an additional test on `process.release` should be added.

is it something you can test on your side (modify melonJS) ? else I can publish a new release

**Comment by obiot** [comment]
I updated the [dist](https://github.com/melonjs/melonJS/tree/master/dist) build that includes the bug fix :
https://raw.githubusercontent.com/melonjs/melonJS/master/dist/melonjs.module.js

there are a couple of others - no fully tested - changes in this wip release, but I don't think that should be a problem.

let me know if it works, then if yes I will finalised testing in // and then release this version.

thanks for the report !

**Comment by 8Observer8** [comment]
Yes, it works: https://github.com/melonjs/melonJS/commit/fcadbec8833c62ea248ade099db355d187ecc3a6

**Comment by obiot** [comment]
awesome, thanks for the feedback !

**Comment by obiot** [comment]
version 11.0 published on NPM, closing this ticket, thanks again for reporting the issue :)
