### ISSUE TITLE
[Feature Request] BitmapText does not support ancestors' alpha / opacity settings

### ISSUE THREAD

**Issue by wpernath** [melonjs/melonJS#1118]
I am using opacity settings in my game UI and have seen that BitmapText component does not respect alpha settings / opacity settings of the component where the text is placed. Would it be possible to integrate this in the BitmapText rendering?

For example: 

```Javascript
let container = new Container(0,0, 400, 400);
let text = new BitmapText(5, 10, {
  font: 'my-font',
  text: 'This is the text to be displayed',
});
let text2 = new BitmapText(5, 25, {
  font: 'my-font',
  text: 'This is another text to be displayed',
});

container.addChild(text);
container.addChild(text2);
container.setOpacity(0.5);
game.world.addChild(container);
```
As other elements do respect global alpha settings, it would be great and handy to have BitmapText respect this settings as well. 

Thanks a lot

**Comment by obiot** [comment]
that's weird, it should definitely work ! looks more like a bug of something that was overlooked. thanks for reporting it !

**Comment by obiot** [comment]
this one fixed ! it was indeed a regression when using the WebGL renderer, that I believe was introduced when we added support for tinted texture. Canvas mode was working though (you can test by adding `#canvas` to your url to force the canvas renderer). 

thanks again for the report, and closing this one !

**Comment by wpernath** [comment]
Thanks a lot for your help with this. I've tested it and it works. I just found another issue: Sprites do not support alpha / opacity settings in Canvas Renderer mode. I just had a look at canvas_renderer.js to see if it should be supported. From what I've seen, it should be, right?
