### ISSUE TITLE
Bug in BitmapText scaling

### ISSUE THREAD

**Issue by SiLiKhon** [melonjs/melonJS#1129]
When scaling a BitmapText object (through `settings.size`) the inter-character intervals are off.

I believe the problem is in [this line](https://github.com/melonjs/melonJS/blob/f615d3976ef7c2bc67e6eec2d1f02177c1ac1128/src/text/bitmaptext.js#L315), which should instead be
```javascript
x + glyph.xoffset * this.fontScale.x,
```
— at least, such change fixes the problem for me.

**Comment by obiot** [comment]
this is now fixed with the latest change, thanks for the report !
