### ISSUE TITLE
BUG / Enhancement in BitmapText: If a glyph is not defined, setting text will result in a strange error

### ISSUE THREAD

**Issue by wpernath** [melonjs/melonJS#1131]
**Describe the bug**
If you have a bitmap font and you're going to write text using 
```javascript
this.addChild(new BitmapText(0,0, {
  text: "<>some text with undefined glyphs"
}));
```
You're getting a strange error: `TypeError: Cannot read properties of undefined (reading 'xadvance')`

**To Reproduce**

**Expected behavior**

I'd expect at least a message on the console saying that the text contains glyphs which are not defined in the font.

**Comment by obiot** [comment]
with the latest changes, melonJS will now throw this kind of warning if a glyph is not defined:
`[Warning] BitmapText: no defined Glyph in for ¬ (melonjs.module.js, line 34967)`

I'm not sure though on what is the best way to be honest, I mean throw a warning, or just throw an exception and stop execution.

thanks for the report and suggestion !
