### ISSUE TITLE
[Improvement?] Move the building melonJS and building the documentation sections from the Readme to the Wiki

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonJS#1133]
This seems like something not a lot of people will be doing and so it might be cluttering up the Readme a bit. That's just my 2 cents anyways

**Comment by obiot** [comment]
indeed, this is not something a lot of people would be doing, so I guess we could move it to the readme and just link to it from the Readme ?

**Comment by obiot** [comment]
new contribution guide added, and moved related section from README into it, feel free to amend/modify anything :)
