### ISSUE TITLE
[Feature request] Convert the examples to Codepen or something similar

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonJS#1137]
**Is your feature request related to a problem? Please describe.**
Currently starting a MelonJS project or toying around with the examples requires a fair amount of setup and knowledge of IDEs. If we converted this to an online code editor it would be easier for people to get started with MelonJS

**Describe the solution you'd like**
Convert the examples to Codepen or some other site that can let the users start toying around with MelonJS instantly in their browser

**Comment by obiot** [comment]
same for this one: https://github.com/melonjs/examples/issues/4

**Comment by L1lith** [comment]
> same for this one: [melonjs/examples#4](https://github.com/melonjs/examples/issues/4)

I know we have remote demos to play the game, but I was suggesting codepen because it's easily editable without using git. Forgive me if I'm wrong I don't see where this has been implemented?
