### ISSUE TITLE
Platformer Demo GUI clipping on mobile

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonJS#1138]
![Screenshot_20220928_134325](https://user-images.githubusercontent.com/34887287/192874452-1d5e7c66-e38b-4154-b477-ad1a1f603787.jpg)

**Comment by obiot** [comment]
this is not a bug in melonJS, just a "limitation" of the virtual controller implementation in the demo.

**Comment by obiot** [comment]
moved here: https://github.com/melonjs/examples/issues/3
