### ISSUE TITLE
[Limbo] Sort out the bundling process

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonJS#1142]
I was thinking it would be best to ship the full source code that way it can be imported directly without needing to load the whole thing. There might need to be a legacy bundle

Also it relates to [this issue](https://github.com/melonjs/melonJS/issues/1130) as we need to orient the tests around our distributions.

It would also make sense to make a special browser dist where the dependencies point to CDN URLs instead of using NPM package names, that way it can be imported directly in the browser without a bundling step (which would also eliminate the need for tree-shaking all-together when being used this way). We could put this distribution on a CDN too (or put a download on the website or both). We could also look for alternative ways to make a browser distro where the dependencies are included inside without requiring bundling the whole lib into one file

**Comment by obiot** [comment]
done, the build process willl now generate a `melonjs.mjs` tree-shakeable build, which is actually a folder with all separate chunk, that includes all required transforms and external dependencies.

I propose to keep the previous/existing `melonjs.module.js` for backward compatibility, but then slowly transition to melonjs.mjs in our source code.

**Comment by L1lith** [comment]
@obiot should we re-open this?

**Comment by obiot** [comment]
yes maybe, I've been working these last 2 days on a bug in the collision system (I should create a ticket for it), as soon I'm done wit it, I'll resume the build process update, now that also rollup 3 has been released

**Comment by obiot** [comment]
@L1lith and we are done I think here !

I kept `dist/melonjs.module.js` as the main entry in package.json, but then changed the module one to `dist/melonjs.mjs/index.js`. Module is the one commonly used by bundler, so this should enable tree-shaking automatically (I'll have to try with the boilerplate and webpack).

Maybe we can rename `melonjs.mjs` to `melon.mjs`, but else if you have no comments, and happy about it we can close this one !

**Comment by obiot** [comment]
adding this one here for reference: https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions

**Comment by obiot** [comment]
@L1lith closing this one
