### ISSUE TITLE
confirm the raycast feature is working properly

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#1151]
following the quick 14.0.1 release to fix an issue with collision detection (#1149), verify that the raycast function is working properly :
https://melonjs.github.io/melonJS/docs/melonjs/collision.html#rayCast

**Comment by cpravetz** [comment]
I believe line 120 of collision.js is:

` rayCast(line, result) { return game.world.rayCast(line, result); }`

but should be:

` rayCast(line, result) { return game.world.detector.rayCast(line, result); }`
