### ISSUE TITLE
[Feature request] Create a Code of Conduct on GitHub

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonJS#1155]
**Is your feature request related to a problem? Please describe.**
A code of conduct is kinda like the rules for contributing. I think this would be a good thing to have :) For example [here's the code of conduct from astro-18next, they're pretty good.](https://github.com/yassinedoghri/astro-i18next/blob/beta/CODE_OF_CONDUCT.md)

**Describe the solution you'd like**
We need to add a Code of Conduct so that it shows up on the side bar on the right, by changing the settings in GitHub

**Comment by obiot** [comment]
@L1lith do you want to give it a go (just the same as Astro, a custom version of https://www.contributor-covenant.org/)  ? you can just write the text here and then I'll add it to GitHub once we are all happy about it ?

**Comment by obiot** [comment]
@L1lith done, I let you review the default text and update if necessary.

**Comment by obiot** [comment]
and also a Pull Request to register melonJS on their website as an Adopter :
https://github.com/EthicalSource/contributor_covenant/pull/1197
