### ISSUE TITLE
Please include epilepsy/vertigo trigger warning for Masking demo [Feature request] 

### ISSUE THREAD

**Issue by AMP3D** [melonjs/melonJS#1163]
I did not expect the [masking demo](https://melonjs.github.io/examples/masking/) to be what it is and it triggered my vestibular issues badly. 10 minutes later and I'm still having problems. If you could be so kind as to add a trigger warning for it in the readme, that would be helpful for those of us with disabilities that may react badly to it. Thank you.

**Comment by obiot** [comment]
oh no, so sorry for that, I did not realize that it could be a trigger.

I'll add first a warning in the README, but then maybe look at writing a less "agressive" demo.

thanks for reporting it, I hope that you are feeling better now.

**Comment by AMP3D** [comment]
> oh no, so sorry for that, I did not realize that it could be a trigger.
> 
> I'll add first a warning in the README, but then maybe look at writing a less "agressive" demo.
> 
> thanks for reporting it, I hope that you are feeling better now.

Yeah I recovered about 30-45 minutes later. Thanks. 
No worries though, you didn't know that would happen (and honestly neither did I until it did). Take care.
