### ISSUE TITLE
npm melonjs package missing type definitions

### ISSUE THREAD

**Issue by russellsteadman** [melonjs/melonJS#1166]
**Describe the bug**

The current (14.2.0) version of the [melonjs package on npm](https://www.npmjs.com/package/melonjs/v/14.2.0?activeTab=explore) is missing all typescript definitions except the `index.d.ts` file at the type root.

**To Reproduce**

1. `npm i melonjs@latest`
2. `cd node_modules/melonjs/dist/types`
3. `ls`

Or alternatively see the files on [npmjs.com](https://www.npmjs.com/package/melonjs/v/14.2.0?activeTab=explore).

**Expected behavior**

TypeScript files from Github repository are present

**Version:**
 - npm: 9.2.0
 - melonJS Version: 14.2.0

**Comment by obiot** [comment]
indeed, thanks for reporting it !

we did some changes following this #1162, going from a single definition file to multiple ones, and I stupidly just forgot to update the `package.json` file 🤦 

this line : https://github.com/melonjs/melonJS/blob/master/package.json#L42
should be as below instead
```
  "dist/types/*.d.ts",
```

I'll publish the current 14.3 version with this fix later today.

thanks again!

**Comment by russellsteadman** [comment]
I think the "types" line in the `package.json` is fine (the index.d.ts exports all of the definitions), but the "files" array should include that wildcard file reference. Otherwise npm does not upload the type definitions when the package is published.

**Comment by obiot** [comment]
I ended up adding the whole directory directly :
```
  "files": [
    "dist/melonjs.mjs",
    "dist/melonjs.module.js",
    "dist/types",
    "src/",
    "package.json",
    "README.md",
    "LICENSE",
    "CHANGELOG"
  ]
```
I did a test publishing (with -dry-run) and it properly included all the .d.ts files.

thanks again for reporting it, I'm just finishing testing all the changes made in this version for any regression, and I'll publish it later today.

**Comment by obiot** [comment]
14.3.0 published, double checked on my side that all files were correctly included, and all good on my side !
