### ISSUE TITLE
Replace XHR with window.fetch

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#1176]
### Discussed in https://github.com/melonjs/melonJS/discussions/1039

<div type='discussions-op-text'>

<sup>Originally posted by **parasyte** March 14, 2015</sup>
- Documentation: https://developers.google.com/web/updates/2015/03/introduction-to-fetch
- Polyfill: https://github.com/github/fetch
- ~~Dependency (Promises polyfill): https://github.com/jakearchibald/es6-promise~~
</div>

looks like this one has been "forgotten" during the es6 transition, but the loader/preloader still relies on XHR

**Comment by obiot** [comment]
also this (https://github.com/node-fetch/node-fetch) to be considered to provide a fetch-like api on both browser and node.

**Comment by Edwardscb** [comment]
You can assign me to this

**Comment by obiot** [comment]
done here, thank you again @Edwardscb !
