### ISSUE TITLE
Option for mouse events to only fire on the object "clicked" with the highest z ordering

### ISSUE THREAD

**Issue by greghouston** [melonjs/melonJS#118]
Note in both of these examples below that there are overlapping objects, but if you click in a spot where they are overlapping only the event on the object with the highest z-index fires. 

I would imagine that the stop-propagation on these is an option like in jQuery, but am not certain.

EaselJS Drag and Drop Demo
http://www.createjs.com/#!/EaselJS/demos/dragdrop

KineticJS Drag and Drop Demo
http://www.html5canvastutorials.com/labs/html5-canvas-elastic-stars-with-kineticjs/

This feature would likely be a prerequisite for Drag and Drop functionality.
https://github.com/obiot/melonJS/issues/116

**Comment by obiot** [comment]
I was looking back at this one, and now that we have a much small array of object to check, 
https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L304
it should be quite cheap to quickly sort them based on the z value.

Shall we do that ? then it's up to the end-user to return false on the object callback to stop the even propagation

**Comment by parasyte** [comment]
Sure, give it a try! I think it sounds good.

**Comment by obiot** [comment]
1 question & 1 remark :

Q: shall we use the same sorting function that we use in the world container ? or is sorting on Z good enough for any type of game, when it comes to input order ?

R:I just realised, that when using the pub nub system for the pointermove event, it is not possible to use the preventDefault feature (by returning false), as the returned value is not sent back by the framework

**Comment by obiot** [comment]
I'm happy about this one, with all the changes made previously it was at the end an easy win, and this only barely 3 years later :P:P:P

**Comment by parasyte** [comment]
Reopened due to: https://github.com/melonjs/melonJS/commit/36c8ab022985b50a1582eb2491c9e5e7c78cc25b#commitcomment-15930536

This bug isn't actually fixed.

**Comment by krisavi** [comment]
I think this problem is again back. It seems to cause the issue that if you want to drag something, then it drags all the objects underneath it, not only the "topmost" one.

**Comment by obiot** [comment]
it's actually a feature, as by default it will propagate the event to all the objects (but properly respecting the z order). if you don't want to propagate the event, just return `false` from the callback of the object that would "swallow" the event.

**Comment by obiot** [comment]
https://github.com/melonjs/melonJS/commit/a0738dae1cdd63b0e921d27d08d6e6c0540abe0b

except if It's hidden somewhere else, it was not really documented :)

**Comment by krisavi** [comment]
Ooh ok, thank you, I didn't notice it. I will try to work with it. Wasn't able to make it to keep from dragging multiple objects.
