### ISSUE TITLE
Some of the Github pages examples are broken

### ISSUE THREAD

**Issue by q00u** [melonjs/melonJS#1202]
**Describe the bug**
Some of the Github pages examples are broken

**To Reproduce**
1. Go to one of the affected demos
    * https://melonjs.github.io/examples/sprite/
    * https://melonjs.github.io/examples/masking/
    * https://melonjs.github.io/examples/graphics/
2. The file https://melonjs.github.io/melonJS/build/melonjs.module.js fails to load
3. Nothing is displayed in the browser

**Comment by obiot** [comment]
oh god yes, looks like some dev version of the example source code were committed to the repo ! thank you for reporting it :)

**Comment by obiot** [comment]
I fixed the 3 you mentioned (so that you can check them(, but will check all the others as well, t

**Comment by obiot** [comment]
all fixed, thanks again for the feedback !
