### ISSUE TITLE
Animation broken on WebGL if TextureAtlas has multiple textures

### ISSUE THREAD

**Issue by CodeAndWeb** [melonjs/melonJS#1207]
When an animated sprite is created with `createAnimationFromName()` on a TextureAtlas which has multiple textures ("multi-pack"), all animation frames must be placed on the first texture. Otherwise the animation is broken:

![broken-animation](https://github.com/melonjs/melonJS/assets/716009/43b703c2-ccec-4db2-bfe1-a529361a76a8)

**To Reproduce**
1. `git clone -b multipack-broken https://github.com/CodeAndWeb/melonjs-sprite-sheet-example.git`
2. `npm run dev`

**Comment by obiot** [comment]
oh ! interesting ! thank you for reporting it !

**Comment by CodeAndWeb** [comment]
Same problem when creating a single sprite with `atlas.createSpriteFromName("spritename")`. Is multi-pack supported at all? or am I doing something wrong?

**Comment by obiot** [comment]
well it is supposed to be supported, but I guess either with limitations, or we had some regression in the last few versions, I'll definitely look into it

**Comment by obiot** [comment]
Hi, so I cloned your git, executed it and ...... it's just working here .... 
![Oct-18-2023 09-44-31](https://github.com/melonjs/melonJS/assets/4033090/88889f95-20be-40b3-aeea-020ed2d8ca3d)

is there something I'm missing to reproduce the bug ?

**Comment by CodeAndWeb** [comment]
Have you checked out the "multipack-broken" branch?

**Comment by obiot** [comment]
of course it did not.... sorry, I did not realize there was a specific branch for it. Saw it now and indeed it's not working properly

**Comment by customautosys** [comment]
Dear Olivier,

Facing same problem on WebGL:

![bildo](https://github.com/melonjs/melonJS/assets/14951259/5f669c4d-a3c6-4938-bf0f-19412b2ee183)

Canvas is working fine:

![bildo](https://github.com/melonjs/melonJS/assets/14951259/26d2d92a-1019-45a1-a70d-adeed3f3510f)

Have already updated my package to the latest melonJS release

**Comment by obiot** [comment]
wow thank you ! I was really scratching my head with this one, looking at the logic implementation of the multi-texture TextureAtlas support, and could not find what was wrong. Now thank to you, I know that the issue is with the WebGL renderer, and now I know where to look !

**Comment by obiot** [comment]
I managed to pin point the issue, it's actually a regression following that change : https://github.com/melonjs/melonJS/commit/16c5d3c8e369a333e1dde7be3482cd32d50d472d

**Comment by obiot** [comment]
fix in version 17.3.0
