### ISSUE TITLE
Code of Conduct contact link broken

### ISSUE THREAD

**Issue by louwers** [melonjs/melonJS#1243]

**Comment by obiot** [comment]
Can you share which link ? I’m not seeing anything wrong on my side.

thank you 🙏

**Comment by louwers** [comment]
When you click on it it takes you to GitHub (it is a relative link)

```
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the community leaders responsible for enforcement on [discord](discordapp.com/users/608636479765348381).
All complaints will be reviewed and investigated promptly and fairly.
```

Probably browser dependent, but it should include `https://`.


But the link leads no-where if you are not already friends with that Discord user.

**Comment by obiot** [comment]
got it, nice catch !

fixed, and thanks again :)
