### ISSUE TITLE
Stage documentation is missing

### ISSUE THREAD

**Issue by raquelhortab** [melonjs/melonJS#1245]
Hi, I am trying to learn about this library and I was wondering in which ways I can define a map since the readme says :  

> Plain, Base64, CSV and JSON encoded XML tilemap loading

However, I cannot find any documentation about `me.Stage` and the link in [this page](https://github.com/melonjs/melonJS/wiki/MelonJS-Core) is broken.

**Comment by raquelhortab** [comment]
the docs link[ in this page](https://github.com/melonjs/melonJS/wiki/Renderables) is also broken

**Comment by obiot** [comment]
thanks for the report, we are in the process of migrating to TS and have already switched to TSDoc for the documentation, which basically breaks all links we had before :P (the fun never stops!)

here is the link to the "new" documentation :
https://melonjs.github.io/melonJS/
and the Renderable class itself
https://melonjs.github.io/melonJS/classes/Renderable.html

**Comment by obiot** [comment]
For map creation though (unless you want to do it programatically) we have integrated Tiled, and what you have highlighted in the readme are the exporting format from Tiled that melonJS supports.

https://www.mapeditor.org
https://github.com/bjorn/tiled/wiki
https://gamefromscratch.com/tiled-map-editor-tutorial-series/

**Comment by obiot** [comment]
> to clarify, I was looking for other options to define maps because I'd like to be able to generate tem programmatically, not using Tiled (or other UIs) but maybe this is not possible using melonJS? Let's see if someone can answer so I can start looking at alternative libraries, thanks!

This has nothing to do with melonJS, you can just follow Tiled Map Format : https://doc.mapeditor.org/en/stable/reference/tmx-map-format/

And then if you dont want to deal with compressing the data with Base64, use the CSV format. It's all supported by melonJS

**Comment by raquelhortab** [comment]
oh thanks! I had checked json and tmx but they both had encoded data, csv is perfect. thanks again
