### ISSUE TITLE
Debug builds

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#126]
We can use a preprocessor to conditionally build profiling instrumentation and other debug utilities. Some ideas:
- Use [console.time](https://developer.mozilla.org/en-US/docs/DOM/console.time) and [console.timeEnd](https://developer.mozilla.org/en-US/docs/DOM/console.timeEnd) for targeted profiling on all major browsers (except IE) See also: https://developer.mozilla.org/en-US/docs/DOM/console#Timers
- Make `me.debug` a conditionally built module
- Make `me.Rect.draw` and similar "debug drawing" conditionally built

**Comment by obiot** [comment]
i dunnot if we will ever do that, but this is easily doable with uglify :
https://github.com/gruntjs/grunt-contrib-uglify#conditional-compilation

there is even a flag that allows removing the console warnings :
https://github.com/gruntjs/grunt-contrib-uglify#turn-off-console-warnings

**Comment by obiot** [comment]
this ticket is 6 years old, and through the improvements made over the year, and it was never a huge miss, so closing this.
