### ISSUE TITLE
Add support for viewport resize / zooming

### ISSUE THREAD

**Issue by melonjs** [melonjs/melonJS#138]
@see ticket #4

**Comment by obiot** [comment]
i'd say that viewport resize capabilities is done !

**Comment by parasyte** [comment]
Almost. ;) It only resizes one dimension of the viewport today.

**Comment by obiot** [comment]
the flex settings yes, but the `me.game.viewport.resize()` function should be fully working now :P

**Comment by parasyte** [comment]
Got it! Yes, I think so, too.

**Comment by parasyte** [comment]
Zoom can be done pretty easily thanks to #704 !See the forum post for details: https://groups.google.com/forum/#!topic/melonjs/fAtFFe2wvCo

How we want to expose this to end users is an open question!

**Comment by obiot** [comment]
i think this ticket can now be closed together with #335 (see there for example) since we do now (and finally) provide a clean way to zoom and even apply any transformation to the level without impacting the viewport.
