### ISSUE TITLE
Tween - broken when moving the screen around on iOS (Safari)

### ISSUE THREAD

**Issue by Tokyonono** [melonjs/melonJS#141]
There is a strange behaviour with "Tween" on iOS (Safari). If you move the screen around with your finger after the tween started, the moving object won't reach its destination.

This issue can be tested on Three-cup Monte :
http://nine-software.com/game/three-cup-monte/index.html

**Comment by obiot** [comment]
I'm closing this one, as I tried to reproduce it without any success, and it's more an issue on old version of iOS (that is not supported anyway)
