### ISSUE TITLE
Performance: Array.splice() is REALLY slow

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#192]
`Array.splice()` is a handy function. But it's awfully slow! It's the reason for the performance problems in ticket #103. `Array.splice()` is used in our `Array.prototype.remove()` (which is also quite handy).

Here is an interesting test case I made: http://jsperf.com/array-modifiers

These tests are not all apples-to-apples. First, the tests are useful to compare to one another in the following groups:
1. `array` vs `object`
2. `pop` vs `array-undefined` vs `global array-undefined`
3. `object-zero` vs `global object-zero`

The "winners" from groups 2 and 3 can then be compared directly. In my test on Chrome 27, `global array-undefined` was fasted for group 2, and `object-zero` was fasted for group three.

Now in group 1, I have two numbers indicating the relative speed: `array` gives ~32MM, and `object` gives ~12MM, meaning `object` is over 2x slower. But that doesn't immediately discount `object` as being slower overall!

Looking more closely at group 2, `array-undefined` is almost exactly the same as the `global` variation, except they access an array in different scopes. The performance for the local scope test is HORRIBLE! ~11MM vs ~149MM (and `pop` is pretty bad too, at only ~16MM)

Now looking closely at group 3, both perform very well; ~135MM and ~107MM respectively.

This tells me arrays have strange scoping problems in Chrome. It also tells me that iterating an object with a for...in loop and "removing" object properties by setting its value to 0 is going to be much faster than iterating arrays that need elements removed in ALMOST ALL CASES.

Ok, now back to the issue with `Array.splice()` ;)

Since `Array.splice()` and `Array.pop()` tend to have pretty bad performance characteristics, I suggest replacing the `Array.prototype.remove()` implementation with a simple overwrite-with-undefined, and updating all of our array iterations to test for `undefined`.

Alternatively, if elements are going to be created and deleted often, it might even be better to use objects, instead. Not that I'm using objects as if they are sets; the key is the data I'm interested in, and the value is only a boolean flag to tell if it's been "removed".

**Comment by adrianhartanto0** [comment]
What's the status of this issue?

**Comment by obiot** [comment]
no real change on since one, the idea was to see if there was any other solution that are faster than manipulating an array using splice (maybe a map or a linked list, or anything else) and does not trigger object re-allocation, and while keeping it simple; and the status as of today is that so far nothing has been pushed forward.

this said, on modern browsers this is not really a big issue, not to mention that this is not used in performance critical part of melonjs (mainly when object are removed, which does not happen massively on each frame).

**Comment by obiot** [comment]
closing Thi
