### ISSUE TITLE
Extend version checking capabilities

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#208]
It will be most useful to have extra version checking capabilities for plugins. Eg node syntax like "~0.9" matching 0.9.\* (I think that is how it works...)

And we should also consider a new version scheme for minor updates vs API breaking updates. This will be especially important for plugin compatibility.

**Comment by obiot** [comment]
Closing this one, greater or equal for what we do of plugins is good enough, i don’t see it as enough as a necesssity to justify the required additional code in the engine
