### ISSUE TITLE
Keep melonJS lightweight!

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#212]
This has been discussed in various places. We all agree we want to help keep melonJS very "lightweight". I guess there are a few ways to do this. Two options I can think of off the top of my head, both require making melonJS components very modular (easy to remove or replace as necessary):
1. Move "heavy" and "uncommon" modules into plugins.
2. Support modular builds.

I really like the first option, since it can make use of the already-available plugin API. The second option makes it sound like melonJS is "bloated" by default. :( Just look at other frameworks with similar "custom build" options, like jQuery-ui/themeroller. And every time I want to update jQuery-ui, I have to redo the tedious custom build steps all over again...

But the first option has some problems, too. Like some plugins might not get much attention during development, or could be an extra maintenance burden.

Either way, melonJS core should be good enough for simple games, and extend it as needed for more advanced projects!

**Comment by parasyte** [comment]
I'm thinking more and more about this one. Wouldn't it be cool if we could use melonJS for competitions like [js13k](http://2015.js13kgames.com/)? Sadly, melonJS-2.1.3 clocks in at just under 52KB minified and gzipped!

With this ticket implemented, we could just strip the unnecessary parts (pretty much everything except the "core" game loop) and have a nice 2KB game engine to start with! That can't be done today, because so many things are tightly coupled; game.js is useless without container.js, which is useless without the entire renderable hierarchy, and matrix and vector classes (at a minimum). The viewport is also required by game.js, which itself depends on tween and minpubsub... And oh geez, the entire renderer infrastructure is needed? That's a non-trivial chunk of code.

What I'm saying is, it's going to be a lot of work to decouple classes enough to make the engine modular. But the benefits are undeniable; this work needs to be done some day.

**Comment by obiot** [comment]
1. melonJS is the smallest framework out there : ~200Kb minified, vs almost 1MB for any others
2. for specific ~10k competition, I believe people use their own mini-library, and I do not want to spend time (nor have the time) working on a possible strip down version of melonJS specifically for it (I'd rather focus on something more interesting in terms of business)
3. proper module support (see #915) should allow to have tailored version of the library
4. this is a 5 years old ticket, and nobody never try to address it !
