### ISSUE TITLE
Support setting global melonjs flags through URL #tag

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#214]
Dunno if my description is clear, but the idea would be to automatically set global Boolean flag if the corresponding name is found in the URL like used in the template today with #debug

**Comment by obiot** [comment]
quick question, where would we make these properties available ?

`me.game.url.options` ?

**Comment by parasyte** [comment]
In my games, I always used the name `HASH`, as that's what it is referred to in the `document.location` object. You might also consider using the parser and hashchange listener: https://github.com/blipjoy/kungfustar/blob/gh-pages/public/js/config.js

**Comment by obiot** [comment]
I'm ok with HASH, but i'm just trying to find the right place where to put, could just be `me.HASH` actually :)

**Comment by parasyte** [comment]
I like it under the `me.game` namespace, for sure. The `me` namespace is already quite crowded. We can get all kinds of performance improvements just by thinning it out. :)

**Comment by obiot** [comment]
would be nice to document this and list the "supported" tags, but I have no idea where to put it :)
