### ISSUE TITLE
Performance: merge prerendered layers

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#216]
I can see this being a pretty big win for large maps with lots of layers. Most of the time, a map is entirely static... There might be a few parallax layers, and maybe an object layer sandwiched between two tile layers, etc. But there are cases where we could (and should!) merge static tile layers when pre-rendering is enabled.

One of the reasons for moving to the "dynamic rendering" method in 0.9.4 was to reduce memory cost. Pre-rendered layers have very high memory consumption with a large map, but memory usage is _doubled_ when there are two layers in the map, and **_quadrupled**_ with four layers, etc. If we could determine at parse-time which layers can be merged into a single canvas, then we can benefit from the improved speed offered by the pre-render feature, as well as reducing the memory footprint AND overall drawing time.

**Comment by obiot** [comment]
interestingly the next Tiled version will have a group layer features, which means that we now have a proper "standard" way to merge layers from the same group.

https://github.com/bjorn/tiled/issues/1038

**Comment by obiot** [comment]
with #876 being done, this one should be one step easier to be done.
