### ISSUE TITLE
new BMFont Beta

### ISSUE THREAD

**Issue by Zaraka** [melonjs/melonJS#279]
As I promised, I wrote javascript parser for BMFonts. You can check it at http://zaraka.github.io/BMFont/ (loading can be a bit longer).

So what exactly is it?
Half year ago I found project now hosted on http://bmf.php5.cz . Someone create a new file format that can store simple bitmap fonts in raw data. Format description can be found here http://bmf.php5.cz/bmf-format.htm
However the format is quite old and it have some cons. Lets sum it up

Pros
* Simple and lightweight
* Many fonts avaible

Cons
* Only ASCII characters!!!
* Only 32 colors for a font
* Only 6 bits per color channel!!
* Parsing can take long time

So it's not exactly a miracle, but I still found them usefull.
Q: That site you posted have some strange behaviour!
A: Yes, I emailed with admin a few months back. He moved his site from bmf.wz.cz. It looks like moving process isn't finished. **But** he said something about creating a **new font version and redesign web**. I will keep in touch with him and help him with this proccess.

And now a few words about parser. It isn't finished, draw method is half-implemented, other methods missing completely and there will be bugs. For making this work I needed to upgrade me.loader for loading ArrayBytes.

The main question is. Are you interested to making this a part of melonJS? If you are I will write proper pull request and put BMF_Font and BMF_Char classes into melonJS core.

**Comment by agmcleod** [comment]
Something like this i feel is a much needed improvement to our bitmap font loader, which is pretty limited. A lot of other frameworks support things like bmGlyph, and formats smilar. I'm honestly not sure how best to even generate a bitmap font file for what we currently have.

**Comment by obiot** [comment]
indeed that would be nice 

note that shoebox also allow to generate bitmap fonts :
http://renderhjs.net/shoebox/bitmapFont.htm

**Comment by obiot** [comment]
just found this one too, by searching on google :
http://kvazars.com/littera/

pretty nice tool

**Comment by agmcleod** [comment]
Yeah i use bmglyph. I have fairly good control about what I can generate. Wasn't sure what the dependent order is for our bitmap implementation, nor was i certain on the sizes to specify. Does it need to be a single row image? Can it be on multiple? There's just a lot we're not documenting here ;). But given other libraries support these formats with meta files, it might be a good idea for us to do so as well.

**Comment by agmcleod** [comment]
I think given the limitation of ascii, using this might be the way to go; http://www.angelcode.com/products/bmfont/. Found this in looking through libgdx's docs on their bitmap font support.

**Comment by obiot** [comment]
The good thing is that this is what zaraka used here above (see also at his repo  https://github.com/Zaraka/BMFont/blob/master/Javascript/font.js) .
The bad thing however (at least for me) is that there is no OSX (oups.... sorry macOS) version of the tools

**Comment by obiot** [comment]
when you start adding this, make sure you do it first on a separate branch, so that we can include that in a next 4.0 version (or 3.2, as this would not break any API i'd say)

**Comment by Zaraka** [comment]
Hello,
Nice to see, someone is interested. I withdraw my attention from BMFont when I realized that standard and community is dead. Also my implementation is quite terrible work of naive student. I never found a good replacement, nowadays everyone use TTF.

**Comment by agmcleod** [comment]
Yeah for sure. One can do that with webfonts pretty easily, just doesn't work that well with WebGL, as you need to pass it a texture to draw. My aim for the angelcode/bmfont is that a number of engines seem to support it. Pixi therefore Phaser is one of em. It would be neat to see freetype get compiled with emscripten to work in the browser, but that sounds like quite an ordeal ;)

**Comment by obiot** [comment]
@agmcleod there is actually an OSX client :P
https://71squared.com/glyphdesigner

**Comment by agmcleod** [comment]
Haha. Yeah i use bmglyph as well :)

**Comment by parasyte** [comment]
IMHO, using vector fonts is the future.

* https://developer.nvidia.com/nv-path-rendering
* ["Path Rendering Acceleration", page 29](https://www.khronos.org/assets/uploads/developers/library/2012-the-graphical-web/GPU-to-the-web_Sep2012.pdf)
* [Chromium already supports this extension](https://chromium.googlesource.com/chromium/src/gpu/+/master/GLES2/extensions/CHROMIUM/CHROMIUM_path_rendering.txt) (but not currently exposed to WebGL)

Even if we can't use path rendering natively in WebGL (yet) we should focus on it for fonts and for #648 Way better than dinosaur bitmap fonts!

**Comment by parasyte** [comment]
Some resources mentioned here are probably worthwhile of exploring: http://stackoverflow.com/questions/12951459/nv-path-rendering-alternative

**Comment by agmcleod** [comment]
Aw, but dinosaurs are cool!

Given the timeline of things, I wonder if supporting bitmap would be worth while. Not an uncommon practice, and it works in both canvas & webgl today.

**Comment by obiot** [comment]
well my point is that it should still work with a simple fix font size bitmap, after it does not mean that we cannot completely revamp the object itself, and manage this through a simple "settinng" object to be passed to the constructor (with just the font width and height)

**Comment by agmcleod** [comment]
@obiot then I should probably set this up as another class entirely. They would be handling sets of data quite differently. For them to be the same class would lead to a lot of confusing code.

**Comment by obiot** [comment]
@parasyte #648 would be great if you have any free time :):):)

**Comment by parasyte** [comment]
It would be really cool! I don't think I'll have time for it though. ;(

**Comment by obiot** [comment]
@agmcleod adding the following in the todo list :)
https://github.com/melonjs/melonJS/wiki/How-to-generate-and-use-Bitmap-Font

**Comment by agmcleod** [comment]
https://github.com/melonjs/melonJS/pull/792
