### ISSUE TITLE
Performance: asm.js

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#282]
[asm.js](http://asmjs.org/) is a new standardization effort pioneered by Mozilla to specify a subset of JavaScript that can be statically compiled directly to native machine code resulting in runtime results that are much faster than compiling straight (dynamic) JavaScript.

asm.js modules are defined as functions tagged with the `"use asm";` directive prologue, and requires the function be valid asm.js (eg. using only the specified subset). Here's an example from the specification:

``` javascript
function DiagModule(stdlib) {
    "use asm";

    var sqrt = stdlib.Math.sqrt;

    function square(x) {
        x = +x;
        return +(x*x);
    }

    function diag(x, y) {
        x = +x;
        y = +y;
        return +sqrt(square(x) + square(y));
    }

    return { diag: diag };
}

var fast = DiagModule(window);     // produces AOT-compiled version
console.log(fast.diag(3, 4));      // 5
```

While not all of melonJS can be rewritten for asm.js, I have a hunch that a lot of the simpler low-level functions can easily take advantage of this new technology (which can currently be used in Firefox, if I'm not mistaken!) Another option is using a JavaScript-to-LLVM compiler [to my knowledge not yet available] with [Emscripten](http://emscripten.org/) to compile all of melonJS to an asm.js equivalent. ThIs compilation step will provide vastly improved performance on browsers that support asm.js.

**Comment by obiot** [comment]
not seeing this one happening, and not in my roadmap, so unless someone wants to step in, I'm closing it.
