### ISSUE TITLE
TMX tileset image loading issue

### ISSUE THREAD

**Issue by petarov** [melonjs/melonJS#296]
Hi,
I think there (probably) is a minor bug when loading TMX tilemaps.

In `TMXTileset.js` at [this line](https://github.com/melonjs/melonJS/blob/master/src/level/TMXTileset.js#L236) the source path/name of the tileset image file is resolved. However, in `me.loader.getImage` the lookup (in `imgList`) is actually done using the `name` field rather than the `src` field. 
Therefore, if the name of the tileset is something different than the image file name, the image won't be found.

Example:
_in resources.js:_

``` json
    {name: "agent", type: "image", src: "assets/agent_fa.png"},
```

_in tilemap.tmx_

``` xml
   <tileset firstgid="401" name="agent" tilewidth="32" tileheight="32">
   <image source="agent_fa.png" width="576" height="256"/>
   </tileset>
```

**Comment by NemoStein** [comment]
I don't know current state of this, but I just stumbled upon this issue.  
Embedded tilesets in Tiled have a name, which I assumed to be mapped to the manifest `resource.name`, but found out that Melon uses the `<image source="...">` basename to find the asset.

> Probably not a bad idea to change it to use the name field instead, to offer that flexibility.

This is what I expected.

Melon 13.0.0
Tiled 1.9.0
