### ISSUE TITLE
me.Sprite.anchorPoint should specify position anchoring

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#309]
Right now, sprites are always drawn with their upper-left corner, regardless of the `anchorPoint`, which is only used for scaling and rotation. `anchorPoint` should also be used for positioning.

**Comment by obiot** [comment]
tagging this one for 3.0.0, following the changes on #715 !

**Comment by parasyte** [comment]
ooooh, really?! This is excellent! I'll have to check out #715 tomorrow. :)
