### ISSUE TITLE
Improve build system to test private methods

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#318]
I want to write a test for #316 but there is a problem; I need access to the `keydown` and `keyup` private functions to properly test this feature. My preferred solution is exposing private methods and properties in a special `_unittest_` namespace that only tests can access, and the build process will strip them out.

The pattern is explained more thoroughly here: http://philipwalton.com/articles/how-to-unit-test-private-functions-in-javascript/

We should make improvements to the grunt build system to make this happen. :)

**Comment by obiot** [comment]
same comment as #126, + 5 years old + did not really bother anyone
