### ISSUE TITLE
Collision with object in another container does not account for container offset

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#330]
If you have a box at 100, 100 by 100,100. Then you have a container at 50, 50. by 500, 500. The container contains a box of 50, 50, by 50, 50. The box in the container should overlap, but it doesnt because 50x50 50w 50h is compared with the original box instead of the container position + the box position.

**Comment by parasyte** [comment]
@agmcleod Status update on this one?

**Comment by agmcleod** [comment]
Don't even recall the test case lol. But knowing how well everything seems to work since we did the absolute position changes, ill close.
