### ISSUE TITLE
Better entity persistence management

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#375]
This is something I've been wanting for a long time, and now seems like a good time to formalize it.

There is an issue with mixing TMX entity references with the `isPersistent` property. E.g. I have the player entity referenced in my "level1.tmx" map, and the `PlayerEntity` class sets `isPersistent = true`. After "level1" is loaded, the player entity is created, and it persists across level loads and state changes. This works well as long as "level1" is not loaded more than once. But in a non-linear game, loading a map multiple times is inevitable.

I would like to brainstorm some ideas to make this work better. I'm really, really happy with making games that are data-driven; you write a little code for entity AI and drawing, and that's all you need for coding. The rest of the game is built by adding maps!

To that end, I think even persistent entities should be defined in at least one map, possibly define it in multiple maps! The TMX loader just needs a way to know whether an entity is persistent, and whether it is already active.

Here is one idea to get things rolling:
- Add an object property to the entity reference in the map, like `isPersistent = true`
- The TMX loader first checks if this persistent entity was added to the world.
  - If yes, do not create another.
  - If no, create a new persistent entity.

**How to identify existing persistent entities?** Would be easy if we could look up entities by class name. Also probably relevant : #302.

And a recent thread on the forum : https://groups.google.com/d/msg/melonjs/_uhC7f_qm1w/WjUBZc2Qr_EJ

**Comment by obiot** [comment]
stalling one
