### ISSUE TITLE
Better animation definitions

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#390]
Animations implicitly use the same same "speed" property for every frame of the animation. Even the simplest animated gifs have the ability to define time delays on each individual frame. This provides some additional control in how an animation plays.

For example, you might be animating a character's attack, which needs a short "pause" cycle to telegraph the coming attack (which a skilled player will identify, and be able to respond with a block or counter-attack). The pause cycle may actually be two or three frames long, while the rest of the animation plays at full speed. With today's animation definitions, an animation like this must be defined as:

```javascript
{
    "frames" : [ "telegraph", "telegraph", "telegraph", "punch1", "punch2", "punch3" ],
    "speed" : 30
}
```

Where the `"telegraph"` frame is duplicated to create the illusion of a short (~90ms) pause. We can make this better by setting the delay on a per-frame basis:

```javascript
{
    "frames" : [
        { "name" : "telegraph", "delay" : 100 },
        { "name" : "punch1", "delay" : 30 },
        { "name" : "punch2", "delay" : 30 },
        { "name" : "punch3", "delay" : 30 }
    ]
}
```

This example shows that the `"telegraph"` frame will be displayed for at least 100ms, and the other three frames for at least 30ms each.

Also notice that the single frame names have been replaced with a dictionary; we can include extra per-frame meta data here, like scale, angle, alpha, background color, composite operation, ... Just for much better control over how each frame is drawn. Some of these can also be Tweened :warning: for smooth animations.

**Comment by parasyte** [comment]
This seems like a good place to mention a minor bug reported on the forum. The animation frame timing is a "minimum frame timing", and needs to be turned into an "absolute frame timing" by taking into account the total elapsed time, and picking the correct frame to display. Right now the next frame in the sequence is always chosen, even if the frame rate would have caused animation frames to be dropped.

See: https://groups.google.com/d/msg/melonjs/mM4BdyQyNY8/ygEJUIPvDJwJ

**Comment by obiot** [comment]
indeed that makes sense, although if ones lower the frame rate, and if the animation speed is not adjusted it would result in skipping frame, might be confusing/disturbing as well I suppose ?

**Comment by obiot** [comment]
so this one is done ?

**Comment by obiot** [comment]
i guess we can properly fix the tmx tile animation stuff then now :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXTile.js#L138

:)

**Comment by parasyte** [comment]
No, this one's not nearly done.

What's broken about the tile animation that you linked to?

**Comment by obiot** [comment]
as far as I remember, we can only define a fix interval between all frames, and Tiled can specify a different one ? or am i mistaken ?

**Comment by parasyte** [comment]
Oh yes! You're right. This ticket could fix that. We still haven't updated the APIs to allow it, though.

**Comment by agmcleod** [comment]
Hmm, do we want to allow usage of both APIs? Indexing with 0 through numbers with one animation delay is kinda nice & easy. Doing something like: `{ name: 0, delay: 10 }, { name: 1,  delay: 10 }, { name: 2, delay: 10 }` Could be annoying.

**Comment by obiot** [comment]
honestly, this one could be done easily in a backward compatible way :
- if the `former` speed is specified, it shall be used to construct the whole animation timing in the `delay` style
- if the new `delay` format, it can be directly used

right? or am i missing the point of your question ?

**Comment by agmcleod** [comment]
Nope, i think it makes sense. What i'll do is check the value of each iteration in the array. If it's a string or number, build an object with the delay of the animationspeed. if it's an object, let it do it's thing.

**Comment by obiot** [comment]
we can close this one then :)
