### ISSUE TITLE
Enable global transformation for the viewport/screen canvas

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#399]
- fix the positioning issue mentioned in ticket #379 

```
When using screencanvas with a webgl context, CSS canvas scales are omitted, 
so your game might not render in full screen. To fix this issue scale or layout your 
game with a projection matrix instead of using canvas.style
```
- clean the me.game.currentLevel.pos ( i want to get rid of this) with something cleaner
- the `localToWorld` and `worldToLocal` should also takes that global transformation in account when translating coordinates.

**Comment by parasyte** [comment]
Here is some good info related to this ticket: http://webglfundamentals.org/webgl/lessons/webgl-anti-patterns.html Especially the recommendation to use `canvas.client[Width|Height]`

And really, all the info on this website is excellent. I met the author on a few occasions.

**Comment by parasyte** [comment]
Also #590

**Comment by obiot** [comment]
and #701 ?

**Comment by obiot** [comment]
i like what is he saying about the resize function, instead of relying on the resize event, just check at the beginning of each frame if you need to resize ! instantly solve how to do polling and avoid resizing 1,000 times per frame when dragging the window :P

**Comment by obiot** [comment]
with the last commit, adding this code anywhere, will produce a nice zoom out effect :
```javascript
        var viewport = me.game.viewport;
        viewport.currentTransform.translate(
            viewport.width * viewport.anchorPoint.x,
            viewport.height * viewport.anchorPoint.y
        );
        viewport.currentTransform.rotate(0.10);
        viewport.currentTransform.scale(0.995);
        viewport.currentTransform.translate(
            -viewport.width * viewport.anchorPoint.x,
            -viewport.height * viewport.anchorPoint.y
        );
````

I still need to check as well the localToGlobal and globalToLocal function, so that the pointer event also work when the viewport is "transformed"

**Comment by dynamo-foundation** [comment]
This code does not work when combined with 
me.game.viewport.follow(this.pos, me.game.viewport.AXIS.BOTH, 0.4);


        var viewport = me.game.viewport;
        viewport.currentTransform.translate(
            viewport.width * viewport.anchorPoint.x,
            viewport.height * viewport.anchorPoint.y
        );
        viewport.currentTransform.rotate(0.10);
        viewport.currentTransform.scale(0.995);
        viewport.currentTransform.translate(
            -viewport.width * viewport.anchorPoint.x,
            -viewport.height * viewport.anchorPoint.y
        );
