### ISSUE TITLE
improve me.pool object initialisation and API

### ISSUE THREAD

**Issue by insidiator** [melonjs/melonJS#423]
Editing a bit the ticket description and title 

* [ ] improve object initialisation (see below initial ticket from insidiator)

> Today I started to use pooling in my game and the first thing I noticed is that it currently calls only the `init` method when an object is created, but calls both `init` and `onResetEvent` when an instance already exists.
> 
> In my opinion it would be better to call `init` only when the object is created for the first time and always call `onResetEvent`. That way I can do stuff that only has to happen once, like creating vectors or similar in the `init` method and reset parameters in `onResetEvent`.

* [ ] add destroy & onDestroy to renderable, see #448

**Comment by obiot** [comment]
pooling system will be revamped as part of the switch to standard es6 inheritance mechanism in the next 10.0 version

**Comment by obiot** [comment]
this one is done, moving to ES6 also made things much easier.

- `OnResetEvent` is now called only when pulling an existing instance from the pool, else only the constructor is called for new ones
- Only objects that are registered with the "pool" flag set to true, and that implements a `onResetEvent` function can be recycled (and actually have their instance being pushed and pulled from the object pool).
- On Object "destruction" (i.e. removed from a container), `destroy` function is not called if an object can be pooled (see above) and put back as it in the object pool
