### ISSUE TITLE
Normalize game object constructor arguments

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#431]
Fair warning: This is another massive change proposal!

One of the annoying things about the class inheritance is that base classes often accept completely different argument lists compares to the classes which extend them. For example, `me.Renderable` takes a `pos` vector, `width`, and `height` arguments. But `me.SpriteObject` takes `x`, `y`, `image`, `spritewidth`, and `spriteheight` arguments! ACK!

There's also the issue with the TMX parser creating objects; it uses `me.pool` for this. The pool is already very generic; it can accept any argument list. The TMX parser only wants to send argument lists that match the `me.ObjectEntity` footprint, except for Tile Objects, because those are implemented as a `me.SpriteObject`, and the argument lists are not compatible:

https://github.com/melonjs/melonJS/commit/35e1904a9a410647a3fb5aba76cdc52535fe2eeb#commitcomment-5375412

Another annoyance is that most objects do not accept a `z` argument in their constructor, and only a few actually do (just the TMX layer objects). Having this is super handy, since you can simplify code that otherwise must be written like this:

```javascript
var obj = new me.ObjectEntity(x, y, settings);
obj.z = z;
me.game.world.addChild(obj);
```

There's an easy solution! Normalize the constructor for all game objects (including non-renderable ones like `me.Tween`?) to accept a single dictionary as its first argument. Classes my choose to accept other arguments as well, but a single dictionary should be capable of passing infinite parameters, anyway! :)

The little snippet above could be simplified to:

```javascript
me.game.world.addChild(new me.ObjectEntity(settings));
```

And the constructor would apply the position, z-index, name, image, etc. based on keys in the `settings` dictionary.

As a bonus, this pattern also allows for optional and default parameters using the `jQuery.extend` pattern. (Described here: https://github.com/melonjs/melonJS/issues/423#issuecomment-34969389)

**Comment by obiot** [comment]
Hidden in the #592 changes, lies the here discussed changes on `me.Sprite` and `me.AnimationSheet` as both consctructor have been "normalized" wiht the following function signature : `(x, y, settings)`

**Comment by parasyte** [comment]
Don't forget:

* [ ] debugPanel plugin
* [ ] Platformer tutorial

**Comment by obiot** [comment]
damn I hate you ! :P

**Comment by obiot** [comment]
what's the link with the debugPanel btw ?

**Comment by parasyte** [comment]
Good point! I spotted this in a quick search, but it doesn't have anything to do with the constructor: https://github.com/melonjs/melonJS/blob/cc79a646d9c3c33f5dd986e18e1712a2730a1e85/plugins/debug/debugPanel.js#L180

**Comment by obiot** [comment]
what's left for this one ? (except from the tutorial update?)

**Comment by parasyte** [comment]
@obiot That's all I'm aware of.

**Comment by obiot** [comment]
then I propose we close it, anyway the "tutorial update exercise" is part of the release process :P

**Comment by parasyte** [comment]
There are some other `me.Renderable` subclasses that could use normalized constructor arguments, like `me.ColorLayer` and `me.ImageLayer` ...
