### ISSUE TITLE
Memory growth

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#434]
I wrote the simplest melonJS app you can possible write; one that doesn't do anything at all. Here's the complete code:

``` javascript
var game = {
    "onload" : function () {
        // init the video
        if (!me.video.init('screen', 640, 480, true, 'auto')) {
            alert("Sorry but your browser does not support html 5 canvas. Please try with another one!");
            return;
        }

        // set the "Play/Ingame" Screen Object
        me.state.set(me.state.PLAY, new PlayScreen());

        // switch to PLAY state
        me.state.change(me.state.PLAY);
    }
};

var PlayScreen = me.ScreenObject.extend({});

/* Bootstrap */
window.onReady(function onReady() {
    game.onload();
});
```

I let it run for 1 minute, then recorded a memory profile for one more minute, to capture a baseline. This was the result:

![screen shot 2014-02-15 at 4 38 12 pm](https://f.cloud.github.com/assets/456942/2179322/e82e5f3e-96a2-11e3-982e-60b74b74e238.png)

It started out looking like a sawtooth from garbage collection. After a minute, GC still hadn't kicked in, so I stopped profiling at that point.

It's pretty clear that melonJS creates at least 1MB of garbage per minute without even doing anything.

**Comment by obiot** [comment]
does it still make sense to keep this one open ?

**Comment by parasyte** [comment]
We haven't profiled in a while. ;)

If we close it, maybe there's a better way to automate profiling. Ideally with graphs that show the changes between each build. We could potentially have Travis-CI pipe statistics to [Librato](https://www.librato.com/) from automated test suites. (The developer plan is free, but only retains data for 2 weeks.)

**Comment by agmcleod** [comment]
Ran a profile on the platformer. I think the flat line it does is wrong, i wonder if the profiler just runs out of memory or something to capture the data. But it still has a slow climb

![image](https://cloud.githubusercontent.com/assets/113275/10836918/04bc250c-7e8a-11e5-8d94-5413b5dbc200.png)

I have the json data saved. Can send it if you want.

**Comment by obiot** [comment]
so I did some profiling this afternoon, and saw no evidence of a memory leak, so unless someone can come up with some further evidence, I see no value in keeping a ticket open to "remind us to be careful" :)
