### ISSUE TITLE
Add destroy & onDestroy to renderable

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#448]
@obiot @parasyte Please close if you simply don't agree, but was thinking since container checks for a destroy function when removing an object, I don't see why the base renderable can't implement it. Have the user simply extend `onDestroyEvent` to keep the pattern consistent with things like Sprite, ScreenObject, etc.

https://github.com/melonjs/melonJS/blob/1.0.0-dev/src/renderable/sprite.js#L321

**Comment by obiot** [comment]
closing this one in favour of #423, for the sake of simplicity !
