### ISSUE TITLE
Align me.Matrix2d API with the DOMMatrix API

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#476]
see here : http://dev.w3.org/fxtf/geometry/Overview.html#DOMMatrix

(assuming we don't end up using the matrix object as defined by Pixi)

**Comment by parasyte** [comment]
What to do with this one?

**Comment by obiot** [comment]
Well the idea was simple, just to rename our matrix API to look more lile the standardized DOM one

**Comment by obiot** [comment]
maybe i will close this one. Our matrix implementation is quite simple for now, and I don't really see anything to change (nor the need to add anything)
