### ISSUE TITLE
Better release strategy (with bower)

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#508]
@agmcleod @obiot I have been investigating [bower](http://bower.io/) more closely, which was discussed a bit in #227.

My understanding of the bower package manager ecosystem is still vague, at best. But it does appear to be useful for the distribution of *pre-built* melonJS releases -- something we are NOT doing with it yet.

In my experiments, I installed jQuery using `bower install jquery` in an empty directory. It creates a subdirectory called `bower_components` (synonymous to `node_modules` with `npm`) and jQuery is installed there. What's interesting to note is that in the `jquery` subdirectory, there's the full source code, plus the pre-built js files in a `dist` directory. And the bower manifest points to one of these dist files: https://github.com/jquery/jquery/blob/master/bower.json#L4

But if you look at the jQuery repo, you'll see that there is no dist directory, and in fact, it is ignored in `.gitignore`! But if you check out their latest tag, you will indeed find the dist directory: https://github.com/jquery/jquery/tree/2.1.1/dist This means the `2.1.1` tag is not in any branch. So jQuery's dist/bower register step must detach the branch, commit the dist files, tag the commit, and push the detached tag.

This is the flow I tested in a new repo, and it works really well: https://github.com/parasyte/hork The build directory is purposefully empty (just a placeholder) And I have made three tags, each with a different build file that never touched a branch, with all tags having histories from different points in the master branch. Here's how we might do this with melonJS:

```
grunt
git checkout --detach
git add -f build/melonjs-1.0.1-min.js
git add -f build/melonjs-1.0.1.js
git commit -m "Release 1.0.1"
git tag 1.0.1
git push origin 1.0.1
```

What we're doing here is building the dist files with grunt, then detaching from the branch and committing the dist files in the detached state. This creates the commit sha1 in git history, but the commit isn't really linked anywhere. To link it with something, a tag is created (which integrates with the github release mechanism) and the tag is pushed to remote (github) to create the release.

And of course, all of these steps can be automated to pull the version number from package.json.

With all of that done, we should be able to `bower install melonJS` and get the dist files (plus source code) installed into our project when starting a new game. No need to build melonJS, no need to install any build dependencies, and finally the `npm install` task does not need to run bower; they can live entirely independent of one another, the way it should be.

----

Final note: This takes us back to our current release strategy of just using tags to keep track of releases. That much won't change. But what will need to change is how the "Stable" branch is initially created. I'll use "1.1.0" as an example for when we start to work on "1.2.0":

1. `master` is the current "1.1.0" development line. We want to start working on "1.2.0".
2. Create a new branch from `master` named `1.1.x`.
    1. Create a new detached tag (see above) named `1.1.0` containing dist files.
    2. Continue work in the `1.1.x` branch, with periodic detached tags for releases. 
    3. Never commit on top of a tag.
3. Update all version numbers in `master` to "1.2.0".
4. Continue work in the `master` branch for unstable/experimental features in the 1.2.x line.

**Comment by luiscoms** [comment]
Add dependency of MelonJS isn't working yet?

**Comment by parasyte** [comment]
This one is fixed. I had a lot of trouble with the last little stretch, but it's now working with rollback on failure cases!

The new release command is:

```
$ grunt release
```

Requires `npm update` to install new dependencies. The first release to use this will be v2.2.0.

**Comment by obiot** [comment]
Ooohh nice !

So basically "grunt release" will do the whole release stuff ?

**Comment by parasyte** [comment]
Yep, it does! There's a followup ticket for a few minor things left to do.
