### ISSUE TITLE
[isometric] - Collision detection not working properly

### ISSUE THREAD

**Issue by eschnou** [melonjs/melonJS#52]
The issue is related to #51 and the fact that in an isometric world, the tile 0 is in fact not at position (0,0) on the screen. This means that when the getTile(x,y) position is invoked for collision detection, the wrong tile is returned.

I guess this could be fixed by either managing the isometric case in a different way in the getTile function, or by computing xLUT and yLUT in a different way when in an isometric level.

**Comment by jumpjack** [comment]
How do I enable debug panel in melonJS 2?

**Comment by obiot** [comment]
https://github.com/melonjs/es6-boilerplate#debug-plugin

**Comment by jumpjack** [comment]
and how do I enable devrlopment mode? I am not very expert, I don't know anything about wasm, em6, ecmascript, boilerplate or whatelse, I use plain javascript.
