### ISSUE TITLE
TMXUtils.applyTMXProperties changes the object's hidden class

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#527]
`TMXUtils.applyTMXProperties` applies properties directly to the object, which is undesirable for the following reasons:
- It changes the object's hidden class (V8 implementation) which will defeat JS engine optimizations.
- It increases the number of properties on the object, further defeating other JS engine optimizations.
- It's impossible to document thoroughly.

I would like to see this resolved by adding a new Object property added to all classes that need TMX properties: `TMXTileMap`, `TMXLayer`, `ImageLayer`, `TMXObjectGroup`, `TMXObject`, `TMXTileset`. The new Object might be called `properties`, or `TMXProperties` ... `TMXUtils.applyTMXProperties` just has to add the properties to this Object property instead. This can also be documented easily as "an object containing the TMX properties defined in the map..."

**Comment by obiot** [comment]
`TMXUtils.applyTMXProperties` is now only called from other objects constructors, which therefore close this ticket.
