### ISSUE TITLE
Tiled 0.10 support

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#542]
It's coming soon now, so....

Changelog : 
https://github.com/bjorn/tiled/blob/master/NEWS

I did not yet go through it properly but first existing ticket(s) that I see useful here :
- #540 add rotation support for polyshape (as tiled now also support rotation from within the editor)

Other potential breaking changes (to be further analyzed) :
- Changed object position and size units from tiles to pixels (by mauve)

**Comment by metaunicorn** [comment]
I know this is old and I am new to MelonJS and I don't know if it's possible currently, but it will be very helpful to be able to extend the Melon TMX engine via plugins, so we can easily adopt other ways to interpret the maps and support new features quickly.

We won't have to wait for new versions of Melon and the cool part is that it will be a way to contribute if the author decides to do so and you want to integrate that into the core.

One strategy to optimize the Tile Collision support is to merge the collision object of all subjacent identical tiles into a single collision mesh, like it has been suggested before. It may not be convex though, so the collision algorithm may need changes.

**Comment by agmcleod** [comment]
@metaunicorn One can use the plugin mechanism to modify existing classes. Otherwise, one could leverage some of the higher base classes to make their own version of the level director. It's worth noting that collision is done purely through shapes. They have to be convex, but otherwise you can batch large sections of the tiles with one shape for collision.

**Comment by obiot** [comment]
I would love to have Tiled as a plugin or a separate library, even just the parser. we have a ticket for that here https://github.com/melonjs/melonJS/issues/513, but we never really had the time to give it that much thoughts.... if you have any idea/proposition on defining what could be a generic API that would suit Tiled and any other tools, that would be a great start !

for the tile collision merge, we also have that ticket : https://github.com/melonjs/melonJS/issues/216 
but I would rather agree with Aaron, as batching large sections is probably easier than changing the SAT collision algorithm to work with convex shapes (that is mathematically designed for concave shapes)

else, is there anything you are missing right now in Tiled, or is this just a general remark ? to be fair, I think the current support in melonJS is quite good (even very good to be honest)

**Comment by metaunicorn** [comment]
I don't miss anything else for now, the framework is awesome and I could quickly get things done.
It is amazing that I can play with my game directly after modifying my maps. You did a very good job with this library and I hope it will be becoming better and better.

If I find a way and have ideas to contribute with it of course I will. Right now I am still learning the API ;) (I will need some help but I think I will post it in the google forums).
Thanks

**Comment by obiot** [comment]
thanks, always nice to read positive feedbacks ! :):):):)

note that we closed the google forum and moved the forum here :
http://www.html5gamedevs.com/forum/32-melonjs/
