### ISSUE TITLE
Update the pointer event detection to make use of the quadtree library

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#549]
would this make sense ? as opposed to today where we check for all registered shapes within the viewport ?

We could easily fake a 1 pixel big square and use the quadtree to retrieve all objects inside the quadtree. 

This might however requires some changes on the quadtree so that we can distinguish entity (that have a physic body) and regular shape objects like a sprite (the latter will be required anyway when adding shape based collision).

**Comment by obiot** [comment]
one interesting point here that I just discovered :

the pointerEvent API defines a `width` and `height` attributes that define the "touched/clicked" zone area, this could be abused in melonJS (with a default value to 1) to define a rectangle out of it, which would help in using the quadtree for event detection.

**Comment by obiot** [comment]
unless someone takes the plunge with #551 for this release, we might have some kind of race condition if we implement this : the quadtree is clear and rebuilt at the beginning of each frame, while an event can happen anytime ! so we might have some cases where an event would be triggered when the quadtree is empty or still being repopulated.

what would be a good solution for this one, defer the event if the quadtree is being rebuilt ? add some boolean in the quadtree, and add a blocking loop on the input side that wait for the quadtree to be updated?

**Comment by parasyte** [comment]
Not to worry about race conditions with events! It's true that an event can be triggered at any time, but it does NOT interrupt any currently running JavaScript. JS is single-threaded and cannot be preemptively scheduled with other JavaScript code in the same process.

Events can only be handled in the "idle time" between each frame. This is also where deferred functions run, etc.

**Comment by obiot** [comment]
Hmmm... This ticket should be quite easy to close then now :)

**Comment by obiot** [comment]
Hi @parasyte @agmcleod 

Except if i'm overthinking this ticket, I'm not seeing a way to easily finish this one without adding some breaking changes.

As as reminder, as of today the API is designed to take as parameter both a `region` area and a `callback` function when registering to an specific event, and when inquiring the quadtree about the objects surrounding the pointer, there is no easy to then identify to which object that region belongs to.

So to make a long story short, I did not find a way around it....

Few ideas I had :
- add another parameter with the object reference (so that we can identify it back), but it's adding another parameter (i don't like it very much)
- actually remove the `region` parameter from the `registerPointerEvent` funtion, and use the object defined shape(s) for it (only limitation then is that you can only register event on "physic" object).

so two questions :
1. does any of you have a better idea (/ compromise)
2. do we do that as part of 2.2.0 ?

**Comment by parasyte** [comment]
Maybe I just don't appreciate the gravity of the situation, but it seems to me like you will get the same shape reference out of quadtree as what's registered in the pointer events:

* Shape is added to quadtree: https://github.com/melonjs/melonJS/blob/c62927776ac5c49d95c13cd9f14d7b27d6df106b/src/physics/quadtree.js#L206
* Shape retrieved from quadtree (fast path): https://github.com/melonjs/melonJS/blob/c62927776ac5c49d95c13cd9f14d7b27d6df106b/src/physics/quadtree.js#L241
* Shape is registered for pointer event: https://github.com/melonjs/melonJS/blob/e96d94ba0312ac9ed11c8807811be4bf5e9536f7/src/input/pointer.js#L639-L642
* Shape is tested when triggering pointer event: https://github.com/melonjs/melonJS/blob/e96d94ba0312ac9ed11c8807811be4bf5e9536f7/src/input/pointer.js#L297

These lines all reference exactly the same objects. And because the pointer event is stored in a Map, you just use the same object reference from the quadtree to lookup the pointer registration details ... which includes the list of callbacks you are interested in.

**Comment by obiot** [comment]
i'm not sure i'm getting where you are going with your explanation, but object references could be differents  :

on one side my object x is inserted into the quadtree (using x.getBounds() to insert it into the right quadrant) :
https://github.com/melonjs/melonJS/blob/c62927776ac5c49d95c13cd9f14d7b27d6df106b/src/physics/quadtree.js#L206

but for the even registration
https://github.com/melonjs/melonJS/blob/e96d94ba0312ac9ed11c8807811be4bf5e9536f7/src/input/pointer.js#L639-L642
It would work only if I pass x as well as the entity object position and size is matching the entity bounds, but if do directly the entity body shape, references are then different (although i don't remember trying the latter to be honest, not even sure it's working)

**Comment by parasyte** [comment]
> https://github.com/melonjs/melonJS/blob/c62927776ac5c49d95c13cd9f14d7b27d6df106b/src/physics/quadtree.js#L206

Here, `item` is a reference to whatever entity is being added to the quadtree. The `getBounds` can be ignored; the bounding rect is not retrieved from the quadtree later; the item itself is.

> https://github.com/melonjs/melonJS/blob/e96d94ba0312ac9ed11c8807811be4bf5e9536f7/src/input/pointer.js#L639-L642

`region` here is the same reference as `item` in the quadtree. `region` === `item`.

**Comment by obiot** [comment]
hmm ... is it, hopefully this is almost all my code, and i'm lost inside of it :P:P:P

**Comment by parasyte** [comment]
The only exception is whether user code registers the pointer event on the entity itself, on the entity bounds, or on a single shape within the entity body... I assume above that it's the latter; the entity itself. And in this case, the fast path is super easy, just compare with ===.

In the other cases (slow path) you have to do boundary intersections at a minimum. :(

**Comment by parasyte** [comment]
Oh, I suppose you could fallback to minpubsub instead of a slow path. If a pointer event is registered on a region that is not an entity reference, subscribe to it as a topic instead. Then in the quadtree lookup, if an entity was touched that has no events registered on it, publish to its topic.

This is similar to how pointer events used to be registered (before Map): the region is given a GUID if it does not already have one. Then minpubsub topic is just something like:

`"me.event.POINTERDOWN.<GUID>"`

Concatenate the GUID, and you've got a unique topic...

**Comment by parasyte** [comment]
The only case that still isn't covered is the special case of registering events on the viewport. I suppose it could be a special case that an event is always published for viewport first, followed by the QuadTree lookup if it's not prevented by a handler.

But then how do you get the `preventDefault` value from a publish? lol

Really, I don't like the thought of supporting legacy registration regions ...

**Comment by parasyte** [comment]
`me.input.registerPointerEvent` throws an exception if the provided region hasn't been added to the scene graph ... Good enough for me. :)

**Comment by obiot** [comment]
will look back at this one once back at home where I can think about it with a clearer mind :)

**Comment by parasyte** [comment]
After more thought, I decided it's a bad idea to throw an exception in the last case. That would break the pattern of registering `this` as the region within an entity constructor. So I've come full circle; it seems like the best approach is the one laid out before; allow arbitrary registrations that won't always trigger. That includes using the viewport, which is quite popular.

We should rely on documenting the limitations, and leave it at that.

**Comment by agmcleod** [comment]
Seems like a fair conclusion to me.

**Comment by obiot** [comment]
after literally a few hours debugging this one (which is not easy with mouse based event), i finally understood why I did not manage to get it working so far, and the reason is super simple :

as a reminder, with this update, before the main event check loop, we obtain first a list of candidates from the quadtree based on the current pointer position.

the symptom was that the pointer move event was not triggered, when other event were working properly.

finally, I realised that the viewport itself is not in the returned list of candidate, for the simple reason that the viewport object itself is actually never added to the quadtree.... hooray, that was my issue !!!  :
https://github.com/melonjs/melonJS/blob/master/src/game.js#L279

i'm not sure yet of what would be the impact of adding the viewport to it, but at least i know now where to look at ! in the mean time, it's time for me to hit the bed :P

**Comment by parasyte** [comment]
lol @obiot I mentioned the special case of the viewport earlier in this ticket. :)

I think it's not a good idea to add it to the quadtree, when you can just unconditionally append it to the list of candidates...

**Comment by obiot** [comment]
Oh really? I guess i have waited too long to come back on this one :(

**Comment by obiot** [comment]
here it is for the pointerMove. Still not finished yet, as the debugPanel is not working.

[EDIT] also tested the whack-a-mole example, and it seems to be broken too :)

**Comment by obiot** [comment]
I think this one is done, i'm merging into master and closing it

**Comment by parasyte** [comment]
Cool! Looks good.
