### ISSUE TITLE
Tweens run in slow mode on V8, due to undefined property lookups

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#557]
From discussion: https://github.com/melonjs/melonJS/commit/68b7ff2c1d9806ff44ba109f13bf0c9258d4ffea#commitcomment-7382414

To fix, define the four required boolean properties:
- ~~`floating`~~
- ~~`inViewport`~~
- `isRenderable`
- `updateWhenPaused`

**Comment by obiot** [comment]
the first two properties are not required anymore
