### ISSUE TITLE
Support canvas hit regions

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#558]
Just learned of a new Working Draft that adds "hit regions" to canvas: http://www.w3.org/TR/2dcontext/#hit-regions It is currently in development for Firefox and Chrome, and apparently already supported by recent versions of IE (?)

@obiot did a lot of work getting this feature supported in melonJS over the years, and now it's finally coming natively! This ticket should serve to investigate how we can take advantage of the new native functionality.

**Comment by obiot** [comment]
> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion
