### ISSUE TITLE
Evaluate replacement for me.Entity.bounds

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#580]
This seems kind of tricky. There has been a lot of discussion about this in the past, mostly in #560. But it seems like maintaining the bounds rectangle separately from the entity rectangle is problematic. See this commit as an example of how it goes wrong: https://github.com/melonjs/melonJS/commit/104b6f45a7c366a662582a796a922fde2ec51ad0 The entity geometry was silently working for most objects, but fails for TMX Polygon and Poly Line objects. :confused:

@obiot What are the reasons for creating a `bounds` object inside the `Entity`, instead of using the entity geometry itself as the bounding box?

I know the entity geometry was once used as the renderable geometry. Then that changed when renderable was broken into its own object. And then the collision box object was removed, but it appears the bounds object has just taken its place.

**Comment by agmcleod** [comment]
Given how we've changed the way bounds works a bit, is this still relevant?

**Comment by parasyte** [comment]
Oh yes. Something still needs to be done. :) The spec may have to evolve with recent changes, but for sure we need something better than shoving more rectangles onto entities to get everything working...

**Comment by parasyte** [comment]
For future reference:

Entity:

* `getBounds()`: return a rectangle that contains all collision shapes, *or* `this` when there is no shape
* `renderable`: a rectangle that contains the visible part of the entity
* `this`: a rectangle that is a union of the above

Sprite:
* `getBounds()`: returns `this`
* `this`: a rectangle that contains the visible part of the sprite

**Comment by obiot** [comment]
I was looking at remove `_bounds` from the entity object, and directly use the entity object geometry for the bounds object, but due to the following lines, i'm not sure we can :
https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L257-L263
https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L241-L247

as `_bounds` also serves as a "cache" where all final value (like initial position + body relative position + movements + ancestor absolute position) is included.

so as far as it goes for this ticket, what I would "only" do so far is to change the following line
https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L263
to :
````
this._bounds.resize(w, h);
this.resize(w,h).union(this.renderable);
````

**Comment by obiot** [comment]
also, are these two functions not somehow redundant :
1. `UpdateBoundsPos` : https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L257-L263
2. `onBodyUpdate` :  https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L241-L247

and especially when you look at the parent function for `UpdateBoundsPos` that almost looks like the `onBodyUpdate` one :
https://github.com/melonjs/melonJS/blob/master/src/renderable/renderable.js#L242-L248

**Comment by parasyte** [comment]
Yes, very similar. It could probably be unified. Not sure if it will be a huge gain. ;P

The `_bounds` cache makes sense due to the current rectangle implementation. The problem with it is really the fact that all rectangles are positioned by their upper-left corner. Because of this, a union is likely to end up changing the position, which will have too many edge cases with unknown consequences.

To make positioning independent of a rectangle's corner, the code will probably have to evolve in the same direction @Giwayume started to explore for #99. That means, the position vector itself does not provide information about a rectangle's left or top boundaries, but instead you have to use the `left` and `top` getter methods for that; `pos` is a point vector, and the shape is anchored to it with the `anchorPoint` unit vector.

With that, changing the shape (and `anchorPoint`) does not affect the position. It would be easier to reason about. And at that point, the entity itself can become the boundary cache. Whether we actually need a union between bounds and renderable is still a valid question; ideally we just won't have cases where these rectangles differ by much. Secondary to that, cache the union or assume it's going to be fast enough to compute the union without needing a cache...

**Comment by obiot** [comment]
design changes, so breaking changes and 4.0.0

**Comment by obiot** [comment]
so with the two last commits, it's now possible to add a physic body to any renderable object, Sprite, container, or whatever object inheriting from me.Renderable.

which means that me.Entity could slowly go to die....as for simple case me.Sprite is enough, and for more advanced use cases (with multiple renderable), ones could use a me.Container.

**Comment by obiot** [comment]
here is an example :
https://github.com/melonjs/melonJS/commit/06c64f790aaa76e4f9e5f9b067dc2f346111a2f2

**Comment by obiot** [comment]
that makes the whole thing much more modular/flexible, as it does not rely anymore on a specific object type for physic/collision.

**Comment by obiot** [comment]
see #1008
