### ISSUE TITLE
Ellipse collision tests only work with circles

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#584]
The collision tests for ellipse assume that the ellipse is a perfect circle, e.g. that its radius is uniform in every direction. Ellipses are allowed stretch over the X and Y axes, turning it into an oval. `me.Ellipse` has some properties for handling this:

* `radius` is the maximum radius
* `scaleV` is a unit vector representing the ratio between the maximum radius and the x,y axes.
* `radiusV` is a pre-scaled vector representing the actual radius along the x and y axes.

The SAT collision tests currently only use `radius`, which is fine for circles. To support scaled ellipses, the `radius` must be scaled by `scaleV` and the `cos` and `sin` for the angle between the ellipses. The angle is determined using `atan2`.

**Comment by obiot** [comment]
same here -> 3.1.0

**Comment by parasyte** [comment]
@obiot Did you really mean to close this ticket?

**Comment by obiot** [comment]
yes, i tried to clean up some tickets, and I created one with all the ellipse limitations, see #809, that refers to this one
