### ISSUE TITLE
Texture packer support for tiles

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#592]
Not sure how this will work, but it would be nice to get working. Problem is if position of a tileset changes inside the atlas'd image, the map will be all wrong. But if anyone has any clever ideas, would be great to implement. Especially for when we get batching in for webgl.

**Comment by obiot** [comment]
i think that one is done and can be closed ?

the last point remaining is the required revamping on the tiledObject, that is already covered by ticket #595

**Comment by obiot** [comment]
merged this ticket into master.

Two things missings now (linked but not related to this ticket) :
-  tiled object rotation is broken/not working, see #639
-  when used with Tile Object, tiles animation is not correct, we need ticket #390 for that
