### ISSUE TITLE
Fix debugPanel and debugParticlePanel with WebGLRenderer

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#593]
I'm making this a blocking bug for v1.2.0. Let's get this fixed, even though WebGL is still "alpha". The uncaught exceptions look quite bad.

**Comment by agmcleod** [comment]
f92058a

Updated the memory graph to not use beginPath() for drawing. Simple rectangle now. It doesnt grow like it did before, but that also gives a slight illusion that it's consuming memory progressively, vs all at once.

**Comment by obiot** [comment]
I like it ! :)

**Comment by obiot** [comment]
i propose to move this to 2.1.1 or 2.2.0, as keep this one as a "known" limitation when using webGL on 2.1.0 (people can anyway switch to Canvas for debugging, not a big deal)

**Comment by parasyte** [comment]
eek! I don't think that's a good idea.

**Comment by obiot** [comment]
it's not a bad one too  :P
* webgl renderer is still in beta stage
* debug panel only works in canvas mode
* 2.1.1 to follow shortly

**Comment by parasyte** [comment]
Since we're alright with skipping this one on 2.1.0, I'm in favor of skipping it on all 2.1.x!

-> 2.2.0 ?

**Comment by obiot** [comment]
Ok for me :)

**Comment by obiot** [comment]
no further progress here, moving it to 3.2 or 4.0 :(

**Comment by obiot** [comment]
job done, one less thing to complain about ! :)
