### ISSUE TITLE
me.input.releasePointerEvent should take an argument that references "which callback" to release

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#596]
`me.input.releasePointerEvent()` releases *all* bound events on the given rectangle. It should also accept a second argument to specify exactly which callback should be released (instead of all).

**Comment by obiot** [comment]
did this one as well, was pretty easy.

One small trap I'd like to mention, as although itseems pretty obvious when you read about it,  yet I felt into it. So if you register on an event somewhere doing the following :
````me.input.registerPointerEvent('pointerdown', this, this.onSelect.bind(this));````
and then release it later doing the following :
````me.input.releasePointerEvent('pointerdown', this, this.onSelect.bind(this));````
it won't work as the bind function will return a different reference to the function :P


(PS: maybe have a look at the documentation, i'm not sure what I wrote is really correct english)

**Comment by obiot** [comment]
and this was the last pointer event related ticket if i'm not wrong ? :P

**Comment by parasyte** [comment]
Very cool! Yeah, the `bind` method creates a new function, so the reference needs to be saved.
