### ISSUE TITLE
trouble in Rect position

### ISSUE THREAD

**Issue by zoiba** [melonjs/melonJS#597]
in melonJS 1.1.0, this.body.addShape(new me.Rect(0, 0, 8, 16)), for example, produce something like this:

![2](https://cloud.githubusercontent.com/assets/5225262/4739357/1599e34c-5a04-11e4-818e-bd5abdbfab5e.png)

instead it should produce something like this:

![1](https://cloud.githubusercontent.com/assets/5225262/4739366/2512a728-5a04-11e4-8d86-72cfcf5024bf.png)

it seems to me the rect is always centered over the image and the first two coordinates are ignored

**Comment by obiot** [comment]
looking at this one again, I'm not sure if this is really a bug (or I'm overlooking it again).

with the default anchorPoint for the renderable being 0,0 :
https://github.com/melonjs/melonJS/blob/master/src/renderable/renderable.js#L118

it's completly normal for me to have the the rectangle as below by default :
https://cloud.githubusercontent.com/assets/5225262/4739366/2512a728-5a04-11e4-8d86-72cfcf5024bf.png

if ones need to have them center it needs to change the anchor point to (0.5, 0.5) a bit like what we do in the platformer to bottom align the sprite and the collision shape :
https://github.com/melonjs/melonJS/blob/master/examples/platformer/js/entities/entities.js#L51-L52

I understand what is written in ticket #580, but I'm not seeing here why changing the anchorPoint would not fix this here above issue.

**Comment by parasyte** [comment]
@obiot Have you tested other values for the `anchorPoint` setting? In my experiments, it's impossible to position a renderable relative to the entity size, because of the way the bounds is computed.

**Comment by parasyte** [comment]
Fixed for 2.1! This was actually really easy. Comparison:

2.0.x:
![screen shot 2015-02-23 at 8 33 44 pm](https://cloud.githubusercontent.com/assets/456942/6343406/df451276-bb9c-11e4-831d-18526ea4717f.png)

2.1:
![screen shot 2015-02-23 at 8 32 38 pm](https://cloud.githubusercontent.com/assets/456942/6343408/e81df606-bb9c-11e4-90e1-9f4233c83f28.png)

In both cases, the renderable is drawn with `anchorPoint` set to `<0.5,1>`

**Comment by agmcleod** [comment]
nicely done!
