### ISSUE TITLE
Add support for hexagonal maps

### ISSUE THREAD

**Issue by bjorn** [melonjs/melonJS#607]
Tiled 0.11 will feature hexagonal maps. The feature is already available in daily builds and could be supported by melonJS. See http://forum.mapeditor.org/t/support-for-hexagonal-maps-added/47 for the details.

Any feedback on the feature as implemented by Tiled is also welcome.

**Comment by obiot** [comment]
https://github.com/bjorn/tiled/blob/master/src/libtiled/hexagonalrenderer.cpp

**Comment by matthewmmorrow** [comment]
https://github.com/melonjs/melonJS/pull/694

**Comment by obiot** [comment]
done, thanks to @matthewmmorrow

**Comment by alanleite** [comment]
Is it possible to create hexagonal isometric using de current version?

**Comment by bjorn** [comment]
> Is it possible to create hexagonal isometric using de current version?

Do you mean the current version of Tiled? That is unfortunately not unsupported yet, but it would certainly make sense to add it.
