### ISSUE TITLE
Add a default shape to an entity body if not overridden by the entity constructor.

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#614]

**Comment by obiot** [comment]
err... this one , I dunno what to do :)

last time we however discussed that settings should provide a `shapes[]` property with all the defined shapes for an object, this will however not help with the "add a default shape iif no shape is defined" question :)

**Comment by parasyte** [comment]
```javascript
this.body = new me.Body(this, settings.shapes instanceof Array ? settings.shapes : [ new me.Rect(0, 0, this.width, this.height) ]);
```

This solves it all. We get our overrides; `settings.shapes` is an array that replaces the `settings.getTMXShapes` callback, and can be an empty array. In the case it is not an array, a default Rect is created.

**Comment by ldd** [comment]
+1000. (it doesn't help with isometric shapes, but...)

settings.shapes = [...];
is better than 
settings.getTMXShapes = function(){return [...]};

**Comment by agmcleod** [comment]
Yeah i agree. I like this proposal as well :)

**Comment by obiot** [comment]
why is `noDefaultShape` no longer needed ? this one is used to prevent from creating a default shape when using Tiled, if not there how do you prevent a default shape to be created  ?

**Comment by obiot** [comment]
my only issue with this is that now we would have a set of instantiated `me.Shape` object into settings, as opposed to now where we only have the shape definition (but no object instances).

which means that when passing `settings.shapes[]` to entities, they will all share the same shapes references, which can be good too, but if one entity start modifying the defined shapes, it will cause issues with other entities of the same type

**Comment by ldd** [comment]
instead of noDefaultShape, in Tiled or programmatically, you set shapes = []
i.e:
//nothing = assume default from Tiled that used to be created by TMXgetShapes()
shapes = [] // no shape
shapes = [new me.Rect...] // some defined shape

**Comment by parasyte** [comment]
In Tiled, it's `shapes = json:[]`

**Comment by obiot** [comment]
no, that does not work as programmatically add or not a default shape defeats the initial purpose of the `noDefaultShape` flag (which is to ignore the default shape given by Tiled).

https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L120

so I would rather do :
```` javascript
if (settings.noDefaultshape === true) {
   this.body = new me.Body(this, []);
} else {
   this.body = new me.Body(this, settings.shapes instanceof Array ? settings.shapes : [ new me.Rect(0, 0, this.width, this.height) ]);
}
````

**Comment by obiot** [comment]
also, as a bonus question, what would be the default value of `this.width` and `this.height` here if the object is programmatically created ?

**Comment by parasyte** [comment]
In what way is `[]` different from `[]`? (I pose this question in the form of making a point that there's no difference between the following inputs to the code you provided.)

```javascript
settings.noDefaultShape = true;
```

... or ...

```javascript
settings.shapes = [];
```

Bonus answer: https://github.com/melonjs/melonJS/blob/35726797b8f657c72c449070b020dd4a0b02b19f/src/entity/entity.js#L127-L130

**Comment by parasyte** [comment]
By the way, `me.Body.addShapesFromJSON` is the new way to specify shapes as a data structure, right? Seems like a practical solution to your issue regarding object references. (It isn't like the rest of melonJS is immune to resource sharing violations. The issue doesn't raise anything new.)

**Comment by obiot** [comment]
yes, they are the same, but from Tiled itself it's easier to set a custom property, rather then settings the array to [].  Butyes, the internal (melonJS) code should set array to [] if the flag is defined.

as a reminder this flag is iniitally only to discard any shape creation when using Tiled.

**Comment by obiot** [comment]
hi guys, so I implemented what I think is the result of the above discussion. Please review and comments (separate branch for now until we reach a consensus)

**Comment by obiot** [comment]
do we merge this branch ?

**Comment by parasyte** [comment]
@obiot Yeah, the last patch is way better! :laughing: I'm ok with merging this branch now.
