### ISSUE TITLE
Expect case-sensitive names

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#616]
There are a lot of internal checks and transformations that occur to make names (even file names) lower case to support case-insensitive matching. This is bad for many reasons. The biggest reason is that JavaScript itself is a case-sensitive language. And second, we could save a few bytes and CPU cycles by removing all of the `toLowerCase` calls scattered through the engine.

I won't belabor the point; this ticket is for discussing whether we agree that case-insensitive matches are a bad idea, and if we can get rid of them for the next major release.

**Comment by obiot** [comment]
Is this one done then?

**Comment by agmcleod** [comment]
Don't think so. There are some places in TMX files i noticed that still use it. I wasn't quite sure about changing those, if that's just how tiled does it sort of thing. Other then that i believe it is done.

**Comment by parasyte** [comment]
Fixed the last of these! There are only four occurrences of `to(Lower|Upper)Case` in the source tree, and the only one left that deals with string comparisons is checking for "collision" in TMX layer names.
