### ISSUE TITLE
Update me.Font to use the new Renderer API

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#619]
See also: #593 and 6f23793cb7bcc39e202ddfc3496de3793b9ba2a9

`me.Font` still requires a `Context2d` reference, while `me.BitmapFont` was updated to use the Renderer API. Let's get these APIs back in sync for the next major release.

**Comment by obiot** [comment]
this one is done too ? except from the performance issue when using webgl, but this is more part of the #591 ticket

**Comment by parasyte** [comment]
Yeah, this is getting fixed on the ticket-591 branch

**Comment by obiot** [comment]
oh the changes for this one are actually in the "ticket-591" branch !

is it ok to merge it then ?

**Comment by obiot** [comment]
closing this one as the related changes in #591 have been merged yesterday into master.

Wiki has been updated too:
https://github.com/melonjs/melonJS/wiki/Upgrade-Guide
