### ISSUE TITLE
Optional QuadTree or SpacialHash for collision detection and nearby object lookups

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#624]
This idea was already mentioned here: https://github.com/melonjs/melonJS/issues/544#issuecomment-51427355 (ticket now closed)

Here's the last spacial hash implementation from #103: https://github.com/melonjs/melonJS/blob/8775c4f160b2815ffe612f3f23fe2d368f58eaff/src/entity/collision.js (it could use some cleanup. For example, the `remove` method does not need/should not use the object bounding box; the cells its in are already available in the double linked list.)

What I would like for this ticket is an API to choose between QuadTree or SpacialHash, user-configurable. Both are useful, and which is best depends on the type of game, number of moving objects and so on.

**Comment by obiot** [comment]
quickly re-had a look at it, and it should be quite easy to align both APIs to then add the possibility to switch on demand from on to the other.

**Comment by ldd** [comment]
so... what's the status on this issue? me.spatialHash exists

**Comment by parasyte** [comment]
It sure does :smile:

Looks like no one has taken the time to clean it up yet for integration.

**Comment by obiot** [comment]
considering the lack of interest on this one since 3 years now, and the fact the current quadtree implementation actually does its job, I'm closing this one.

anyone willing to add proper support, feel free to reopen it :)
