### ISSUE TITLE
Performance: SIMD.js

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#626]
SIMD support in JavaScript means we can rewrite the `me.Matrix2d` class to use proper vector mathematics, performing the multiplications and additions in parallel.

https://hacks.mozilla.org/2014/10/introducing-simd-js/

**Comment by parasyte** [comment]
A nice look at how SIMD improves performance in some cases (especially vector computations) : https://blog.mozilla.org/javascript/2015/03/10/state-of-simd-js-performance-in-firefox/

**Comment by obiot** [comment]
now that we mostly have matrix based transformation, this one would definitely be nice.

An interesting article i just found back, totally applicable to melonJS now :
https://hacks.mozilla.org/2015/12/bringing-the-power-of-simd-js-to-gl-matrix/

**Comment by obiot** [comment]
Closing this one, Google actually removes the support from Chromium last year, it still mostly experimental and does not seem it will become mainstream any time soon (if ever).
