### ISSUE TITLE
Performance: The color/matrix stack is slow.

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#628]
From my performance analysis work in #591, I have determined that the addition of the color stack to the CanvasRenderer (introduced in https://github.com/melonjs/melonJS/commit/ddbdc1fed16e795dc4f636eeb7c603c0ab32852e) has made the particle editor example 2x slower. I've been making tweaks to the `me.Color` class and `me.pool` namespace to workaround this issue, but it's clear that we will never be able to get the same raw speed that a dumb string value provided.

In one attempt, I tried to remove the pool overhead by storing the color as a string, and pushing strings to the stack. This has the unintended consequence that the color and alpha values are handled separately, and the primary reason `me.Color` exists. In order to preserve the alpha value, it must be parsed from the string, incurring parsing overhead.

There are three solutions I envision:

1. Disallow reading the color; don't use a color stack and require framework code to call save()/restore() instead of attempting shortcuts by reading/writing the color.
2. Continue using a stack, but make it faster.

Option 1 is preferred, IMHO. The canvas save/restore calls are pretty quick, even if they are a bit heavy. The good news is that save/restore for changing the color is not really necessary, since each object should be self-contained and set its color before using it. Nested calls are expected to be rare.

I don't know how to do option 2. I think I've done everything I can with it at this point. :confused:

This brings up another point to audit the draw path for potential bad stuff like overzealous save/restore calls... After all, WebGL kind of needs these stacks for its save/restore implementation!

**Comment by parasyte** [comment]
I also briefly considered doing away with a stack-style save/restore system at all, but it is required for drawing hierarchical objects like the Container tree, Spine animations, and particle emitters. Transforms have an inverse function (e.g. the inverse of a 30 degree rotation is a -30 degree rotation) but we don't necessarily have inverse functions for color manipulations.

**Comment by agmcleod** [comment]
No exactly. That's why the stack was needed. To keep track of colour changes

**Comment by parasyte** [comment]
I took the path of option 1, removing the color stack and `getColor`. Here are the before-and-after screenshots:

Before:
![before](http://i.imgur.com/CxCzABj.png)

After:
![after](http://i.imgur.com/pGSlB44.png)

This brings the particle editor back in line with numbers from the v2.0.0 release. This one is done.
