### ISSUE TITLE
Add support for new canvasContext2d.measureText bounding box attributes

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#630]
See: https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-measuretext

The following attributes will provide a bounding box for the text passed to `measureText`:
- `actualBoundingBoxLeft`
- `actualBoundingBoxRight`
- `fontBoundingBoxAscent`
- `fontBoundingBoxDescent`

Note that `font*` prefixed attributes are used instead of `actual*` for `Ascent` and `Descent`. That's because these properties provide the maximum limits in the vertical direction, regardless of the text string passed to `measureText`. This provides considerably more accurate measurement than the `width` attribute alone. Unfortunately, these attributes are not currently supported by any browser on the market. We can simulate them by measuring different characters and analyzing the pixel output.

**Comment by obiot** [comment]
not to mention that we already return a custom object, and could be use both for `me.Font` and `me.BitmapFont` !

i'm moving this one to 3.1.0 :P

**Comment by obiot** [comment]
following closing of ticket #875 and #950, I decided not implement this one; first the current bounding box computation for system text is working quite nicely now, and is good enough for what we need it for here, and finally these new properties are still not commonly implemented in all browsers (desktop and mobile).
