### ISSUE TITLE
Renderer: Add support for Gradient, Path, and Pattern objects

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#631]
- [`context.create*Gradient()`](https://html.spec.whatwg.org/multipage/scripting.html#fill-and-stroke-styles:canvasgradient-7)
- [`new Path2D()`](https://html.spec.whatwg.org/multipage/scripting.html#path2d-objects)
- [`context.createPattern()`](https://html.spec.whatwg.org/multipage/scripting.html#fill-and-stroke-styles:canvaspattern-8)

This will be tricky with WebGL, but possible with triangulation and a custom shader: http://http.developer.nvidia.com/GPUGems3/gpugems3_ch25.html

**Comment by obiot** [comment]
will help with #612 too maybe

**Comment by obiot** [comment]
closing this one, for createGradient there is already ticket #612, for path2d #648, and createPattern is already implemented
