### ISSUE TITLE
[Tiled 0.10+] support the various Tile Render Order options

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#633]
Tiled defines 4 different order for how tiles on tile layers are rendered :
- Right Down (default mode)
- Right Up
- Left Down
- Left Up

As for now, melonJS only support the `right down` one, which means that tiles are being draw starting from left to right, and from top to bottom.

**Comment by parasyte** [comment]
Oh, this should be really easy. :)

Maybe we should consider using iterators for this, instead of for-loops: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/The_Iterator_protocol

We can specify a `range` iterator, like the Python function: https://docs.python.org/2/library/functions.html#range to iterate over arbitrary ranges. Especially handy when the numbers can increment forwards or backwards, like in this case. :wink:

**Comment by obiot** [comment]
that would be nice to be honest, and the iterators looks super cool and simple, but I'm afraid it's maybe a bit too much "advanced" for the current browsers version/implementation, and adding a (slower) polyfill for it in the tile main drawing loop is probably not one of the best idea :(

**Comment by parasyte** [comment]
@obiot It doesn't need to follow the spec exactly. An iterator is just an object with a `next` method that returns the next value in the series. It can be be written in plain old ES5 JavaScript.

```javascript
var LoopRange = Object.extend({
    "init" : function (start, stop, step) {
        this.start = start || 0;
        this.stop = typeof(stop) !== "undefined" ? stop : Infinity;
        this.step = step || 1;
        this.reverse = (this.step < 0); 
    },

    "next" : function () {
        var result = this.start;
        if ((!this.reverse && result >= this.stop) || (this.reverse && result <= this.stop)) {
            return { "done" : true };
        }

        this.start += this.step;
        return { "value" : result };
    }
});

var result;
var iter = new LoopRange(10, 0, -1);
while ((result = iter.next()) && !result.done) {
    console.log(result.value);
}
```

Or with closures:

```javascript
function loopRange(start, stop, step) {
    start = start || 0;
    stop = typeof(stop) !== "undefined" ? stop : Infinity;
    step = step || 1;
    var reverse = (step < 0); 

    return {
        "next" : function () {
            var result = start;
            if ((!reverse && result >= stop) || (reverse && result <= stop)) {
                return { "done" : true };
            }

            start += step;
            return { "value" : result };
        }
    };
}

var result;
var iter = loopRange(10, 0, -1);
while ((result = iter.next()) && !result.done) {
    console.log(result.value);
}
```

The ES6 parts are `for...of` loops and the use of Symbols.

**Comment by obiot** [comment]
don't you think it would still be slower than a good old for.. loop ?

**Comment by parasyte** [comment]
Slightly slower. But future-proof, and easier to write loops that are dynamically ascending and descending.

**Comment by ldd** [comment]
random suggestion:
```
var LoopRange = function(from, to){
 var c = (from <= to)? 1 : -1;
  for(var i= from; i*c <= to*c; i+=c){
   console.log(i);
 }
}
```
or if you want a step 
```
var LoopRange = function(from, to, step){
 step = step || 1;
 var c = (from <= to)? 1 :-1;
  for(var i= from; i*c <= to*c; i+=step*c){
   console.log(i);
 }
}
```
