### ISSUE TITLE
Collision bug with nested containers

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#634]
@agmcleod discovered a bug with collisions when a container is moved around the scene. The issue is that QuadTree only adds items based on their position, which is relative to its parent, and does not take into account the item's absolute position in the world.

To solve this, we should extract this code into a reusable class:

* https://github.com/melonjs/melonJS/blob/ad250e05740229ca443456839978df3c9cad9c3e/src/renderable/container.js#L619-L636
* https://github.com/melonjs/melonJS/blob/ad250e05740229ca443456839978df3c9cad9c3e/src/renderable/container.js#L644-L657

And then we can use the same logic for `inViewport` testing and QuadTree insertions.

This bug will also be relevant to #624.

**Comment by agmcleod** [comment]
Just kind of noting stuff as i go through code. The instance of this re-usable class would effectively be used here: https://github.com/melonjs/melonJS/blob/061a815054704a3c799afdbde350d8785f2e777e/src/physics/quadtree.js#L165

**Comment by agmcleod** [comment]
Trying to think on how this will actually work. We store the objects themselves in the various nodes. That's fine, the positioning needs to be determined before hand to figure out which node to put them in. This is done by passing the result of getBounds() to the getIndex() method. So with that, I'm not sure how the new object I created will be of any use here. I think it would be more sensible to have a method on the entity: `getAbsoluteBounds` that goes up the ancestor linked list to calculate absolute position.

**Comment by parasyte** [comment]
Walking the ancestor tree will get really slow. I would prefer a system that always inserts items into the QuadTree with absolute coordinates, and always looks up items using absolute coordinates. The translation stack gives us the offsets we need ... just have to add those coordinates at insert and retrieve in the quadTree code.

I don't know of the best way to do that, however. It's kind of non-obvious. ;(

**Comment by agmcleod** [comment]
Yeah i was hoping we could do manual changes to the quad tree. But might not be the case. Probably have to remove getBounds() call to maybe the transition_stack + object.getBounds().pos or somethin.

**Comment by parasyte** [comment]
I want thinking about passing an offset vector up to `getIndex`, but that would be a manual processes for performing the lookups...

**Comment by obiot** [comment]
walking through the ancestor tree might be slow, but in real life how many levels do you think people will actually use ? 1 most of the time, and I bet we can say that nobody will go further than 3 levels, so i don't really think this should bring any issue (we just need to ensure to keep a special case for the 1 level so that we don't add any extra math for the simplest case)

else, please do not remove `getBounds()`, and I believe we should rather redefine it where needed to add the extra calculation. or (i like the idea) actually rather go for the additional `getAbsoluteBounds()` vs `getLocalBounds()` to better distinguish what we need. Although i did not check what their code was doing, I think that Pixi actually has something similar with their getLocalBounds() and getWorldBounds()

**Comment by parasyte** [comment]
I feel the "*n* in `O(n)` is small, so it doesn't matter" argument is flawed. "Small" is fine if it's always `1` (best case). Every entity is already a child of the world container, which is `n == 1`. This ticket deals with nested containers, where `n > 1`.

Entities in the QuadTree are referenced at multiple levels within the QuadTree; resolving entity positions is already `O(n)` for `n > 1`. What you're suggesting is to make it `O(n*m)`. We've already determined that both `n > 1` and `m > 1`, so we are entering really slow territory here.

**Comment by agmcleod** [comment]
Keep in mind olivier, i would not remove the function itself, simply the
use of it here. Since as Obi wan kenobi would say "This is not the
rectangle you're looking for"

**Comment by agmcleod** [comment]
Another one bites the dust!

**Comment by obiot** [comment]
fantastic work Aaron, have a good night !

**Comment by parasyte** [comment]
@agmcleod Wow, how was this finally solved? I haven't been keeping up with changes on your branch. :laughing: Just a few words of description is enough.

**Comment by parasyte** [comment]
I see: It only works for single-level containers, not multiple nested: https://github.com/melonjs/melonJS/blob/b569ec4654e25283ba280f7e42a2061b1d15807e/src/renderable/renderable.js#L149

**Comment by parasyte** [comment]
Oops! I have broken logic! hahaha! `me.Container` extends `me.Renderable`, so the hierarchy automatically gets absolute bounds.

Is there any chance that these `_absolutePos` vectors get out of sync? Meaning, if I write a contrived example, could it break the calculation of absolute positioning in deterministic or indeterminable ways?

**Comment by agmcleod** [comment]
@parasyte only way i can think of is you mess with them directly, but it is a concern of mine as well. Given one object invokes update before another. If you have some ideas on how we can better test this, i'm happy to try and build some.

Another thing worth testing as well would be floating objects. Perhaps getAbsoluteBounds() should invoke a check on isFloating?

**Comment by parasyte** [comment]
Sounds good to me! I've created a followup ticket for adding tests.
