### ISSUE TITLE
Support texture atlas configuration in entity constructor

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#635]
Would be nice, so users can specify an atlas & set of regions in Tiled as well.

**Comment by obiot** [comment]
as entities and renderables are two different things (the latter being a component of the first one), how would you then use this from the entity constructor ?

i could see a value to pass this one to a renderable constructor, but to an entity i find it right now pretty confusing

**Comment by obiot** [comment]
closing this one, as no further feedback since 1 year, and since added since then to renderables constructor
