### ISSUE TITLE
image-rendering: pixelated

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#638]
http://updates.html5rocks.com/2015/01/pixelated

W3C spec :
http://dev.w3.org/csswg/css-images-3/#the-image-rendering

still a bit confused though compared to the current `imageSmoothingEnabled` property

**Comment by agmcleod** [comment]
that's neat.

**Comment by parasyte** [comment]
The difference is in how images are scaled.

* Scaling with `drawImage` uses bilinear filtering by default, and can be overridden with `imageSmoothingEnabled`
* Scaling with CSS also uses bilinear filtering by default, and can be overridden with `image-rendering`

**Comment by obiot** [comment]
oh i see, we should then probably set both of them when the melonjs video `antiAlias` property is set to  false then ?

**Comment by obiot** [comment]
Reading this one again, we do not actually need this one as we don't (at least currently) use CSS for scaling.

So we can close it without further action? Or shall we add it anyway to stay on the safe path for the futur ?

**Comment by parasyte** [comment]
In truth, we need to scale with CSS to get the proper pixelization with WebGL. So I would vote for this.

**Comment by obiot** [comment]
hi guys, so I renamed the current `setSmoothingEnable()` function to `setAntialias()` and updated as follow :
````javascript
// enable/disable antialis on the given context
me.agent.setPrefixed("imageSmoothingEnabled", enable === true, context);
// disable antialias CSS scaling on the main canvas
this.canvas.style["image-rendering"] = enable === false ? "pixelated" : "auto";
````

However i'm not sure of the following :
- shall i rather use context.canvas when setting "image-rendering" ?
- am i not overwriting over values for it, like we defined in the boilerplate ? if yes do we care ? shall I write them all here in `setAntiAlias` too ?
https://github.com/melonjs/boilerplate/blob/master/index.css#L26-L32

**Comment by obiot** [comment]
for the second question, it seems that not :P

**Comment by parasyte** [comment]
`this.canvas.style` will work for WebGLRenderer, but needs to be the "screen canvas" for CanvasRenderer (depends on whether back buffering is enabled) Instead use `this.getCanvas().style`

For the last question, just *add* `image-rendering: pixelated;` to the boilerplate and examples. I would say we can eventually remove it, but the CSS has a lot of fallbacks for older UAs.

**Comment by parasyte** [comment]
Ack! `getCanvas` returns the back buffer instead of the screen canvas. so `this.canvas` is correct after all. Disregard the first part of my response. :)

**Comment by obiot** [comment]
I actually like the idea of setting it through javascript, maybe i'll do something like the following, that will only set the field if there is not value set by default or different from "pixelated"

````javascript
if (enable === false && this.canvas.style["image-rendering"] !== "") {
    this.canvas.style["image-rendering"] = "pixelated";
} else if (enable === true && this.canvas.style["image-rendering"] === "pixelated" ) {
     this.canvas.style["image-rendering"] = "auto";
}
````

**Comment by parasyte** [comment]
IMHO, it should always be set to "pixelated" if antialiasing is disabled. No need for complex conditions; just set it.

**Comment by obiot** [comment]
i agree, but as you were saying we have a lots of fallbacks for proprietary values in the boilerplate CSS (like `-moz-crisp-edges`)

**Comment by parasyte** [comment]
It's fine; an unrecognized CSS value cannot be used. It won't overwrite a known value.
