### ISSUE TITLE
me.collision documentation issue

### ISSUE THREAD

**Issue by wangTheTiger** [melonjs/melonJS#640]
Hi,

This is the first time I write a bug so hopefully I'm doing it ok.

I was reviewing the documentation you have for the me.collision Namespace and the example you have included for the 'Types' member is wrong.

Currently it says:

// set the entity body collision type
myEntity.body.setCollisionType = me.collision.types.PLAYER_OBJECT;

Instead, it should be:

myEntity.body.collisionType = me.collision.types.PLAYER_OBJECT;

Regards.

**Comment by obiot** [comment]
fixed ! thank you very much :P
