### ISSUE TITLE
Add tests for me.Renderable.getAbsoluteBounds

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#642]
Spinoff from #634

> Is there any chance that these _absolutePos vectors get out of sync? Meaning, if I write a contrived example, could it break the calculation of absolute positioning in deterministic or indeterminable ways?

> Another thing worth testing as well would be floating objects. Perhaps getAbsoluteBounds() should invoke a check on isFloating?

**Comment by obiot** [comment]
dont we have one now ? (that you @parasyte added)

**Comment by parasyte** [comment]
I don't think so. At least, we don't have full coverage for sure. That's how we missed https://github.com/melonjs/melonJS/commit/5a7c112f32c7363e03f3831089ab49fed0ff8632

**Comment by obiot** [comment]
@parasyte @agmcleod just added a test to (finally) cover this ticket. Do you see any additional use case needed ?

also, we do not have a `getAbsoluteBounds()` function, just`getBounds()` that indeed returns the absolute position of the object. I still wonder though if it would be useful to add a `getLocalBounds()` function.

**Comment by agmcleod** [comment]
@obiot with a getLocalBounds(), wouldnt that simply `return this;`?

**Comment by obiot** [comment]
Yes, but that only works for simple rectangle based object ?

**Comment by agmcleod** [comment]
Aye, but we're referring to me.Renderable, no? If talking about me.Entity, I agree that's a bit of a different thing entirely.
