### ISSUE TITLE
Simplify me.Rect

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#643]
See https://github.com/melonjs/melonJS/issues/578#issuecomment-58314976

**Comment by obiot** [comment]
@parasyte you should like this one, it's not working though (runtime error), but that's a good start already !

**Comment by obiot** [comment]
still not sure though if this would be better than the previous implementation in terms of performance :P

**Comment by obiot** [comment]
@parasyte all there and working ! just need further optimisation now ;P

**Comment by obiot** [comment]
this one really start to look good !

one thing I don't know what to do with :
now that `me.Rect` extends `me.Polygon`, it also can be rotated, but this will however cause some issues as the `getBounds` function of `me.Rect` returns the rectangle itself, which would not then be correct anymore ?

**Comment by parasyte** [comment]
I left you a few comments so far. It will be nice to get rid of a lot of special-case case, while retaining fast paths where they are useful. That's what I like about this one.

**Comment by obiot** [comment]
to be honest right now, i'm out of idea on how to optimize this further :)

do you think it's good enough to be merged back to master ?

**Comment by parasyte** [comment]
@obiot I will give it some actual testing a bit later. :) So far I have only been looking at the code. It's kind of hard to identify other potential issues that way. I'll let you know what I find!

**Comment by obiot** [comment]
+1 :) can't wait to find what you'll find out !

I was intending to do some profiling yesterday, but I ended up doing some code review everywhere to see what in relation with me.Rect could be optimized, and later on I was too tired to do anything :p

**Comment by obiot** [comment]
@parasyte how do you properly profile this thing ? 

I tried to record two cpu profile for master branch and the $643 branch, using the collison example (as it uses a lot of me.Rect) but it's kind of hard to compare the same point in the game, and based on which frame I'm comparing I'm having different results...

globally though, I'm not seeing any visible changes on the framerate, so I'd suppose that maybe we are good here.

**Comment by obiot** [comment]
so guys, do we merge this one ?

**Comment by parasyte** [comment]
I still haven't had a chance to try it, but I'm ok with merge if you are. We can always revert if it's catastrophic. Or just attempt to make fixes along the way. :)

**Comment by obiot** [comment]
@parasyte still no chance to had a look at it ? :P

**Comment by obiot** [comment]
i guess this one can be closed now :P
