### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#644]
Just an idea. Wondering if maybe we should publish a gh-pages branch of this, that keeps the stable version of code. 2.0.2 for example. And have it link all the examples. Update the jasmine test page to be specs.html instead of index.html.

We don't need to maintain an examples repo that way, and we can improve accessibility of the engine.

**Comment by parasyte** [comment]
:+1:

**Comment by obiot** [comment]
yes and no, as adding gh-pages branch, is, as implied, a different branch so it's not only a symbolic link to the examples, so we still need to copy them all from master to gh-pages when updated.

**Comment by parasyte** [comment]
It will have to be done as part of the release task, anyway. Because we currently don't commit the melonjs build files...

**Comment by agmcleod** [comment]
@obiot for the examples, we simply merge master into the gh-pages on update. Jason is right though, we will need something to handle the build files.

**Comment by agmcleod** [comment]
Question. I know the examples repo has: http://melonjs.github.io/examples/, but no index. And then this repo has its index to list examples. Should we try to consolidate?

**Comment by parasyte** [comment]
@agmcleod I like the original proposal the best. Now that we have a release task, it can be updated to merge the tag into gh-pages before it pushes. Seems like that should be simple enough.

**Comment by parasyte** [comment]
Oh! Oh! https://github.com/pajtai/grunt-build-gh-pages Just what we need. Seems like we should also put the generated docs into gh-pages, too. ;)

**Comment by parasyte** [comment]
Success! http://melonjs.github.io/melonJS/examples/platformer2/#webgl

The one thing left to do IMHO is add a link for the docs to index.html. Then we can deprecate the examples and docs repos! Have them forward to the new gh-pages branch.

**Comment by obiot** [comment]
so wait, we do not need that repository anymore then :
https://github.com/melonjs/examples

correct ? as the examples are automatically put online on the melons/melonjs `gh-page` branch, when using `grunt dist` ?

not sure I got where is the docs though, but if build out of master, we need anyway to keep melons/docs for the stable version.

**Comment by obiot** [comment]
Oh, I just noticed that the platformer is not working on my iphone under ios9 :(

Did u get it to work using the simulator? Maybe a texture related issue with webgl?

**Comment by parasyte** [comment]
WebGL is broken on iOS. I updated the TODO list in #637 to get that fixed...

The other thing is we won't always run `grunt gh-pages`, it's a sub-task of `grunt release`. I expected it to be updated with releases only. We have the ability to run `grunt gh-pages` separately though, and from any branch (though I only tested it on master). That would be nice for dot-releases and minor updates, anyway.

**Comment by obiot** [comment]
hmm... shader ? the exception I had on my side was the following, with max_size being equal to 8 :
https://github.com/melonjs/melonJS/blob/master/src/video/texture_cache.js#L37

**Comment by parasyte** [comment]
According to http://webglstats.com/ only 10% of devices support 8 texture units (`MAX_TEXTURE_IMAGE_UNITS`) ... While 90% support 16.

Which iPhone do you have? We can always cut down the number of textures that get loaded. There is one 1x1 px white texture that is required (for color fills) and another is required for font drawing. Platformer2 has two image layers which cannot be packed, because they use the repeat modes. And of course the texture atlas. We should be able to get by with just 5 textures!

I'll do some debugging to learn why it adds more than 8...

**Comment by parasyte** [comment]
Got it... There's a bug. :smiley: 

Here's a list of all textures that get uploaded on Platformer2:

1. fillTexture
1. **fillTexture**
1. fontTexture
1. **fontTexture**
1. "http://localhost:8000/examples/platformer2/data/img/tileset.png"
1. "http://localhost:8000/examples/platformer2/data/img/background.png"
1. **"http://localhost:8000/examples/platformer2/data/img/background.png"**
1. "http://localhost:8000/examples/platformer2/data/img/clouds.png"
1. **"http://localhost:8000/examples/platformer2/data/img/clouds.png"**
1. "http://localhost:8000/examples/platformer2/data/img/texture.png"
1. "http://localhost:8000/examples/platformer2/data/img/atascii_24px.png"

What's this? Duplicates?! (Highlighted in bold) This is an easy fix, and will reduce the number to 7. But still, we have three textures that could be packed into one ... the tileset, the characters (texture.png), and the bitmap font (atascii_24px.png)

**Comment by obiot** [comment]
awesome, that's what I also noticed yesterday night. I was not satisfied with what I saw versus your feedback and saw the same duplicates when I listed all the textures used in the examples :) but it was too late though and went to sleep :P

**Comment by obiot** [comment]
oh and it's a iphone6, which is why it really raised my suspicions in terms of texture limitation :)
