### ISSUE TITLE
Update the input pointer management to support any shape for region definition, and not just me.Rect

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#645]
This should be quite simple actually :
- quick update on `registerPointerEvent` and `releasePointerEvent` to accept any Shape object
- we already use `getBounds` here (which is actually kind of useless on a me.Rect) : https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L296
- replicate what I did here (https://github.com/melonjs/melonJS/blob/master/examples/shapes/js/entities/entities.js#L25-30), if the containsPoint on the shape bounding rect returns true, call the shape containsPoint function directly (except for me.Rect shape).

and that's it.

**Comment by parasyte** [comment]
:+1: Do you want to prioritize this ticket for any particular milestone?

**Comment by obiot** [comment]
I'll maybe do it today, as i might need it for my game too (testing some idea for the gameplay at the moment)

**Comment by obiot** [comment]
done, closing this one then. i'll further test it with my game, but as far as I could test, it should do it.
