### ISSUE TITLE
Add a me.Path2D API for better abstraction between Canvas and WebGL

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#648]
https://github.com/melonjs/melonJS/blob/939428e821f374cfdb4d3565fed800e9169df8ed/src/video/canvas/canvas_renderer.js#L454

This method uses stroke calls. It should be an option to do stroke or fill.

**Comment by parasyte** [comment]
Reminder: We don't have `fill` operations in the WebGL compositor.

**Comment by agmcleod** [comment]
Oh that's a good point, hmmm.

**Comment by parasyte** [comment]
We will need an equivalent of the Canvas Path API to support all of the fill operations in WebGL. At the moment we can only fill rectangles using the quad shader.

**Comment by obiot** [comment]
moving to 3.0.0, looks like too many changes to have this ready for 2.2.0

**Comment by obiot** [comment]
looking at this old ticket, we already have some `fill[Shape]` function :
https://github.com/melonjs/melonJS/blob/master/src/video/canvas/canvas_renderer.js#L223

but to make it generic, i would rather keep only the generic `drawShape` one as the public one :
https://github.com/melonjs/melonJS/blob/master/src/video/canvas/canvas_renderer.js#L500

and then mimic the canvas API by adding a `fillStyle` and `setStroke` properties or function that can be called before and after the `drawShape` function

note: Flash defines a `beginFill` and `endFill` function, we could reuse the same approach and extend to stroke with `beginStroke` and `endStroke` ?
http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001280.html

that would give the following semantic :
````javascript
renderer.beginFill(0x333333);
renderer.beginStroke(0xFFFFFF);

renderer.drawShape(myShape);

renderer.endFill(); // optional if subsequent shapes should use the same
renderer.endStroke(); // optional if subsequent shapes should use the same

**Comment by parasyte** [comment]
That Flash API doesn't feel much like Canvas. What we really need to do is polyfill the Path2D API: https://developer.mozilla.org/en-US/docs/Web/API/Path2D (and implement it directly for WebGL) as a replacement for custom stuff like `drawShape`.

**Comment by obiot** [comment]
oh, i like that idea even better !

**Comment by obiot** [comment]
both renderer now support stroke and fill operations for all me.Shape objects, what we need now is a path2d implementation to provide one more layer of abstraction when drawing these shapes and move away drawing code from both corresponding renderer.
