### ISSUE TITLE
Cocoon js and the "drag and drop" example

### ISSUE THREAD

**Issue by dakairus** [melonjs/melonJS#651]
Hi guys, has I commented before in the google group, I got some issues on the drag and drop example from the repository, the issue only is replicable into cocoon js in any of the version available now(2.0.2, 2.1 and 2.1.1).

The issue consist in that the draggable object can be dragged just once, if you release the finger and try to drag again, won't respond.

Making some debugging I put logs on the "drag start" and "drag end" events, the drag end never is executed, but in the browser or mobile browser is execute.

Cheers and thx in advance.

**Comment by parasyte** [comment]
Hi again! Thanks for the detailed explanation and extra debugging info.

Can you do one more test with the drag-n-drop example using a melonJS 2.1 WIP build? http://melonjs-builds.s3.amazonaws.com/artifacts/master/931/build/melonJS-2.1.0.js The latest drag-n-drop example can be copied from the melonJS source archive, it's in the examples directory: https://github.com/melonjs/melonJS/archive/master.zip

**Comment by dakairus** [comment]
Hi, just tested with the new version, but the game know don't even start x.x, through error on logs:

"me.video.Error: width or height was zero, Canvas could not be initialized !"

**Comment by parasyte** [comment]
@dakairus Did you use the current example sources from the zip archive? There were some changes to the `me.video.init` method, so the older example code won't work correctly.

**Comment by dakairus** [comment]
sorry I don't put the last version, know through a new error:

TypeError: cannot call method 'substr' of undefined,
At Window.parseHash(../../build/melonJS-2.1.0.js)

**Comment by parasyte** [comment]
The error in the hash makes perfect sense. I don't know why the touch events wouldn't be working in webview+ though.

Let me fix the bug in hash handling, and I'll get you a new WIP build for testing.

**Comment by obiot** [comment]
with the hash fix in place (https://github.com/melonjs/melonJS/commit/aa88ec2d9ec9376851c1f602b9932a874b964ed9), what was the result of the testing on the current master branch ?

**Comment by dakairus** [comment]
I have no tested it yet, where I can download a fixed version for testing?

**Comment by obiot** [comment]
should be the one here :
http://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/984/build/

thanks !

**Comment by dakairus** [comment]
Not too much luck this time, is drawing the object but when I try to drag the draggable entity,I got a:
Javascript Exception(Tag: 'touchstart/touchmove')
TypeError: Object #<Collection> has no method 'sharedValues'
at Collection.sharedForEach[as forEach](js/melonJS-2.1.0.js:1241:23)
at Window,dispatchEvent(js/melonJS-2.1.0.js:15557:21)
at HTMLCanvasElement.onPointerEvent(js/melonJS-2.1.0.js:15746:13)

**Comment by parasyte** [comment]
ahhh, that's something broken in the `Map` polyfill!

**Comment by parasyte** [comment]
@dakairus Please try build [987](http://melonjs-builds.s3.amazonaws.com/artifacts/master/987/build/melonJS-2.1.0.js)

**Comment by dakairus** [comment]
Great! now works fine in the cocoon JS launcher using the actual master branch example of draw and drop and the build supplied. Really thx

**Comment by obiot** [comment]
Nice, one more issue fixed :)
