### ISSUE TITLE
Allow Tile in tileset to define class for the tile.

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#653]
We need to adjust the parser to check a custom property on a tile for a class. Fallsback to me.Tile if property is not defined.

Presently the engine uses me.Tile for each tile from a level. @terebentina brought up the idea to specify a class to use for a given tile in its tileset. This can be done similar to how type "solid" was used for collision in the past.

**Comment by obiot** [comment]
since this one is already possible through the use of TileObject, is there a need to keep it open ?

**Comment by agmcleod** [comment]
@obiot can it be done through tiled as a setting, or is it in code?

**Comment by terebentina** [comment]
For my use case none worked ok after all. Tiles are too dumb in melon (no complaint, I understand why they're so) while TileObjects are too chaotic in Tiled (they're stored in a list, in the order I drew them in Tiled, no relation to the 7x7 grid I had, no way to find neighbours, etc).
I ended up creating my own grid object and implementing this with sprites.
So...I really have no use for this patch anymore.

**Comment by agmcleod** [comment]
Yeah but I can still see the value. My thought on this is more:

for a tile layer, not an object layer, be able to specify a class on the tile in the tileset to be used. So instead of me.Tile, it can use a me.AnimationSheet.

**Comment by parasyte** [comment]
@terebentina [me.game.world.sortOn = "y"](http://melonjs.github.io/docs/me.Container.html#sortOn) probably would have helped with the sorting issue. Though you can also override the sorting algorithms and define your own.

**Comment by obiot** [comment]
i want to close this, as i can see it, this would cause a major overhead in the current parsing code, adding specific condition in the parser where a Tile would need be "converted" to an object, and would also probably hugely impact other part of the engine (like the renderer, and other similar functions like `getTile`) .

for smarter things than just drawing a tile, Tile Object is the way to go, and as suggested by Jason, a custom sort algorithm can also be defined for any specific use case.

seems like @terebentina went for its own custom engine anyway :)
https://github.com/terebentina/bandit.js
