### ISSUE TITLE
DraggableEntity and DropTargetEntity not appearing in docs

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#655]
These classes have documentation, but they are not appearing in the generated documentation. I guess it's because we don't have a `@class` doc comment for these.

**Comment by obiot** [comment]
not directly linked but related, now that we a proper `mouseenter` and `mouseleave` even emulation, we could probably rewrite these entities to use them, after all that all that do, keep track of the mouse entering the entity bounds to enable the drag and then stop when release the mouse button, right ?

**Comment by parasyte** [comment]
I thought about this, and `pointerleave` is going to be tricky for any shape that moves with the pointer position. Here are some examples:

* There was a request on the forum today asking how to limit the movement of a `DraggableEntity`: https://groups.google.com/forum/#!topic/melonjs/2h4Lth7o56k When this kind of thing is done, it means the entity can be stopped by a collision shape while the pointer leaves its bounds.

* If the pointer position moves fast enough, it will leave the entity bounds.

It absolutely needs to handle the `pointercancel` event, though. This one can be fired by the pointer moving into UA chrome and such:

1. http://www.w3.org/TR/2013/WD-touch-events-20130124/#the-touchcancel-event
2. https://msdn.microsoft.com/en-us/library/ie/hh846776%28v=vs.85%29.aspx
3. https://developer.mozilla.org/en-US/docs/Web/Events/touchcancel

**Comment by parasyte** [comment]
This is done. @obiot if you want to explore how to use `pointerenter` and `pointerleave`, we'll do it in another ticket.

**Comment by obiot** [comment]
indeed, let's avoid any further breaking changes in 2.1.0, and let's keep this one for 2.2.0 :)
