### ISSUE TITLE
more advanced scaling modes

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#656]
Following the work on scaling mode in 2.1.x (see #641), few additional modes could be added :

- [x] `fit` : Letterboxed; content is scaled to design aspect ratio 
- [x] `fill-min` : Canvas is resized to fit minimum design resolution; content is scaled to design aspect ratio
- [x] `fill-max` (current `fill` mode) : Canvas is resized to fit maximum design resolution; content is scaled to design aspect ratio
- [ ] `flex` : Canvas is resized to fit; content is not scaled
- [x] `flex-height` : Canvas height is resized to fit; content is scaled to design aspect ratio
- [x] `flex-width` : Canvas width is resized to fit; content is scaled to design aspect ratio
- [x] `stretch` : Canvas is resized to fit; content is scaled to screen aspect ratio

(@parasyte, l took the list from the gitter chat)

**Comment by parasyte** [comment]
FYI, we should rename `fill` now, so it doesn't become a breaking change later. :)

**Comment by obiot** [comment]
Indeed good idea :)

Is fill-max correct though, i meant to verify that later when taking screenshots of all modes, but for now i'm confused :p

**Comment by parasyte** [comment]
I'm making the change now.

**Comment by obiot** [comment]
Nice !!!
