### ISSUE TITLE
Multiple shape collisions are not working correctly

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#659]
From the following comment: https://github.com/melonjs/melonJS/commit/1fb211e3b6f47c3caa6b134c6d5d3fe46db97e48#commitcomment-9854892

Also a recent thread on the forum mentions the same issue (2.0.2): https://groups.google.com/d/msg/melonjs/2h4Lth7o56k/Xi0Sp2CwrzUJ

**Comment by obiot** [comment]
indeed, something is really off here and was probably broken in a previous commit, I just launched the "shapes" examples and got the following results (it was working when I added the support for the physic editor) :
![screen shot 2015-02-21 at 11 29 07 pm](https://cloud.githubusercontent.com/assets/4033090/6314636/77da6c70-ba21-11e4-84aa-80d9f6eb605e.png)

**Comment by obiot** [comment]
hmm this is something else, as the `noDefaultShape` is only taken in account when specified through Tiled, and as a consequence a default shape is added to each object (a square here, giving this result).

that however shows that the multistep stuff is working properly !

**Comment by obiot** [comment]
fixed !
![screen shot 2015-02-21 at 11 41 56 pm](https://cloud.githubusercontent.com/assets/4033090/6314693/f8a9c36c-ba23-11e4-851e-3183167c5133.png)

**Comment by agmcleod** [comment]
Nicely done sir. Was scared my _absouteBounds broke something again :D

**Comment by obiot** [comment]
Well I just fixed the example, from what I see, and since it used mutiple polygon shapes for every objects, multishape is working properly :)

**Comment by parasyte** [comment]
Do collisions work between the shapes? Maybe it's only an issue with overlapping shapes on a body? I'll look into it today using the code from the commit comment. (See below.)

```javascript
game.PlayerEntity = me.Entity.extend({
    init: function(x, y, settings) {
        settings.shapes = [
            new me.Rect(0, 0, settings.width, settings.height),
            new me.Ellipse(0, 0, settings.width, settings.width)
        ];
        // call the constructor
        this._super(me.Entity, 'init', [x, y , settings]);
```

Use this in the platformer, and run to the left. When the circle collides with the barrier, the player bounces back to the right. It feels related to #580, #597, etc.

**Comment by parasyte** [comment]
@agmcleod I have determined this is directly related to #634.

An ellipse is positioned by its center point (makes sense!) and a polygon is placed by its point of origin, which is usually the upper-left corner (also makes sense!) Things start to get confusing when the bounds is calculated, because the information about the point of origin gets lost.

Try this: Replace the mainPlayer shape with a circle in the platformer:

```javascript
settings.shapes = [
    new me.Ellipse(0, 0, settings.width * 2, settings.width * 2)
];
```

When you run it with the debugPanel enabled, you'll see that the collision offset is miscalculated. It can be traced back to this line: https://github.com/melonjs/melonJS/blob/4f115420b3e6dcbfde70b6f4069d74fc23127b91/src/physics/collision.js#L575 It attempts to calculate the ellipses **center position** relative to the polygon. But because the absolute bounds is used, and the ellipse's `pos` property is `<0,0>`, this actually computes the position of the **upper left corner of the boundary box** relative to the polygon.

This bug can be swept under the rug by adding the ellipse's radius, but this only works for a single-shape body. When a body has multiple circles, the computations get WAY off.

The boundary box is not the right tool for computing an ellipse's position ... or any shape for that matter, since *it will only work with shapes whose origin is at the upper-left corner of its own boundary box*.

What we really need for shape hit testing is an absolute position vector, instead of a bounding box. Such that the position of a circle is computed by:

```javascript
entity.ancestor.absolutePos + entity.pos + circle.pos
```

Where `ancestor.absolutePos` is the proposed absolute position vector. AFAICT, this should work for all shapes and all groups of shapes.

**Comment by parasyte** [comment]
@agmcleod I tested the ticket-659 branch with a few different configurations of body shapes (with ellipse), and it is all looking good here. It's also much simpler than a bounding box approach.

```javascript
// Only a circle
settings.shapes = [
    new me.Ellipse(0, 0, settings.width * 2, settings.width * 2)
];

// A rectangle and a circle at <0,0>
settings.shapes = [
    new me.Rect(0, 0, settings.width, settings.height),
    new me.Ellipse(0, 0, settings.width * 2, settings.width * 2)
];

// A rectangle and a circle centered
settings.shapes = [
    new me.Rect(0, 0, settings.width, settings.height),
    new me.Ellipse(settings.width / 2, settings.width * 0.9, settings.width * 2, settings.width * 2)
];

// A rectangle and a circle on the right
settings.shapes = [
    new me.Rect(0, 0, settings.width, settings.height),
    new me.Ellipse(settings.width * 2, 0, settings.width * 2, settings.width * 2)
];
```

**Comment by agmcleod** [comment]
Ah interesting. I'm really surprised i didnt notice the issue in the collision test. Perhaps because of the speed & shapes being small enough.

**Comment by parasyte** [comment]
@obiot @agmcleod This ticket is *fixed* in two different flavors: `ticket-659` branch and `ticket-659-getAbsBounds` branch. The former changes `getBounds` to return an absolute bounding box per RFC on the forum. The latter implements `getAbsBounds` for the absolute bounding box, following @obiot's comment.

`ticket-659` is pretty simple; everything has a `getBounds` method as usual. Shape bounds are relative to an arbitrary point of origin. And the boundary box for everything else is relative to the world container. None are relative to arbitrary parent containers.

`ticket-659-getAbsBounds` is crazy complex as mentioned in the commit message: https://github.com/melonjs/melonJS/commit/9e7bb3a95bdf13c66d7aea9daa19c64daca905b5 This branch makes `getBounds` almost useless for everything except the debug panel and shapes (shapes don't have absolute bounds, same as above). The breakdown:

* `getBounds` for shapes is relative to an arbitrary point of origin
* `getBounds` for everything else is relative to an arbitrary parent container ~~unused~~ (used by debugPanel)
* `getAbsBounds` is relative to the world container
