### ISSUE TITLE
DOMContentLoaded not found

### ISSUE THREAD

**Issue by dakairus** [melonjs/melonJS#662]
Hi guys, after tested the drag and drop example successful, I started to use the new build of melon js into my actual project and I got this error(again only happens in Cocoon js):

javascript exception (Tag:'DOMContentLoaded')

Debugging a little bit I found that the problem start when the  line of code:

me.loader.onload = this.loaded.bind(this);        

is added to the onLoad method, don't happened with the drag and drop example, because don't use the loaded listener event(don't use resources).

**Comment by parasyte** [comment]
According to this article, CocoonJS supports `document.addEventListener("DOMContentLoaded")` : http://support.ludei.com/hc/en-us/articles/200807787-HTML5-feature-list And this article is over 1 year old.

**Comment by dakairus** [comment]
Hi jay, yes sorry for this, there was a buggy thing in the compilation on Cocoon JS yesterday, they already fixed so this issue don't have sense x.x. I will close it.

**Comment by parasyte** [comment]
After some more research, it looks like this may be related to WebGL on CocoonJS: http://www.html5gamedevs.com/topic/1645-phaser-107-with-ludei-cocoonjs-error-with-canvas-scaling-problems-with-webgl/ and http://www.html5gamedevs.com/topic/1613-cocoonjs-webglrenderer-scaling-question/

The suggested solution is `me.video.init(window.innerWidth, window.innerHeight, ...)` but that seems odd, and it won't work properly with video scaling.

**Comment by parasyte** [comment]
Ah! Just saw your response. Glad this is resolved then! :relaxed:
