### ISSUE TITLE
Improve the DraggableEntity and DropTargetEntity by using the built-in `pointerevent` and `pointercancel` events

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#663]
see #655 for the related discussion. 

Also most probably some tweaking around the `pointercancel` event.

**Comment by parasyte** [comment]
Whoops! I thought the GUI/pointer fixes in 2.1.1 was fixing this ticket, but that's not the case. :sweat_smile:

**Comment by parasyte** [comment]
Following discussion in another commit, this ticket is invalid: https://github.com/melonjs/melonJS/commit/a363519cd05c3f83d22a30c7f21a1c8d787ed7e2#commitcomment-12380661

> The takeaway is that none of these three events [`enter`, `leave`, and `move`] should be used on entities that can be dragged by the pointer.
> That's why the `move` event was never used on the entity itself, but instead subscribes to the "global" `move` event.

**Comment by obiot** [comment]
Hmm... Let me finish my night first, i'll come back to comment on this one later ;)

**Comment by obiot** [comment]
wait so why can't i use both pointermove and poinverenter/leave together, i'm not getting it.

first pointerevent and pointerleave are simulated event, and just triggered after the pointermove, so I don't see any reason why they could not be used to be honest.... even if an entity is dragged, as the pointer remains in the entity region, none of the pointerevent or pointer leave will be "re-triggered" during the drag, and actually it's kind of working on the shape example. but maybe it's the "kind of" that is my issue here :)

**Comment by parasyte** [comment]
@obiot Did you see the other link in gitter chat? This one: https://github.com/melonjs/melonJS/issues/655#issuecomment-74804820 It explains the problem as perfectly as I possibly can. If the entity can be dragged, you cannot use any of the three events on it. I believe it is worth documenting this "limitation" (I don't have a better word for it yet)...

Implementing a draggable entity requires handling "global" events with special filtering considerations. Does it make sense why it cannot be done any other way?
