### ISSUE TITLE
add a 3d vector class (new one or extend the current `me.Vector2d()` one

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#664]
to be used to provide a true 2.5D implementation, as the vector `z` property could be used to replace `object.z` property in a more standard way, and will be then more useful for the webGL implementation.

**Comment by parasyte** [comment]
:+1::+1: Because +1 is not enough

**Comment by obiot** [comment]
here they are ! I'm not really sure though on when or not to include the z value for the more advanced mathematical functions. Any advice/opinion ?

Also I did not use them yet, i'm waiting until we are clear on the here above question.

**Comment by obiot** [comment]
i was thinking as well that maybe we should make the z parameter optional for every function, just to make it easier when using vector2 with vector3d object ? 

typically to manage this case :
https://github.com/melonjs/melonJS/blob/master/src/physics/body.js#L495

**Comment by parasyte** [comment]
What I like about `Vector3d` is that we can move the `z` property off of Renderable and into `pos`

**Comment by obiot** [comment]
Same for me, i have the exact same goal :p

**Comment by obiot** [comment]
ticket done guys, and all merged into master. They are certainely some futher improvements yet to find, but this one is done,

other big addition of this ticket, is all the unit test for all the vector classes, and I did found a few bugs/issues here and there :)

**Comment by obiot** [comment]
14 tickets to go !
