### ISSUE TITLE
Regression: TMX compression no longer raises an exception

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#665]
Reported on the forum: https://groups.google.com/d/msg/melonjs/VH8YYVo251s/_s8PnS94orcJ

Looks like the detection doesn't exist: https://github.com/melonjs/melonJS/blob/master/src/level/TMXMapReader.js#L279

The `null` should be the value of:

```javascript
var compression = Array.isArray(data[TMXConstants.TMX_TAG_DATA]) ? data[TMXConstants.TMX_TAG_COMPRESSION] : data[TMXConstants.TMX_TAG_DATA][TMXConstants.TMX_TAG_COMPRESSION];
```

**Comment by obiot** [comment]
uh, funny, but else detection is here : https://github.com/melonjs/melonJS/blob/master/src/level/TMXMapReader.js#L240
then :
https://github.com/melonjs/melonJS/blob/master/src/utils/utils.js#L193

**Comment by parasyte** [comment]
:+1: That's what I got out of it, too
