### ISSUE TITLE
Incompatible with underscore/lodash

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#666]
I discovered that melonJS breaks underscore/lodash, because a module I wanted to use has such a dependency. The issue is an incompatible implementation of `Object.prototype.extend`.

Here is a workaround for node.js, but it is not applicable to browser environments... where `pathwatcher` is the module with the underscore dependency.

```javascript
var vm = require("vm");
var pathwatcher = vm.runInNewContext('require("pathwatcher")', { "require" : require });
```

**Comment by obiot** [comment]
moving this to future, i bet the best solution would be to switch to ES6 inheritance, but the ecoystem is not ready yet for that.

**Comment by agmcleod** [comment]
Well we can get started using a babel in our grunt process. But really i'm in no rush. I'd rather get a couple stable builds of 2.1 or 2.2 out first before changing the class system.
