### ISSUE TITLE
[regression] XML layer data format parsing is broken

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#667]
Loading of TMX/XML map is working, the issue is when using 'XML' as the encoding type for layers.

Current Status :
* [ ] ~~XML~~ *(deprecated in Tiled 0.15)*
* [x] Base64 uncompressed : 
* [ ] ~~Base64 gzip compressed~~ *(deprecated in Tiled 0.15)*
* [ ] Base64 zlib compressed *(not supported)*
* [x] CSV
* [x] JSON (although thsi one is through the export function)

Note sure i really do care about XML, as first it produces bigger files, it's longer to parse, and won't be working anyway with CocoonJS. So instead of spending (wasting) time on it, we could also remove the corresponding code and throw an nice exception ?

**Comment by parasyte** [comment]
Ooooh, I didn't know there was an XML format for layers! It makes sense though, if you want your map data to be easily writable by external tools. Have you tried to JSON export a map with XML format layers? I imagine it would end up in a similarly verbose format that we don't support?

**Comment by obiot** [comment]
the exported JSON file is always in the same format actually, whatever the format chosen in Tiled, this really only applicable when loading the Tiled "built-in" XML format.

Also, if you want to generate your map by an external tools, why not choose then JSON, is it not easier to generate ? (not to mention that Tiled does actually support loading a JSON map directly)

**Comment by obiot** [comment]
Small update here as both `XML` and `gzip` support have been dropped (or deprecated) in the last Tiled 0.15 release. Remaining task here is therefore rather to display a `deprecated` message when using these two formats.
