### ISSUE TITLE
Redesign `me.TMXTileMap` using `me.Container`

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#669]
me.TMXTileMap would then contains all related layers and entities, and would be added to the game.world. As opposed as now where we add all the me.TMXTileMap "childs" directly into the game world.

see as well the comments here :
https://github.com/melonjs/melonJS/commit/531c8a22b82a5aa0f8401fdf653b285c8133137b

**Comment by parasyte** [comment]
This should be pretty easy; `levelDirector.loadTMXLevel` already accepts a destination `container` argument.

https://github.com/melonjs/melonJS/blob/531c8a22b82a5aa0f8401fdf653b285c8133137b/src/level/LevelDirector.js#L40

Some thoughts: We probably want to pass an optional `settings` object to `levelDirector.loadLevel` (e.g. as part of #455 to provide a callback) which can also be given an explicit destination container.

```javascript
var map = new me.Container(0, 0, 0, 0);
me.levelDirector.loadLevel("map1", {
    "callback" : function () { /* ... */ },
    "container" : map
});
// ...
```

**Comment by obiot** [comment]
i was more actually thinking about directly define a container, instead of loading the object into a container, but i suppose this is quick win as a temporary solution :P

**Comment by obiot** [comment]
so I kind of solved the issue I had by redesigning these objects, but i'm still not happy about it :
- objects are initialized two times : the first time when the reference `me.TMXTileMap` object is created (through the consttuctror and `onActivateEvent` when added to the container). and the second time when added to the world container (where`onDeActivateEvent` is first called when "removing" it from the previous container, and then again `onActivateEvent`)
- there is no real cleaning anymore, object array like `layerData` stay allocated the whole time

so, still thinking about ditching this branch, and wondering if the best is not to keep the `me.TMXTileMap` the way it was before (as a reference of the parsed/interpreted JSON) and then build it into either the world container or the given one (to bounce back of the suggestion here above, that would then also allow to add different levels into the world)

**Comment by parasyte** [comment]
Are all of the objects moved to the world container? Or is the map container moved into the world container?

**Comment by obiot** [comment]
they are moved into the world container. I wish i could move directly the map container into the world container but thats where things are not simple, as except for layers objects, the entities are only instantiated when moved into the world container. Until that the map container only contains `me.TMXGroupObject` hold the TMX object definition (basically the position and settings). This prevents creating potentially thousands of object in memory for level that are not even loaded.

**Comment by obiot** [comment]
this one really starts to look good !

I still need though to fine-tune/fix the usage of an object container as the base `TMXTiledMap` object to avoid the double-initialization for the Layer objects. I'm thinking maybe to add (or override) the addChild function and customize it a bit, since anyway, it's still a private objeft and  cannot be added directly into a game world

**Comment by parasyte** [comment]
Wow, that's looking great!

**Comment by obiot** [comment]
indeed, i did some nice clean up ! not sure though it's ready yet to load two different levels, escpecially when I see that line that automatically center a level when loaded, but it's already way better than before :)

**Comment by obiot** [comment]
(why was this issue closed?)

I think anyway i start to be happy enough about it, that we can close it and merge it back into master.  will do some more testing/debugging though first to be sure there are no regression, especially in terms of object allocation/deallocation

**Comment by obiot** [comment]
hi guys, with this last change, I finally merged both the map reader and the tmx map objects.

Having a map object as a container was not convenient at all, as it was adding more complexity (how to reset object state, etc..), so I took back the previous approach and just over-simplified the whole thing.

So now a level object defines the following API (look at the changes in the LevelDirector):
`reset()` : to reset what might need to be resettled (level pos for example)
`addTo(me.Container, flattten)` : to add all level objects into the given container
`destroy()` : to clean the allocated objets 

it can for sure be further improved/simplified, but so far i'm really happy about this ticket !

**Comment by obiot** [comment]
and as well, we have one less object in the global me scope :)

**Comment by parasyte** [comment]
:flushed: I have to admit, it's a bit too much to take in at one time. My only hope here is that this ticket provides the ability to load multiple maps simultaneously. The container approach seemed like the right way to do it; load the map into a container, and add the container to the world. Want to stitch another map into the world? No problem, load another one into a second container and add that container to the world, too!

Extending `me.Container` isn't necessary to do anything I just described. The load function can just as easily create and return a new container with all the stuff already in it...

**Comment by obiot** [comment]
well it can, since a level can be added to any container using the `addTo` function, that takes any container as parameter :)

**Comment by obiot** [comment]
closing this one as such, created #704 to finalize it
