### ISSUE TITLE
custom collision masks

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#670]
This one is really easy. We just need a new `me.collision.types.USER` and some documentation for how to use it:

```javascript
game.collisionTypes = {
    LOCKED_DOOR : me.collision.types.USER << 0,
    OPEN_DOOR   : me.collision.types.USER << 1,
    LOOT        : me.collision.types.USER << 2
};

// Set collision type for a door entity
myDoorEntity.body.collisionType = game.collisionTypes.LOCKED_DOOR;

// Set collision mask for the player entity, so it collides with locked doors
myPlayerEntity.body.setCollisionMask(
    me.collision.types.ENEMY_OBJECT |
    me.collision.types.WORLD_SHAPE |
    game.collisionTypes.LOCKED_DOOR
);
```

**Comment by obiot** [comment]
eerr... this is a dangerous one actually. for the me.state constants it's quite easy as the value are just regular numbers, but here one cannot use any value, and people need to be educated on what are binary values, bitwise operations to at least understand why you use `<< 1` in your example, and how not to break the collision mask filtering with a non correct value.

**Comment by parasyte** [comment]
It's a matter of education, and I do not consider any matter of education dangerous at all.

**Comment by obiot** [comment]
Yeah, i just see more "my game does not work" kind of question popping up :)

**Comment by obiot** [comment]
do it or not do it, that is the question :)
