### ISSUE TITLE
dispose() on audio objects

### ISSUE THREAD

**Issue by samifruit514** [melonjs/melonJS#671]
unload method does not dispose() audio objects like its done with images.

**Comment by obiot** [comment]
which version of melonJS ? and when writing `dispose()` are you referring to the cocoonJS dispose function ?

**Comment by obiot** [comment]
@samifruit514 any comments ?

**Comment by obiot** [comment]
"CocoonJS’ Canvas+ environment exposes a method called “dispose” on canvas, image and audio objects. This method immediately frees the associated texture or internal buffer, which is very useful for games with heavy textures or for games that need a greater control over the memory."

add something like `audioTracks[sound_name].dispose && audioTracks[sound_name].dispose()` before the next line should do the trick
https://github.com/melonjs/melonJS/blob/master/src/audio/audio.js#L467
