### ISSUE TITLE
Cutscene Domain Specific Language (using a Finite State Machine)

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#672]
Cutscenes can be coded easily enough with JavaScript. But it would be far better to have a DSL for describing cutscenes, instead of code that chains Tweens. The argument for this is that it will be easier to write a "cutscene editor" that can read and write a DSL than one which reads and writes JavaScript. The DSL will just be a JSON structure that can represent a FSM.

As far as the JSON FSM goes, there's this project: https://github.com/hyperandroid/Automata which we may not use verbatim, but could probably lift some ideas from the schema they have. This is a nice project because it separates the logic from the state. In our world, the logic would be hardcoded, and the states describe the cutscene as a series of instructions for the hardcoded logic.

Some ideas to include in the FSM logic:
- [ ] Tweens, animations, timers, and audio with state transitions on complete
- [ ] Add and remove entities from the scene
- [ ] Transitions on user input sync (e.g. wait for keypress) and async (e.g. skip dialog)
- [ ] Load maps with state transitions [depends on #455 and #669]
- [ ] Call methods and set properties on entities in the scene

_Am I missing anything obvious?_ There might be some considerations around conditional logic, especially if a state needs to be executed only on specific platforms? This would be weird and not recommended, but "unexpected" stuff like this should be considered.

**Comment by luizfilipe** [comment]
This could be awesome +1

**Comment by obiot** [comment]
just stumbled on this, quite nice ! :
https://github.com/Vandise/melonjs-scenes
