### ISSUE TITLE
Add support for Web Audio 3D sound positioning

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#673]
Howler 2.0 already does support it through the effect plugin :
https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js

but we don't have any similar API exposed, nor have that plugin currently used when building the melonJS library

**Comment by parasyte** [comment]
I'm more interested in synthesizing audio with the WebAudio API than the 3D audio capabilities, but that's just me. :)

**Comment by obiot** [comment]
yeah, I still have also that sweet dream to add back that mod player we had in a super old version of melonJS, but this time implemented as a howler plugin :P

https://github.com/melonjs/plugins/tree/master/deprecated/audio/ym
