### ISSUE TITLE
TypeError: c is NULL

### ISSUE THREAD

**Issue by echarlotte** [melonjs/melonJS#675]
I completed the tutorial and it worked fine, and I started to change it for my own project. I get the TypeError: c is NULL when I move from screen 1 to screen 2. It says it is for the c in the minified js. What gets put into c? I can't figure out what thing is returning null.

**Comment by agmcleod** [comment]
Going to close this issue, as this is more of a support question. Ask again on the forum: https://groups.google.com/forum/#!forum/melonjs. Also, use the debug (unminified) build to get a better idea of what c is. The boilerplate you downloaded should provide both in the lib folder. Update index.html to point to the unminified.
