### ISSUE TITLE
EnemyEntity Correction in Tutorial

### ISSUE THREAD

**Issue by echarlotte** [melonjs/melonJS#677]
In Part 5 of the tutorial the code for the width and height of the sprite needs a correction. It currently shows: 
settings.spritewidth = settings.width = 64;
settings.spritewidth = settings.height = 64;

I think it should be:
settings.spritewidth = settings.width = 64;
settings.spriteheight = settings.height = 64;

**Comment by parasyte** [comment]
Hello! Thanks for the notice @echarlotte We have a repo dedicated for the tutorial, so I've moved this ticket there: https://github.com/melonjs/tutorial-platformer/issues/22

**Comment by agmcleod** [comment]
@echarlotte thanks for the report! fixed: https://github.com/melonjs/tutorial-platformer/commit/7031c4400dcda33281c044bda66431608a629a5f
