### ISSUE TITLE
sprite problems

### ISSUE THREAD

**Issue by Battleaxe19** [melonjs/melonJS#679]
I went through the platform tutorial and got everything working. When I tried to bring in my own sprite sheet for MainEntity, it just wasn't working. The sprite sheet used in the tutorial was 512x64 pixels. The sprite sheet I was using was 383x64. Since everything was divisible by 64 still it should have worked. My game would crash after going through the sprite sheet once and would give me an error in the min.js file. It boggled my mind.. I ended up jsut adding some extra sprites to my sheet and making it 512x64 like the example which allowed me to play without crashing. Anybody know why this might happen?

**Comment by AngyPengy** [comment]
383 is not divisable by 64, so that would be the issue

**Comment by obiot** [comment]
Hi, 

Can you please use the forum for support question, the tickets are rather used for bug report or roadmapping : https://groups.google.com/forum/#!forum/melonjs

as for your issue, probably an issue with the spritesheet, as 383 is not a multiple of 64, also are you sure that the platformer animation definition are fully applicable to your datasheet (seems yours is smaller) ? Last but not least I would suggest to use the un-minified version of melonjs (the one without the "-min" postfix) to make it 'understandable" when checking for exception in the console.log

thank you for your understanding !
Oliver.

**Comment by Battleaxe19** [comment]
That was a typo on my part. I meant to type 384. My spritesheet was set to 384 when I had the issue.

**Comment by obiot** [comment]
repost this message in the forum, and copy/paste the code for your entity with the animation deifnition.

**Comment by parasyte** [comment]
A 384x64 image divided into 64x64 cells has 6 columns by 1 row, so the valid frame ID range is 0 - 5.
