### ISSUE TITLE
2.1.1 maintenance release

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#680]
so guys, I moved the milestone for 2.1.0 for the end of this week (next Wednesday), we really need to release this one now ! We also have a few members using the master branch for a while now, and except of the last `updateBounds` stuff it seems to be stable enough

Also created a maintenance 2.1.1 release for end of April to cover the few bugs that will certainely pop-up when 2.1.0 will go mainstream.

so, to our keyboards !

**Comment by parasyte** [comment]
@obiot Ok, I've cleaned up all the remaining 2.1.1 tickets. Release looks good from my end. If anyone has something else to add, now is the time. @agmcleod :)

**Comment by agmcleod** [comment]
Nope, nothing on my plate!

**Comment by obiot** [comment]
Awesome! I'm at a tradeshow until tomorrow, but i can then prepare the release this weekend :)

**Comment by obiot** [comment]
all done, nice maintenance release !

**Comment by agmcleod** [comment]
:)
