### ISSUE TITLE
loop false option for animation sheet?

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#682]
Was chatting with a user on gitter. He/she asked me how to make an animation play once. I responded to use setCurrentAnimation which accepts a callback to set to another animation. However this isn't exactly intuitive. I wonder if maybe we have a loop option which defaults to true on setcurrentanimation. When the animation finishes, it maybe just triggers a pause or something.

**Comment by parasyte** [comment]
You can set `animationpause` in the animation complete callback.

**Comment by agmcleod** [comment]
Thought about that, but it's more a question of a concept being obvious.

**Comment by parasyte** [comment]
There's also #390 where each frame may be given its own duration. A duration of Infinity seems pretty obvious.

**Comment by obiot** [comment]
with #390 being done now, do we still need to keep this one opened, since we can indeed specify a `Infinite` duration for the last frame (although it does look more like a hack than a proper feature)

**Comment by obiot** [comment]
keep it or close it ?

**Comment by obiot** [comment]
decided on this one, that the `Infinity` trick was doing it, so I added an example in the documentation.

Closing this one too then.
