### ISSUE TITLE
Pooling Problems

### ISSUE THREAD

**Issue by aaschmitz** [melonjs/melonJS#683]
Hi guys

With melonJS 2.2-dev (the lastest in repo), when using the pooling with a object registered as:

me.pool.register("anim", game.animation, true);

The message below is show in the console when calling me.pool.pull:

Uncaught TypeError: Cannot redefine property: width  melonJS-2.2.0.js: 7084

me.Renderable.me.Rect.extend.init @ melonJS-2.2.0.js:7084
me.Sprite.me.Renderable.extend.init @ melonJS-2.2.0.js:7334
me.AnimationSheet.me.Sprite.extend.init @ melonJS-2.2.0.js:7640
_super @ melonJS-2.2.0.js:597
game.animation.me.AnimationSheet.extend.init @ build.js:3521
me.pool.api.pull @ melonJS-2.2.0.js:3065
game.generator.Object.extend.update @ buil.js:4984
me.Container.me.Renderable.extend.update @ melonJS-2.2.0.js:9252
me.game.api.update @ melonJS-2.2.0.js:1834
(anonymous function) @ debugPanel.js:174
Object.defineProperty.value @ melonJS-2.2.0.js:23549
_renderFrame @ melonJS-2.2.0.js:9993

Registering the object with me.pool.register("anim", game.animation) works normally when calling me.pool.pull.

**Comment by aaschmitz** [comment]
The same problem occurs with me.ParticleEmitter, when calling "burstParticles".

**Comment by obiot** [comment]
Hi, do you mean the problem was not present with the 2.0.x branch ?

Right now I don't really remember what we changed on that :P

**Comment by aaschmitz** [comment]
Hi, yes, in the 2.0.x the problem was not present.

**Comment by parasyte** [comment]
This is definitely related to the observableVector2d changes; https://github.com/melonjs/melonJS/commit/1d2594f377cac806ee8a6ba0d68d3941654649dc#diff-50ced4be4c6f7b469bb9aeb52b44a6a9R158

**Comment by obiot** [comment]
oh, so if we check first if the property is undefined, it should then fix it I suppose :

````javascript
if (typepof(this.width) === "undefined") {
 Object.defineProperty(this, "width", {
       get : function () {
            return this._width;
        },
       set : function (value) {
            this._width = value;
            this.updateBounds();
        }
   });
}
````

and same for `height`

@aaschmitz would you mind give it a try ? should be quite easy to modify :P

**Comment by aaschmitz** [comment]
Hi @obiot, worked like a charm! Added the "typeof" in me.Renderable width and height. 

Perhaps this change go in melonJS 2.1.1 ;)

Thanks!

**Comment by obiot** [comment]
yep, definitely will :) 

Thank you Andre !

**Comment by obiot** [comment]
done in the 2.1.1 branch !
https://github.com/melonjs/melonJS/tree/2.1.x

**Comment by obiot** [comment]
@parasyte @aaschmitz @agmcleod 

hi guys, I made some further changes following my comments here :
https://github.com/melonjs/melonJS/commit/62ef097fdc606a926f0f6e210798c38aedd03b91

I believe we have something cleaner now, and succesfully tested with the platformer examples, the particle editor, and the space invaders tutorial.

Would appreciate your feedback :)

Note: the `me.Rect` object now uses a getter/setter for the width/height properties, that might not sound super useful right now, but it will if we convert the me,Rect object to inherit from a polygon object (#643)

Note2 : did also a bunch of others fixes (see the latest commits), i'm not sure however they were all regression linked to this last commits

thanks !

**Comment by obiot** [comment]
off to bed now ! :P

**Comment by parasyte** [comment]
My only concern at the moment is that the hacks are getting worse all the time. :stuck_out_tongue_closed_eyes:

**Comment by aaschmitz** [comment]
Hi guys, tested with lastest 2.1.x version and it's ok!

**Comment by obiot** [comment]
Thank you so much Andre !
