### ISSUE TITLE
Add support for the Physic Body Editor Tool

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#684]
http://www.aurelienribon.com/blog/projects/physics-body-editor/

![image](https://cloud.githubusercontent.com/assets/4033090/7696688/16daabb0-fe32-11e4-8537-947d57799fa7.png)

This is a free and great alternative to the Physic Editor Tool we already support (#413) and can also export to JSON file that can be used in melonJS.

Should not be that hard to add, format is just a bit different, and we then need some logic to recognize which one is it and parse it properly.

It also allow to define additional physic properties (for #588) as with PE :
* `density`
* `friction`
* `restitution` (`bounce` in PE)

**Comment by obiot** [comment]
first feature of the 2.2 branch :P

**Comment by ferrancarles** [comment]
El 28/05/2015 19:00, "Olivier Biot" <notifications@github.com> escribió:

first feature of the 2.2 branch :P

—
Reply to this email directly or view it on GitHub
<https://github.com/melonjs/melonJS/issues/684#issuecomment-106489514>.
