### ISSUE TITLE
Critical: MelonJS 2.1 doesn't work on Chrome v43.x (maxTouchPoints issue)

### ISSUE THREAD

**Issue by rvanzon** [melonjs/melonJS#685]
The error

“Uncaught TypeError: Cannot set property maxTouchPoints of #<Navigator> which has only a getter”.

turns up when using MelonJS 2.1.x on Chrome Version 43.0.2357.65 (64-bit) as Chrome implemented maxTouchPoint as a getter now.

Commenting out 
```
// navigator.maxTouchPoints = me.agent.prefixed("maxTouchPoints", navigator) || 0;
```

in me.device fixes it.

**Comment by obiot** [comment]
Yep, moving it under me.device for later check is properly anyway cleaner than modifying the browser properties :)

**Comment by obiot** [comment]
done, I will still wait a few more days, to see if any other isssues are popping up in this branch.

thanks again for you feedback :P
