### ISSUE TITLE
GUI_Object binds both down & enter pointer events

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#686]
https://github.com/melonjs/melonJS/blob/970927095d77c4672f181a05d3d33b79454829b0/src/renderable/GUI.js#L99

Realized due to bug in: https://groups.google.com/forum/#!topic/melonjs/204CYK6Yoe4

Given that pointerenter is the event that does not bubble for entering a section, I don't see how this should resolve to onClick. So i think we have 3 options:

1. Remove the calls to pointerenter & pointerleave
2. Keep the events, but bind to different callback functions. `onEnter`, `onLeave`
3. Change the constructor to accept options of what events should be bound.

**Comment by parasyte** [comment]
At a minimum, the `pointerleave` event *needs* to stay. GUI_Object might benefit from a new `cancel` action, instead of performing a `click` action when the pointer leaves the GUI rect.

**Comment by agmcleod** [comment]
Agreed on the cancel bit. But why do we need the pointerleave?

**Comment by parasyte** [comment]
For cases like this: https://github.com/blipjoy/sprung_fever/issues/2

**Comment by agmcleod** [comment]
Ah okay, was thinking about it like with DOM events. Typically a mouseup on
a dom element will still fire on that element, but here we're doing at run
time rect calculation.

**Comment by obiot** [comment]
agree, the `pointerEnter` event should not trigger the `onClicked` event, but rather use a specific callback (`onEnter`, `onLeave` as suggested by Aaron).

if we all agree, I can modify this for inclusion in the 2.1.1 release ?

**Comment by obiot** [comment]
hi guys, see the above commit : is this what we all agreed on ?

**Comment by parasyte** [comment]
As long as the default `onLeave` handler cancels the current hover/click state.

**Comment by obiot** [comment]
tell me again why the `onPointerLeave` event should also cancel the click state ?

**Comment by parasyte** [comment]
I posted the reason in this ticket two days ago. :disappointed: Here's the link again: https://github.com/blipjoy/sprung_fever/issues/2

If `leave` doesn't cancel the click, you get really broken behavior.

**Comment by obiot** [comment]
Ahha sorry, I saw it actually, but then just forgot, must be one of these "senior moments" :p

**Comment by obiot** [comment]
we should be all set now then ! :p

i also added a test on the release flag to avoid multiple event triggering :
https://github.com/melonjs/melonJS/commit/1bbc4e26e6d7e05227f99fffb73fe0a126326c7c#diff-4542aeba5835ce6807cf6e36a774d767R205

**Comment by obiot** [comment]
everybody's happy with this one ?

**Comment by agmcleod** [comment]
Yep

**Comment by obiot** [comment]
great, I will wait the feedback from Lamberto before closing it anyway
