### ISSUE TITLE
drawStroke is broken

### ISSUE THREAD

**Issue by zoiba** [melonjs/melonJS#687]
If I haven't misunderstood the functionality of drawStroke function, it seems it's broken because it returns a filled text.
the _drawFont function inside melonJs don't handle the lineWidth property when stroke parameter is set  and it makes use of the context.fillText in any case.

**Comment by obiot** [comment]
Interesting ! I'll have a look tomorrow, but i have not used that one in a while so i'd say it's possible :)

**Comment by parasyte** [comment]
Closed via #688
