### ISSUE TITLE
Setters for me.Container.pos need to update child bounds

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#689]
When the position is updated/assigned directly on a `me.Container`, it needs to update the bounds on its children, then update its `childBounds` cache.

This was originally reported on the forum: https://groups.google.com/forum/#!topic/melonjs/GAs1_pkaFCM It looked at first like a bug in the demo, but it is doing the right thing, and melonJS is not updating the children's bounds appropriately.

**Comment by obiot** [comment]
Does the container object not inheriting from me.Renderable,  and by consequence has a observale vector pos object that automatically update the child bounds?

**Comment by parasyte** [comment]
It does inherit from me.Renderable, but that's not the issue. The issue is that changes to `me.container.pos` do not cascade into its children... Because the default ObservableVector2d doesn't (cannot) do the children iteration...

**Comment by obiot** [comment]
Can't we just redefine the callback to do what we want ? Or am i missing something obvious ? :)

**Comment by parasyte** [comment]
Yes. Of course, that is the solution to fix this bug. :)
