### ISSUE TITLE
ObservableVector: make scalar components private

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#691]
There is a lot of code out there that uses (and will continue to be enticed by) the scalar components of an observable vector. It is against intuition that assigning the scalar components directly is actually slower than using the vector methods like `set`, `scale`, `add`.

It is slower due to compounding computation:

``` javascript
this.pos.x += foo;
this.pos.y += bar;
```

This simple code executes the following _on both lines_:
- A getter method
- A setter method
- The update vector update method

The last one is really heavy, and can cause cascading updates on `me.Container` hierarchies (since 2.1.1)

The solution is to manipulate all vectors as an atomic unit (as if it were actually a real vector!) and the way forward is by marking the scalar components as private and tell users to not touch them. In other words, we'll remove the implicit getter/setter, and move to explicit getter/setter methods. That makes the above code example invalid, which is a major breaking change. Therefore this ticket is in the milestone for the next major release.

**Comment by obiot** [comment]
this one should be future and not 3.0.0

**Comment by obiot** [comment]
Closing this one, this is a major rewrite for the whole library, and replace all properties by a getter/setter won’t bring performances improvements (at the opposite) nor “new features”.
