### ISSUE TITLE
me.Container.draw should clip children to its own bounds

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#692]
From https://github.com/melonjs/melonJS/issues/649#issuecomment-75360960

Canvas clipping regions: https://developer.mozilla.org/samples/canvas-tutorial/6_2_canvas_clipping.html

``` javascript
renderer.save();
renderer.clipRect(this.pos.x, this.pos.y, this.width, this.height);
// ... loop through children here and call their draw method
renderer.restore();
```

For WebGL, use the stencil buffer.

**Comment by obiot** [comment]
wait, two different questions on this one :
- if the container should clip children to its own bounds, should the children position also capped to the maximum container limits ?
- at the contrary, is it not more logical and practical to dynamically resize the container based on all children position/size ?

**Comment by parasyte** [comment]
1. No, the position clipping isn't necessary. Rendering clips will be way faster.
2. Again, clipping in the renderer is going to be way faster than manipulating properties. Resizing the container is particularly heavy because it requires recursive resizing. Where clipping at the renderer is just a union of clip regions.

**Comment by obiot** [comment]
1. it won't be bit weird that if the position of a children if too close from the container limit, the sprite will be potentially "truncated" ?

**Comment by parasyte** [comment]
Yeah, it would be odd. But in my mind, that would be less surprising than the case where a small container goes out of the viewport, while one of its "overflowing" children stays on screen; in this case, the whole thing seems to disappear because the container's `inViewport` flag has suddenly evaluated to false, even though a child is still technically visible.

The clipping means that any overflowing children will never be visible in the first place.

**Comment by parasyte** [comment]
I have to write this down so I don't forget.

With #704 we'll have the ability to load multiple maps into the world. If we don't clip container children (this ticket) then we'll have some really weird issues with moving entities between maps and scrolling the viewport:

* Entities that are children of a map container *must* be bound to their parent map;
  * When the parent map scrolls off the screen, its children will disappear.
* Entities that are children of the world (root) container can go anywhere;
  * The world container is always visible.

**Comment by obiot** [comment]
so wait, if you are stitching several maps together into the same world, how does the main player can navigate through them ? I mean we should assume, that the main player would be added in one of these maps ?

**Comment by parasyte** [comment]
Exactly. The player entity needs to be a child of the world container, not a child of any single map container.

**Comment by obiot** [comment]
?@parasyte you wanna do this one maybe ? seems easy?

**Comment by obiot** [comment]
moving this one to 3.1.0

**Comment by obiot** [comment]
feature complete ! this will be super useful when implementing multiple camera/viewports :)

Keeping the container flag to false by default for now, will see later "when" to turn it to true by default
