### ISSUE TITLE
found oddity on AnimationSheet

### ISSUE THREAD

**Issue by zoiba** [melonjs/melonJS#697]
It only happens on animationSheet entities on scrolling levels,
I made a test case for explaining the problem:  dots on level are animationSheet entities, the pac-man travels the level, when it's on the opposite side, the level will be reloaded. The first run it's ok but the from the second time animationSheet entities blink randomly.

http://www.officinepixel.com/test/testCase_AnimationSheet/

zipped file

http://www.officinepixel.com/test/testCase_AnimationSheet/testCase_AnimationSheet.zip

**Comment by parasyte** [comment]
@zoiba, Thanks! This is another bug with the object pooling. I'm working on a patch right now.

**Comment by obiot** [comment]
wow, I would not have thought to look at those :P good job debugging this one !

**Comment by obiot** [comment]
@zoiba thank you again for the feedback, seems like that we have been able to fix a lots of nasty issues in this 2.1.x branch thanks to you :)
