### ISSUE TITLE
me.Renderable.pos is GC'd with pooling

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#698]
https://github.com/melonjs/melonJS/blob/b36c040e59a55c0eacd852b3d58593af5f18d99c/src/renderable/renderable.js#L162

This needs the same "create if undefined, else reset values" pattern used everywhere else. We'll need a new API to set the ObservableVector onUpdate callback for this.

**Comment by obiot** [comment]
this one was kind of tricky! I had to add a "silent" setter, as else the callback was being triggered when resetting the values (leading to an exception, since when entities are recycles,  body is undefined at that moment)

**Comment by obiot** [comment]
applied the same changes on `ObservableVector3d`, although its' completly unused for now :P

**Comment by parasyte** [comment]
Good win!
