### ISSUE TITLE
doc mouse navigation is broken

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#700]
When clicking one of the items on the right side (list of attributes & functions of a class) the main (left part) does not scroll down anymore to the selected items.

did not try with the 2.1 branch, but it's probably the same :P

**Comment by obiot** [comment]
closing this one, as fixed by @parasyte :)

**Comment by parasyte** [comment]
Oh yeah: https://github.com/melonjs/melonJS/commit/587f555f049e7027ba275bdea75596e3d5c023a8
