### ISSUE TITLE
Support CanvasRenderedPixelSize

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#701]
See: https://wiki.whatwg.org/wiki/CanvasRenderedPixelSize

**Comment by parasyte** [comment]
Not yet supported on any UA.

**Comment by obiot** [comment]
i thought about "polyfilling" it but it also seems to still be experimental

**Comment by obiot** [comment]
does not look like this one is ever gonna make it in the standard, and as for now, everybody seems to be "happy" with `devicePixelRatio` (event the new `backingStorePixelRatio` has been deprecated since then)
