### ISSUE TITLE
Followup: Non-intrusive language extensions

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#703]
Follows #702 (re: #666 #699)

melonJS adds the following language extensions which need to be sandboxed into the `me` namespace:
- [ ] `Array.prototype.random`
- [ ] `Array.prototype.remove`
- [ ] `Array.prototype.weightedRandom`
- [x] `Error.extend` -> `me.Object.extend`
- [ ] `Function.prototype.defer` -> [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/window/postMessage)
- [ ] `Number.prototype.clamp`
- [ ] `Number.prototype.degToRad`
- [ ] `Number.prototype.radToDeg`
- [ ] `Number.prototype.random`
- [ ] `Number.prototype.randomFloat`
- [ ] `Number.prototype.round`
- [x] `Number.prototype.sign` ->  [safe `Math.sign` ES6 polyfill ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign)
- [ ] `Number.prototype.toHex`
- [ ] `Number.prototype.weightedRandom`
- [x] `String.prototype.contains` -> [`String.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)
- [ ] `String.prototype.isBoolean`
- [ ] `String.prototype.isNumeric`
- [ ] `String.prototype.toHex`
- [x] `String.prototype.trim` -> (safe ES6 polyfill)
- [x] `String.prototype.trimLeft` -> (safe ES6-like polyfill, and candidate for ES7 standard)
- [x] `String.prototype.trimRight` -> (safe ES6-like polyfill, and candidate for ES7 standard)
- [x] `window.onReady` (replaced by [me.device.onReady](http://melonjs.github.io/melonJS/docs/me.device.html#onReady), window.onReady still present but marked as deprecated for now) -> #212 and [ES6 Module Loader Polyfill](https://github.com/ModuleLoader/es6-module-loader)
- [ ] `window.throttle` (this one also needs some update to increase accuracy by using RequestAnimationFrame)

Some of these (eg. `Error.extend`) are easy to solve (replace with `me.Object.extend`). Others could use `me` as a callable that returns a proxy class that may be instantiated or its prototype directly accessed:

``` javascript
var foo = 15;
console.log(me(Number)(foo).clamp(0, 10)); // >>>10
console.log(me(Number).prototype.random(0, 3)); // >>>2
```

Alternatively, just bring these proxy objects into the `me` namespace directly (seems more natural):

``` javascript
var foo = 15;
console.log(me.Number(foo).clamp(0, 10)); // >>>10
console.log(me.Number.prototype.random(0, 3)); // >>>0
```

**Comment by obiot** [comment]
few of them coukld also be replaced with a ES6 equivalent :P

**Comment by parasyte** [comment]
Yeah! `Function.prototype.defer` -> [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/window/postMessage) (Not ES6, but a W3C standard that is implemented everywhere.)

**Comment by parasyte** [comment]
In fact, I'll exit the list into a TODO list.

**Comment by obiot** [comment]
what about `setImmediate` to replace `defer`, I thought it was a better candidate ? 
https://github.com/melonjs/melonJS/issues/422

**Comment by parasyte** [comment]
I discovered that `window.setImmediate` is not going to be standardized. It is only supported in IE10+. From the MDN wiki:

> Note: This method is not expected to become standard, and is only implemented by recent builds of Internet Explorer and Node.js 0.10+. It meets resistance both from Gecko (Firefox) and Webkit (Google/Apple).

**Comment by obiot** [comment]
oh really, that's just sad :(

**Comment by obiot** [comment]
I would actually propose to remove `trimLeft` and `trimRight`, the latter can be replaced by `trim` in the `me.Font` and `me.BitmapFont`

**Comment by parasyte** [comment]
`trimRight` has a very specific use case in `me.Font` et al. It preserves text formatting that contains indentation. That's an important property with ASCII art.

**Comment by obiot** [comment]
allright, let's keep it, there are no ES6 safe polypill for those ones however :)

**Comment by obiot** [comment]
i'd say the easy one with no or minimum impacts are done :)

**Comment by parasyte** [comment]
Pretty awesome!

**Comment by obiot** [comment]
moving the rest to the next Major release

**Comment by obiot** [comment]
see #915

**Comment by obiot** [comment]
all done !
