### ISSUE TITLE
particles are broken in latest build

### ISSUE THREAD

**Issue by ldd** [melonjs/melonJS#705]
reproduction steps: 
1) build melonJS
2) browse the examples online using grunt serve...
3) select particle examples.
4) it fails

reasons: Cannot read property '0' of undefined

commit where things (probably) break:
https://github.com/melonjs/melonJS/commit/05da4c8f34b000680dd8a314c7f35aa495623c13

**Comment by obiot** [comment]
seems like this change :
https://github.com/melonjs/melonJS/commit/b36c040e59a55c0eacd852b3d58593af5f18d99c

is causing issue with this one :
https://github.com/melonjs/melonJS/blob/master/src/particles/particlecontainer.js#L24

not sure yet (late here) how to fix this one, but I'd probably move `this._bounds = me.game.viewport;` after the call to the constructor, and would also probably redefine the `resizeBounds()` function to prevent resizing the viewport :P

**Comment by ldd** [comment]
I can confirm that moving this._bounds after the call to the constructor works as a fix

**Comment by parasyte** [comment]
The quick fix is rename the property to something else like `_viewport`.

The particle container code predates changes to the bounding boxes. Now there's a property name collision.

**Comment by obiot** [comment]
oh yeah, even better, let me do it that way :P

**Comment by obiot** [comment]
@ldd done, thank you very much for the Feedback

@parasyte i let you close it if you are ok with the fix :P

**Comment by parasyte** [comment]
Wow ... That was easy! Also pushed to 2.1.x (and bumped version to 2.1.3)
