### ISSUE TITLE
Hexagonal TMX improvements

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#706]
- [x] `TMXHexagonalRenderer`: `pixelToTileX` and `pixelToTileY` methods are not ideal
  - [x] Don't create temporary vectors
  - [x] Don't compute tile coordinates twice in `me.TMXLayer.getTile`
- [x] Uncaught exceptions in hexagonal example:
  - [x] `TMXHexagonalRenderer` doesn't clamp the pointer position when looking up tile coordinates.
  - [x] When moving the pointer over the viewport while the map is loading

**Comment by obiot** [comment]
for the position clamping issue, it's not a problem specific to the hexagonal map, as the `me.TMXLayer.getTile()` does not actually any error check or clamping before accessing the data array.

**Comment by obiot** [comment]
I was looking at the first one `don't create temporary vectors", but we don't actually, we just pull one from the object pool the time to calculate the whole thing, and then we put them back :P

**Comment by obiot** [comment]
same for `getTile` we are actually calling 2 diferent functions, `pixelToTileX` and `pixelToTileY`

**Comment by parasyte** [comment]
Yeah, that's what I meant by temporary vectors; don't do that. It will be better to not rely on the vector class for these functions. See the other TMX Renderers...

**Comment by parasyte** [comment]
`getTile` calls those two functions, yes. Did you notice they both call `pixelToTileCoords`, and it's friggin huge? :laughing: Don't do that, either.

In other words, this is bad because the first time `pixelToTileCoords` is called, it throws away the `y` from the resulting vector (uses only the `x`). The second time it's called, it throws away the `x` so it can use the `y`!

# WTF

**Comment by obiot** [comment]
about uncaught exception :
https://github.com/melonjs/melonJS/commit/ecc4dd5aef9701a67dfce918f7b41213e565a284#diff-1081e93d612904ecd80024589950e1f9
