### ISSUE TITLE
Vector2d/3d classes cleaning

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#708]
Call for a vote :

while working on the vector3d class, and adding some test units for all the vector classes, I realized that some function are either not used or not correct.

So i would propose to remove the following ones :
* [ ]  `reflect/reflectN` : not used, and from what I understand they are not even correct 
* [x] ~~`rotate` : nice, but is this useful for ?~~
* [x] `reverse` : identical to `negateSelf`
* [x] ~~`div` : similar to `scale` with a negative scalar~~

**Comment by parasyte** [comment]
* `rotate` is very useful indeed! And is used all over the place, especially in shapes and collision detection.
* `div` is not the same as negative scale, it's the inverse operation to `scale`;

```javascript
div(n) === scale(1 / n)
```

**Comment by obiot** [comment]
oupsieee yes....  I need more coffee :P

**Comment by obiot** [comment]
reflect(N), keep it or leave it ?

**Comment by parasyte** [comment]
I vote remove it. #212 !

**Comment by obiot** [comment]
cool, lot's of unused code to remove :)
