### ISSUE TITLE
Replace ColorLayer with a Container.setColor method

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#710]
`me.ColorLayer` is not optimal, being an entity that draws a solid color over the entire screen. Because it's an entity, it is a child of a Container; this implies that it can be sorted in any order along with other children, overdrawing all children that draw before the ColorLayer.

In this ticket, I want to replace ColorLayer with a new method on `me.Container` to set its background color, something like `setColor`. The method will store a `me.Color`, to be passed to `renderer.clearSurface` in its `draw` method prior to drawing the children.

**Comment by obiot** [comment]
oh I thought you wanted this one for 2.2.0 ?

**Comment by parasyte** [comment]
I added it to the 3.0 milestone "just in case" it misses the 2.2 deadline. (This should not block the 2.2 release.)

And also I envision the `me.ColorLayer` change to be breaking, not just a "feature added"; Make the constructor signature and the class's behavior match other renderables. So in attempt to limit breaking changes to major version numbers (see: semver) this one was scheduled for 3.0!

**Comment by obiot** [comment]
Great, so my last commits are not a good fit if we were not supposed to introduce any API changes in 2.2.0 :p :p :p

**Comment by parasyte** [comment]
I saw that. The good news is, we can branch 2.2.x at any point before those commits... It will be a bit of a weird workflow, but doable.

**Comment by obiot** [comment]
in the mean time, it's not a big breaking changes, so on my side i'm ok and happy with it :)

**Comment by obiot** [comment]
3.1.0 as thsi one can be implemented without any API changes

**Comment by obiot** [comment]
better later than never, but this became a super low hanging fruit after the various code refactoring in the 2 or 3 latest version, and this without breaking any API
