### ISSUE TITLE
Ability to specify each frame delay with tile animations

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#712]

**Comment by obiot** [comment]
following #390

**Comment by parasyte** [comment]
For reference: https://github.com/melonjs/melonJS/blob/4f115420b3e6dcbfde70b6f4069d74fc23127b91/src/level/TMXTile.js#L138

**Comment by obiot** [comment]
i'm confused then, what is the following doing :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXTileset.js#L63-L72

and where is the TSX `duration` property read from ?
https://github.com/melonjs/melonJS/blob/master/examples/platformer/data/map/tileset.tsx#L6-L7

**Comment by parasyte** [comment]
@obiot This ticket is for "Tile objects". The tileset animations in tile maps already works (that's what you're looking at. FYI the duration is read here: https://github.com/melonjs/melonJS/blob/3b2646cf4ce4f1d4b99ce03930d389286bd3bcf4/src/level/TMXTileset.js#L175

**Comment by obiot** [comment]
and one more done !
