### ISSUE TITLE
Create an origin point in each frame of a texture atlas that determines the frame's position relative to the coordinates it's drawn at.

### ISSUE THREAD

**Issue by Giwayume** [melonjs/melonJS#715]
Basically the rundown is:
1. The "anchor point" becomes a point that scaled from the entity's x and y position (0,0) to the entity's width and height (1,1). Similar to today.
2. Each animation (atlas) frame gets a new property, the origin point (a pixel offset from the "offset" point), that is defined by the pivot point in TexturePacker (or shoebox equivalent, or manually, whatever). The origin point is drawn at the entity's anchor point, with the rest of the texture drawn relative to that origin point.
3. Scaling and rotation transformations happen around each frame's origin point.

This change can impact existing projects. So maybe an opt-in? 3.0?

Link to the original discussion:
https://groups.google.com/forum/embed/?place=forum%2Fmelonjs&showsearch=true&showpopout=true&hideforumtitle=true&parenturl=http%3A%2F%2Fmelonjs.org%2Fforum#!topic/melonjs/KYes1bzTsBU

**Comment by Giwayume** [comment]
If the melonjs lords Oliver, Jason, Aaron agree with this direction, assign this issue to me?

**Comment by agmcleod** [comment]
Can't assign to non collabs :). I agree with the issue. AnimationSheet & TextureAtlas should be the only classes changing I think. Be sure to run `grunt` after making any changes, fix any issues jshint or the tests complain about. Once you have a working scenario, and you have tested it against the platformer example (didn't break existing behaviour), make a pull request.

**Comment by Giwayume** [comment]
How do I collab?

Also, by design it should break the platformer example because the pivot point exported from TexturePacker is at [0.5,0.5] but the platformer example sets the anchor point at [0.5,1]. Half the sprite should end up clipping through the floor without modifying the TexturePacker file.

**Comment by agmcleod** [comment]
@Giwayume even if the anchorPoint needs to be changed, that's fine. That's a good learning in what other users might need to do in an upgrade guide.

For collaborating, fork the project. Push commits to your own repo. Do a pull request to our master.

**Comment by Giwayume** [comment]
I'm seeing the "Texture" class inside of video/canvas/texture.js, what do you mean by the "TextureAtlas" class? Am I looking at old code?

**Comment by agmcleod** [comment]
@Giwayume yes that's it. Sorry i had actually forgotten about the rename.

**Comment by Giwayume** [comment]
OK, before I make a mess, I've noticed something.

An `Entity` is a `Renderable` that owns another `Renderable` as its renderable property. So we're dealing with two anchorPoints, one for the `Entity` relative to its body width, and a second one for the `Renderable` it is drawing by proxy.

In theory the anchorPoint of the renderable (Sprite) can act as the origin I'm referring to, so I would be creating a property that's pretty much an alias for anchorPoint, just defined in pixels instead. That doesn't sound good.

The problem I'm looking at, is a `Sprite`'s anchor point isn't actually used unless it is either scaled or rotated. Why is this? I'm looking at renderable/sprite.js line ~280. Is there a reason I can't move `renderer.translate(xpos + ax, ypos + ay);` outside of the scaleFlag and angle check loop?

**Comment by Giwayume** [comment]
It looks to me like this was solely done for performance gains since previously there was no need to translate a sprite unless it had been rotated or scaled.

**Comment by Giwayume** [comment]
It looks like I'm done. My animation is running smoothly now that it isn't jerking around due to varying frame sizes.

I've ditched the pixel origin idea and opted to utilize the existing anchorPoint property of the renderable.
I've added two properties to the atlas frame definition:

**{boolean} hasTextureAnchorPoint** - Whether or not the current frame defines its own anchor point.
**{me.Vector2d} anchorPoint** - The current frame's anchor point (0,0) top-left to (1,1) bottom-right.

If you're creating a custom AnimationSheet, you can pass an anchorPoint in addition to the framewidth and frameheight.
```
var animationSheet = new me.AnimationSheet(0, 0, {
    image : "animationsheet",
    framewidth : 64,
    frameheight : 64,
    anchorPoint : new me.Vector2d(0.5, 0.5)
});
```
If an anchorPoint is set by the texture atlas json or manually like above, the entity.renderable's anchorPoint is drawn at the entity.body's anchorPoint. (as described in my first post)

Otherwise, it acts the same as it does today, where the entity attempts to keep the renderable inside the body's bounds.

Because it keeps the current functionality when a texture anchor point is not defined, the platformer example has not been affected because its texture json does not define the pivot on any of its frames. (which I have no idea how that happened, because I can't get TexturePacker to not set a pivot... maybe the json was created in an older version?)

**Comment by Giwayume** [comment]
Committed. Created a push request.

**Comment by obiot** [comment]
ahahah the melonjs lords :P:P:P

**Comment by obiot** [comment]
lots to read, I need a coffee first (just woke up on my side)
