### ISSUE TITLE
Followup: Investigate differences between entity geometry and bounds geometry

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#717]
Follows #714, especially https://github.com/melonjs/melonJS/issues/714#issuecomment-125753224

In that ticket, I discovered that (at least these particular entities in that demo) have a different geometry from that of the bounding rectangle. See that ticket for steps to reproduce (E.g. using a conditional breakpoint).

May also be related to #580 ?

**Comment by obiot** [comment]
Hi @parasyte, sorry but I was trying look at this one, and not really getting what you mean...

**Comment by parasyte** [comment]
@obiot Configure the conditional breakpoint as shown in https://github.com/melonjs/melonJS/issues/714#issuecomment-125753224 Notice the debugger will pause when the pointer hovers over the blank area to the right of, and below the food shapes. The area of coverage here is really big; 200x200 px

**Comment by obiot** [comment]
the issue is here actually, as `width` and `height` are mandatory when creating an entity :
https://github.com/melonjs/melonJS/blob/master/examples/shapes/js/screens/play.js#L13

but then (once the body is created) only the entity `_bounds.width` and `_bounds.height` are updated, while the entity size is not (and remains the one initially defined) :
https://github.com/melonjs/melonJS/blob/master/src/entity/entity.js#L263

**Comment by parasyte** [comment]
That makes sense, for sure! Matches what I was seeing.

**Comment by parasyte** [comment]
Ok, this is exactly #580. We have some tests for it, they are disabled until that ticket is fixed. ;)

**Comment by obiot** [comment]
Then the question is to know if we are happy with it or if we should change it.

As far as I can remember or see, the entity "geometry" is never used (as we refers to the bounds directly), and if we want to change it, what shall we use ? (Body and/or renderable size?)

**Comment by obiot** [comment]
Oh i forgot about that ticket :):):)

Good then as it also replies to my last question, and should be pretty easy to fix !

**Comment by parasyte** [comment]
Yeah, the pointer hit test code definitely uses entity geometry. That's how I noticed it ...
