### ISSUE TITLE
Is sound not working in Firefox? 

### ISSUE THREAD

**Issue by Giwayume** [melonjs/melonJS#719]
If I run the platformer demo in the main branch in Firefox, I don't get any sound. No errors in the console. In Chrome I get sound. 

I seem to remember it working in the 2.1.3 version. Can anyone reproduce?

**Comment by parasyte** [comment]
It's working fine here.

**Comment by obiot** [comment]
yep same here, no issues, and tested with both FF35 and FF39

**Comment by Giwayume** [comment]
I downloaded 2.1.3 again to test and it's no longer working. I will diagnose this as a client issue.

**Comment by Giwayume** [comment]
Was a problem on my side. Pulseaudio's cubebutils had the volume set to 0 for Firefox specifically. No clue how this happened.
