### ISSUE TITLE
Handle Lost Context in WebGL

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#720]
was trying to better educate myself yesterday about WebGL, and realized we were not handling these events : https://www.khronos.org/webgl/wiki/HandlingContextLost

looks like we should :)

**Comment by parasyte** [comment]
Correct. It was on my plate, but apparently never mentioned anywhere.

**Comment by obiot** [comment]
i also started to put things on the 3.1.0 milestone, the 3.0.0 release is already quite full, and we should really start thinking on what we absolutely want to be in 3.0.0, and plan for both the 3.0.0 release and the 4.0 and 3.x ones.

**Comment by obiot** [comment]
one more old ticket done !
