### ISSUE TITLE
TMX - Loading with CSV Layer Data incorrect

### ISSUE THREAD

**Issue by peterhull90** [melonjs/melonJS#723]
I was loading a tilemap where the layers were defined as CSV. Tiled 0.12 is fine with this map.
MelonJS only loads the top row. 
The XML looks like this
```
<layer height="70" name="map" width="95">
    <data encoding="csv">11,44,11,11,11,11,11,11, ... 70x95 ints in total ... </data>
</layer>
```
Looking at the code for `TMXMapReader.setLayerData()`

```javascript
                // CSV encoding
                case TMXConstants.TMX_TAG_CSV:
                // Base 64 encoding
                case TMXConstants.TMX_TAG_ATTR_BASE64:
                    // and then decode them
                    if (encoding === TMXConstants.TMX_TAG_CSV) {
                        // CSV decode
                        data = me.utils.decodeCSV(data, layer.cols); <-- here
                    } else {
                        // check if data is compressed
                        if (typeof compression === "string") {
                            data = me.utils.decompress(data, compression);
                        }
                        // Base 64 decode
                        data = me.utils.decodeBase64AsArray(data, 4);
                    }
                    break;
```

it seems to me that the line `data = me.utils.decodeCSV(data, layer.cols);` should be `data = me.utils.decodeCSV(data, layer.rows * layer.cols);`

**Comment by parasyte** [comment]
Hi @peterhull90 

Which version of melonJS are you using? The CSV decode function has been updated in our current 3.0.0 WIP builds: https://github.com/melonjs/melonJS/commit/3b2646cf4ce4f1d4b99ce03930d389286bd3bcf4#diff-be73193a7de1c86c1903f5cf92321d2aL206

And in fact, the entire section of code you pasted was moved in the same commit: https://github.com/melonjs/melonJS/commit/3b2646cf4ce4f1d4b99ce03930d389286bd3bcf4#diff-e92b257652008828bc7c9bb9bb1c3188L56 It's now done in the XML->JSON converter: https://github.com/melonjs/melonJS/blob/f9048a77af647a17af90a9c176a245a7a3bc87f5/src/level/TMXUtils.js#L94

**Comment by peterhull90** [comment]
It was the development version of 2.1.3, downloaded today. If you've fixed it, that's great, thanks.
