### ISSUE TITLE
Sprite anchor points and the rotated property in TexturePacker

### ISSUE THREAD

**Issue by Giwayume** [melonjs/melonJS#726]
While working on my game, I've noticed when I accidentally allowed TexturePacker to rotate sprites to save space in the texture map it wasn't being positioned properly in-game.

Putting this here before I forget.

**Comment by parasyte** [comment]
FYI This is implemented here: https://github.com/melonjs/melonJS/blob/master/src/video/canvas/texture.js#L157 If you are resetting the `angle` property on your renderable, that will break it.

Also of note is that this feature may save a few bytes of memory, at the cost of rendering performance to undo the rotation.

**Comment by Giwayume** [comment]
Yeah, that's why I said "accidentally". Every time I create a new sprite sheet I have to turn that setting off...

**Comment by parasyte** [comment]
Understood. ;) Sounds like there's a bug here to fix, though?

**Comment by Giwayume** [comment]
Yeah. I'll ask how rotate is supposed to work with the pivot.

**Comment by parasyte** [comment]
That explains the bug! ;) We just add `-Math.PI / 2` to the user's rotation angle. It's really expected to be rotated in two steps.

**Comment by Giwayume** [comment]
What I'm experiencing:
renderable.flipX(false) -> frame is rotated correctly but is placed in wrong position
renderable.flipX(true) -> frame is not rotated but is placed in correct position

**Comment by Giwayume** [comment]
I believe the problem is that _sourceAngle isn't supposed to take pivot into account. It's supposed to rotate the sprite in-place, then angle rotates considering the sprites' pivot point.

Supporting evidence for this is that spriteSourceSize doesn't change when rotated == true.

![untitled note - aug 20 2015 6 47 pm - page 1](https://cloud.githubusercontent.com/assets/4075314/9397577/2c4a3b90-476c-11e5-9c0e-b912c7f6e3cb.png)

**Comment by Giwayume** [comment]
Is _sourceAngle used for anything except defaulting the angle from TexturePacker/ShoeBox?

**Comment by parasyte** [comment]
Yes, that all fits with my understanding.

Here's where `_sourceAngle` is applied: https://github.com/melonjs/melonJS/blob/bc9cf96b64ff755dd83f5006006e6a2b0faf6f2d/src/renderable/sprite.js#L263

Doing this "unrotation" outside of the normal rotation step will fix it. But in addition, the "unrotation" requires a translation to swap corners before (or after) the rotation. We currently do that here: https://github.com/melonjs/melonJS/blob/bc9cf96b64ff755dd83f5006006e6a2b0faf6f2d/src/renderable/sprite.js#L289-L290

**Comment by Giwayume** [comment]
#727

**Comment by parasyte** [comment]
Closed via #727
