### ISSUE TITLE
Allow tiled to control the z position of layers

### ISSUE THREAD

**Issue by Giwayume** [melonjs/melonJS#729]
In tiled I can set a custom z property on object layers and they will be drawn in that order respectively. However this does not work on tile and image layers.

I need all my characters/npcs to be drawn at a specific (unchanging) z position room-to-room, so when I create entities on the fly I have full control over whether it appears above or below characters.

The way it is now, for example, I wouldn't be able to create an explosion effect that appears above a character but below a foreground tile layer, because the tile layers auto increment leaving no space for gaps... Unless I create an extra empty object layer in each room (tedious, and doesn't solve the problem of the z position changing room-to-room)

**Comment by ldd** [comment]
I'm pretty sure that right now you have to modify the z value **after** everything is set up.

For example, before adding an explosion effect:
someTilelayer.z = 3;
someTilelayer2.z = 5;

**Comment by parasyte** [comment]
Is this a feature of Tiled? Setting a `z` property on a layer changes its rendering order within Tiled? That would definitely be our bug, in that case.

Else, @ldd is right. We have just started migrating all position vectors to 3D coordinate space (#664), so melonJS is ready for this internally. It's still missing the interface to set the z-coordinate during instantiation for most objects. That will be fixed by #709 - It's scheduled for 4.0.0, but we would probably accept a patch for 3.0.0. (It's a breaking change, and 3.0.0 is a major release with breaking changes.)

I can think of one quick workaround right now; create an empty object layer (as you initially described), but make sure the "merge groups" feature is disabled: http://melonjs.github.io/docs/me.game.html#mergeGroup This will keep the original scene graph structure that you create in Tiled, and you can insert new entities into the proper layer by container name. It's still tedious, because you need an empty layer (or two) on every map. But it does solve the problem, because the target container is guaranteed to be at the correct z-index.

**Comment by Giwayume** [comment]
No, it's not a tiled feature. I'm talking about setting custom layer properties (like ratio, repeat-y, etc)

**Comment by Giwayume** [comment]
I figured since setting z as a custom property on object layers already works, it's supposed to work for other layer types as well.

I guess if I make a layer naming convention it's not so bad to handle in-engine.

**Comment by parasyte** [comment]
I'm not sure if it makes sense but we might be moving away from the custom property, and making 3D vectors a first-class citizen. In Tiled, the current method of setting z-index is on a per-layer basis. That "layer ordering" will continue to set the z-coordinate in melonJS.

On the same topic, Tiled also supports a per-layer configuration switch to choose the sorting method for objects within an object layer: [objectgroup.draworder](http://doc.mapeditor.org/reference/tmx-map-format/#objectgroup)

The static map format doesn't really have a whole lot to do with how entities are manipulated at runtime; The editor allows you to configure the initial state of everything in the map. What we prefer with our Tiled integration is that the initial map state matches 1:1 with what Tiled shows. And during runtime, all of it can be changed dynamically.

The way I envision it, creating entities with a specific z-index is an exercise in offsetting vectors relative to one another. Create an explosion that renders on top of the player sprite, but below some foreground scenery? `explosion.z = player.z + 0.1` Something like this works even when the foreground scenery is 1 unit higher than the player entity; `foreground.z === player.z + 1`

BTW, the z-coordinate is set at insert time today, in [me.Container.addChild](http://melonjs.github.io/docs/me.Container.html#addChild). #709 will remove this feature, in favor of the z-coordinate being set at instantiation time along with the x- and y-coordinates.

I hope that helps with understanding the current state of things with 3D coordinate space in melonJS, and how we intend to make it better in the near future.

**Comment by Giwayume** [comment]
I didn't know the z-layer sort allowed non-integer values. I guess I assumed it didn't because of how that works in other engines I've used. Thanks, that helps.

What is the new constructor format? (x, y, z, settings)?

**Comment by parasyte** [comment]
That's what I had in mind for the renderable constructor signature. It was touched upon in this discussion: https://github.com/melonjs/melonJS/commit/52a0a02648aa47595a98dffc3e7e792c1f595d7f#commitcomment-12161615

**Comment by Giwayume** [comment]
It seems that changing the z pos of a me.ParticleEmitter has no effect. Is this a bug?

**Comment by parasyte** [comment]
Possibly; did you re-sort the parent container after changing the z-index?

**Comment by Giwayume** [comment]
Yeah, I've changed the z pos above and below different layers and sorted. It appears in the correct position in the array, but it's always drawn on top.

**Comment by parasyte** [comment]
I see. The particles themselves are probably drawn at the wrong z-index. There are three parts: the emitter, the container, and the particles. Particles are children of the container. And the container isn't necessarily connected to the emitter in any way. It's a weird situation. Particles were a user contribution. I would have designed it differently (the emitter and the container should be the same thing).

I would call it a bug.

**Comment by Giwayume** [comment]
Yeah I thought it was kind of weird you have to add `emitter` and `emitter.container` to the game container. Anyway this is a bit off topic. I suppose a ticket should be opened about the particle emitter z sorting bug and close this one.

**Comment by parasyte** [comment]
FWIW, I found the discussion about the particle emitter/container thing: https://github.com/melonjs/melonJS/pull/372#issuecomment-32666629
