### ISSUE TITLE
me.Font.fontSize.y === NaN when initialized with a string like "24px"

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#732]
This is done in the device test example: https://github.com/melonjs/melonJS/blob/7976a11ed35da3742151322385c1b04142045556/examples/devicetest/js/screens/play.js#L16

A bad fix is using `parseFloat` instead of numeric coercion: https://github.com/melonjs/melonJS/blob/52a0a02648aa47595a98dffc3e7e792c1f595d7f/src/font/font.js#L145

A good fix would estimate the proper height based on CSS units, e.g. `24 === "24px" ~= "18pt"`

Here's the full list: https://developer.mozilla.org/en-US/docs/Web/CSS/length

**Comment by obiot** [comment]
the question being : do we want just to this using maybe `parseFloat` and then only support `px` units ? or do we want to support the full range of CSS units ?

**Comment by parasyte** [comment]
Canvas supports all of the CSS units.

**Comment by obiot** [comment]
after some quick research, its seems that :
`2ex` ~= `1em` ~= `24px` ~= `18pt`

source :
http://www.w3schools.com/tags/ref_pxtoemconversion.asp
https://developer.mozilla.org/en-US/docs/Web/CSS/length
