### ISSUE TITLE
Errors with empty TMX layers

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#735]
This issue was reported on the current 3.0.0 WIP: https://groups.google.com/d/msg/melonjs/fAtFFe2wvCo/_e3XD4EtBwAJ

> "TMX loader doesn't like empty layers. I just put a polygon in each empty one."

Actual effect is TBD.

**Comment by obiot** [comment]
the bug is actually when defining empty object layers, it's all fine with Tile Layer (I actually remember us fixing the later one in the past).
