### ISSUE TITLE
Update debugPanel plugin (and debugParticlePanel?) to use me.Object.extend

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#736]
Reported on the forum: https://groups.google.com/d/msg/melonjs/fAtFFe2wvCo/f4szE5o1BwAJ

**Comment by obiot** [comment]
I'm confused about this one, as it's already the case :
https://github.com/melonjs/melonJS/blob/master/plugins/debug/debugPanel.js#L24
https://github.com/melonjs/melonJS/blob/master/plugins/debug/debugPanel.js#L46
https://github.com/melonjs/melonJS/blob/master/plugins/debug/particleDebugPanel.js#L19

and the current version of debugPanel is working just fine with the platformer, something else i'm missing?

**Comment by parasyte** [comment]
Hmmmm, nope! LGTM. User error.
