### ISSUE TITLE
Shapes for pointer events are offset when using browser zoom

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#740]
Posted on the forum: https://groups.google.com/d/msg/melonjs/dvi7G00aJkA/qTnKDUTIBwAJ

This is easy to reproduce by _disabling video auto-scale_ in the shapes demo, and zooming with the browser. Even a small amount of zoom makes the offset really noticeable.

I was not able to reproduce the issue with auto-scale enabled.
I didn't test zooming in a mobile browser.

**Comment by obiot** [comment]
what do you mean to zoom with the browser ??

**Comment by parasyte** [comment]
Zoom:

* [Chrome](https://support.google.com/chrome/answer/96810?hl=en)
* [Firefox](https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages)
* [Safari](https://support.apple.com/kb/PH19288?locale=en_US)

Also pinch-to-zoom on mobile?

**Comment by obiot** [comment]
I cannot recall right now where it is (maye you will remember it), but I guess a proper way to fix this would be to change the way we manage resize, to check for a potential changes on a beginnning of a frame, instead of listening to an event as we do now.

**Comment by parasyte** [comment]
Yeah: number 4 on http://webglfundamentals.org/webgl/lessons/webgl-anti-patterns.html

Also, I used it in my js13k game:

* [The resize function](https://github.com/blipjoy/lovelydrive/blob/1e2639769e221e3cc79bf199ea1b493b1e47b45d/src/webgl.js#L106-L134)
* [Call the function in the main loop](https://github.com/blipjoy/lovelydrive/blob/1e2639769e221e3cc79bf199ea1b493b1e47b45d/src/main.js#L7-L8)

**Comment by obiot** [comment]
yeeesss !

**Comment by parasyte** [comment]
hrmmmm... auto-resize doesn't work as expected on iOS 9 (what a pain this update is!)

When using `apple-mobile-web-app-capable`, iOS 9 will only hide the UI if the web content is big enough. Because we are stretching the canvas to fit the available screen area, the UI doesn't need to hide itself.

Lovely Drive has a similar problem... I'm using the "better" method of auto-sizing (using CSS to stretch the canvas, and a little JS to change the pixel density), but still the UI won't hide itself. I found a workaround; add a 1px div below the canvas, and the `apple-mobile-web-app-capable` "full screen" works again. The UI only hides itself after a portrait->landscape rotation, but that's Apple's bug. I haven't found a workaround for that issue, yet.

**Comment by obiot** [comment]
did you try to click on the fullscreen button (from the branch with the UI buttons) to see how it works now on iOS9?

**Comment by parasyte** [comment]
No, I didn't try the branch yet. Still plugging away at some other bugs here and there.

**Comment by parasyte** [comment]
The full screen button doesn't work on iOS (full-screen API is not supported at all). The only thing that worked was adding the 1px div hack.

**Comment by obiot** [comment]
note to myself : `me.video.getPos()` would definitely deserve being moved under `me.device`, it just makes more sense
