### ISSUE TITLE
Add GUI_Object to Platformer demo

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#747]
Good idea from #746; We need an example to show the GUI_Object class. May as well put it into the Platformer.

Side note: There are currently 2 platformer examples, because I only managed to get one of two maps updated to use a new tileset. Consider updating "Platformer2" only.

**Comment by obiot** [comment]
we could add a mute button ? simple and useful example :)

**Comment by obiot** [comment]
as I was writting it on gitter,,I found some issue here, as the GUI_Object sprite is draw at the righ position, the offset is wrong by something like 10 pixels.

**Comment by obiot** [comment]
also, the new PNG needs to be added into the existing texture, instead of being loaded indivually like now

**Comment by parasyte** [comment]
Sounds good.

**Comment by obiot** [comment]
yep, but it does not work as expected, I fixed my comment, as I wrote the opposite of what I was thinking :P

**Comment by obiot** [comment]
@parasyte I just realised, i was too much focusing on the UI button, the all the graphics in the platformer2 examples are being draw at the wrong position.... the platformer1 example though is correct.... wtf ???!!! :P:P:P

**Comment by obiot** [comment]
turns out, the problem was due to the updated anchor point code, I still have no clue though why this was not creating any issue with the platformer “1”

**Comment by parasyte** [comment]
You can't mean the new anchorPoint code for `me.ImageLayer` ... That code only touched the one class?

**Comment by parasyte** [comment]
Do you mean #714 maybe?

**Comment by obiot** [comment]
No no, i mean the code that manage anchor point for entity & renderable. Just pull this branch, and test without my last commit, you will see

**Comment by parasyte** [comment]
I just don't remember where/when/how that changed. :)

**Comment by obiot** [comment]
Around this commit :)

But yet, how come the platformer 1 has a different behavior... I'm lost here :(

**Comment by obiot** [comment]
Oups sorry, this commit:
https://github.com/melonjs/melonJS/commit/8a00979805fb0972690c358de5048529580f3bf1

**Comment by parasyte** [comment]
aaaaaahh, yes! Does that mean we need to change the default anchorPoint from `<0.5, 0.5>` to `<0, 0>`?

**Comment by obiot** [comment]
dunno... are you understanding why the original platformer was not affected ? i'm still not getting it ... :(

**Comment by parasyte** [comment]
No, I haven't looked into the issue, yet.

**Comment by parasyte** [comment]
@obiot I played with this new branch a bit. It looks good... Except the fullscreen button is useless on mobile. :stuck_out_tongue_winking_eye:

**Comment by obiot** [comment]
merged into master, if further fine-tuning is required, it can be done from there :P
