### ISSUE TITLE
redesign (again) `me.GUI_Object`

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#748]
while adding UI buttons (see #747) to the platformer, I realised it's impossible to use texture packer when using `me.GUI_Object`. As the latter is directly inheriting from `me.Sprite` it only expect an image to be passed to its parent constructor.

What we should do (IMO), is to make it extend `me.Renderable` and add a renderable property/child to it, a bit like entities object. And actually I do wonder if it should not directly extend GUI_object, also makes sense somehow as then the body itself can be use for the area/mouse detection.

**Comment by agmcleod** [comment]
Why should it be impossible without a redesign? Just need to set the offset & sizes appropriately:

https://github.com/melonjs/melonJS/blob/master/src/video/canvas/texture.js#L284

Really though, I wonder if sprite can be changed to use settings for this. Specify a region name.

**Comment by parasyte** [comment]
I'm going to throw my two cents in right about here and point out that the `createXXXFromName` pattern is not ideal. We could provide more flexibility if the lowest level class had all of the texture atlas support built into it.

If we assume `me.Sprite` understood how to work with textures, then having `me.GUI_Object` select a texture region is just a matter of passing the region name to the constructor; which of course is simply forwarded to the super constructor, where the logic of texture region selection happens.

For that matter, what about `me.AnimationSheet`? We could have animated GUI buttons by extending that class instead.

Anyway, just IMO.

**Comment by obiot** [comment]
oh indeed ! the `settings` object we pass to the `me.Sprite` constructor could accept an additional (optional) `texture` parameter that, when present, will make `me.Sprite` uses the given `image` region from the specified texture. (if not present, just fetch the specified `image` from the loader.

**Comment by obiot** [comment]
closing this one for now
