### ISSUE TITLE
me.audio API Improvements

### ISSUE THREAD

**Issue by thedrumchannell** [melonjs/melonJS#752]
The addition of me.audio.resume() would help complete the api for me.audio.

me.audio.playTrack() is not consistent with me.audio.play(). One issue is that looping background tracks is very challenging. Another issue is that background tracks can't be played once without using the play function and losing access to track functions and pauseOnBlur, etc. I am proposing that me.audio.playTrack() accept the same arguments as me.audio.play() but playTrack would default loop to TRUE.

The other suggestion is that a me.audio.setTrackVolume() function be created for modifying the volume of the current track. Currently there is no simple way of separating the background track and sound effect volumes once the track has been started.

I also want to suggest that a new Boolean, me.audio.pauseOnBlur be created to ease sound management during game pauses. me.device.check would use this value inside the blur and focus handlers instead of forcing the music to pause during game pauses.

// device.js - Line 81
if (me.sys.pauseOnBlur) {
    me.state.pause(me.audio.pauseOnBlur);
}
// device.js - Line 90
if (me.sys.resumeOnFocus) {
    me.state.resume(me.audio.pauseOnFocus);
}

I could make these changes if you guys agree with the proposals Olivier, Jason and Aaron?

**Comment by parasyte** [comment]
I like the `me.audio.pauseOnBlur` idea. Those lines (and the two for visibility change event) are hardcoded with `true` right now. The change makes sense to me.

Maybe you can provide some extra details in regard to behavior. You must have some specific use case in mind, like synthetically pausing the game (from a button or whatever) while leaving the music playing. These kinds of use case details will help us understand the motivation behind the suggested changes.

**Comment by obiot** [comment]
actually the `resumeTrack` function is just an alias for the `play` one:
https://github.com/melonjs/melonJS/blob/master/src/audio/audio.js#L364

and `me.audio.play()` is to be called once you paused a track, the only difference between calling  `pause()` and `stop()` is that the `stop` one does reset the internal `currentTime` property (so play acts as resume).

the initial idea of providing `***Track()` set of functions was to more easily manage audio track, but as these are just aliases to the other regular functions, they are not really useful anymore. This to say that in my opinion, instead of actually completing them we should maybe simplify the API.

**Comment by thedrumchannell** [comment]
@parasyte Yes, the use case that sparked this idea was a pause menu that I added to my game. The player opens the pause menu and the game pauses along with the music. The problem occurs when the window changes focus. I patched me.state.pause/resume but couldn't get it just right, it's more than should be required for something that should be so simple.

@obiot Thanks for sharing about the resumeTrack function. It makes sense and I have made changes to my code to accommodate.

**Comment by obiot** [comment]
@thedrumchannell note that we can still add a `resume` function that will just call back the `play` one but with only the sound clip name parameters (as the other ones should not change). At least it will make it more coherent between "audio clip and audio track" (i'm using commas, as at the end it's actually the same)
