### ISSUE TITLE
Update Howler

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#753]
Howler just merged two important changes that melonJS relies upon (and which we contributed upstream).

Let's update Howler to the current 2.0 beta for the 3.0.0 release. Also, we can remove the following workaround, after the Howler upgrade:

746d3dd4c8bd5b236be2b8c2543fcdf5e80fb901

The fixes included are:

* https://github.com/goldfire/howler.js/issues/328
* https://github.com/goldfire/howler.js/pull/352

**Comment by obiot** [comment]
We do not want to merge this into the 2.x branch as well ?

**Comment by parasyte** [comment]
I don't think it's relevant for 2.x. This is mostly for future development, since it doesn't actually fix anything that 2.x needs. IOW, 2.x is fine on the patched Howler + Opera workaround. Unless you have a compelling reason to upgrade Howler on 2.x?
