### ISSUE TITLE
me.Entity anchorPoint is really messed up

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#754]
This is probably a regression from #716...

The spikes on the ceiling use
- `anchorPoint = {"x" : 0.5, "y" : 1}`
- `anchorPoint = {"x" : 0.5, "y" : 0.75}`
- `anchorPoint = {"x" : 0.5, "y" : 0.5}`.

Uhhh? I don't get it.

<img width="1485" alt="screen shot 2015-10-03 at 12 15 37 am" src="https://cloud.githubusercontent.com/assets/456942/10261893/31638608-6964-11e5-89da-4830661e0404.png">

**Comment by obiot** [comment]
just saw it happening live, and I also thought : wtf... !

**Comment by obiot** [comment]
what kind of object do you use for the spike, the "stock" one from the platformer ? because it looks like it's working in map1, but not in yours ?

**Comment by parasyte** [comment]
Same object, yes. The difference is this one uses the vertical flipping feature in Tiled. It's really hard to aline it in this mode. To make matters worse, the green box (from debug panel) is positioned opposite the sprite. :(

**Comment by agmcleod** [comment]
Might take a look at this tonight.

**Comment by agmcleod** [comment]
So im not sure this is a bug. I think this is a discrepancy between how its displayed in tiled because of its coordinate system, and how are are aligning an anchor point relevant to its coordinate. Playing with the position of the tile, and the anchor point. It tends to work as i expect it. The position of it in tiled is still top left relevant. Ours by default now is in the middle, with the anchor point set to 0.5 0.5

**Comment by obiot** [comment]
so is it not maybe just an initialisation "issue" for tiled object ?  (that should be forced to an anchor point of [0,0] to match with Tiled)

**Comment by obiot** [comment]
forget my last comment, stupid remark :)

**Comment by parasyte** [comment]
@obiot :confounded: Ok, I was confused momentarily. Actually trying to use `anchorPoint` with flipped tiles is not at all friendly.

**Comment by parasyte** [comment]
@agmcleod Disregarding how Tiled displays the map, the `anchorPoint` setting in melonJS still does not make sense (at least when the tile is flipped/rotated). The image ends up completely outside of the shape when anchored to the extremes (0, or 1)... That's completely unexpected.

**Comment by Giwayume** [comment]
> The image ends up completely outside of the shape when anchored to the extremes (0, or 1)... That's completely unexpected.

This looks like it's addressed in #756?

Maybe to get it working sensibly in tiled, what if melonJS internally flips the provided anchor point when the "flip horizontally" or "flip vertically" settings are used in tiled?

**Comment by obiot** [comment]
see #1008
