### ISSUE TITLE
me.Rect.resize looks outdated

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#758]
https://github.com/melonjs/melonJS/blob/ccd31cc5a8a798ae6c23da8d6c65c663549eb873/src/shapes/rectangle.js#L74-L75

These properties are not used anywhere else. Instead, `this._width` and `this._height` are used. These lines haven't been touched in about 2 years!

**Comment by obiot** [comment]
??? There are 2 setters for them defined at the end of the object file.

**Comment by obiot** [comment]
Also, why is this tagged as a bug ?

**Comment by parasyte** [comment]
Oh, ... this code is starting to get unreadable. I guess that's the bug.

**Comment by obiot** [comment]
So i'm closing it :)
