### ISSUE TITLE
3.0.0 release

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#759]
@agmcleod @parasyte 

Hi guys,

It's time to get this one released, but before we do, does any of you has a ticket he absolutely want to close ? if so please use the "assignee" function. Let's however try to keep low-hanging fruits with minimum risk on the current code base.

On my side i'm done for the release, and I will focus on preparing it (upgrade guide, blog, etc...). Once done, we can have that twitter contest that we can "associate" with the release :)

**Comment by parasyte** [comment]
I haven't looked at the open tickets in a while, TBH. Stuck on real life stuff for the last few weeks.

I think it's about time to get something out there... The only thing I have trouble with is claiming that 3.0 has "multi level" support... From my experiments, it still does not. :P (What a mess that was.)

**Comment by obiot** [comment]
sure, but this is not anyway in the CHANGELOG so far :)

**Comment by obiot** [comment]
maybe also a good time to create a specific 3.0.0 branch ?

**Comment by obiot** [comment]
shall we also create a 3.1.0 one, and keep master for 4.0.0 ? or shall we do ?

**Comment by obiot** [comment]
@parasyte i just remember that you did change the process for the release, and that's it's all automated now, including for doc, examples, and everything.

Would you mind documenting it somewhere (wiki?) i'm a bit lost at what do to to be honest :)

**Comment by parasyte** [comment]
`grunt release`

**Comment by obiot** [comment]
I created a 3.0.x branch, now we can get crazy on master and break everything ;P
https://github.com/melonjs/melonJS/tree/3.0.x

**Comment by obiot** [comment]
RC1 : 
https://github.com/melonjs/melonJS/releases/tag/3.0.0-RC1

**Comment by obiot** [comment]
@agmcleod @parasyte so that's it this time, nothing left for this release ?

we actually still have the https://github.com/melonjs/melonJS/tree/es6-collection-optimization branch, but i did not succeed so far in re-applying Jason's optimisation to the latest version.
