### ISSUE TITLE
Incomplete docs on TMXLayer setTile, clearTile, getTile and getTileID

### ISSUE THREAD

**Issue by darkodraskovic** [melonjs/melonJS#760]
While setTile and clearTile accept x and y args in map coordinates, getTile and getTileID accept x and y args in world coordinates. This is nowhere mentioned in the documentation and should be, IMO, added to docs.

**Comment by parasyte** [comment]
Also #107 

This in particular is a regression from #537, introduced by febe23108c092c77ae6855c91188e67059f1c6f4 (release v1.1.0)
