### ISSUE TITLE
physic implementation does not respect delta time

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#761]
``` javascript
        /**
         * update the body position
         * @name update
         * @memberOf me.Body
         * @function
         * @return {boolean} true if resulting velocity is different than 0
         */
        update : function (/* dt */) {
            // update the velocity
            this.computeVelocity(this.vel);

            // update player entity position
            this.entity.pos.add(this.vel);

            // returns true if vel is different from 0
            return (this.vel.x !== 0 || this.vel.y !== 0);
        },
```

https://github.com/melonjs/melonJS/blob/master/src/physics/body.js#L506

**Comment by obiot** [comment]
an interesting reading on this topic:
http://www.learn-cocos2d.com/2013/10/game-engine-multiply-delta-time-or-not/

**Comment by agmcleod** [comment]
Yeah that is interesting. It seems like there's arguments for both, and really it depends on the type of game if you want it to slowdown or move at the same pace. I would make the argument: should we let the developer decide? Simply update the api of the body#update to allow delta time. If it's set, apply it, if not just calculate without.

**Comment by obiot** [comment]
another interesting article :
http://gafferongames.com/game-physics/fix-your-timestep/

**Comment by obiot** [comment]
i will tag this one for a 4.1.0 release, anyway we need to update a bit how we compute motion, ideally also add what is in ticket #588, and this one fit into that change

**Comment by obiot** [comment]
closing this one, as the recommendation, and general usage in other engine, is not to apply the delta time. The day we have a box2d/matter/etc... physic plugin we can have a better physic simulation, but until then this fits with the current "simple" one.
