### ISSUE TITLE
tile AD rotation issue when using non-rectangular tiles

### ISSUE THREAD

**Issue by dtturcotte** [melonjs/melonJS#764]
[EDIT - Renamed the ticket to highlight the remaining issue with rectangular tiles]

MelonJS (melonJS-2.1.1) is having issues rendering rotated tiles (horizontally and vertically).
Tiled version: 0.12.3

**Rotated: the rotated tiles (stroke lines) are malformed when rendered in game:**

In Tiled:
http://i.imgur.com/5dx6I5G.png

In game:
http://i.imgur.com/7yVxLDj.png

**Not Rotated: the rotated tiles (stroke lines) line up perfectly in game:**

In Tiled: (building on left is the correctly rendered building)
http://i.imgur.com/U7tB9m4.png

In Game:
http://i.imgur.com/CecxwVt.png

**I played around with simply rotating tiles:**

In Tiled:
http://i.imgur.com/phXjwvn.png

In Game: you can see the tile that looks like a "1" is offset downwards on the Y axis by 64px:
http://i.imgur.com/aLt7em8.png

**More information:**
Tile flipping: http://doc.mapeditor.org/reference/tmx-map-format/

"When rendering a tile, the order of operation matters. The diagonal flip (x/y axis swap) is done first, followed by the horizontal and vertical flips."

I've tried to follow this, but without much success, or perhaps I don't understand the implications of doing it incorrectly. 

**More screenshots**:
Tiled without flip: http://i.imgur.com/dP0HVUi.png
In game: http://i.imgur.com/q0TPowo.png

Tiled with Z (clockwise) flip hit once: http://i.imgur.com/TyFtSF2.png
In game: Error: http://i.imgur.com/bSlWRJz.png

Tiled with X (horizontal) flip hit once: http://i.imgur.com/deXOX2K.png
In game: seems to work: http://i.imgur.com/JtYkrqN.png

Tiled with Y (vertical) flip hit once: http://i.imgur.com/7kGQoB5.png
In game: seems to work: http://i.imgur.com/ZCllyXf.png

So I guess it's just the **Z clockwise** flip that is wrong?

**Comment by parasyte** [comment]
@dtturcotte Can you provide a TMX map and tileset for testing?

**Comment by dtturcotte** [comment]
I can e-mail to you.

**Comment by parasyte** [comment]
jay@kodewerx.org

**Comment by dtturcotte** [comment]
Sent

**Comment by parasyte** [comment]
Got it. Will take a look when I get a chance!

**Comment by dtturcotte** [comment]
See above for more images. I took pics in Tiled and In Game with all rotations

**Comment by dtturcotte** [comment]
Jay,

Should I continue building my maps out with rotated tiles or move on to non-rotatables (like trees and stuff)?

**Comment by obiot** [comment]
wow, you really need such a big tiles ? that's a huge texture to load in memory !
````
 <tileset firstgid="1" name="stickersheet" tilewidth="64" tileheight="64" tilecount="10000" columns="100">
  <image source="stickersheet.png" width="6400" height="6400"/>
 </tileset>
````

**Comment by dtturcotte** [comment]
Obiot, the bug doesn't have to do with the size of this. I've tested on smaller assets. Moreover, even though the image source is 6400x6400, the filesize is only 204kb. I trimmed the file to 2304 × 512 @ 51kb and encountered the same error. As mentioned above, the bug is with clockwise/counter clockwise rotations.

**Comment by obiot** [comment]
i know i know, just saying :P

**Comment by obiot** [comment]
so here is the fix for it !

I have not yet committed anything, as i want to further test it with non rectangular tiles, but you can simply test it by replacing the following lines :
https://github.com/melonjs/melonJS/blob/2.1.x/src/level/TMXTile.js#L111-L121
by these ones :
````javascript
            if (this.flippedX) {
                this.transform.translate(
                    (this.flippedAD ? 0 : this.width),
                    (this.flippedAD ? this.height : 0)
                );
                a[0] *= -1;
                a[3] *= -1;
            }
            if (this.flippedY) {
                this.transform.translate(
                    (this.flippedAD ? this.width : 0),
                    (this.flippedAD ? 0 : this.height)
                );
                a[1] *= -1;
                a[4] *= -1;
            }
````

on a side note (for @parasyte), I feel like we should rewrite this piece of code to looks more the one we used for renderable, after all it;s all about rotation
https://github.com/melonjs/melonJS/blob/2.1.x/src/level/TMXTile.js#L151-L164

**Comment by dtturcotte** [comment]
This works!!! 

What was the issue?

**Comment by obiot** [comment]
two cases were ignored in the `flippedX` and `flippedY` conditions... not sure why the were missing, I'd bet on a regression following some previous refactoring :)

**Comment by obiot** [comment]
well, seems like we have other rendering issue with non rectangular shapes, so i'm unsure i'll keep investigating that one for now...

**Comment by obiot** [comment]
here is a couple of ready to use test case (just missing the latest melonJS 3.0.x build)

AD rotation with square tiles (working) :
[tiled-bug.zip](https://github.com/melonjs/melonJS/files/97071/tiled-bug.zip)

AD rotation with non-square/rectangular tiles (not working) :
[tiled-bug rect.zip](https://github.com/melonjs/melonJS/files/97072/tiled-bug.rect.zip)
