### ISSUE TITLE
`me.Container.childBounds` and ``me.Container.bounds` are redundant 

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#767]
I think I was probably the one adding the former one, but while updating the space invaders tutorial and simplifying the tutorial code to use it, i realised that having a separate rect for child bounds deserve no real useful purpose, and that we should rather resize the bounds rect directly . 

unless i'm missing a use case here ? 

also, i think we should automatically update the container bounds when add/removing childs. (except or the root container)

what do you think ?

**Comment by parasyte** [comment]
That would be really expensive for anything like `me.ParticleContainer`. I think the reason we don't want to recompute child bounds automatically is because children are free to move independently.

**Comment by obiot** [comment]
good point, I forgot about it. Although we could make it a user configurable option through a boolean flag, and being disable by default. this solves the root container scenario and the particle container, while allowing the user to enable it when needed for child container(s).

**Comment by agmcleod** [comment]
You mean having an extra rect in the space invaders tutorial? https://github.com/melonjs/tutorial-space-invaders/blob/gh-pages/tutorial_step5/js/enemy_manager.js#L7

I'm fine with it, as it's more "special" behaviour, and is easily dictated in what's going on. I think too many settings complicates the system.

**Comment by obiot** [comment]
@agmcleod I actually removed the local copy of `chidBounds` you added in the enemy manager : https://github.com/melonjs/tutorial-space-invaders/commit/84458ec68b3d1f4b7872e990a7dea139cf0da2b2?diff=unified#diff-55e845ee3be24edb5008664636b102d0L7

but what I was suggesting is to also remove `childBounds` from the `me.Container` implementation and directly use the `bounds` rect inherited from the `me.Renderable` object. As i was saying having two different rect is not really useful

**Comment by parasyte** [comment]
I think we're coming full-circle on this issue. We've had discussions in the past about the `me.Container` architecture in relation to its bounding boxes.

Here are a few considerations off the top of my head:

* Container bounds should not be adjusted automatically.
  * Performance implications, especially with particle containers.
  * Impossible to statically size a container, e.g. a TMX map implemented as a container.
    * Breaks the concept of clipping children to the container bounds. See #692 
* Caching the union of all children's bounding boxes must be a manual (explicit) request.
  * Using the container's own bounds for this cache will have unintended side effects, e.g. clipping.
  * Storing the cache in a separate rect is perhaps inconvenient, but at least its behavior is well defined and understood.

**Comment by obiot** [comment]
so I wanted to come back on this one. Can't we define some flag, that define if bounds should be automatically updated ? it would then be on by default for anything, except container ? 

I really dislike this double bounds objects in container, and it just adds extra complexity to everything.
