### ISSUE TITLE
melonJS anchor point's coordinate system is against "de-facto" standard

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#768]
In melonJS, `(0, 0)` means the top-left corner, and `(1, 1)` means the bottom-right corner. 

in most of the software out there, the y coordinates are the opposite, with `(0. 0)` being the bottom left corner of the sprite (example from the iOS SDK) :

![unit_coord_2x](https://cloud.githubusercontent.com/assets/4033090/12664293/73175c98-c669-11e5-94f0-c150fa852255.png)

this should also be more inline (if i'm not wrong) with the webgl coordinates system.

and finally, couple of related tickets : #613 #754

**Comment by parasyte** [comment]
FWIW, this is just conventional. WebGL does not care about which direction axes point. Most rendering systems *should* use logical coordinates, to avoid this issue. Obviously, melonJS doesn't use logical coordinates; it is opinionated.

**Comment by Giwayume** [comment]
I've seen both float around. Typically engines that use (0,0) bottom-left are ones that support 3d rendering. But they still have quirks like mouse coordinates are still (0,0) top-left, leading to confusion.

Traditionally for 2d game engines (0,0) is the top-left. This makes sense in terms of the order the pixels are rendered for display on the monitor.

If you switch to bottom left, though, your coordinate system will be out of sync with Tiled. TexturePacker also works with (0,0) being top-left, so you'll have to flip those y coordinates as well.

**Comment by agmcleod** [comment]
Is this an issue we still want open?

**Comment by obiot** [comment]
Yep :D

**Comment by obiot** [comment]
conclusion is to keep the current (0,0) as is the top-left coordinates, and I will probably add the above picture (but adapted to melonJS) in the documentation to clarify it.

so except other features that have been fixed in my working branch (like having different top/left coordinates between entity and sprite), this ticket can be closed.

**Comment by obiot** [comment]
(pour reference) 

![image](https://cloud.githubusercontent.com/assets/4033090/23055313/1a1d0976-f520-11e6-8ce5-80d8f2f2f03a.png)

**Comment by parasyte** [comment]
It still just doesn't feel right. Something something cartesian coordinate system. :) `(0,0)` is in the center of cartesian space, not its upper-left corner.

Also consider a unit circle, defined by a coordinate pair and a radius; the coordinate pair is the circle's origin. Now extend the circle to a square (which can also be defined by a point and a minimum-radius). The square's origin should also be in its center, for consistency.

**Comment by obiot** [comment]
but wait i'm confused... if you replace this box by a sprite, that's exactly what we have today, no ?

**Comment by parasyte** [comment]
Dunno, is it?

**Comment by obiot** [comment]
yes of course...

**Comment by parasyte** [comment]
Ok, I stand corrected. `^_^` This ticket is just about changing the direction of the Y-axis, then?

**Comment by obiot** [comment]
Correct, that we agreed not to change at the end :)

**Comment by parasyte** [comment]
:+1:
