### ISSUE TITLE
add a CONTRIBUTING.md file in the root directory

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#769]
nothing really critical, but I just realised that it then pops up automatically when you create a new issue
https://github.com/blog/1184-contributing-guidelines

before adding it I was looking for where we actually write down about our code style/format requirements (4 spaces tab, etc...) but could not find it (unless we actually never did), does one of you know?

**Comment by parasyte** [comment]
I think the [jshint rules](https://github.com/melonjs/melonJS/blob/master/.jshintrc) rules are as close as you'll get to a formal code style guide. :P
