### ISSUE TITLE
apply back the "hash" optimisation to the es6 collections

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#770]
non working attempt here :
https://github.com/melonjs/melonJS/tree/es6-collection-optimization

**Comment by obiot** [comment]
map support seems to be quite good these days:
http://kangax.github.io/compat-table/es5/#test-Array.prototype.map
not sure this is still that useful to spend energy/time on this one

**Comment by obiot** [comment]
@agmcleod @parasyte do you guys agree on my last comment ?

if yes we can close this ticket, and delete the following branch :
https://github.com/melonjs/melonJS/tree/es6-collection-optimization

**Comment by parasyte** [comment]
Sounds good to me.

**Comment by obiot** [comment]
great !
