### ISSUE TITLE
Implement shape transformations with matrix2d

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#771]
Issue was reported on the forum: https://groups.google.com/d/msg/melonjs/lXxOv__I0fA/Y9G3rSEiGAAJ

The shapes API does not allow rotation or scaling around an arbitrary center point. Using matrix2d will solve this.

Bonus: #601 can be fixed by setting the default matrix to identity for orthographic projections, and a pre-projected matrix for isometric and hexagonal projections.

**Comment by obiot** [comment]
this thing should be as simple as something like this actually (pseudo-code) :

````
Shape.transform(Matrix2d mat) {
    for point in this.points {
        transform all the point of this shapes using the given matrix
        mat.transformPoint ( point ) ;
    }
} 
````

and that's all ?

**Comment by obiot** [comment]
````javascript
        transformPoint : function(x, y, vec) {
            vec = vec || new me.Vector2d();
            vec.x = x * this.a + y * this.c + this.e;
            vec.y = x * this.b + y * this.d + this.f;
            return vec;
        },
````

**Comment by parasyte** [comment]
I thought for sure we already had that ... Because I implemented it specifically for WebGL: https://github.com/melonjs/melonJS/blob/8311f97fe7e1cdc918c28363a686b7e996a52f46/src/math/matrix2.js#L141 --> https://github.com/melonjs/melonJS/blob/8311f97fe7e1cdc918c28363a686b7e996a52f46/src/video/webgl/compositor.js Strange thing is you renamed it, for some reason... That's not very nice from a semver point of view; usually we would go through a deprecation period for API breakage like that.

**Comment by obiot** [comment]
the function was private before I renamed it (@ignore tag) so does not really matter as nobody knew it was there, except you and me :)

**Comment by obiot** [comment]
actually, only you knew it was there :P

**Comment by parasyte** [comment]
FWIW, the function multiplies a matrix and vector together. So the previous name was more fitting, right? The only other method we have named `transform` is just an assignment operator.

**Comment by obiot** [comment]
sure I can modify it back to `multiplyVector` if you think it's a better fit. now `transformVector` also means that we apply this transformation matrix to the given vector, so both actually works for me,
