### ISSUE TITLE
Dependency management with npm

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#772]
We have a couple of third-party dependencies: https://github.com/melonjs/melonJS/tree/0b92a9c8868d63358f9ce756af620457a27ac176/src/vendors

It would be way better to maintain these through a package manager like Bower or npm. I'm slightly opposed to using npm for managing dependencies in a web framework (it's the right tool for node dependencies) [regardless](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) [of](http://dontkry.com/posts/code/using-npm-on-the-client-side.html) [the](http://beletsky.net/2015/04/npm-for-everything.html) [claims](http://browserify.org/). I could enumerate the reasons, but suffice to say the npm _ecosystem_ is not ready for this; the npm _tool_ and _service_ are. (Hint: CommonJS is dead.)

Anyway, we just choose a package manager and maintain our dependencies with a manifest. It will ease the maintenance burden for sure.

**Comment by parasyte** [comment]
There are a few other dependencies spread around the repo:

* [Collision handling](https://github.com/melonjs/melonJS/blob/c13f6dea1a3c2f2c7ae725c6520cd9cf31df6807/src/physics/collision.js) is based on(not using) SAT.js
* [QuadTree](https://github.com/melonjs/melonJS/blob/7913322a3a71a3bb85c4b3f4d3596d7ec1060581/src/physics/quadtree.js) is based on quadtree-js
* [me.Object](https://github.com/melonjs/melonJS/blob/c13f6dea1a3c2f2c7ae725c6520cd9cf31df6807/src/lang/object.js#L315) is based on jay-extend

**Comment by agmcleod** [comment]
I think the main reason for not using npm is because we don't use anything like commonjs or amd. Thats' where i think bower would be a bit nicer, for pulling static files.

Still if we slowly transition to using es6 modules, i don't see why we shouldn't use NPM at that point.

**Comment by parasyte** [comment]
Most packages in npm don't support the ES6 module pattern, either. But yeah, pretty much what you said.

**Comment by agmcleod** [comment]
it's polyfilled through some matter. My point is we would have the ability to require npm dependencies quite easily. Given Olivier mentioned doing it at sometime, it would be the best time to switch to pulling npm vs static files via html/grunt concat ordering.

**Comment by parasyte** [comment]
It's been my experience that packages in npm tend to expect CommonJS+Browserify, or go all in with ES6 `import`. Meanwhile, we already have our dependency order expectations in line. https://github.com/melonjs/melonJS/blob/85eacab650ad596fb46d0f8290af0544a6e19265/sourceFiles.json

**Comment by obiot** [comment]
I like the idea, but don't we have custom code on literally each of them ? maybe a good start would be to push back all the changes we did on all respective repos ?

**Comment by parasyte** [comment]
I did similar work on the tutorials; they now have dependency management through npm. For example: https://github.com/melonjs/tutorial-space-invaders/blob/fd5e86b018e60dce53675c5289d9bc77d54100a2/package.json#L7

Install devDependencies with npm, then run that npm script to copy the dependencies to a location that the browser can reach. This allows us to commit only the built dependency files, and not the entire source tree for them.

```bash
$ npm install
$ npm run update:deps
```

**Comment by Ascheere** [comment]
I've really enjoyed npm as the dependency manager because it can be locally managed to the solution. That might be because I've used npm a lot.

**Comment by parasyte** [comment]
After using `npm` exclusively for all dependency management (and even as the build system) it's definitely grown on me. I can't think of a good reason to use Grunt or Gulp... Or bower. :)

The one missing piece is native ES6 module support. It's being worked on right now, but there's still the problem of backward compatibility.

**Comment by krojew** [comment]
+1 on using npm
-1 for bower, since it's dead

**Comment by parasyte** [comment]
Agreed. Updated title.

**Comment by agmcleod** [comment]
@parasyte @obiot @krojew Curious on what you guys think. For building a solution here, i wonder if we need to update the build system. Whether we keep with grunt or w/e, but more importantly do we need to use modules? Or do we just have one file that has the require() vendors, and still do a concat?

**Comment by parasyte** [comment]
Modules will finally give us #212 😄

**Comment by agmcleod** [comment]
Fair point. Since we updated to use eslint, i'd love to take it the next step and start leveraging things like webpack, as i find it builds faster, easier to integrate the watch changes workflow as well. I'm more of a mocha + chai fan these days instead of jasmine, though unless updating build system demands it, i'm not rushed to change the testing framework.

**Comment by parasyte** [comment]
Also with ES6 module support coming soon :tm: to all major browsers, I'm not opposed to skipping CommonJS/Webpack and going straight to `import`/`export`.

**Comment by obiot** [comment]
https://github.com/ModuleLoader/es-module-loader :)

**Comment by parasyte** [comment]
Yeah, but native support is coming to every browser already...

**Comment by itsjavi** [comment]
Would be nice to have the library in `npm` (where it already is) an compatible at least with ES6 exports:
```js
// src/scenes/MyScene.js

import {LevelDirector, ScreenObject} from "melonjs";

class MyScene extends ScreenObject {
  onResetEvent() {
    LevelDirector.loadLevel("Level_01");
  }
}

export default MyScene;
```

I have a workaround with `webpack`, `babel` and `shim-loader` which is able to treat a global variable as an export, but I can only use the `me` centralized object.

You can see an example in the source code of my game prototype: [https://github.com/pokettomonstaa/NewBark](https://github.com/pokettomonstaa/NewBark/tree/2fba4d725e442e98dcbe60ed8a0a8d31ffae5eb7)

**Comment by obiot** [comment]
For those of you still reading these comments here : build process has finally be changed to npm, and external dependencies managed through npm and rollup ! I realized i just broke karma with my last commit, but else its working like a charm :)

**Comment by obiot** [comment]
all done, jasmine fix, the new build process is a success ! I even added a dependencies badge on the README :P

**Comment by obiot** [comment]
@parasyte could you add me as a collaborator on npm, looks like I have no right to publish any new version there :)
https://www.npmjs.com/package/melonjs

thanks!

**Comment by itsjavi** [comment]
I added you @obiot

**Comment by obiot** [comment]
@itsjavi  finally we have an updated version of melonJS on npm :)

**Comment by parasyte** [comment]
Sorry about that. I would have gotten to it sooner, but I was asleep. :)
