### ISSUE TITLE
Pointer events don't work correctly with floating regions

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#773]
The discussion: https://groups.google.com/d/msg/melonjs/osvb7I2a9C8/6gU-9Y-IGAAJ

This is probably the easiest of the three bugs I enumerated in that post. IMHO, this should be fixed by using the absolute position (and especially converting floating regions to world coordinates) here: https://github.com/melonjs/melonJS/blob/7913322a3a71a3bb85c4b3f4d3596d7ec1060581/src/physics/quadtree.js#L131-L134

**Comment by obiot** [comment]
Just thinking out loud, but should we rather not pass object to the quadtree with the right coordinates, and keep the quadtree implementaiton agnostic of these consideration?

Also it might not be as straightforward as you imply, as when dealing with container there are thses cases where an object is floating because its parent container is a floating object

**Comment by parasyte** [comment]
We already enforce certain characteristics of floating containers, e.g. that the entire tree under them is treated as floating, too: https://github.com/melonjs/melonJS/blob/af864c554b487ec617e738c1f3c27e6c9f14a02c/src/renderable/container.js#L731 There's no reason we can't enforce the flag to be set on all "implicitly floating children", too. Just put `obj.floating = true` on line 733. This gives a opportunity for code outside of the update loop to act on implicitly floating objects, which is all we really need.

As for how you prefer the implementation, of QuadTree ... doesn't bother me any. QuadTree is already specialized for melonJS. But if we plan to change that in the future (#772) then it might be wise to keep it agnostic to coordinate spaces. I just don't see how that is even possible. ;) The QuadTree algorithm only works on one logical coordinate space at a time.

**Comment by parasyte** [comment]
Two implementations that I can see working:

1. When inserting an item into the QuadTree, it must be inserted with its absolute world coordinates (currently missing); All QuadTree lookups are done with absolute world coordinates (as today).
2. Items are inserted into QuadTree with their natural coordinates (as today); All lookups are performed in two separate steps (currently missing):
  1. Lookup by world coordinates (as today) but also filter out all floating items (currently missing).
  2. Lookup by screen coordinates, and filter out all non-floating items (currently missing).

So we're definitely half-way there, no matter when implementation we choose. IMHO, the former will have better performance in the long run. The latter will be harder to maintain/remember that the lookups must be done in two distinct steps... (Though that complexity could be hidden away in the lookup method itself.)

**Comment by obiot** [comment]
I'd certainely go as well for solution 1 for the exact same reasons you described against solution 2, not to mention (if i'm correct) that the actual code for this fix is already wandering around somewhere in the forum :P

would you however have the time to look at it ? i'm travelling on my side for the next couple of days and won't probably be able to do anything before the end of this week

**Comment by parasyte** [comment]
#786 addresses this issue. Still needs validation, but it has now been merged.

**Comment by obiot** [comment]
can you give a quick try to the "UI" example as well ?

**Comment by obiot** [comment]
similar issue reported here, also fixed through the changes in #786
