### ISSUE TITLE
add support for audio sprites

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#774]
Howler already supports audiosprite, but we do not through our exposed API.

This should be quite easy though through the resource list.

for now we add audio assets by doing :
````javascript
     { 
        name: "sound",
        type: "audio",  
        src: "data/sfx/"
     }
````
we can then simply one more `sprite` property to it 
````javascript
     { 
        name: "sound",
        type: "audio",  
        sprite: {
            blast: [0, 1000],
            laser: [2000, 3000],
            winner: [4000, 7500]
        }
        src: "data/sfx/"
     }
````
`sprite ` Object {}

Define a sound sprite for the sound. The offset and duration are defined in milliseconds. A third (optional) parameter is available to set a sprite as looping. 

````javascript
{
  key: [offset, duration, (loop)]
}
````
with `sprite` that will then automatically passed to Howler when instantiating an audio element, no other impact on the current API.

as also indicated on the Howler page, an easy way to generate compatible sound sprites is with [audiosprite](https://github.com/tonistiigi/audiosprite).

**Comment by parasyte** [comment]
But audio sprite is for supporting old UAs, and WebAudio is the way forward. Are you sure we want to put the energy into things like this?

**Comment by agmcleod** [comment]
Yeah i agree with @parasyte. Having done some web audio code recently, you can do that kinda stuff, plus way more using web audio code.

**Comment by obiot** [comment]
not sure i'm following you on this one guys.... audio sprites are like texture atlas, it's about combining small audio assets into a big one, and with the same kind benefits when it comes to loading them.

also the effort is as big as adding one line of code, as it's all supported already by Howler

**Comment by parasyte** [comment]
The only benefit is fewer HTTP requests, but that's getting solved in other ways; HTTP/2 and self-sufficient apps. Audio buffers don't have the same memory constraints as WebGL, so it's not even comparable.

Audio sprites also have a lot of drawbacks, like inserting sufficient silence between clips to avoid aliasing. And if your timestamps are not accurate, you'll either have the clips playing too soon or too late.

**Comment by parasyte** [comment]
The [HTTP/2 FAQ](https://http2.github.io/faq/#why-revise-http) puts it nicely:

> ... This has led the industry to a place where it’s considered Best Practice to do things like ***spriting***, data: inlining, domain sharding and concatenation. These hacks are indications of underlying problems in the protocol itself, and cause a number of problems on their own when used.

(Emphasis added.)

**Comment by obiot** [comment]
still a "one line of code" thingy to expose the "API"...  don't really see it as such a big deal

**Comment by parasyte** [comment]
You can do it, but using it is not recommended. Therefore, doing it seems silly.

**Comment by agmcleod** [comment]
Also it's always worth keeping in mind that any feature we add, we need to support, test and keep up to date. It's worth adding if we get enough demand for it.

**Comment by obiot** [comment]
Closing this one then :)
