### ISSUE TITLE
Onclick Issue in Tutorial:  title.js

### ISSUE THREAD

**Issue by jumpingjackson** [melonjs/melonJS#776]
in the code for title.js in the tutorial  http://melonjs.github.io/tutorial-platformer/ it has this line of code on line 59 

_me.input.bindPointer(me.input.pointer.LEFT, me.input.KEY.ENTER);_

When run it gives this error:
_Uncaught TypeError: Cannot read property 'LEFT' of undefined_

[Assignment4.zip](https://github.com/melonjs/melonJS/files/140014/Assignment4.zip)

**Comment by agmcleod** [comment]
Hi there, so the guide was written for MelonJS version 3.0, the attached zip includes 2.1.3.

You can grab the latest release here: https://github.com/melonjs/melonJS/releases/tag/3.0.0

Here's our upgrade guide as well: https://github.com/melonjs/melonJS/wiki/Upgrade-Guide
