### ISSUE TITLE
"optimise" the melonJS bootstrap size

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#778]
as discussed on gitter, it might be wise to move the following line "inside" melonJS directly :
https://github.com/melonjs/boilerplate/blob/master/index.html#L42-L51

and probably put it there :
https://github.com/melonjs/melonJS/blob/master/src/system/device.js#L25

**Comment by parasyte** [comment]
I'm also thinking about some other potential wins here. Like adding and running the loading screen automatically. Removes one line of code: https://github.com/melonjs/boilerplate/blob/beafef3865e6217f10f5c9898a8616b953e6325c/js/game.js#L37

Initializing audio automatically to remove another line. (Could stretch this idea a bit so that audio *and* are always initialized and just "ready to rock" right from the start.)

Then combine `me.loader.preload` and `me.loader.onloaded` to remove another line:

```javascript
me.load.preload(game.resources, game.loaded);
```

The debug hash stuff should be moved to the debugPanel plugin...

Lots of little things, I think. The goal is to shrink the bootstrap requirements enough to have a complete "hello world" in just a handful of lines.

**Comment by obiot** [comment]
> I'm also thinking about some other potential wins here. Like adding and running the loading screen automatically. Removes one line of code: https://github.com/melonjs/boilerplate/blob/beafef3865e6217f10f5c9898a8616b953e6325c/js/game.js#L37

how you would see it working then ? as soon as the "user" is calling the `preload` function, it would trigger a state change ?

> Initializing audio automatically to remove another line. (Could stretch this idea a bit so that audio and video are always initialized and just "ready to rock" right from the start.)

I do like that one, we do have change some logic though, as today the audio.init function is used to passed the list of audio extension we use, since they are not specified in the resource list

> Then combine me.loader.preload and me.loader.onloaded to remove another line:
me.load.preload(game.resources, game.loaded);

I'm not sure i'm getting what you mean with this one ? can you clarify ?

**Comment by parasyte** [comment]
Preload just starts loading resources. Until that function is called, the loading screen is idle. So it can be the "default" screen state when melonJS starts; create the load screen and switch to it immediately without requiring the user to do this.

---

Trying to clarify the combination of the preload function and callback definition...

Old:

```javascript
me.loader.onload = this.loaded.bind(this);
me.loader.preload(game.resources);
```

New:

```javascript
me.loader.preload(game.resources, this.loaded.bind(this));
```

**Comment by obiot** [comment]
btw does anyone has any recollection of why we have that `me.skipAutoInit ` variable there (that is not declared anywhere) ?
https://github.com/melonjs/melonJS/blob/da0d66d2db290066d099253b78b6b3f5b31ea6d6/src/lang/window.js#L149

**Comment by obiot** [comment]
@parasyte I followed your idea and set the loading state as the default, but this has some side-effects, (requiring further code change) in case the "user" wants to define a custom loading screen. So since I don't want to spend one day on this what I would rather do is to add a third (boolean) parameter to the preload function that would than switch to the load state if set to true

**Comment by obiot** [comment]
any idea on `skipAutoInit` ? if nobody knows, I'll remove it

**Comment by parasyte** [comment]
> skipAutoInit

`git blame` says: https://github.com/melonjs/melonJS/pull/442

@obiot What is the challenge with a user-defined loading screen? Don't they just create a new state object for it and switch to it?

**Comment by obiot** [comment]
yes I suppose they can too :P anyway it makes sense as well (at least to me) to switch to the loading screen when calling the `preloader` function; as if you have nothing to preload, there is no reason to show a loading screen.

good finding for #442, thanks !

**Comment by obiot** [comment]
looks better and smaller :
https://github.com/melonjs/boilerplate/blob/dev/js/game.js

:)

**Comment by parasyte** [comment]
Yeah! Good start, and good work so far. Any thoughts on the holdover? https://github.com/melonjs/boilerplate/blob/fd4d1ccb5f8968fba976a28633c08b3bba923757/index.html#L38-L43

It feels like ... hypothetically, if this was ES6 ... we would explicitly get around this one directly with the module loader:

```javascript
const me = import("melonjs");
me.loader.preload(game.resources).then(function () {
  // Insert magic here...
});
```

:wink:

**Comment by obiot** [comment]
nope.... :( I tried to think about something, but did not have any good idea so far :(
I thought about moving the `onReady` function under the `me.device` namespace, but it does not lower the amount of code we need (just it prevent from adding more stuff under `window`)

and sure, es6 module would be great !

**Comment by obiot** [comment]
now it's your turn to add that hello world into the website :P:P:P

**Comment by obiot** [comment]
closing this one
