### ISSUE TITLE
animated tiles are not working when `preRender` is on

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#780]
add `me.sys.preRender = true;` to the platformer example (in game.js) and watch the magic "not happening" !

**Comment by obiot** [comment]
actually it's not as simple as that, as after checking the code it;s more like :

-> forcing `preRender` when animated tiles are used is not always working

Test case :
1. add `me.sys.preRender = true` to game.js for the platformer
2. open the platformer, in level 1, the water animated tiles are not animated
3. go to level 2, the water is correctly animated.

I did not really investigate furthermore, but so far the difference i can see is that level 1 is originally a TMX map, and level 2 a JSON one, so maybe there is a if/else missing or misplaced somewhere.

**Comment by parasyte** [comment]
Snap! There was code to handle that case. I don't recall if it was tested thoroughly, though.

https://github.com/melonjs/melonJS/blob/1d959de42ae371a4cb299abf27d942ae1d2b611c/src/level/TMXLayer.js#L478-L481

**Comment by parasyte** [comment]
So actually ... I get this in the platformer when setting `me.sys.preRender = true;`

![screen shot 2016-03-10 at 11 17 10 pm](https://cloud.githubusercontent.com/assets/456942/13695747/4ae65440-e716-11e5-96d9-6b38df3e55b5.png)

**Comment by obiot** [comment]
Wtf....

I left already so i cannot share a screenshot, but i'm not having that at all on my side, and the only issue is the animated tiles.

**Comment by parasyte** [comment]
* Operates as described in Safari and Firefox (CanvasRenderer)
* Operates as shown in screenshot in Chrome and Firefox (WebGLRenderer)

**Comment by obiot** [comment]
Funny! And yeah then i understand, as i mostly use Safari during development (don't ask me why, i'm a sentimental)

**Comment by obiot** [comment]
Maybe a texture size issue or something? What's the limit on all these browsers ? Or they dont like big non power of 2 textures?

**Comment by parasyte** [comment]
Fixed the black rendering thing. Safari and Firefox doesn't support the "opaque" canvas feature, which is why it didn't happen there. I guess Firefox WebGL context does support it, though?

**Comment by parasyte** [comment]
Regressed here: https://github.com/melonjs/melonJS/commit/1a5cf12637c9ee92de9314cfe33caf4d5ab4dd8f#diff-1081e93d612904ecd80024589950e1f9L432

**Comment by obiot** [comment]
nice finding, I did not think at all about this :)

**Comment by parasyte** [comment]
I understand this bug with preRender vs tileset animation. When a TMX layers references an animated tileset, the animated tile set is added to a list for updates. The tileset animation is disabled so that the next layer that references the same tileset will not have to update the tileset more than once per frame. This all happens here: https://github.com/melonjs/melonJS/blob/38b7fd32a2e360b0021b5bddd19a21ece4cd97bc/src/level/TMXLayer.js#L469-L472

This "disable the tileset animation" causes the preRender flag to be disabled only on the first background layer in the platformer, and the other two layers (which contains the water animations) continue to use preRender.

We need a better way to prevent multiple-updates-per-frame on the tilesets, or at least make them idempotent.

**Comment by obiot** [comment]
Wow, that's way more complex than what i initially thought :)

Note that this could be done at the parsing level instead of during a layer instantiation : when parsing the tileset object, if animated tiles are detected, the flag is forced back to false ?

**Comment by parasyte** [comment]
That has the same problem, though? The trick is getting every layer that references the animated tileset to not use preRender, but the animated tileset can only be updated once per frame. :smiley:

**Comment by obiot** [comment]
Yes indeed, I was just thinking outloud and did not have the opportunity yet to go through your analysis

**Comment by parasyte** [comment]
A quick and dirty hack to making the tileset update only once per frame is by recording the return value from `me.timer.getTime()`, since it is cached and only updated once per frame... I'll try it out. :)

**Comment by obiot** [comment]
Interesting, i'm a bit confused by the changes, i'll check it later ;)

**Comment by parasyte** [comment]
This line is what fixed it: https://github.com/melonjs/melonJS/commit/e2ab9b1bd6761bc13b98069bd159311537730a73?w=1#diff-1081e93d612904ecd80024589950e1f9L470

The rest of the patch is for working around a bug that the single-line fix exposes; preventing the tileset update from occurring more than once per frame.

**Comment by obiot** [comment]
oh yeah, because all layers were previously updating all the tilesets ! I did not see that at all :P
