### ISSUE TITLE
[Tiled 0.16] add support for typed custom properties

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#782]
property type can be defined now in the coming Tiled 0.16 (string, float, int, boolean), see the CHANGELING here :
https://github.com/bjorn/tiled/commit/f4875998d2d320e406d9d432a0fe5680874fe4ec

**Comment by parasyte** [comment]
This is good. We do a "best effort" type detection right now, but data type annotations are way better. Ref: https://github.com/melonjs/melonJS/blob/1fa660c41706e01e0363133219ca1571d606a50c/src/level/TMXUtils.js#L37-L70

**Comment by parasyte** [comment]
Found the implementation: https://github.com/bjorn/tiled/blob/master/src/tiled/objecttypes.cpp

**Comment by obiot** [comment]
:+1  :)

**Comment by obiot** [comment]
I just realized that Tiled 0.16 has been released 10 days ago :
https://github.com/bjorn/tiled/releases

right timing to include this in the 3.1.0 version as well. should be pretty quick/easy to add
