### ISSUE TITLE
me.video.renderer.strokeRect breaks the webGL renderer

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#783]
I noticed this when working on my current game, as I use a lot the `me.video.renderer.fillRect()` and `me.video.renderer.strokeRect()` functions to dynamically draw elements of the game. As it does not seems to be that easy to fix (at least for me), and as I do not really plan to use the webGL renderer for it (Canvas is enough for my game performance-wise, not to mention that webGL has lower performances in my case), here is a ticket to keep track of it.

## test case 
I wrote the following few lines to mimic what I am doing to showcase the issue. it's basically drawing 3 overlaping rectangle using semi-transparent primary colours, and add a stroke on each of them using almost the same colour 
````javascript
var game = {
    /**
     * Initialize the application
     */
     onload: function() {

        // Initialize the video.
        if (!me.video.init(320, 240, {wrapper : "screen", scale : "auto"})) {
            alert("Your browser does not support HTML5 canvas.");
            return;
        }

        var r = new me.Color (255, 0, 0, 0.5);
        var g = new me.Color (0, 255, 0, 0.5);
        var b = new me.Color (0, 0, 255, 0.5);

        me.video.renderer.clearSurface(null, "#ffffff");

        me.video.renderer.setColor(r);
        me.video.renderer.fillRect(60, 20, 100 ,100);
        me.video.renderer.setColor(r.darken(1.0));
        me.video.renderer.strokeRect(65, 25, 90 , 90);

        me.video.renderer.setColor(g);
        me.video.renderer.fillRect(110, 70, 100 ,100);
        me.video.renderer.setColor(g.darken(1.0));
        me.video.renderer.strokeRect(115, 75, 90 , 90);

        me.video.renderer.setColor(b);
        me.video.renderer.fillRect(160, 120, 100 ,100);
        me.video.renderer.setColor(b.darken(1.0));
        me.video.renderer.strokeRect(165, 125, 90 , 90);
    }

}; // game
````
The expected result is as follow using the Canvas Renderer (on Chrome 48) :
![3_stroke_canvas](https://cloud.githubusercontent.com/assets/4033090/13768943/8c6b039a-eab6-11e5-9872-662d410b5f02.png)
Using the webGL renderer however (adding `#webgl` to the URL, and still using Chrome 48), the alpha component of the stroked line seems to be ignored by the renderer :
![3_stroke_webgl](https://cloud.githubusercontent.com/assets/4033090/13768950/9b405dc0-eab6-11e5-8389-36ba1c67f62e.png)

Note : the `darken` function does not modify the alpha component of a color :
https://github.com/melonjs/melonJS/blob/master/src/utils/color.js#L271-L286

## more fun with strokeRect
things become even more interesting if we simplify the test and remove some strokeRect. After a few trials, I actually realised that the trick to reproduce the issue is to *not* finish the script with a strokeRect.

so let's modify the script as follow to only keep the first one :
````javascript
var game = {
    /**
     * Initialize the application
     */
     onload: function() {

        // Initialize the video.
        if (!me.video.init(320, 240, {wrapper : "screen", scale : "auto"})) {
            alert("Your browser does not support HTML5 canvas.");
            return;
        }

        var r = new me.Color (255, 0, 0, 0.5);
        var g = new me.Color (0, 255, 0, 0.5);
        var b = new me.Color (0, 0, 255, 0.5);

        me.video.renderer.clearSurface(null, "#ffffff");

        me.video.renderer.setColor(r);
        me.video.renderer.fillRect(60, 20, 100 ,100);
        me.video.renderer.setColor(r.darken(1.0));
        me.video.renderer.strokeRect(65, 25, 90 , 90);

        me.video.renderer.setColor(g);
        me.video.renderer.fillRect(110, 70, 100 ,100);

        me.video.renderer.setColor(b);
        me.video.renderer.fillRect(160, 120, 100 ,100);
    }

}; // game
````
Using the Canvas renderer, the result is  correct (chrome 48) :
![1_stroke_canvas](https://cloud.githubusercontent.com/assets/4033090/13768967/bcb1158a-eab6-11e5-9514-39ec79b6434b.png)

However using the webGL renderer it's kind of interesting :
![1_stroke_webgl](https://cloud.githubusercontent.com/assets/4033090/13768970/c1a99ef4-eab6-11e5-94fe-03bccff4d481.png)

## Safari
Using Safari, the result are completely different, as soon as you use the strokeRect :

without strokeRect (webGL/Safari 9.1) :
![no_stroke_safari](https://cloud.githubusercontent.com/assets/4033090/13768983/d6479ca8-eab6-11e5-805b-0cb0f48f83cb.png)
a bit blurry compared to Chrome, but correct

with strokeRect (webGL/Safari 9.1) :
![stroke_safari](https://cloud.githubusercontent.com/assets/4033090/13768979/ce239b26-eab6-11e5-9f43-99b21b70d393.png)

## conclusion
that was fun ! also, and although I did not use nor try them, I suspect we probably have the same issue with the other `strokeXXXX` functions.

**Comment by obiot** [comment]
here is a zip with the actual test script, it includes the latest build from the master branch, and the above screenshots :
[testcase.zip](https://github.com/melonjs/melonJS/files/173354/testcase.zip)

**Comment by parasyte** [comment]
I haven't looked yet, but it's probably related to what I posted in gitter:

> Those APIs are synthesized by the WebGL renderer. It has to swap the shader each time you alternate those calls.
> That's a full flush and `useProgram` call for each fill and each stroke. Not really ideal.

Your last screenshots look like Chrome and Safari are choking on the quad buffer.

**Comment by obiot** [comment]
Sure i can understand the performance part, but it's funny to see how it breaks everything once used. Slow yes, but at least one should expext it to work as with the canvas renderer.

**Comment by parasyte** [comment]
Right, I don't know what's up with that. Maybe calling `useProgram` 200 times per frame is exposing bugs in the WebGL driver. :wink:

**Comment by obiot** [comment]
while trying to do some step by step debugging (which is a bit difficult by the way, not to mention that the result is then not correct when debugging), i noticed the following exception : `WebGL: INVALID_OPERATION: uniformMatrix3fv: location is not from current program`

it's from the setter here (smart piece of code by the way) :  https://github.com/melonjs/melonJS/blob/master/src/video/webgl/shader.js#L136

and seems to happen when it draws the final (3rd) `strokeRect`

**Comment by obiot** [comment]
> Right, I don't know what's up with that. Maybe calling useProgram 200 times per frame is exposing bugs in the WebGL driver. :wink:

or just 6 times like here :P:P:P

**Comment by obiot** [comment]
also, by looking at the webGL documentation, should we not use a varying `vColor` instead of a uniform `uColor`, so that we can properly (if not already) pass the color attribute to the shader ? maybe that would fix the alpha component issue ? 

(sorry if i'm saying anything stupid, just trying to make sense of it, and understand where would the issue be)

**Comment by parasyte** [comment]
> `WebGL: INVALID_OPERATION: uniformMatrix3fv: location is not from current program`

I see. It should probably initialize all of the vertex attribute and uniform locations for each shader.

> also, by looking at the webGL documentation, should we not use a varying `vColor` instead of a uniform `uColor`, so that we can properly (if not already) pass the color attribute to the shader ? maybe that would fix the alpha component issue ?

I didn't use a varying because the line color does not vary between vertices. Since the color is static for the entire line, a uniform works better. Passing color as a vertex attribute will just duplicate the color unnecessarily over every element in the vertex array.

If the compositor were to draw multiple lines, each potentially a different color, then using a vertex attribute and varying would make sense. That's a nice optimization for specific use cases, but you won't hit that code path anyway since you're alternating between shaders.

The alpha component is already part of the color (it's a vec4). The blend function may have to be set for each program (compiled shader): https://github.com/melonjs/melonJS/blob/cef6ffdfb6059a07b2d2945a1c482fafc0b4db24/src/video/webgl/compositor.js#L188-L190 But that seems weird because these methods look global to me!

> and another question : why is precision set to highp in the line-vertex.glsl.dot shader, while for others is dynamically set ?

Uhm? It's set dynamically for both shaders:

https://github.com/melonjs/melonJS/blob/cef6ffdfb6059a07b2d2945a1c482fafc0b4db24/src/video/webgl/compositor.js#L109-L123

**Comment by parasyte** [comment]
I just started researching this. Here are my initial findings:

* Alpha is not ignored in the line shader. It is just blended with the existing back buffer (which already contains `alpha = 0.5` from `fillRect`). The blending is additive: `0.5 + 0.5 = 1.0` So you get a fully opaque color. Try it with `alpha = 0.1`!
  * `darken(1.0)` is a no-op.
  * The canvas spec does not *stroke* vector shapes with pixel alignment. It actually uses half-pixel alignment; The line width is doubled, and the opacity is halved. Add `0.5` to the `x` and `y` arguments in the `strokeRect` calls, e.g. `me.video.renderer.strokeRect(65.5, 25.5, 90, 90);` Now you get almost identical rendering in both canvas and WebGL.
    * It's not quite identical because the blending function expects pre-multiplied alpha. Here's a comparison with a hack that pre-multiplies the alpha component on the `stroke` calls in WebGL:

Canvas:
![canvas-1](https://cloud.githubusercontent.com/assets/456942/13830215/7c7a5bfc-eb88-11e5-8d63-414a1cfd3652.png)

WebGL:
![webgl-1](https://cloud.githubusercontent.com/assets/456942/13830214/7c7a2fa6-eb88-11e5-9f30-9e996d594e57.png)

* Your second test (removing some `strokeRect` calls) has one fatal flaw: you aren't flushing the compositor! `strokeRect` automatically flushes the compositor so the shader can be switched. You have to do that manually, now. Put `me.video.renderer.blitSurface()` at the end of the draw calls to fix it.
  * You have the same problem with the canvas renderer when double buffering is enabled. :wink:

* Looks like Safari has some of the same behavior that I experienced in iOS. I thought it was a bug in the GLES driver on mobile, but it looks like a bug in Safari! Chrome and Firefox work correctly.

**Comment by parasyte** [comment]
@obiot I just pushed a workaround for the Safari bug. Apparently `gl.useProgram` kills all of the vertex attribute bindings in Safari, for some reason. So we're just going to make a few more totally pointless calls because Safari is dumb and won't keep the state that was set at instantiation time and never gets touched ever again. :)

**Comment by obiot** [comment]
well I would say "who cares about Safari" to be honest, but the annoying point as you mentioned above is that iOS has the same behaviour.. 

anything that can be useful here ?
https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html

**Comment by obiot** [comment]
few additional questions :
- does it means that the blending mode used with the webGL renderer is not the same as when the canvas renderer is used ? 
- what do you mean `darken` is a no-op ? (the goal was just to change the color so that it is visible)
- back on the alpha question, and pixel alignment, should we not provide the same behaviour on both renderer ?

**Comment by parasyte** [comment]
Good questions.

> anything that can be useful here ? https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html

Probably not. In the end, Safari is going against the GLES spec (AFAIK! I could be wrong, but Chrome and Firefox exhibit the same behavior there, and they are both independent implementations). We should probably just file a bug against WebKit and have them fix it.

> * does it means that the blending mode used with the webGL renderer is not the same as when the canvas renderer is used ?

That's right. Pre-multiplied alpha is specific to OpenGL. My understanding is that it's also the only way to get alpha blending working correctly. In short, this is a change to the representation of color values in the form: `color.rgb * color.a`. A premultiplied color with green at full brightness and alpha at 0.5 would give you `(0, 1, 0) * 0.5 = (0, 0.5, 0)`

> * what do you mean darken is a no-op ? (the goal was just to change the color so that it is visible)

`darken(1.0)` does nothing. Just look at the code. :) It multiplies each component by 1! lol.

> * back on the alpha question, and pixel alignment, should we not provide the same behaviour on both renderer ?

I don't see why not. It just hasn't been done.

Also, there are tons of compatibility things like this that are not currently supported or working properly in the WebGL renderer. I'm not really "sure" about supporting a compatibility layer for the long term. Going all-in on WebGL is definitely the way for the future ... And there is a lot of unnecessary overhead in doing things in a perfectly compatible way, as you've seen.

**Comment by obiot** [comment]
> darken(1.0) does nothing. Just look at the code. :) It multiplies each component by 1! lol.
okay yeah, that was just super dumb.... :package: 

> Also, there are tons of compatibility things like this that are not currently supported or working properly in the WebGL renderer. I'm not really "sure" about supporting a compatibility layer for the long term. Going all-in on WebGL is definitely the way for the future ... And there is a lot of unnecessary overhead in doing things in a perfectly compatible way, as you've seen.

sure yes, but i like the idea though of pushing the current implementation towards webGL, even as a first step to implement things like pre-multiply alpha or pixel alignment on the canvas renderer. that would definitely help in a transition where we would remove the canvas renderer :)

**Comment by obiot** [comment]
this one can be closed, there is another specific ticket for the pre-multiply alpha question,
