### ISSUE TITLE
melon js not working in phonegap

### ISSUE THREAD

**Issue by codex8** [melonjs/melonJS#784]
hi i made a game using melonjs and it's working good on web and desktop version but it's not working on phonea app im using phone gap for building phone apps.

**Comment by parasyte** [comment]
Can you provide an example that can be run in the iPhone or Android simulator?

**Comment by obiot** [comment]
Hi, also please provide some details on both melonJS version, phonegap version, and "WHAT" is not working.

by the way, is phonegap really a good choice as a game wrapper ? I know i would rather use cocoonJS that is more adapted for gaming

**Comment by codex8** [comment]
After building app with phonegap when i run my app in android it stuck on melonJs loading bar 

melonJS version 2.1.1

PhoneGap (iOS / Android / Windows)
cli-6.0.0 (4.0.1 / 5.1.0 / 4.3.0)

Download the app from phonegap 

https://build.phonegap.com/apps/1959794/share

**Comment by parasyte** [comment]
@codex8 Thanks, I'll install the Android SDK and try to help debug it.

**Comment by codex8** [comment]
@parasyte thanks! :+1:

**Comment by agmcleod** [comment]
@codex8 

Hi there, just tried your build on my nexus 4, it works fine. I'd recommend connecting your phone via usb, use chrome://inspect page to see if there are any xhr errors loading assets. You can reload the page via the chrome console if you need to using `window.location.reload()`. It could be the format of the audio you're using (mp3), as it could be specific to the device on what browser it's running internally.

Technically olivier is right, in that you should use cocoonjs to run games over phonegap. In more recent devices, phonegap performs a bit better than it used to, but cocoonjs has optimized this quite well already. Phonegap is good if you want to use the DOM, or many other APIs that cocoon doesnt provide. Well I know cocoonjs is supporting more app specfic stuff these days, but i think that's a build ontop of phonegap anyways :)

**Comment by codex8** [comment]
@agmcleod   Did you tried .apk because it's not working when we build apk app using phonegap.And It's working good when we use HTML app on web browsers

**Comment by agmcleod** [comment]
@codex8 yep. I downloaded the APK you linked through the chrome browser. Installed it, and it launched fine. Definitely need to debug what's going on when you test it to get to the bottom of this.

**Comment by wb9688** [comment]
@codex8 I think that your phone's webview doesn't support some features used by melonJS. Does it work with Cordova and Crosswalk using [this guide](https://crosswalk-project.org/documentation/cordova.html)?
