### ISSUE TITLE
global composition mode & blending features

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#785]
the following is a raw input, but basically melonJS should allow to :
- [x] set/change the current blending mode (both for the canvas and webgl renderer)
- [x] change the blend mode globally (through `me.video.init`) or per container (`me.Container.setBlendMode` ?) 
- [x] align the canvas renderer to the webgl one (or the opposite) in terms of default blend mode (webgl uses pre-multiply alpha, canvas does not)

for reference :
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by parasyte** [comment]
These might be doable with a fragment shader in WebGL. Most of them will require reading contents of the frame buffer, which adds overhead, and could be prohibitively expensive with complex scenes.

**Comment by obiot** [comment]
yeah but I was actually thinking about something more simple before going full steam, a bit like what pixi was supporting in the early 1.x releases (with basically a add and mulitply blend mode)

**Comment by parasyte** [comment]
Pretty sure that's going to need a shader. There are a bunch of weird blend mode things you can do, but really none of them make sense expect premultiplied alpha.

**Comment by obiot** [comment]
couple of interesting links :
http://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html
http://www.zovirl.com/2012/08/24/webgl_alpha/

**Comment by obiot** [comment]
this is mostly done and I'm happy how it is working for now. Definitely can be improved in the future, but I'm closing this ticket for now
