### ISSUE TITLE
viewport effect reset or nothing

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#790]
Hi Guys,

small question here : in my current game I use a lot the shake and fade effects, and I realized that the current implementation is not really friendly with it,

As for now, if you call the shake of fade function, when a similar "effect" is already running, nothing will happen, when in my opinion, the new call should rather stop the current effect. what do you think ?

**Comment by parasyte** [comment]
@obiot These effects (fade and shake) are not mutually exclusive, it's reasonable to allow them to run simultaneously. We should support that.

On the other hand, there is no good reason to allow multiple shake effects run simultaneously, or multiple fade effects. But up to one of each running in any combination/duration/phase is acceptable.

**Comment by obiot** [comment]
i'm more talking about requesting for a fading efffect when a fade effect is already running.  For example in my infinite runner,  i have meteor crashing randomly on the level, and at each crash I add a small shake and fade effect to better simulate the explosion/crash.

Now when my player dies, i also use a "big" shake and fade effects when it explodes into particles, but if that happens right when a meteor just crashed, then this second call is just ignored (since each of the effect are already runnning) and that's quite annoying. 

So hence my question, what would be the best solution to manage this ? systematically overwrite, or ,maybe add an additional parameter to `shake` and `fade` that indicate to stop the previous one ?

**Comment by parasyte** [comment]
Yeah, that's the conflict. I am not sure it makes sense to allow two fades to run at the same time... Technically we could do it with another color layer and tween for each effect instance. The shake effect I guess could also be doable, if we had additional tweens again... We would probably want to use the midpoint (average) intensity, or even make it additive.

It's just unclear to me which behavior is expected:

* One effect at a time
  * First effect wins (current implementation)
  * Last effect wins
* Allow all effects requested

**Comment by obiot** [comment]
yep, so a way to let the user manage this choice is definitely a better option, by adding a `force` parameter to all function ? (it `true` last effect wins, else the first wins)

**Comment by obiot** [comment]
by the way, I thought as well to redo the effect implementation and to use a Color Layer object, that would be much cleaner and would allow to multiply effects, but in the context of this 3.1 version I want to keep it more simple :P

**Comment by obiot** [comment]
if you guys don't have any strong opinions, i'll go for the `force` flag then :)

**Comment by parasyte** [comment]
Sounds good. I'll create the followup ticket for a major bump.

**Comment by obiot** [comment]
I'm giving up on this one ! it was pretty easy for `shake` but implementing the same for fadeIn/Out triggers a lots of code changes to address side-effects or unforeseen race-condition due to stopping/resetting/restarting the same tween. and this defeats the purpose of a simple flag/minor modification. 
 
Same time would be better spend in a better/proper implementation as described in #791 

therefore closing this ticket.
