### ISSUE TITLE
Inconsistent viewport follow

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#798]
Hi,
I'm trying to implement moving around the loaded level using a pointer. For this to work I'm using pointer events which update a Vector2d, and I pass it down to viewport.follow:

        onResetEvent: function() {
                function stopDrag() {
                    this.pointerDown = false;
                };

                this.state = {
                    position: new me.Vector2d()
                };

                this.pointerDown = false;
                this.pointerMove = new me.Vector2d();

                this.cameraSpeed = 1;

                me.input.registerPointerEvent("pointerdown", me.game.viewport, (function(event) {
                    this.pointerDown = true;
                    this.pointerMove.set(event.gameX, event.gameY);
                }).bind(this));

                me.input.registerPointerEvent("pointerup", me.game.viewport, stopDrag.bind(this));
                me.input.registerPointerEvent("pointerleave", me.game.viewport, stopDrag.bind(this));
                me.input.registerPointerEvent("pointercancel", me.game.viewport, stopDrag.bind(this));

                me.input.registerPointerEvent("pointermove", me.game.viewport, (function(event) {
                    if (this.pointerDown) {
                        var pos = new me.Vector2d(event.gameX, event.gameY);

                        var pointerDelta = new me.Vector2d(pos.x, pos.y);
                        pointerDelta.sub(this.pointerMove);
                        pointerDelta.scale(this.cameraSpeed);

                        this.pointerMove.copy(pos);

                        this.state.position.add(pointerDelta);
                        this.state.position.clampSelf(0, Infinity);

                        console.log(this.state.position);
                        console.log(me.game.viewport.pos);
                    }
                }).bind(this));

                me.game.viewport.setDeadzone(0, 0);
                me.game.viewport.follow(this.state.position);
            },

Unfortunately, the viewport.pos has values which are in no way consistent with local position. Console logs show that local position is updated correctly, but viewport has it offset by some unexplained value, and doesn't register all moved. Note: the deadzone is set to 0.

I've also tried using viewport.moveTo() and it sent the position correctly, but the view isn't redrawn.

**Comment by parasyte** [comment]
A few things to note;

* `me.viewport.follow` puts the center of the viewport on the given position.
* `me.viewport.moveTo` puts the upper left corner on the given position.
* You will need at least one object in your scene to return `true` from its update method if you want the viewport to redraw. Or you can call `me.game.repaint()`.

You probably don't want the follow function, unless you're ok with the viewport being centered on the position you give it. This is of course very useful for following game characters and such, but probably not the right thing for scrolling around a scene.

If you want to continue using it, though, you may find it useful to follow a normal sprite, so you can at least visualize how it's working. This will especially be important when the sprite gets close to the world boundaries; the viewport will not leave the boundary, but the object it is following might!

**Comment by krojew** [comment]
That would explain the inconsistencies. I was basing on the official docs, which don't explain the difference between those two methods.

**Comment by obiot** [comment]
indeed, you are right, this is not really clear from a documentation point of view, thanks for highlighting that !

**Comment by obiot** [comment]
@see https://github.com/melonjs/melonJS/commit/997a13c4362e37c1aa2b5b27de7b6a568d235125
