### ISSUE TITLE
regression after `Fix for getting parent node dimensions`

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#801]
@krojew
@see the #799 PR.

behavior when rescaling the window as changed, for example the platformer does not seem to react anymore to window height changes.

Before/After Screenshot (left side is the online platformer example, right side using the master build) :
![image](https://cloud.githubusercontent.com/assets/4033090/17237703/5ac33ab0-5587-11e6-9625-1e85d2916aad.png)

**Comment by krojew** [comment]
This bug manifested because the parent dimensions started to actually work. Before the change the code to get max dimensions:

```
var _max_width = Math.min(maxWidth, parentNodeWidth || window.innerWidth);
var _max_height = Math.min(maxHeight, parentNodeHeight || window.innerHeight);
```

was always getting undefined as parentNodeWidth and parentNodeHeight, so it took the whole window size. Now, the platformer demo creates a canvas with explicit 600 height, so _max_height becomes smaller than before. That in turn causes the screenRatio to change and the whole game viewport is resized to different size.

I just tested the results and the game wishes to scale to 1920x600 on a full hd screen, which is correct, as far as width is concerned.

**Comment by obiot** [comment]
indeed, I change the video init to specify a 0 size canvas, and it works as previously as well
`me.video.init(0, 0, {wrapper : "screen", scale : "auto", scaleMethod : "flex-width" });`

**Comment by obiot** [comment]
now that I'm giving a second thought, it's then maybe a bug in the `flex` mode implementation, as it's supposed to fit with the display.

see this blog entry that better describes the current scaling mode we have :
http://blog.melonjs.org/2015/02/shine-get-resolution-independence.html

**Comment by krojew** [comment]
According to the blog entry:

> Along the same lines, flex-width keeps a constant height (600) and grows or shrinks the width to fit the display. In this case, you get to see more of the level, while you still see the same amount of sky as the original image.

The fixed behavior seems to be correct - the width get scaled to fit the display, while the height is indeed constant. This is exactly how the blog explains it. Previously your height would scale too, which did not conform to the flex-width specification.

**Comment by parasyte** [comment]
The intention with the flex modes is that the canvas is given a size that the designer intends, like 1200x1600, or 1024x768, and melonJS figures out how to best fit *that design size* into the available space. Setting the design size to 0x0 does not make any sense; who would want a game that is designed to run at 0x0 screen resolution?

There is probably a non-obvious issue with the container getting a new size based on its child's size (whose size is based on its parent's size). Sounds like a recursive mess.

**Comment by krojew** [comment]
0x0 makes no sense, indeed. But, basing on that blog post, I think the flex-width mode works correctly now. In platformer, the width got resized to available space, and height was kept constant. I think the issue is not with the corrected behavior of flex-width, but wrong scaling method chosen for platformer.

**Comment by parasyte** [comment]
"Consistent height" is in respect to "non-scaled height", though. The designer wants the screen height to be 600px but that does not mean the display must be exactly 600px high. It just that the inner contents are 600px, and the screen is allowed to scale while maintaining the expected inner height. The previous behavior was actually the expected behavior, based on this understanding of "consistent height".

**Comment by krojew** [comment]
That is possible, I only know the reasoning behind it through the blog post. The description for this mode states:

> Along the same lines, flex-width keeps a constant height (600) and grows or shrinks the width to fit the display.

Now, the height is kept constant and the width is resized to fit the display - exactly as quoted. So either both the blog post and the algorithm are wrong now, or everything works as intended.

**Comment by parasyte** [comment]
It's just a misunderstanding of semantics; I wrote both the code and blog post. Hint: `flex` only works with auto-scale enabled. If it's not auto-scaling the height, it's broken.

**Comment by obiot** [comment]
@parasyte can you maybe quickly help with this one then ? since you wrote the original scaling code ? :)

**Comment by parasyte** [comment]
I'll see what I can do. The recursive resize is probably related, however; since #799, the parent now has an exact size, where previously we were allowing the parent to stretch up to any configured maximum size.

**Comment by obiot** [comment]
to be honest, i'm not sure i'm actually following you and yo are saying that this is recursive issue ... :)

**Comment by obiot** [comment]
:P

**Comment by obiot** [comment]
@parasyte did you have the time to have a quick look at this one ?

**Comment by parasyte** [comment]
Nope. On vacation for a few weeks 😬

**Comment by obiot** [comment]
@parasyte back from holiday ? :):):)

**Comment by obiot** [comment]
ok, so until we find a better fix that does not introduce a regression on the flex behavior, i'v reverted the related PR :
https://github.com/melonjs/melonJS/commit/3679c0c0b96e3930187bdaada8b7c8da0296a9c1

**Comment by krojew** [comment]
Any update on this one? It's really hard to get melon look right without that PR.

**Comment by obiot** [comment]
not really.... I would suggest that you modify it for now in your own project.

you don't need to actually modify melonJS, as you can use the patch feature to modify the `onresize` function, see the related documentation here :
https://melonjs.github.io/melonJS/docs/me.plugin.html#patch

basically it would be something like adding this in your game initialization  :
```` javasript
// redefine the me.video.onresize function with a new one
me.plugin.patch(me.video, "onresize", function () {
   // copy paste the original function from, adding required modification in the code
   // https://github.com/krojew/melonJS/blob/43b59d6d29536c9fd9ea9a91d3fe2df9eb4c505d/src/video/video.js#L349-L457

});
````

**Comment by krojew** [comment]
Since the current behavior is supposed to be the desired one (which I find strange, since it works like my patch if you have Ejecta, but totally different otherwise), maybe we should add another scaling method which properly handles parent dimensions?

**Comment by obiot** [comment]
I like that idea ! but instead of adding an additional setting (that specify what to do wrt to the parent), instead of adding scaling modes ?

**Comment by krojew** [comment]
An additional setting might also be a good idea - that way other scaling modes might potentially benefit from it.

**Comment by obiot** [comment]
for sure it's great if you have the time to work on a PR :) we can then review/comment it and then merge it when we are all happy about it :)

for the new flag, just make sure that the default value matches the current behaviour.
