### ISSUE TITLE
Layers having visible==="0" are still visible

### ISSUE THREAD

**Issue by Ld00d** [melonjs/melonJS#802]
When setting visibility on a layer to "0" (as the Tiled editor does), the layer remains visible.

The problem appears to be here:

`            // layer opacity
            var visible = typeof(layer.visible) !== "undefined" ? layer.visible : true;
            this.setOpacity(visible ? +layer.opacity : 0);
`

If layer.visible === "0" it won't be falsey because it's a string with content. The simplest fix could be to coerce visible into a number:

`            // layer opacity
            var visible = typeof(layer.visible) !== "undefined" ? layer.visible : true;
            this.setOpacity(+visible ? +layer.opacity : 0);
`

I could make the change and submit a PR if you like.

**Comment by parasyte** [comment]
Nice find!

According to [TMX format docs](http://doc.mapeditor.org/reference/tmx-map-format/#layer), the value (if defined) should only be "0" or "1". The coercion should happen prior to assignment, and use the correct data type regardless:

```javascript
var visible = typeof(layer.visible) !== "undefined" ? +layer.visible : 1;
this.setOpacity(visible ? +layer.opacity : 0);
```
