### ISSUE TITLE
How can I position the hitbox?

### ISSUE THREAD

**Issue by BookOwl** [melonjs/melonJS#805]
It seems that the center of the hitbox defaults to the center of the sprite frame. How can I change the position of the hitbox to something else?

**Comment by obiot** [comment]
you can change the anchorpoint to change the hitbox default alignement, see the platformer where both are aligned at the bottom :
https://github.com/melonjs/melonJS/blob/master/examples/platformer/js/entities/player.js#L58-L59

also closing, as this is not an issue, for question/support please rather use the forum:
https://groups.google.com/forum/#!forum/melonjs

**Comment by BookOwl** [comment]
OK, thanks! Sorry about not using the forum - will do that in the future.

**Comment by agmcleod** [comment]
No worries! Glad we were able to give you a hand regardless. We try to keep more help stuff in the forum to not clutter the issues up to much, but don't  be afraid to submit one if you think there might be a bug.
