### ISSUE TITLE
ES6 Collections tests are failing under Jasmine 

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#810]
this only happen when running the test in the browser (by executing  the test [index.html](https://github.com/melonjs/melonJS/blob/master/tests/index.html) file).
- **ES6 Collections test Map#set** : 
  - _Expected true to equal false._
  - _Expected Function to be undefined._
  - _Expected Object({  }) not to equal Object({  })._
- **ES6 Collections test Map#forEach with mutations** :
  - _Expected undefined to equal '[1,3,0]'._

the reason being that the es6 collections is deprecated and not fully aligned anymore with the standard : https://github.com/WebReflection/es6-collections 

> This  is a very old polyfill which served old browser decently for the last 4+ years. I am not actively maintaining this project but I would eventually accept PRs if you really need to use it.
> 
> Please have a look at better alternatives such [ES-Shims](https://github.com/paulmillr/es6-shim)

Solution(s) :
- push a PR, a modify our local version ?
- change for a more up-to-date shim ?
- dont'do anything, this is not impacting melonJS itself, and at some point we should be able to remove the shim ?

**Comment by parasyte** [comment]
Solution: Remove the polyfill in #829 :) `Map` is now supported in all the browsers we target!

**Comment by obiot** [comment]
as much as I agree with you on the rest (#829), i'm not sure this is yet ready to be removed for mobile browser, and especially Android 5.0 and lower :
http://kangax.github.io/compat-table/es6/#test-Map

not a problem on IOS though, as most of the installed based has migrated already
