### ISSUE TITLE
further clean-up `me.Sprite`

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#815]
@parasyte @agmcleod 

I was looking at further cleaning `me.Sprite`, and I'm not sure what I want to do with the followings :
* flipX : internally call this.scale(-1, 0), marked as deprecated
* flipY : internally call this.scale(0, -1), marked as deprecated
* scale : scale the sprite object, marked as deprecated
* scaleV : scale the sprite object, marked as deprecated

So I have the following ideas, and I don't know which to pick :

1. keep them there for now but mark them as deprecated
2. move them to me.Renderable, as they are anyway agnostic to the kind of renderable implemented since they now rely on the renderable transformation matrix
3. implement flip on the matrix object (including these `lastflipX/Y flag), and free the renderable or sprite object from them.

**Comment by parasyte** [comment]
I vote for choice 1. I never was a big fan of having multiple ways to do the same thing. **DRY**. ;)

Also, isn't the matrix the ultimate source of truth for transformations? E.g. `this.scale()` is just a convenience function for a matrix transformation ... then we also have a convenience function for `scale(-1)`? 😝  **WET**; Write Everything Twice.

**Comment by agmcleod** [comment]
To be fair, the flip is a convenience function around scale, and a descriptive one at that. Likewise with scale being an application to transformation. I'm alright with removing flip if you prefer, but you can't take away my scale!

**Comment by parasyte** [comment]
Teehee! I wasn't suggesting deprecating `scale`. But now that you mention it ... 😉

**Comment by obiot** [comment]
indeed, `sprite.scale` is just a convenient method for `sprite.currentTransform.scale`, and its only purpose now is to provide backward compatibility

**Comment by obiot** [comment]
ok, so this is what i'm going do :
- keep `flipX/Y` in me.Sprite, and as deprecated
- move the `scale` functions one level up in `me.Renderable`, as these are redefining the ones defined in the original shape objects, and it actually does not make sense, in terms of API consistency
 to have them redefined "only" in me.Sprite, and not in `me.Renderable`.

**Comment by parasyte** [comment]
@obiot I started removing some deprecated stuff (since there was a major version bump) and I came across this ticket. Do we want to remove the `flipX` and `flipY` methods from Sprite now? Maybe move them to Renderable ... And update the examples and tutorials, of course.

@agmcleod Any thoughts as well?

**Comment by agmcleod** [comment]
Going to a major version it makes sense to me :)

**Comment by obiot** [comment]
my initial idea was to completely remove `flipX` and `flipY`, but it seems that this is a popular features, so maybe we should just move it to me.Renderable. It's still a nice utility function anyway when you are manipulating sprites :)
