### ISSUE TITLE
[CR] Observable Vector class callback not practical 

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#816]
today, both the `me.ObservableVector2d` and `ObservableVector3d` are made in a way where we first trigger the callback, and then only set the values :
https://github.com/melonjs/melonJS/blob/master/src/math/observable_vector2.js#L71

this is causing me some headaches while trying to remove the unnecessary bounds object from me.Renderable, as typically what is happening is the following :
- the renderable position is updated
- the vector callback is triggered
- within the callback i set the renderable position using the new value and the parent position (if defined)
- the vector is then updated with the new position

the issue being of course the last point, as the coordinates I set with the ancestor one are just erases/rewritten in the original vector setter (and thus without taking in account the additional parent position).

not sure i'm clear, but i would like is to change from this 

``` javascript
        _set : function (x, y) {
            this.onUpdate(x, y, this._x, this._y);
            this._x = x;
            this._y = y;
            return this;
        },
```

to this :

``` javascript
        _set : function (x, y) {
            this._x = x;
            this._y = y;
            this.onUpdate(x, y, this._x, this._y);
            return this;
        },
```

also, do we really need all 4 or 6 parameters when calling the callback ? in my opinion only the new values are useful, I might be wrong, but I did not see any code using the "old" one

**Comment by obiot** [comment]
@agmcleod @parasyte

**Comment by obiot** [comment]
oh, i just realized that `ObservableVector2d` is actually not used at all anymore in melonJS ! anyway just saying, still can be useful for developers.

**Comment by parasyte** [comment]
If you make that change, you won't be able to observe the delta between new and old. The code is currently written so that observers can use either the "new" or "old" values without calling the getters (since both are passed as arguments to the callback).

Honestly, I would prefer using the callback return value as an indicator for updating the coordinates. Your callback should not be touching the private properties `_x`, `_y`, `_z` ... And it looks like that's the only way you could be getting into the described situation. Using the callback return value would be much cleaner.

If instead you're using the setter within the update callback, that sounds like a recursive disaster waiting to happen...

**Comment by obiot** [comment]
what kind of use case do you have in mind, where you need to track the old value ?

so what you say is that rather than changing the way I described it, the callback should rather returns a boolean (for example) that prevent the original setter for setting the new x/y/z values ? that could work too actually.

**Comment by obiot** [comment]
i think i'm gonna postpone the whole "remove renderable unnecessary bounds" stuff for this release, as it has too many ramification (the further deep I go, the more required changes I discovered), and rather focus on improvements required for that one in this release. This said, it might also come for free at the end :)

**Comment by parasyte** [comment]
I was actually thinking something like ...

```javascript
_set : function (x, y) {
    var updated = this.onUpdate(x, y, this._x, this._y);

    // Use the updated coordinates from callback instead of the x and y inputs
    if (updated && 'x' in updated && 'y' in updated) {
        x = updated.x;
        y = updated.y;
    }

    this._x = x;
    this._y = y;

    return this;
},
```

**Comment by obiot** [comment]
me like it ! :)

**Comment by obiot** [comment]
the only thing though is that you create an object every single time... 

what I had in mind reading your comment was rather something like :
````javascript
_set : function (x, y) {
    if (this.onUpdate(x, y, this._x, this._y) !== false) {
        this._x = x;
        this._y = y;
    }
    return this;
},````

then the callback itself is free to set any values it want (it can use `setMuted` to prevent recursivity)

**Comment by parasyte** [comment]
I'm a little spoiled by ES6, where destructuring assignments are first-class, so will receive engine optimizations:

```javascript
_set : function (x, y) {
    { x : this._x, y : this._y } = this.onUpdate(x, y, this._x, this._y) || { x, y };
    return this;
},
```

No fuss, no muss. 😁 It's like the language *wants* temporary objects.

**Comment by obiot** [comment]
wait, does this kind of assignement works ? (in ES5 mode?)

then the callback becomes something like that ? :
````javascript
UpdateBoundsPos: function (newX, newY) {
    if (this.ancestor) {
        return { newX + absPos.x,  newY + absPos.y }
    } 
},
````

**Comment by parasyte** [comment]
It's ES6 syntax. But yeah, that's pretty much the whole callback... You still need to define the object keys `x` and `y` ... Or return and destructure an array if you don't care about the keys.

**Comment by obiot** [comment]
ok so in ES5 syntax, and trying to avoid temporary object creation, probably something more like the following :
````javascript
_set : function (x, y) {
    var ret = this.onUpdate(x, y, this._x, this._y);
    if (ret && 'x' in ret && 'y' in ret ) {
        this._x = ret.x;
        this._y = ret.y;
    } else {
      this._x = x;
      this._y = y;
   }
   return this;
},
````
