### ISSUE TITLE
transformation bug in webgl mode

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#818]
how to reproduce it :
- launch the platformer example, adding `#webgl` to the URL to force the use of the wegl renderer.
- move the player to the right, then to the left, the position is then offset incorrectly i'd say by the size of the sprite itself.

I think the issue is maybe in the `me.Matri2d.multiplty` function, as this is the only one used by the webgl renderer.

**Comment by obiot** [comment]
well i just made a quick test and replaced our multiply implementation from the one from gl-matrix :
https://github.com/toji/gl-matrix 
````javascript
        /**
         * multiply both matrix
         * @name multiply
         * @memberOf me.Matrix2d
         * @function
         * @param {me.Matrix2d} b Other matrix
         * @return {me.Matrix2d} Reference to this object for method chaining
         */
        multiply : function (b) {
            b = b.val;
            var a = this.val,
            a00 = a[0], a01 = a[1], a02 = a[2],
            a10 = a[3], a11 = a[4], a12 = a[5],
            a20 = a[6], a21 = a[7], a22 = a[8],

            b00 = b[0], b01 = b[1], b02 = b[2],
            b10 = b[3], b11 = b[4], b12 = b[5],
            b20 = b[6], b21 = b[7], b22 = b[8];

            a[0] = b00 * a00 + b01 * a10 + b02 * a20;
            a[1] = b00 * a01 + b01 * a11 + b02 * a21;
            a[2] = b00 * a02 + b01 * a12 + b02 * a22;

            a[3] = b10 * a00 + b11 * a10 + b12 * a20;
            a[4] = b10 * a01 + b11 * a11 + b12 * a21;
            a[5] = b10 * a02 + b11 * a12 + b12 * a22;

            a[6] = b20 * a00 + b21 * a10 + b22 * a20;
            a[7] = b20 * a01 + b21 * a11 + b22 * a21;
            a[8] = b20 * a02 + b21 * a12 + b22 * a22;
        return this;
    },
````
and the result is exactly the same (even pass our test suite), so it does not look like being the issue here...

**Comment by obiot** [comment]
@parasyte i could use your lights here, i'm completely in the dark :P

**Comment by parasyte** [comment]
Write 0 here to apply the same (broken) behavior to canvas renderer: https://github.com/melonjs/melonJS/blob/7582d7060ae9a4daca20c4cd7fa5471cea6c3954/src/renderable/sprite.js#L546

Looks like the `me.Matrix2d.translate()` doesn't work as expected.

Compare:

* [`glMatrix.mat2d.translate`](https://github.com/toji/gl-matrix/blob/b5484842918f87917d5997ba7dc12d3b884cfcd0/src/gl-matrix/mat2d.js#L256-L274)
* [`me.Matrix2d.translate`](https://github.com/melonjs/melonJS/blob/8b3d5c2d76ee461dc858ea5aa3d0955342142bfb/src/math/matrix2.js#L254-L270)

Shortcut hack looks wrong.

**Comment by parasyte** [comment]
Should add a unit test, but this fixes it:

```patch
diff --git a/src/math/matrix2.js b/src/math/matrix2.js
index aca7bfd..a4da352 100644
--- a/src/math/matrix2.js
+++ b/src/math/matrix2.js
@@ -263,8 +263,8 @@
         translate : function (x, y) {
             var a = this.val;

-            a[6] += x;
-            a[7] += y;
+            a[6] += a[0] * x + a[3] * y;
+            a[7] += a[1] * x + a[4] * y;

             return this;
         },
```

**Comment by obiot** [comment]
mystery solved ! thanks Jason :)
