### ISSUE TITLE
Object.extend incorrecly extends objects

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#821]
Let's consider a typical inheritance in JS:

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A() {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        _super.apply(this, arguments);
    }
    return B;
}(A));

/*
    Equivalent to:

class A
{
}

class B extends A
{
}
*/
```

Unfortunately, melon doesn't really support this and uses its own mechanism. This leads to problems:

`var C = me.Entity.extend(B);`

We could assume C now inherits me.Entity and both B and A. Turns out it's missing anything from B and A. Let's change it:

`var C = me.Entity.extend(A.prototype);`

Now we have both Entity and A. So far, so good.

`var C = me.Entity.extend(B.prototype);`

And now we have Entity extended with B, but not A. There's no way to actually make this work in a normal way where you can simply write 'this.something();' from B and it will call something() in A. You have hack around with some "_super" field, which is extremely dirty. Why not incorporate the simple extension mechanism, as shown at the beginning (which actually works without any hacks)?

**Comment by krojew** [comment]
Tried another approach:

`var C = me.Entity.extend(A.prototype, B.prototype);`

This is extremely awkward, but solves one problem - C sees methods of both A and B. But, of course, another thing stopped working:

```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var A = (function () {
    function A() {
    }
    return A;
}());
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        _super.apply(this, arguments);
        this.member = 1;
    }
    return B;
}(A));

/*

    Equivalent to:

class A
{
}

class B extends A
{
    member: number = 1;
}
*/
```

C has no access to 'this.member'.

**Comment by parasyte** [comment]
The second approach is the right way to do "multiple inheritance" patterns with [jay-extend](https://github.com/parasyte/jay-extend);

But there's a problem with your ES2015 class descriptor for `B`: It needs a `constructor` to apply default properties like `member` (ignoring the syntax error). See: http://www.ecma-international.org/ecma-262/6.0/#sec-class-definitions

The second issue is that jay-extend does not compose correctly with ES2015 classes [because it predates any implementation I'm aware of]; the `init` constructor does not automatically call `constructor` on any of the inherited classes. This was an exercise left to the end-user, by calling `this._super()`. Unfortunately, the ES2015 `constructor` requires that it is called only with the use of the `new` operator. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

As a result, the only workaround is something like this following:

```javascript
class A {}

class B extends A {
    constructor() {
        super();
        this.member = 1;
    }
}

const C = Jay.extend({
    'init' : function () {
        // Workaround epic fail with ES2015 classes
        const b = new B();
        Object.keys(b).forEach((key) => {
            this[key] = b[key];
        });
    }
}, B.prototype, A.prototype);

console.log(new C()) // Jay { member: 1 }
```

**Comment by krojew** [comment]
The sample class equivalent isn't JavaScript - I wrote it only for explanation (it's TypeScript actually). Nevertheless, ES2015 has nothing to do with the issue that we have strangely done inheritance. The first code fragment is how to do inheritance in JS correctly, without the need for _super. Is there any change for Object.extend to support both methods? I think (but I haven't checked) it's possible to have both by extending and injecting init and _super symbols. That way we can have the best of both worlds (or rather inheritance + backwards compatibility).

**Comment by agmcleod** [comment]
There were some concious decisions around it all, as we wanted to keep a fairly similar API to what we had before with John Resig's inheritance implementation. But also wanted to improve on the parts it fell short. The inheritance model we have now is where we landed. Jay talks about the why a fair bit in this article here: http://blog.kodewerx.org/2014/03/melonjs-should-be-all-about-speed.html

**Comment by krojew** [comment]
That blog post pretty much summarizes why current implementation is better than a similar one. Ok, I don't claim otherwise. The problem is - it has problems with normal prototype-based inheritance. I don't wish to argue which method is better, although numbers would trivially prove which is, but:

1. Given prototype inheritance is a language feature, it is more natural and it's more common.
2. Upcoming classes will prove problematic.
3. Modern languages which are transpiled to JS, like TypeScript, abstract away inheritance by using the best method available, which usually is prototypes.

I claim this is a problem in melon. I think both can be used at the same time, and I think this is something worth considering for performance and future-proofness.

**Comment by agmcleod** [comment]
I agree with all your points for sure. I'd like to move towards using something like babel in the near future, maybe webpack as well to have a faster build system (ive found it to compile faster to changes over grunt watch). That way we can standardize things a bit more, and have less parts like language features need to be maintained by us. Just not something I want to dive into right now. To setup both the build, and start using proper commonjs modules would require some good effort.

**Comment by krojew** [comment]
If you want to do a major refactor, I suggest dropping JS altogether and using TS - you get all the benefits of a type-safe language with built in module/inheritance support. While creating TS typings for melon, I already found several problems inside, which the compiler picked up. Also, you wouldn't need Object.extend anymore :)

**Comment by parasyte** [comment]
I would propose that the "correct" way to do inheritance is with ES2015 classes. 😃 I'm not about how the rest of the team feels about transpilation tools like Babel (to continue supporting older user agents). But my personal thoughts go like this:

1. Transpilation is a good way to build an ES5 application using ES2015+ grammar, but a very bad way to build ES2015+ applications.
  * Transpiling classes generates ES5, even if the user agent supports classes natively. :cry:
2. We have a hard requirement on the user agents we support, so moving to ES2015 means we *have to transpile* the code.
3. Going down this route would keep us "vendor locked" on the transpiler for the foreseeable future. We'll miss out on any performance improvements that are natively available in the UA.

Whatever the case with transpilation, my gut says we need to adopt native ES2015 as a first class language. The time for it *might* actually be right, if we can justify that the next major melonJS version only supports Edge 13+ and Safari 9+ which are both about a year old.

... IMHO

**Comment by krojew** [comment]
That might really be an argument to switch to TS. Just put a flag which JS version you want to transpile to and you're done. You can transpile the same code to old and new JS versions for people with older and newer browsers without hanging anything in your code. And you won't need Babel at all.

**Comment by agmcleod** [comment]
> Whatever the case with transpilation, my gut says we need to adopt native ES2015 as a first class language. The time for it might actually be right, if we can justify that the next major melonJS version only supports Edge 13+ and Safari 9+ which are both about a year old.

I can agree with that. The browsers really are stepping up in this regard. Though are we also really stuck in to a vendor? Couldn't we strip out babel from the process?

**Comment by parasyte** [comment]
> And you won't need Babel at all.

Right, we'll just need Typescript, instead. It's just a different Koolaid.

**Comment by krojew** [comment]
> Right, we'll just need Typescript, instead. It's just a different Koolaid.

What I meant was - you won't an extra step which transpiles the same thing (JS) into the same thing (JS), just because JS is a mess. Let the compiler handle proper JS version, along with modules etc. in a single pass.

Small rant: we are now in a place with JS where you need a ton of steps to create a single usable thing. The less of those you have, the better. Better to have one codebase with one compiler which can automatically create all flavors of JS anyone would ever need. Personally, I believe every once in a while JS makes one step towards being a modern language, while taking two steps back in terms of actually making anything useful.

**Comment by krojew** [comment]
Another problem with Object.extends - it doesn't always work with instanceof. There's no way to make it work with the use case I described; when inheriting multiple classes.

**Comment by obiot** [comment]
see #915 , this will be addressed in the next major milestone with ES6 class definition/usage
