### ISSUE TITLE
base64 format loading

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#822]
I had this idea of using a bitmap font to fix the debug panel in WebGL mode (see #593), but we have no proper way of adding a base64 encoded asset into the loaded asset pool, and that's especially a problem for the `.fnt` one (standard image is not really an issue)

for reference :
https://melonjs.github.io/melonJS/docs/me.loader.html#load

maybe we could add a `format` type on top of the `type` one to indicate when the format is not native but encoded into something else like base64 ?

**Comment by parasyte** [comment]
AFAIK, [Data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) are already supported by all platforms we care about. There's probably no need to special-case support for it, just provide the full URI and specify that it uses base64 encoding.

**Comment by obiot** [comment]
indeed :
https://github.com/melonjs/melonJS/blob/master/plugins/debug/debugPanel.js#L149
https://github.com/melonjs/melonJS/blob/master/plugins/debug/debugPanel.js#L216-L217

but I was rather meaning something that would allow directly add this in the available asset pool, as when it is preloaded.

**Comment by parasyte** [comment]
Yeah that's what I meant too. We just need to allow full URIs (opposed to only relative paths, as today) and we get it "for free", no?

**Comment by obiot** [comment]
correct :)

**Comment by parasyte** [comment]
Is there anything to do here, then? https://jsfiddle.net/mj2zovwh/2/

**Comment by obiot** [comment]
lol, no nothing indeed :)
