### ISSUE TITLE
glitch on some Font when drawing space (0x20) character using a BitmapFont

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#823]
Not sure if it's a bug or a regression (as I'm not sure this was there before), but as you can see from the following screenshot, our BitmapFont class has some troubles rendering some font space characters :
![image](https://cloud.githubusercontent.com/assets/4033090/19672030/d7ca57a6-9aa5-11e6-9981-78b9e7905213.png)

it does not appears to be the case with all fonts, here only the [arialfancy](https://github.com/melonjs/melonJS/blob/master/examples/font_test/arialfancy.fnt) font exhibits the issue, while the [xolo12](https://github.com/melonjs/melonJS/blob/master/examples/font_test/xolo12.fnt) one is fine.

also after a bit of debugging the issue seems to be more on the drawing side, as the [`_createSpaceGlyph`](https://github.com/melonjs/melonJS/blob/master/src/font/bitmapfontdata.js#L52-L71) function seems to be working just fine and setting a proper (?) width and height value when `0`.

**Comment by obiot** [comment]
ok I got it I think, the issue comes where font are packed, and therefore the space character having a width of 0. Which we then change internally to fake it to a proper value, and then render the character like any other (which then has incorrect offset, and draw a part of the first one, like visible here).

Not sure how to do this properly, expect from adding a test for the space character though.

**Comment by obiot** [comment]
job done (explanation in the commit) ! 

@agmcleod can you test on your side as well ? for me it's all working fine.

**Comment by agmcleod** [comment]
Nice :). I'll check it out.
