### ISSUE TITLE
me.Sprite internal/private data clean-up

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#824]
Following the merge of me.Sprite and me.Animation, it would be nice as well to review a bit how we store the animation definition data within a me.Sprite object.

today it's working just fine, but it could greatly be optimized and written a bit better (cleaner).

typical issue, where I don't know what is happening :
https://github.com/melonjs/melonJS/blob/master/src/renderable/sprite.js#L378

**Comment by adrianhartanto0** [comment]
Mind elaborating of what you have in mind? @obiot

**Comment by obiot** [comment]
the way the animation data (frame index, etc...) is stored in the sprite object needs a good clean-up/rewrite. 

There are some quick hacks to make it working, see here for example :
https://github.com/melonjs/melonJS/blob/master/src/renderable/sprite.js#L412-L425

**Comment by adrianhartanto0** [comment]
Looking through the src, I saw the the `this.current` is rather redundant as there is already `this.anim`. To replace the this.current, I thought of just keeping only the name of current animation frame. So any modification to `this.current` such as in `setAnimationFrame` will just modify the `this.anim[currentAnimationName]` @obiot

**Comment by obiot** [comment]
yes, most probably some redundant stuff there :)

**Comment by obiot** [comment]
note that `this.anim` is supposed to contains all the index/delay of a given animation (defined through setAnimation), while `this.current` only contains the current frame to be displayed

**Comment by adrianhartanto0** [comment]
@obiot Sorry I submit another commit without reading you comment in here. So my commit isn't suitable?

**Comment by obiot** [comment]
this was done it 5.0
