### ISSUE TITLE
Replace JSHint with ESLint

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#828]
a) It's way better
b) Editor support is quite good around eslint.

**Comment by parasyte** [comment]
:+1: times a million billion.

**Comment by obiot** [comment]
turning the following one "on" (`indent": [2, 2, { "SwitchCase": 1 }],`)
https://github.com/melonjs/melonJS/blob/master/.eslintrc.json#L62

generates a billion errors.... either i did not figure out how to set it properly, or all our code is not correct..

but time to go home for today, if you guy want to give it a try, feel free :)

else, eslint really has countless non-enabled options for now (compared to jshint)

**Comment by obiot** [comment]
don't forget to run a `npm update` !
