### ISSUE TITLE
No way to iterate over container children

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#830]
Hi,
I think I noticed some functionality missing in me.Container - you cannot iterate over children. The inner collection is not exposed in the API. You could _potentially_ use getChildAt(), but the container doesn't expose its size either. So the only way now to work around it, is to call getChildAt() until an exception is thrown. Pretty awkward, if you ask me. Or, given how terrible JavaScript is, you could tap into the inner collection, despite it being non-public, which is even more awkward and error-prone.

Why is it important? Example use case: check which child is at specified coordinates - no clean way of doing it at the moment.

**Comment by obiot** [comment]
that's indeed something missing, thanks !

**Comment by obiot** [comment]
note that you can use the getChildByType() function to retrieve all the Entity objects or even Renderables.

as `me.game.word.getChildByType(me.Renderable)` should actually returns all the object derivating from `me.Renderable`.

what would nice though to add is some iterator function to allow something like :

```javascript
me.game.world.iterator(function (child) {
    // do something with the child
});
```

**Comment by obiot** [comment]
actually rather a forEach style of function (rather than an "iterator") :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by obiot** [comment]
done ! (on the master branch though)
