### ISSUE TITLE
Renderable bounds do not respect anchor point

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#833]
When trying to get the bounding rect of a renderable through getBounds() (or just using .left etc.), the anchor point is totally ignored. This results in bounding box being offset in relation to what is actually drawn.

**Comment by obiot** [comment]
@parasyte @agmcleod as anchorPoint is also a vector object, we could probably also use a obvservable vector object for that one, and then just use it to update the bounding box position when the anchor point is modified. Should be easy to modify

**Comment by obiot** [comment]
partially done at me.Sprite level
