### ISSUE TITLE
Entity Update Method Causing Weird Lag

### ISSUE THREAD

**Issue by Dillybob92** [melonjs/melonJS#835]
Hey guys, decided to make a video to help showcase this.

https://streamable.com/i1sb

This happens on 3.1 and 4.0.

It happens on CANVAS and WEBGL. For some odd reason though, if you enable the #debug, it works flawlessly. (Or if you don't return the `._super` in the update method)

Edit: I also removed
```
	this.body.update(dt);
	me.collision.check(this);
```
With no luck

**Comment by obiot** [comment]
Did u try calling the _super method, and then the line after "return true" ? If you just do return the value returned by the super method, you only get frame update based on your animation timing

**Comment by Dillybob92** [comment]
@obiot Hm, like this?
```
    return (this._super(me.Entity, 'update', [dt]) || this.body.vel.x !== 0 || this.body.vel.y !== 0);
```

I've been following [this](http://melonjs.github.io/tutorial-platformer/#part3)

What's really weird is.. If I enable the `#debug` all of the lag goes away. I'm trying to find out what lies inside `debugPanel.js` that is doing this.

I also found this:
https://groups.google.com/forum/#!msg/melonjs/EcPrLnmuvcQ/o3kOW5wdGjoJ

```
return this.renderable.update(dt);
```
Which works but w/o animation

**Comment by obiot** [comment]
Like this :

this._super(me.Entity, 'update', [dt]);
return true;

Not sure why your line does not work though, but i'm only on my mobile, and it's too small to see your code in the video.

Once again if no object/entity are return "true" for a frame, melonjs will skip that frame, so the lagging that you see is probably because you only have one stuff moving on screen.

**Comment by Dillybob92** [comment]
> Once again if no object/entity are return "true" for a frame, melonjs will skip that frame, so the lagging that you see is probably because you only have one stuff moving on screen.

Hmm, weird because I have the game hud from that tutorial and If I go to its `update` method and console.log the `delta` time it works. Which means melonjs isn't skipping any frames?

Or, are you suggesting that I need to have atleast 1 `return (this._super(me.Container, 'update', [dt]));` running at all times?

**Comment by Dillybob92** [comment]
> this._super(me.Entity, 'update', [dt]);
return true;

Looks like this works now for whatever reason. I am starting to understand it now better though. I guess the entity needs to be updated to continue and then also needs to be returned true to continue the entire cycle?  Thank you @obiot for your help
