### ISSUE TITLE
Custom Properties from Tiled not being set in constructor

### ISSUE THREAD

**Issue by Dillybob92** [melonjs/melonJS#837]
I have no idea if this is a bug, my lack of knowledge, or even a issue.

However, look here:
![image](https://cloud.githubusercontent.com/assets/10387670/20390094/017c72d0-ac82-11e6-9089-a671b915f008.png)

See how there is `warp_name` and `warp_to`

Here is my Entity:

```
/**
 * a Warp entity
 */
game.WarpEntity = me.CollectableEntity.extend({
    // extending the init function is not mandatory
    // unless you need to add some extra initialization
    init: function(x, y, settings) {
        // call the parent constructor
        this._super(me.CollectableEntity, 'init', [x, y, settings]);
    }
});
```

Now, if I do `settings.warp_to` it will work as the extra `Tiled` Map Editor properties get sent through that sexy argument. It's also shown if I `console.log(settings)` like so:
![image](https://cloud.githubusercontent.com/assets/10387670/20390159/4c0aa592-ac82-11e6-9a89-8fd1a08b2e6d.png)

The problem is, when this is referenced from another entity, for example my Player's `onCollision` method, I do: 
`console.log(response.b.warp_to)`

And it's undefined, why? O_o

Doesn't the tiled map properties get set through the `settings` parameter and get applied to the constructor automatically? Or do I have to hard code each new property like `this.warp_to = settings.warp_to`.

Is it possible to apply those extra tiled map properties already to the constructor so I can use them when its being referenced outside of *that* constructor? Thanks in advance!

**Comment by agmcleod** [comment]
Your assumption is correct. You will need to set a reference to the value on the object itself. If i need stuff from the settings, I usually just store a reference to the whole object.

    this.settings = settings;

If you want to automate this a bit, you can create a base class that does it, then derive the warp entity from that.

game.SettingsCopy = me.CollectableEntity.extend({
  init: function(x, y, settings) {
        // call the parent constructor
        this._super(me.CollectableEntity, 'init', [x, y, settings]);
        this.settings = settings;
    }
})

game.WarpToEntity = game.SettingsCopy.extend({})

Also for support requests, we have a google groups forum that we're fairly active on: https://groups.google.com/forum/#!forum/melonjs.

**Comment by Dillybob92** [comment]
Sweet! @agmcleod Thanks a lot! I'll post there for future questions, I just wasn't quite sure.

**Comment by agmcleod** [comment]
You're most welcome, and no problem at all. Happy to help.
