### ISSUE TITLE
Overlap2D support

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#838]
http://overlap2d.com/

As discussed on gitter

**Comment by agmcleod** [comment]
Wonder how the development has been on it. I know it was mostly 1 or 2 people working on it. Integration with libgdx was more solid (they built it ontop of that)

**Comment by Dillybob92** [comment]
FWIW, [here](https://github.com/UnderwaterApps/overlap2d) is their github. Looks about 6 months was the last update? Last release was more than a year ago. Is there anything like Overlap2D that's out there?

**Comment by parasyte** [comment]
You might actually hate this comparison, but ... it looks like any ol' SVG editor. :P

The output might be simpler than SVG ... well, anything is simpler than SVG ... but yeah, same basic concept.

**Comment by obiot** [comment]
website is down, does not look to be maintained anymore, not a future proof solution
