### ISSUE TITLE
Fix the fucking platformer tutorials

### ISSUE THREAD

**Issue by GodotIsAMess** [melonjs/melonJS#840]
They are a fucking mess. So much bullshit, unused piece of fucking garbage code in there that doesn't even coincide to the fucking current API. One fucking random example is that bullshit fucking transform matrix shit property which doesn't even fucking work before 4.0 builds. But hey, you know let's use bullshit syntaxical changes that don't even work under 4.0 in the tutorials. Because you know, new people coming to the engine really want to switch between 4.0 and 3.0 all the fucking time. But wait that's none of my business because you're just going to close this github request.

Also. 

- Get a scene editor like Godot if you want to compete.
- Fix your ugly piece of shit looking website
- Get a new professional logo and not a melon that's drawn using 5 lineTo method's via Canvas's shitty draw method
- Get a proper examples page like Phaser's website
- The dev tool (debug panel) bullshit doesn't even work in WebGL. But that's really none of our business though right because WebGL isn't important to you guys right? /s
- There are about a thousand WebGL errors when using textures. Remove that shit or atleast use PixiJS as a proper WebGL renderer, jesus fuck.

Have a wonderful fucking day.

**Comment by GodotIsAMess** [comment]
..and closed. Way to dismiss all valid arguments raised! Too bad bug issues don't give a fuck about your feelings.

**Comment by obiot** [comment]
alright, I guess being polite and respectful is not one you value, but nevertheless :
- 4.0 is not public yet, so as the corresponding tutorial, but the update is available here : https://github.com/melonjs/tutorial-platformer/tree/4.0.0
- for the rest, i'm not sure how I should respond, maybe I should just deeply apologise to you for the poor and shitty stuff we allow ourselves to put on github and the internet. after all, it's true that we are just like 3 guys doing this thing on our free time, and you are right to expect much more from us.

have a nice day as well.

**Comment by GodotIsAMess** [comment]
Well the problem is there is no fucking point in being respect though as bug issues don't have feelings.

Okay, 4.0 is not public yet that's fine and a fair point.

No need to apologize, but you should look at the points raised in the bulleted list and fix shit because game developers like myself have no time for fuckery.

However, if you really like to see 500 + WebGL warnings in your Dev Console when creating a game that's fine too.

**Comment by obiot** [comment]
https://github.com/melonjs/melonJS/issues/593
https://github.com/melonjs/melonJS/issues/637

warnings in the console when using webGL are usually logged when not using texture atlas (which should not be the case when using webgl)

also about the changes in 4.0 :
https://github.com/melonjs/melonJS/wiki/Upgrade-Guide

and last but not least instead of trashing everything for free, why not submitting pull request ? Help from professionals like you is definitely always welcome.

**Comment by parasyte** [comment]
I don't understand the point of complaining. Your input and criticism is always welcome, but vitriol is not.

If you would like to have an honest discussion in an attempt to help the project and community, please do. But this "ticket" is just trash. There's not a single piece of useful information to gather from it. The closest it comes is, "someone doesn't like it." We're not trying to please everybody.

You said it yourself, knowing this would be closed. What did you expect?

**Comment by GodotIsAMess** [comment]
> warnings in the console when using webGL are usually logged when not using texture atlas (which should not be the case when using webgl)

Yeah, but that type of logging will cost extra cpu power. Use Pixi as a rendering engine where such of these issues are not prevalent and already fixed. One of their main developers works at Blizzard entertainment and is a WebGL specialist. Not using is just being silly.

Also, not only it's being silly but it's being abusive and detrimental towards game developers that fucking come here and look for a good engine. They look at MelonJS's api and love it, then realize WebGL is being hindered by one that's not be utilized 100% and has errors popping all over the place. 


> I don't understand the point of complaining. Your input and criticism is always welcome, but vitriol is not.

If you would like to have an honest discussion in an attempt to help the project and community, please do. But this "ticket" is just trash. There's not a single piece of useful information to gather from it. The closest it comes is, "someone doesn't like it." We're not trying to please everybody.

You said it yourself, knowing this would be closed. What did you expect?

Here's the thing, Jay. My issues raised in my bulleted list are 100% valid. You however now even attempting to take them as criticism is a fucking joke, why? Because you are letting your personality get into the way of development. And the success / future of melonjs. Fuck my personality.

> There's not a single piece of useful information to gather from it.

- Having WebGL spit out 300-500 + Warnings because it doesnt' like a sprite's dimensions is pretty useful.
- The melonjs website? You think it's fine and represents melonjs perfectly?
- No examples page where game devs can get help. Like a cheat sheet. Hell, even PandaJS (which is abandoned has a better fucking cheat sheet on their site)
- Debug panel doesn't work in WebGL render mode.

But wait, none of this is useful information right? I'm just a troll, move along.

**Comment by parasyte** [comment]
Look, I appreciate your passion. It's just severely misplaced.

I've no reservations to recommend you check out some other great game engines, such as [Phaser](http://phaser.io/), [GoDot](https://godotengine.org/), or [Unity](https://unity3d.com/); Your energy will be much better spent building games. If you can find something else that you like, everyone wins!

**Comment by GodotIsAMess** [comment]
My passion is directed towards melonjs and the success of your project but it's misplaced. Man, the fucking logic here hurts so much I might pass out.  I appreciate you being nice and professional but honestly... you're just going to dismiss my points raised? You atleast agree they are valid issues, do you?

**Comment by parasyte** [comment]
You have a funny way to show support. It's abhorrent. The validity of your arguments was never called into question, just your mannerisms and motivations.

**Comment by GodotIsAMess** [comment]
> The validity of your arguments was never called into question, just your mannerisms and motivations.

My mannerisms are irrelevant. Bug issues don't have feelings though. You shouldn't give two fucks about my personality. You should be looking at the points I have raised and understand what needs to be fixed and acknowledge it.

**Comment by parasyte** [comment]
If you're ready to play nice and act like a civilized human being, you can attempt to restate your issues. Or, you know, you can get off your high horse already and go make a game with something else.

**Comment by GodotIsAMess** [comment]
And why would I want to report the issues again? So they can get closed again? The github developer culture nowadays is a fucking nightmare. Developers like you and others really don't give a fuck about me, or anyone that wants to help. You guys don't listen to us at all, but only on things that you think should be implemented. That doesn't even make it a community project imho, it makes it more of a closed source thing.  

We make suggestions and want melonjs to be better. And what do you do? "No, he's trolling, flaming, his attitude sucks!, etc". What a fucking scapegoat to be honest. If you can acknowledge my issues in my bulleted list, I will never both ya again. If not, you will see this thread daily under new accounts as I have thousands ready.

**Comment by obiot** [comment]
FYI, 
https://github.com/melonjs/melonJS/commit/a8172f78327255a1a96039cd190419398078d4a1

**Comment by obiot** [comment]
And btw, if you are looking for the (professional version) logo, they are here :
https://github.com/melonjs/melonJS/tree/master/media

**Comment by agmcleod** [comment]
> Get a scene editor like Godot if you want to compete.

Mmmm, no. There are many engines out there that don't use them, personally I prefer more code oriented work. The tiled integration works pretty well for most 2d content where I've needed a level editor. Outside of that, writing the games purely via JS has worked pretty well.

> Fix your ugly piece of shit looking website

While your attitude is pretty terrible, and really degrades your argument, the website does need work. We have an updated version in progress, just needs to be finished up. Again it's only three of us really working on this project, so it's hard to prioritize.

> Get a new professional logo and not a melon that's drawn using 5 lineTo method's via Canvas's shitty draw method

I like our logo :(. But hey if you'd like to pay for a designer to do one for us, that be a nice way to contribute.

> Get a proper examples page like Phaser's website

I agree on the examples being hard to find off our website, we need to put these things more front and centre. But it does exist. http://melonjs.github.io/melonJS/index.html

> The dev tool (debug panel) bullshit doesn't even work in WebGL. But that's really none of our business though right because WebGL isn't important to you guys right? /s

Our WebGL support is in beta for a reason, there are things that don't work with it yet, and somethings that just haven't been heavily tested.

> There are about a thousand WebGL errors when using textures. Remove that shit or atleast use PixiJS as a proper WebGL renderer, jesus fuck.

Jay & Olivier addressed some of this already, but I wanna talk about Pixi. It has a number of bugs, and some really wonky behaviour. We had a fork of pixi at the games company I was at last year, to fix bugs we ran into. It's also really big. About the same size as MelonJS itself. There's a reason why Phaser v3 (LazerJS) is moving away from Pixi.

**Comment by faststare** [comment]
I received a console log throw that stating the flipX is depreciated. please the update the console.log throw error something for newbie. "flipX is depreciated, kindly this new API(example this.FLIPX(false);"

PS: I following the old platformer tutorial and new link platformer tutorial is still broken 404 page.

**Comment by parasyte** [comment]
Yes, that's actually a bug in melonJS core, not the tutorial. See discussion here: https://github.com/melonjs/melonJS/issues/815#issuecomment-287601116

**Comment by obiot** [comment]
can you point out which link is broken, they all seems fine to me

**Comment by obiot** [comment]
https://github.com/melonjs/melonJS/commit/865757be41d1a2a233e6358a71da038ea9fd2eb4
done, and in a backward compatible way :)

**Comment by parasyte** [comment]
Looks great!

**Comment by obiot** [comment]
i thought about simplifying the feature actually, to avoid all these private variable/method/etc,,, by just using two global boolean that the user can change to false or true, but at the end i just kept the old implementation.
