### ISSUE TITLE
[WebGL] setColor override the `globalApha` value

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#841]
The following code does not work, and will result in a global alpha value of 1.0

```javascript
renderer.setGlobalAlpha(0.5);
renderer.setColor("black");
```

the reason being that the webgl renderer store the global alpha value in the [`currentColor`](https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L509) property, that is then overriden when calling [`setColor`](https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L520)

workaround is to specify the alpha together with the color
```javascript
renderer.setColor("#00000080");
```
the canvas renderer has the correct behaviour (in my opinion).

**Comment by parasyte** [comment]
I played with this issue sometime last year (or earlier! wow it's been a long time)

The Canvas API surely separates the global alpha component from the global color. But it also does a lot of other weird stuff like the global composite operation.

Simulating the global alpha (by mixing the existing alpha with the setColor alpha) might end up with decent results.

**Comment by obiot** [comment]
Funilly enough, and despite font just killing the peformances, this was the reason for both panels rendering black in WebGL....

I'll try multipliying both values, i was rather thinking about storing it in a different value, but i was afraid it would trigger too many changes.

**Comment by obiot** [comment]
Another issue detected here
https://github.com/melonjs/melonJS/blob/master/src/utils/color.js#L222

There is never a default 1.0 value applied if the argument is missing

**Comment by obiot** [comment]
I feel like we did fix that in the past... although i could not find it in the history... maybe in a branch that was never merged into master then!

**Comment by obiot** [comment]
scratch that last comment, it's there  ( i forgot we used a setter for it) :
https://github.com/melonjs/melonJS/blob/master/src/utils/color.js#L558

**Comment by obiot** [comment]
done, but i think a better implementation would be to actually add/manage a globalAlpha value in the renderer. But I'll add that to ticket #637 for follow up.

**Comment by parasyte** [comment]
Keep in mind that the global color doesn't do what you think it does; There is no analog in the Canvas API. The global color is multiplied with the texture color on its way through the fragment shader: https://github.com/melonjs/melonJS/blob/4.0.0RC/src/video/webgl/glsl/quad-fragment.glsl.dot#L86

So even with this patch, there are other discontinuities with the two APIs. E.g `setColor("red")` makes *everything* red in WebGL, but not with Canvas.

**Comment by obiot** [comment]
indeed yes, but at least it does not completely override it anymore :)

further improvements for this should also be part of #785
