### ISSUE TITLE
me.levelDirector.loadLevel fires callback two times

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#844]
Hi,
I've encountered a strange nondeterministic behavior. Sometimes when refreshing the page with melon running, calling me.levelDirector.loadLevel _once_ causes the onLoaded callback to fire (at least) _twice_. I really don't know where it's coming from and why, since the stack comes from some async callback which calls safeLoadLevel.

**Comment by krojew** [comment]
I think I'm getting closer to tracking it down. It might be related to me.loader.preload() - it calls checkLoadStatus() which schedules itself to be called in the future and then call global api.onload, when everything is loaded. There might be some bad global state/timing problem when me.loader.preload() gets called two times with different callbacks.

**Comment by obiot** [comment]
maybe we should clean it up when the page is unloaded
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

not sure though it works in case of refresh

**Comment by krojew** [comment]
This won't help. Seems like the checkLoadStatus() function isn't reentrant because of the global status, which implies me.loader.preload() isn't reentrant. I think this is the case I've stumbled upon, and it would explain why it's nondeterministic.

**Comment by krojew** [comment]
Did a quick fix - seems to work now.

**Comment by krojew** [comment]
I'm happy my PR was merged, but be aware it's not the final fix - just a quick workaround. To make me.loader.preload really reentrant, it should never touch any global state. The same goes for any function which takes a callback.

Well, since I'm already talking about it, I might as well make a proper fix for this one :)
