### ISSUE TITLE
TypeError: res is undefined

### ISSUE THREAD

**Issue by bunnyhat** [melonjs/melonJS#849]
Hi, I seem to getting an error "TypeError: res is undefined" on melonJS.js (line 13638, col 29)

**Comment by agmcleod** [comment]
Hi there! We have a support forum where we can help you here: http://www.html5gamedevs.com/forum/32-melonjs/

Typically we reserve issues for surfaced bugs. When you post on the forum, please show us your code, and where in your code the error is being triggered. Have a look at the callstack in your browser to see where in your code the error is happening.

Thanks!
