### ISSUE TITLE
better filter objects that are to be added in the quadtree

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#850]
see discussion here :
https://github.com/melonjs/melonJS/commit/1c4dd213040ea28b758d7d95fa7e20279bcbb9c3

basically it's about adding a clean way to only add clickable object or physic enabled entities.

**Comment by obiot** [comment]
i have been thinking how to implement this properly, but the best thing i came up with was to set some private flag to the object when used to register to an event.  I don't really like to be honest.... for physic enabled object it's easy, as we just need to check if the entity has a body, but for event enabled object there is nothing as trivial .... 

any idea from you guys ?

**Comment by parasyte** [comment]
I would guess it needs a public property to opt-in or opt-out of collision detection. There are special objects like `me.Container` which needs to be added to the QuadTree if it contains collision-enabled or clickable children. Autodetecting that might be a bit difficult?

**Comment by obiot** [comment]
indeed, we could add a new public property to me.Renderable, like `pointerEventEnabled` or something, and that would also allow to temporarly disable any event for a specific object without having to register/unregister it.

the only thing thouhg, is that when calling `releasePointerEvent()`, the method should set the flag back to false if there is no more event registered for that object. (should be easy too add there though : https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L805)

**Comment by obiot** [comment]
this said, if we are back in a situation where only physic & event enabled objects are in the quadtree, that could add some performance boost in games where sprite are used, or even non clickable UI elements.

**Comment by parasyte** [comment]
Feels like this one should be default enabled for pretty much everything that could be clickable or physics-enabled. Classes can opt-out with a boolean property (true to opt-out). Some examples that would opt-out: `me.ParticleContainer`, `me.Sprite`, `me.ImageLayer`, ...

This model also aligns with what Unity does (`isKinematic`) so at least we can have the peace of mind that it's exactly the same solution used by other popular engines.

**Comment by obiot** [comment]
i'm not sure I understand the actually meaning of "Kinematic" in english to be honest, but from what I see from the Unity documentation is more about disabling the physic body and related physic of an object.

Don't get me wrong, I like the idea of having an op-out flag for it, but i'm just not sure I see here how isKinematic relates to it here when it come to opt-out me.Sprite or me.Tween object from the quadtree. Not to mention that only object with a 'bounding box" (so basically only object inheriting from renderable object.)

last but not least, does this mean you will give this one a shot ? :)

**Comment by parasyte** [comment]
The word "kinematic" defines motion of objects relative to one another (more or less). It's pretty much just another term for "motion in physics".

Anyway, the reason for `isKinematic` in Unity is so you can disable the effects of physical interactions on the object. For example, because the object is a sword that can be held in a player's hand. It would be really bad if that sword was interacting with the hand that held it; the sword (or hand) would be bouncing all over the place as the character tried to swing it.

The reason I bring it up is because it's a boolean flag available on every game object [in Unity] that defaults to false. And that's exactly what we want with this feature. ;) To opt-out `me.Sprite`, the constructor just sets the boolean to `true`. Subclasses are free to opt-in by setting the boolean back to `false`.

Ok, so `me.Tween` doesn't need it. The other three do, and maybe some other classes that haven't been considered.

I don't think I'll be able to take this in the short term. Still trying to focus on my VR game.

**Comment by obiot** [comment]
i see, so basically, it should be false by default, unless you have a physic body (so an Entity) or if the object is clickable. am I correct ?

**Comment by parasyte** [comment]
No, it should be false by default unless you want to opt-out of all physics interactions and click events. :)

**Comment by agmcleod** [comment]
kinematic should still be detectable by collision checks no? It's just bounceless, doesn't rotate on collision. Kinda works like simple AABB? Or have i been using kinematic types wrong?

**Comment by parasyte** [comment]
@agmcleod You're perfectly right... I guess using Unity's `isKinematic` option in comparison to this feature is more confusing than anything else. To clarify, I'm **not** suggesting we implement a similar feature in melonJS. I was just using it as an example of *some boolean* on all game objects which defaults to false. That's really where the similarities stop. :)

**Comment by agmcleod** [comment]
I found Unity's isKinematic more annoying lol. I love using that type in box2d based games when i want arcade-y physics, but still have super reliable collision detection. I move via position instead of forces.

**Comment by obiot** [comment]
pretty simple actually. let me know if you have any comments, else we can close this one :)

**Comment by obiot** [comment]
no comments, so I close this one.
