### ISSUE TITLE
MelonJS.js:4184 Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by metaunicorn** [melonjs/melonJS#851]
This happens when you register something in the pool that is `undefined`.
Concretelly, in `api.pull` on `obj = new (proto.bind.apply(proto, args))();`.

I would prefer to have a more specific error if we try to register something that is undefined, it took me a couple of hours to know what was going on :/

Thank you

**Comment by obiot** [comment]
oh, i'm surprised we don't actually have indeed a proper error message!

**Comment by obiot** [comment]
a check should probably added here:
https://github.com/melonjs/melonJS/blob/master/src/system/pooling.js#L74

if the given object is not a proper object, throw an execption. 

@metaunicorn is this correct vs the issue you were having ?

**Comment by obiot** [comment]
done, thanks again for reporting this :)

**Comment by metaunicorn** [comment]
I did the check on a higher level but I think it will be good to have it there.
Thanks to you!
