### ISSUE TITLE
transform not applied properly to base me.Sprite objects

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#854]
see here :
http://www.html5gamedevs.com/topic/27137-flipx/

current workaround is to manually enable `autoTransform` in the me.Sprite constructor :
````javascript
this.autoTransform = true;
````

**Comment by obiot** [comment]
@parasyte @agmcleod 

quick question before I merge my branch :

now transform are automatically applied to any renderables (which fixes the issue here), but that also means that anchor point are now truly (0.5, 0.5) by default for any renderable as well, which kind of changes a few things here and there. For example anchor point was never applied for container before (it's still not the case though systematically, as when loading a "Tiled" game, level, container and entity objects anchor points are set to the tiled default one).



so question, shall I :
 * 1. keep it this way and merge it into the 4.1.0 branch, as after the "behavior" changes is actually the way it should have been (part of the fix)
 * 2. turn back off the flag (https://github.com/melonjs/melonJS/commit/2725cfe5106d987d65f8a0916785c15e2d2d1bcc) for me.Renderable, but keep it "starting" from me.Sprite object so that we both fix this issue and keep the previous (wrong) behavior.

**Comment by obiot** [comment]
or option 3 : release 4.1.1 as it is now, and merge this one into the next 5.0.0 branch with all the other anchor and bounds fix (I would even remove the actual autoTransform flag, it's actually not really useful)

**Comment by obiot** [comment]
well so I'll go for option 3 actually and will release the 4.1.1 as it, then merge my stuff into a 5.0.0 branch

**Comment by parasyte** [comment]
:+1:
