### ISSUE TITLE
Not all code paths return a value

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#855]
me.audio.play() doesn't return a value in all code paths and this is undocumented. It either should explicitly return something other than undefined, or it should be documented.

**Comment by krojew** [comment]
Same for rate().

**Comment by obiot** [comment]
`play` always return the instance id if a correct sound/audio clip name was specified, else it will return undefined.

**Comment by obiot** [comment]
I guess that the issue here is that we should actually throw a few more error, instead of silently doing nothing in case a give sound name does not exist !
