### ISSUE TITLE
me.Polygon.recalc problems

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#862]
The result type of me.Polygon.recalc is undocumented, and it uses _public_ fields "edges" and "normals" which are also undocumented.

**Comment by obiot** [comment]
edges and normals are not public fields, that's why they are not documented :
http://melonjs.github.io/melonJS/docs/me.Polygon.html

**Comment by krojew** [comment]
They are being used in collision detection, so they pretty much are public. Maybe expose them in the interface?

**Comment by obiot** [comment]
yes but it's internally used by the collision detection and solving functions. these are really internal things that the end user does not need to know about and should stay private, so i really don't see the value in documenting them.

**Comment by krojew** [comment]
I think the issue here is that we understand public properties differently. I assume everything which is accessed from the outside is public; you assume public things are only those described as such. JS, being the terrible language that it is, doesn't really help here - you can't simply label a thing as public or private.

**Comment by obiot** [comment]
protected should be the correct definition for these properties, but it does not exist in the jsdoc dictionary :)

**Comment by krojew** [comment]
Yeah, that's one way of doing it. And another reason why JS is a terrible language :)
