### ISSUE TITLE
me.Rect.setShape is incompatible with me.Polygon.setShape

### ISSUE THREAD

**Issue by krojew** [melonjs/melonJS#863]
Since Rect extends Polygon, a Rect can be passed as a Polygon. Unfortunately, setShape() methods are incompatible - calling it from the Polygon interface will call Rect implementation, but the parameter types will be incompatible, which will result in an error. This not only violates the substitution principle, but makes it necessary to check the actual class of given Polygon object before calling setShape() to avoid any errors.

**Comment by obiot** [comment]
fair enough, but i'm not sure I want to change this now :

- me.Rect is only used for bounds management, as even if you add a me.Rect to an entity body, it will be converted to a me.Polygon object. So setShape is really only called internally, but this said, it's actually a good reason to change it :P
- me.Rect and bounds management are long due for a design change, see #580 (there was another ticket  as well, but I could not find it)
- changing it now would mean breaking the API and therefore a 5.0 version, when i was going for a small update with 4.1.0 and no api changes.

**Comment by krojew** [comment]
You can always add a deprecation warning in 4.1. In melonTS I've already split those to two separate ones, and the compiler took care of fixing the references.

**Comment by agmcleod** [comment]
I kinda see this as valid though. It's like the polygon implements an override of the original. Points is also an arbitrary length, where as the params in rect are hard set. Trying to recall exactly what it was, but i remember having to use a super simple rect over what's in melonjs, because it was slow. I feel like making them have the same api could make that even worse.

**Comment by obiot** [comment]
@krojew in case you are still around, `me.Rect.setShape` now accepts both type of parameter set, the former `(x, y, w h)` one, and the polygon style `(x, y, points)` one. I won't do better than that though
