### ISSUE TITLE
(N)POT Texture & WebGL

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#864]
see discussion here : http://www.html5gamedevs.com/topic/27408-imagelayer-and-webgl-problem/

what do we want to do if a NPOT texture is used when using WebGL (knowing it will potentially break the game)  :
- warning in the console log
- throw an exception

**Comment by parasyte** [comment]
Detecting NPOT dimensions is very easy. I thought I added this at one time ...

```javascript
function isPOT(image) {
    return (
        (image.width  & ~(image.width  - 1)) === image.width &&
        (image.height & ~(image.height - 1)) === image.height
    );
}
```

**Comment by obiot** [comment]
indeed, and i thought we also had this already, but the question is rather what to do if this returns false :)

**Comment by parasyte** [comment]
Crash loudly. ;)

**Comment by obiot** [comment]
not sure where to check for it to be honest ...
- there is only 3 places where we use `uploadTexture`,  createPattern, and then two more for font or fill texture where we create our own texture "cache"
- I initially wanted to add it inside `uploadTexture` but it can also takes a byte array as parameter
- for regular image (with `drawImage`), it uses the `addQuad` function, and pulling directly the image from the cache. So i'm not sure what we should do here

**Comment by parasyte** [comment]
Right here: https://github.com/melonjs/melonJS/blob/02e8a27edef763d88665557bedb880869a1bb766/src/video/webgl/shader.js#L175

Prefer the `w` and `h` params if passed, else use `image.width` and `image.height`

**Comment by obiot** [comment]
well putting it there just make it throw an exception as soon as it create the main canvas itself :)

**Comment by obiot** [comment]
maybe we should just test it, at the same place, but only for Image element ?

**Comment by parasyte** [comment]
Really? Then that's a bug ... the main canvas should not be used as a texture.

**Comment by obiot** [comment]
ah ! nice finding then :)

**Comment by obiot** [comment]
maybe it's the offscreen one actually, that would make sense after all

**Comment by obiot** [comment]
actually the issue is with the font texture :
https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L121-L122

that creates a texture (canvas) of the size of the main canvas

**Comment by parasyte** [comment]
Gotcha. Definitely a bug. Simple workaround for now is creating that texture with the next Power of Two size. Proper fix is either pure WebGL font rendering with a bezier shader and tessellation of font glyphs (hard). Or just use HTML elements or an overlay canvas the with Canvas2D API...

**Comment by obiot** [comment]
that's potentially a huge texture created right away, and potentially for just the loading screen.

the simple workaround I would rather see is :
- stop using regular font in the loading screen (we can embed a bitmap font now)
- don't automatically create a fontTexture, unless used
- warn the users (in the console) that font texture are killing performances in webGL 
- size the font texture to the canvas size next POT

I would love to see the proper fix coming, but I have a hunch this won't happen anytime soon  :)

**Comment by parasyte** [comment]
So it goes. :p

An overlay is easier to implement. I'm not sure what the implications will be though. Compatibility issues with mobile wrappers?

**Comment by obiot** [comment]
or memory issue, as we just basically create a giant overlay :)

**Comment by obiot** [comment]
and of course, now when I put back the POT check in createTexture, it throws an exception because the tileset file we used is not a power of two texture :P oh boy.....  it's time for lunch !

**Comment by obiot** [comment]
i think I'm going to close this ticket as it is. I mean, having NPOT texture for tileset does work, the issue was more with pattern.

**Comment by obiot** [comment]
after reading the article [here](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL#Non_power-of-two_textures) again ,i think the best compromise is really the following :
- throw an exception if a NPOT texture is use for pattern.
- throw a warning only (in the [createTexture](https://github.com/melonjs/melonJS/blob/02e8a27edef763d88665557bedb880869a1bb766/src/video/webgl/shader.js#L175) function) if a texture is a NPOT, but do not stop execution
