### ISSUE TITLE
Duplicate mousewheel events

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#867]
Reported here: http://www.html5gamedevs.com/topic/28275-mousewheel-event-gets-triggered-3-times/

I did some debugging, and the duplicate events come from the following sources:

* [Line 198](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L198); an EventListener is added with `event == "mousewheel"`
* [Line 239](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L239); an EventListener is added with `event == "wheel"`
* [Line 371](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L371); the QuadTree data structure reference is modified in-place, adding duplicate copies of `me.game.viewport`

The first two are a regression from the Pointer Events refactor work for v4.0.0; Only one of these events should be registered. It looks like we can get rid of the second one entirely. Also fun to note, the old non-standard "mousewheel" event name was added to the event lists, instead of the new and improved "wheel".

The third point is the most surprising of all! `me.QuadTree.retrieve` returns an array *reference* to its [internal set of children](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/physics/quadtree.js#L258) (And even more surprisingly, this code concats other nodes' children to its own!) I believe *this* line needs to create a clone of the array, instead of using a reference. That will fix this particular issue, as well as other related issues.

TODO checklist:

* [x] Replace every reference of `mousewheel` to `wheel`
* [x] Remove the duplicate `addEventListener`, `onMouseWheel` function, module-global `wheeltype` variable
* [x] Fix the reference leak in `me.QuadTree.retrieve`

**Comment by agmcleod** [comment]
Okay, next time i wanna mess with the event system, feel free to tell me no. XD.

**Comment by obiot** [comment]
There is nothing wrong with the quadtree retreive function, best case it returns the current list of children, wort case a concatenation of child nodes. And concat returns a new array : https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

**Comment by obiot** [comment]
[Line 102](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L102) should be 
````javascript
var wheeltype = "onwheel" in document.createElement("div") ? "wheel" : "mousewheel";
````
and [Line 111](https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L111) should then use the defined variable.
at least it would just generate the wheel event for the correct type

**Comment by parasyte** [comment]
Ah yeah, so concat is all good. But then the push is still an error in the case that concat is not called.

**Comment by Sairahcaz** [comment]
@obiot your fix throws this exeption:
https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/input/pointer.js#L759

**Comment by obiot** [comment]
i probably forgot a detail somewhere, i'll take a look later and try myself to apply the changes.

**Comment by parasyte** [comment]
@obiot @Sairahcaz The fix is now in a branch if you want to check it out. The WIP build is here: https://melonjs-builds.s3.amazonaws.com/artifacts/bug/duplicate-wheel-events/1956/build/melonJS.js

**Comment by obiot** [comment]
awesome :)

**Comment by parasyte** [comment]
@obiot does this look good to merge?

**Comment by obiot** [comment]
it does, i was expecting for @Sairahcaz though to also provide some feedback and confirm it fixes his issue on his side.

**Comment by parasyte** [comment]
Good call. Will await feedback. At least for a few days. :)

**Comment by obiot** [comment]
@agmcleod 

> Okay, next time i wanna mess with the event system, feel free to tell me no. XD.

it's rather that we should not add or modify things, without adding a corresponding test. but admittedly it's a bit complex when it comes to pointer events !  but else, man, please do continue to mess with things :)

**Comment by obiot** [comment]
@Sairahcaz +1 for your feedback on the bug fix, thanks !

> @obiot @Sairahcaz The fix is now in a branch if you want to check it out. The WIP build is here: ? https://melonjs-builds.s3.amazonaws.com/artifacts/bug/duplicate-wheel-events/1956/build/melonJS.js

**Comment by obiot** [comment]
@parasyte I just tested the wheel event before and after your fix, and it does correctly generate only one event, so on my side we can merge it.

however as I was commenting in your commit, the following code should be removed:
https://github.com/melonjs/melonJS/blob/bug/duplicate-wheel-events/src/input/pointer.js#L532-L535

these are non standard values, and since we now only support the "wheel" event we should do the same for these properties :
https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent

**Comment by parasyte** [comment]
@obiot Hum? The code you highlighted is only executed for old `mousewheel` events. This is our "backup plan" for a `mousewheel -> wheel` polyfill. So you're suggesting we should remove the polyfill?

**Comment by parasyte** [comment]
If we remove the polyfill, we will sacrifice some compatibility. Vis-à-vis our least common denominator UA support becomes [[1]](https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Browser_compatibility) not [[2]](http://melonjs.org/#compatibility)

**Comment by obiot** [comment]
okay, let's keep it then I guess for now. But if we do a 5.0.0 release finally instead of 4.x, I would propose we remove it to be also aligned with that ticket #829

**Comment by parasyte** [comment]
That's I'm ok with. I wrote the patch under the assumption that this is just a bug fix and should not break compatibility.

**Comment by obiot** [comment]
i will add it in that other ticket, so that we do not forget

**Comment by Sairahcaz** [comment]
@obiot @parasyte Hi guys, the fix looks fine to me, thanks!

**Comment by Sairahcaz** [comment]
@obiot I know this is not a good place to ask, you can remove this comment after reading.
I wrote you an email (olivier.biot@me.com) 2 days ago, do you check this mail address?

**Comment by obiot** [comment]
yes I saw it sorry. I wanted to discuss it with Jason first, but then I have been swamped with other things. I will do tonight, or worst case tomorrow morning :)

**Comment by Sairahcaz** [comment]
Ok, no stress, just wondered if the mail reaches you...

**Comment by obiot** [comment]
merged ! thanks again :P
