### ISSUE TITLE
Bug in Number.prototype.round function

### ISSUE THREAD

**Issue by Sairahcaz** [melonjs/melonJS#868]
Think this: 
```javascript
Number.prototype.round = function (num, dec) {
    // if only one argument use the object value
    num = (arguments.length < 2) ? this : num;
    var powres = Math.pow(10, dec || num || 0);
    return (~~(0.5 + num * powres) / powres);
};
```

should be like this?: 
```javascript
Number.prototype.round = function (num, dec) {
    // if only one argument use the object value
    if (!dec) {
        dec = num;
        num = this;
    }
    var powres = Math.pow(10, dec || num || 0);
    return (~~(0.5 + num * powres) / powres);
};
```

**Comment by obiot** [comment]
the current version looks fine to me. In case dec is undefined pow uses num, and if both are still undefined it reverts back to the 0 value.

did you encounter a non-working use case ?

**Comment by Sairahcaz** [comment]
/**
 * round a value to the specified number of digit
 * @memberof! external:Number#
 * @alias round
 * @param {number} [num=this] value to be rounded.
 * @param {number} dec number of decimal digit to be rounded to.
 * @return {number} rounded value
 * @example
 * // round a specific value to 2 digits
 * Number.prototype.round (10.33333, 2); // return 10.33
 * // round a float value to 4 digits
 * num = 10.3333333
 * num.round(4); // return 10.3333
 */

second example will not work with your version:
num.round(4) //return -0.0331130614010332

**Comment by obiot** [comment]
interesting ! :P

**Comment by parasyte** [comment]
Works for me.

<img width="195" alt="screen shot 2017-02-08 at 7 00 20 pm" src="https://cloud.githubusercontent.com/assets/456942/22767558/e38c3882-ee30-11e6-9098-c3a0a8360ce5.png">

**Comment by parasyte** [comment]
Well, this explains why it works for me. I'm testing the wrong implementation. Don't know what this is, jQuery or Underscore, maybe?

<img width="564" alt="screen shot 2017-02-08 at 7 07 00 pm" src="https://cloud.githubusercontent.com/assets/456942/22767685/e1f6c46e-ee31-11e6-8cb4-f1b604b00876.png">

Our impl is definitely broken.

**Comment by obiot** [comment]
Number.prototype.round could go die and rest in peace in my opinion :
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

we don't need it !

**Comment by parasyte** [comment]
Well, until we deprecate it, the bug is now fixed!

**Comment by obiot** [comment]
the following code works :
````javascript
Number.prototype.round = function (num, dec) {
    if (typeof dec === "undefined") {
        dec = num || 0;
        num = this;
    }
    num = num || this;
    return Math.round(num * Math.pow(10, dec)) / Math.pow(10, dec);
};
````

tested with the following simple test unit :
````javascript
describe("Lang : Number", function () {

    it("round a specific value to an Integer value", function () {
        var num = 10.3333333;
        expect(num.round()).toEqual(10);
    });

    it("round a specific value to 2 digits", function () {
        expect(Number.prototype.round(10.33333, 2)).toEqual(10.33);
    });

    it("round a float value to 4 digits", function () {
        var num = 10.3333333;
        expect(num.round(4)).toEqual(10.3333);
    });
});
````

note that is also works with negative value, but If I add a test with a negative value, the test is successfull, but then jasmine is crashing at the end on me.input test unit (which is completely unrelated as we don't even use Number.round() at all in melonJS)

**Comment by parasyte** [comment]
The exception was fixed in the other commit. ;)

**Comment by obiot** [comment]
yeah, I saw that after posting my last comment :P

**Comment by parasyte** [comment]
4792a2336eef54ed478002ef71a230a2ee62a88e so we don't have to go searching for it, when we start investigating these changes in a few years. :P

**Comment by obiot** [comment]
thanks !
