### ISSUE TITLE
Game on http://melonjs.org restarts forever

### ISSUE THREAD

**Issue by stefan-reich** [melonjs/melonJS#870]
I can't even read the home page, the game restarts itself all the time, lol. This is with Firefox (Linux).

**Comment by obiot** [comment]
hehehe niiiice ! would you be able to capture the console output to see what is happening ?

you should be able to read the home page though, as the game is only in the background

**Comment by obiot** [comment]
I just pushed a couple of updates to the website, please have a try to see if it changed anything.
