### ISSUE TITLE
Body falling and jumping flags are inaccurate when gravity is reversed

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#871]
This bug surfaced on the forum when a user attempted to implement double-jump with gravity reversed (a la [VVVVVV](https://en.wikipedia.org/wiki/VVVVVV)).

I have posted what I think is a solution, but I am now awaiting confirmation whether it fixes the issue or not. See the forum post for details: http://www.html5gamedevs.com/topic/28336-reversed-gravity-double-jump/#comment-163010

----

Patch this: https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/physics/body.js#L481

With this:

```javascript
this.falling = (vel.y * Math.sign(this.gravity)) > 0;
```

This may also need to change: https://github.com/melonjs/melonJS/blob/22401642a0e35ddcacfff5a62e5909ae30b4ab3a/src/physics/body.js#L369-L370

To this:

```javascript
var dir = Math.sign(this.gravity) || 1;
this.falling = overlap.y >= dir;
this.jumping = overlap.y <= -dir;
```

**Comment by obiot** [comment]
just made me realized that we forgot to include this one (https://github.com/melonjs/melonJS/blob/master/src/lang/math.js#L13-L28) in the list of ES5 polyfill to be removed ! (ticket #829)

**Comment by obiot** [comment]
so at the end do we add these patches ? they look fine to me :)

**Comment by parasyte** [comment]
Good call! Done.

**Comment by obiot** [comment]
:P
