### ISSUE TITLE
bindPointer touchstart doesn't fire

### ISSUE THREAD

**Issue by Ld00d** [melonjs/melonJS#872]
When the code gets to line 585 of pointer.js:

`if (e.type === POINTER_DOWN[0] || e.type === POINTER_DOWN[1] || e.type === POINTER_DOWN[2]) `

It's missing the check for touchstart:

`var POINTER_DOWN = ["pointerdown", "MSPointerDown", "mousedown", "touchstart"];`

I can fix it and submit a pull request.

**Comment by obiot** [comment]
good catch and thank you for the pull request :)
