### ISSUE TITLE
add support for Text Object (Tiled 1.0)

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#875]
see https://github.com/bjorn/tiled/issues/1429

**Comment by bjorn** [comment]
The text object will be available in the next Tiled release (probably 1.0), not the 0.18.2 patch release.

**Comment by obiot** [comment]
oh ok, my bad :) thank you for the feedback :)

**Comment by obiot** [comment]
nice to see that Tiled is "finally" reaching a 1.0 version !!!

**Comment by parasyte** [comment]
This will be really cool for building HUDs and Menus!

**Comment by obiot** [comment]
see #950 (required first)

**Comment by obiot** [comment]
easy peasy with the new `me.Text` and `me.BitmapText` object :)
