### ISSUE TITLE
Add support for Group Layers (Tiled 1.0)

### ISSUE THREAD

**Issue by bjorn** [melonjs/melonJS#876]
Will be in the next Tiled release, but the feature is already available in development snapshots.

See bjorn/tiled#1038

**Comment by obiot** [comment]
interesting one triggering some nice refactoring.

**Comment by bjorn** [comment]
Interesting that you have one TMXGroup that can contain either objects or layers. I guess this made something easier?

In Tiled, the introduction of the GroupLayer changed quite a lot of code...

**Comment by obiot** [comment]
Yes, I thought this was the most simple option when parsing (+normalizing) the map files, and I could not see a real benefit of having an additional object, not to mention that at the end they all end up (one instantiated) into the same "standard" melonjs container.

Actually i thought it was the same in Tiled until i saw that you kept the "objectgroup" and "group" in the xml :) but i already made my mind on how to implement it on my side :)

**Comment by bjorn** [comment]
Yeah, when I will ever get to redesign the map format I'll probably unify the grouping functionality.
