### ISSUE TITLE
Error when running downloaded MelonJS file

### ISSUE THREAD

**Issue by Devix167** [melonjs/melonJS#878]
So I got melonJS thinking: "Oh sweet it has isometric support AND it's javascript! Heck yea!".
I downloaded it, scanned it for viruses, no viruses detected, so i ran it. It spits out this:
http://prntscr.com/egxcx7
So I downloaded a lower version.
http://prntscr.com/egxcx7
I tried putting it in its own folder.
http://prntscr.com/egxcx7
What can I do to fix this?

**Comment by obiot** [comment]
Official download links are here:
https://github.com/melonjs/melonJS/releases

and your links look suspicious so i'm not going to open it. If this is not a scam/spam, just follow the link here above, both minified and plain version are working

**Comment by parasyte** [comment]
FWIW the links are just for a screenshot hosting service, and the screenshot is attached here:

![054dadc2c2db4345a63e8497938e00a2](https://cloud.githubusercontent.com/assets/456942/23638910/543137be-0299-11e7-9777-d3b3386800f8.png)

@Devix167 It looks like you are attempting to run the JS file by double clicking on it? That's not going to work. melonJS requires a full web browser environment. Here are the minimum supported versions: http://melonjs.org/#compatibility

**Comment by parasyte** [comment]
A few good links to get you started:

* [Platformer Tutorial](http://melonjs.github.io/tutorial-platformer/)
* [Space Invaders Tutorial](http://melonjs.github.io/tutorial-space-invaders/)
* [Boilerplate Project](https://github.com/melonjs/boilerplate)
