### ISSUE TITLE
Re-open of my issue

### ISSUE THREAD

**Issue by Devix167** [melonjs/melonJS#879]
Thanks a ton whoever closed my issue and didnt bother to listen to me...
I DOWNLOADED THE FILE FROM THE OFFICIAL DOWNLOAD PAGE AND STILL GOT THE ERROR...
FFS YALL I JUST WANT TO USE YOUR FREAKING GAME ENGINE!

AND JUST FOR GOOD F****** MEASURE, HERE IS THE ERROR I GET:
![fml](https://cloud.githubusercontent.com/assets/24801762/23638867/dded2340-02a9-11e7-8dee-f5777936d35e.png)

And once again, thanks a ton to who closed my issue!

**Comment by Devix167** [comment]
Edit: someone helpful replied to my other issue, so im closing.

**Comment by obiot** [comment]
I did, and sorry i was mistaken ! this said, always loved the capital letters and the poetry in a message, really set the tone in case you need further help in the future.

now, you just don't double-click on a javascript file from the explorer ..... and if you need help, follow the tutorial here : http://melonjs.github.io/tutorial-platformer/

another useful link is the boilerplate here, that provides a project template to start with :
https://github.com/melonjs/boilerplate
