### ISSUE TITLE
me.device.isFullscreen returns false if fullscreenElement is not the canvas

### ISSUE THREAD

**Issue by paseonline** [melonjs/melonJS#881]
In the property me.device.isFullscreen the fullscreenElement is checked against the video wrapper. Therefore it returns false if for example the whole document body is set to fullscreen with `me.device.requestFullscreen(document.getElementsByTagName("body")[0]);`. It should just check if a fullscreenElement is currently set or not.

**Comment by parasyte** [comment]
https://github.com/melonjs/melonJS/blob/285df7570af71d749a87493c7702dd3642ff9481/src/system/device.js#L787

**Comment by obiot** [comment]
unless i'm mistaken that's what we do (see link above).  we can re-open if misunderstood.

**Comment by parasyte** [comment]
Reopened. :) The link I provided was corroboration of the bug. We should change this line as suggested in the OP.

**Comment by obiot** [comment]
really, i'm not getting what's wrong then..... what we do is check on which element fullscreen is set, and then return true if on the canvas (on which we did set it initially)  else we return false

we can just return `!!(el)` but I don't the see the difference to be honest

**Comment by paseonline** [comment]
In our project we were using this to set the whole body to fullscreen because we had other elements outside of the video wrapper that should be visible in fullscreen too. If you check for the video wrapper only, fullscreen will not be recognized in this case. If the function should only work for the video wrapper, then the possibility to set any element to fullscreen should not be given.

**Comment by obiot** [comment]
that should do it ! :)
