### ISSUE TITLE
Various issues with debugPanel show/hide key bindings

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#883]
The debugPanel appears to support configurable key bindings, but I can't seem to understand how this is expected to work. The plugin is registered *without passing any custom key bindings*, so it always binds the default keys `S` and `H`. This has some implications:

* The platformer example binds `S` to the down arrow (part of the WASD control scheme)
    * Pressing `S` to drop from a platform causes the debugPanel to appear
    * It does not seem to be possible to change the debug panel key bindings for the platformer example
* The debugPanel `onDestroyEvent` always unbinds the `S` and `H` keys, regardless of the configuration (!)

**Comment by parasyte** [comment]
Also, I think it would be handy to have a "toggle" type of key configuration. So I can bind tilde and use it to toggle the debugPanel on/off. Kind of like a real game, you know?

**Comment by obiot** [comment]
@parasyte done, however it seems like the ~ key cannot be used... whatever i tried I could not get it to work (if you want to give it a try on your side).

also, now only one key is use (`s` by default) to show/hide the panel, and it's configurable through a URL parameter :  e.g. `http://myURL/index.html#debugToggleKey=d`

**Comment by parasyte** [comment]
@obiot Cool! I left a comment which may help explain why tilde was not working?

**Comment by obiot** [comment]
thanks :)
