### ISSUE TITLE
Stale example for input "edge" detection?

### ISSUE THREAD

**Issue by emarcotte** [melonjs/melonJS#886]
Hi there,

I'm trying to use me.event.subscribe to get key events, rather than poll in my update functions. https://melonjs.github.io/melonJS/docs/me.event.html#KEYDOWN suggests that I should be able to bind edge triggers and then check the "edge" flag as the third argument to the subscription callback.

This doesn't seem to work, when I look through the code it looks like the only place that actually sets `KeyLocked[action]` to a true value is in `isKeyPressed`.

If you take the sample on the page and add an extra call to isKeyPressed(action) and ignore its result you get something closer to the desired behavior.

Should the subscription callback wrapper set `KeyLocked[action] = true` after processing all subscribers?

Thanks for your consideration,
Eugene

**Comment by parasyte** [comment]
That's a good point. Sounds like we need a better way to automate the event listener model.

**Comment by obiot** [comment]
See https://github.com/melonjs/melonJS/commit/3393536d8500ea801d1c0515b2c59849ec128d5b
