### ISSUE TITLE
pointerdown not working in Android in version used in Boilerplate

### ISSUE THREAD

**Issue by drbobrinkman** [melonjs/melonJS#887]
I'm using
me.input.registerPointerEvent("pointerdown", me.game.viewport, function (event) {
	        me.event.publish("pointerdown", [ event ]);
	});
to catch and publish events. See https://raw.githubusercontent.com/drbobrinkman/ld38-game/1805ad41964bec8ddc21ead6009d4184bf3f9e71/js/screens/play.js

I have two android devices: Samsung Galaxy S8 running Android 7, and Asus Nexus 7 (2013) running Android 6.0.1. In both cases the "pointerdown" events don't seem to be happening. It is working both in Chrome on my Mac and in Safari in iOS on my iPad Mini 3.

I have verified that all other events (pointerup, pointerenter, pointerleave, pointermove) are working as expected in Android. Only pointerdown is malfunctioning.

I have not found the problem yet, though. I'll keep looking, but maybe not until after LD38 is over.

This report only applies to the version of MelonJS included in the current version of boilerplate. I have not had time to check if it is fixed in the latest version.

**Comment by agmcleod** [comment]
Hey thanks for reporting. Yeah i think this is a regression from some of the input re-working I did a bit ago. I'm running a pre dev version of 4.0 for my game, and pointer events do work on android there.

**Comment by agmcleod** [comment]
Google Chrome on Android over Mobile Safari supports PointerEvents. So what happens in MelonJS 4+ is that it binds both pointer events & touch events. This is to support devices that might have dual inputs. Mouse & touch screen for example. In this case android seems to fire the pointerenter event, but not the pointerdown. Where as when it only had the touch events in MelonJS 3, it would fire the touchstart (which we map to the pointerdown name).

**Comment by parasyte** [comment]
hmmmm, Listen for all events and de-dupe as necessary? :) I don't know if UAs are supposed to reuse event IDs to make de-duping easier. But we can always use a timer-based approach; when similar events fire within ~10ms of each other, just ignore the second one.

**Comment by agmcleod** [comment]
@parasyte maybe. Right now the idea of pointerenter and pointerdown are separate. Which makes sense, as on desktop pointerenter works the same as mouseenter. You don't have to hold down to trigger it.

We could do what you said, essentially let pointerdown handle both, and only execute whichever comes first. Just sounds hacky, and potentially buggy on desktop.

**Comment by obiot** [comment]
looking a bit on what could be wrong here :
https://github.com/melonjs/melonJS/blob/master/src/input/pointer.js#L470

should this line rather test `event.pointerId`  ? just wondering on platform that is compatible with both events type if there is some kind of hybrid events with both pointerEvent and Touch properties (or if they are two event generated).

**Comment by obiot** [comment]
I managed to test 2 games on android, and could not reproduce this issue.... so I'll assume this was fixed somehow, maybe through this commit : https://github.com/melonjs/melonJS/commit/d9bea57ca19511e87738e29349cd9d7cd657e3e0

**Comment by agmcleod** [comment]
It's possible an OS update fixed it.

**Comment by obiot** [comment]
oh yes, and several times, ahahahah :)

**Comment by agmcleod** [comment]
![image](https://user-images.githubusercontent.com/113275/33024483-3322d7e2-cdd9-11e7-8031-2ac2b81584ea.png)

**Comment by obiot** [comment]
:P:P:P:P
