### ISSUE TITLE
Configure Travis CI to use headless Chrome for tests

### ISSUE THREAD

**Issue by kibertoad** [melonjs/melonJS#894]
See https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode

Then Chrome could be used as a default engine for executing tests, PhantomJS dropped and ES6 used to write tests :).

**Comment by obiot** [comment]
I'm definitely for it, we had issues in the past with phantomJS not supporting few features, and if we can have a full fledge (headless) chrome, that then allow us to have ES6 test, and I'm all for it !

**Comment by kibertoad** [comment]
@obiot It'd need someone with access to the Travis account for melonJS, though. From sources side the only change needed is swapping PhantomJS to ChromeHeadless in grunt file.

**Comment by obiot** [comment]
actually you don't, as all the magic happen in the [travis.yml](https://github.com/melonjs/melonJS/blob/master/.travis.yml) file.

**Comment by obiot** [comment]
love the nyan cat by the way :)
````javascript
10 07 2017 10:40:12.530:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket MybWDp60p6FCag5AAAAA with id 52316809
 292 -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_,------,
 283 -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|   /\_/\
 0   -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-^|__( o .o)
 9   -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-  ""  ""

     292 total   283 passed   0 failed   9 skipped
````

**Comment by obiot** [comment]
also when switching to ChromeHeadless, the following errors needs to be addressed :
````javascript
Failed Tests:
 ES6 Collections test
    Map#set
       Chrome 59.0.3071 (Windows 10 0.0.0)
          1) Expected true to equal false.
             at Object.<anonymous> (tests/spec/es6-collections.js:163:22)

    Map#forEach with mutations
       Chrome 59.0.3071 (Windows 10 0.0.0)
          2) Expected undefined to equal '[1,3,0]'.
             at Object.<anonymous> (tests/spec/es6-collections.js:260:39)


 me.input
    Pointer Event
       PointerDown event triggering
          Chrome 59.0.3071 (Windows 10 0.0.0)
             3) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.


     292 total   285 passed   3 failed   4 skipped
````
for the mouse input one it's pretty easy we just need to replace `mousedown` by `pointerdown` [here](https://github.com/melonjs/melonJS/blob/master/tests/spec/input-spec.js#L37).

for the es6 collections, it's a bit more tricky. Either we remove the corresponding test, or we modify the outdate polyfill to comply with the latest ES6 Specifications (which I personally believe is a waste of effort)

**Comment by obiot** [comment]
last change to autodetect the testing environment and fix the input test (so that we don't need to keep changing the test between phantomjs and chrome)

**Comment by obiot** [comment]
unless anyone else ( @parasyte , @agmcleod ) it's ready to fully switch to ChromeHeadless for automated testing :)

**Comment by obiot** [comment]
enabling Chrome in Travis way more difficult than I initially thought, so I reverted for now to PhantomJS (no more extra time for me to test today)

few results I found and tried to apply :
https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
https://unix.stackexchange.com/questions/176980/please-set-env-variable-chrome-bin
https://github.com/travis-ci/travis-ci/issues/938

**Comment by obiot** [comment]
FYI I initially followed the below steps :
https://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647

but there is a issue with the "latest" travis environement and sandboxing that prevent it from working

**Comment by obiot** [comment]
the missing bit was `sudo: required` in the travis.yml file to make it work with Sandboxing.

Chrome is starting now and karma running but 2 tests are failing under the travis environement, and the end of the log is missing, so I'm not able to see which one .....

here is copy/paste of the last lines :
````javascript
292
 265
 2
 4
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
-_-_-_-_-_-
````
no idea though how to get the end of the log....

**Comment by obiot** [comment]
log problem solved

**Comment by obiot** [comment]
so Chrome working, but 2 tests are failing (so I left it using PhantomJS for now), 

Left to do  : identify the failing tests and assess the issue + solution. signing out on my side for today, I reaaaaaaaalllly have to run

**Comment by obiot** [comment]
interesting ...
 Failed Tests:

1st issue, again with the polyfill :
````
ES6 Collections test
WeakMap constructor behavior
Chromium 37.0.2062 (Ubuntu 0.0.0)
Expected false to equal true.
at Object.<anonymous> (tests/spec/es6-collections.js:35:22)
````

2nd one is weirder though, seems like the float precision is different, leading to a slightly different value on Linux/Chromium
````
Shape : me.Polygon
Isometric transformation
shape should have an isometric diamond shape
Chromium 37.0.2062 (Ubuntu 0.0.0)
Expected 31 to equal 32.
at Object.<anonymous> (tests/spec/polygon-spec.js:94:41)
````

**Comment by obiot** [comment]
second issue is fixed

for the first, no idea so far on why the weakmap constructor fails on Chromium :
https://github.com/melonjs/melonJS/blob/master/tests/spec/es6-collections.js#L35

@parasyte @agmcleod @kibertoad in case you have any idea.... :P 

this is the very last thing to fix, and then we can fully switch to Chrome!

**Comment by obiot** [comment]
issue seems to be that with the current script Chromium 37 is installed
````javascript
 LOG MESSAGES FOR: Chromium 37.0.2062 (Ubuntu 0.0.0) INSTANCE #: 35999929
    'Initializing melonJS'
````

have not succeed yet to make it install the latest version, and it's kind of difficult to test everytime.... lunch time !

**Comment by obiot** [comment]
job done !
````javascript
13 07 2017 05:03:39.061:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
13 07 2017 05:03:39.063:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
13 07 2017 05:03:39.073:INFO [launcher]: Starting browser ChromeHeadless
13 07 2017 05:03:41.754:INFO [HeadlessChrome 0.0.0 (Ubuntu 0.0.0)]: Connected on socket JXLIE6HeptKA6X1VAAAA with id 83669012
 292
 288
 0
 4
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
-_-_-_-_-_214m-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
292 total288 passed0 failed4 skipped
 LOG MESSAGES FOR: HeadlessChrome 0.0.0 (Ubuntu 0.0.0) INSTANCE #: 83669012
    'Initializing melonJS'
Done.
````
Unit tests are now using chrome headless  ! 

Interesting exercise, I learned a lot, just by switching from phantomJS to Chrome :)

**Comment by parasyte** [comment]
Wow!

One concern; Chrome 37 is ancient. It's not much better than the ancient WebkitQT in PhantomJS.

**Comment by obiot** [comment]
Chrome 59 is the one currently installed with the Trusty distribution, so aaaall gooood! :)
