### ISSUE TITLE
Support "Collection of Images" tilesets (Tiled 0.10)

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#895]
This feature was implemented [way back in 2012](https://github.com/bjorn/tiled/pull/261) and never hit our radar. The incompatibility was reported to us on gitter. The reporter provided a TMX tileset as created by Tiled, and a hand-edited tileset that works in melonJS.

Does not work, generated by Tiled 1.0.2:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tileset name="blank" tilewidth="132" tileheight="99" tilecount="1" columns="0">
 <tile id="0">
  <image width="132" height="99" source="../img/landscapeTiles_075.png"/>
 </tile>
</tileset>
```

WORKS, but hand-edited from above markup:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tileset name="blank" tilewidth="132" tileheight="99" tilecount="1" columns="1">
 <image source="../img/landscapeTiles_075.png" width="132" height="99"/>
 <tile id="0">
  <objectgroup draworder="index" name="blank">
   <object id="0" x="0" y="0" width="132" height="99"/>
  </objectgroup>
 </tile>
</tileset>
```

Additional comments:

> Grey @GreyDev Jul 15 15:42
> okay so I produced a small tiled map and filled it with a single tile type. The tile is a single image in the data/img directory. I then exported the .tsx and .tmx from Tiled 1.0.2 and put both in the data/map directory.

**Comment by obiot** [comment]
Done, but I must say that I would highly discourage the use of this feature, as this won't allow texture size/packing/optimization on mobile devices.

**Comment by obiot** [comment]
@Grey better later than never :P
