### ISSUE TITLE
[WebGL] deprecated arguments for texImage2D

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#896]
reported by Firefox :
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. [melonjs.js:17741:17](https://github.com/melonjs/melonJS/blob/master/src/video/webgl/shader.js#L196)

The error is from within the shader class, when creating textures :
https://github.com/melonjs/melonJS/blob/master/src/video/webgl/shader.js#L196

**Comment by rofrol** [comment]
Might be relevant:

- https://github.com/mapbox/mapbox-gl-js/issues/5292
- https://bugzilla.mozilla.org/show_bug.cgi?id=1400077
