### ISSUE TITLE
the location of the me.Sprite is also changed

### ISSUE THREAD

**Issue by cubemoon** [melonjs/melonJS#899]
After calling the scale method, the position of the me.Sprite is also changed

**Comment by obiot** [comment]
Which version of melonJS?

**Comment by cubemoon** [comment]
v4.1.1

**Comment by obiot** [comment]
can you try with the last (5.0) build :
https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2071/build/

API wise there should be no breaking changes, so just a quick replacement :
https://github.com/melonjs/melonJS/wiki/Upgrade-Guide

**Comment by cubemoon** [comment]
It should be anchored by the center point.
Scale around the center
