### ISSUE TITLE
In Platformer tutorial the "renderable" of the "Player" entity flips based on left boundary instead of the middle axis

### ISSUE THREAD

**Issue by zosiakropka** [melonjs/melonJS#916]
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Mac OS 10.11.6 / Chrome 63.0.3239.132
 
#### melonJS version 
v5.0.1

This bug doesn't occur in MelonJS 4.*.

#### Bug description  
Having a game implemented according to the [Platformer tutorial](http://melonjs.github.io/tutorial-platformer/), I can see the Player character flipping far to the left - the left boundary of the Player's `renderable` is used as the flip axis (instead of the middle axis of it).

The character is rendered incorrectly only when walking to the left. Walking to the right is ok.

Example from platformer tutorial, walking to the right - ok:
<img width="360" alt="melon_flipx_tutorial_step3_right" src="https://user-images.githubusercontent.com/3936494/35018183-a3789a26-fb20-11e7-8e0e-3628fe72aa85.png">
Example from platformer tutorial, immediately after pressing left arrow *once*:
<img width="369" alt="melon_flipx_tutorial_step3_left" src="https://user-images.githubusercontent.com/3936494/35018184-a3a0fbf6-fb20-11e7-8278-94dd27202d27.png">
Own implementation, with debug, walking to the right - ok:
<img width="400" alt="melon_flipx_own_implementation_debuggable_right" src="https://user-images.githubusercontent.com/3936494/35018185-a3bf4282-fb20-11e7-9994-3ea8d9af5fcc.png">
Own implementation, with debug, immediately after pressing left arrow *once*:
<img width="408" alt="melon_flipx_own_implementation_debuggable_left" src="https://user-images.githubusercontent.com/3936494/35018186-a3ddd5e4-fb20-11e7-8fc7-d7e5c64c34db.png">

#### Steps to reproduce the bug
Prerequisites:
1. Clone the platformer tutorial https://github.com/melonjs/tutorial-platformer/tree/81c29f6/ (81c29f6 is the most current revision as of today).
2. Replace `tutorial_step3/lib/melonJS.js` in the tutorial files with the most current MelonJS lib (v5.0.1).
2. Serve from the `tutorial-platformer` repository root
3. Open game (the modified step of the tutorial) in a browser (eg. `http://localhost:8081/tutorial_step3/`)

Steps:
4. Walk to the left.
Expected: The renderable associated with `Player` should flip in place
Actual: The renderable associated with the `Player` entity immediately jumps by 64px to the left compared to where it should stay

#### Console log Extract 

No errors here:

```
127.0.0.1:8081/tutorial_step3
melonJS.js:17940 Spritesheet Texture for image: http://127.0.0.1:8081/tutorial_step3/data/img/map/area01_level_tiles.png is not divisible by 32x32, truncating effective size to 640x224
parseFromSpriteSheet @ melonJS.js:17940
init @ melonJS.js:17843
Class @ melonJS.js:326
get @ melonJS.js:17072
init @ melonJS.js:23889
Class @ melonJS.js:326
readTileset @ melonJS.js:25339
(anonymous) @ melonJS.js:25507
readMapObjects @ melonJS.js:25505
getLayers @ melonJS.js:25739
addTo @ melonJS.js:25585
loadTMXLevel @ melonJS.js:25855
safeLoadLevel @ melonJS.js:25805
me.levelDirector.api.loadLevel @ melonJS.js:25991
onResetEvent @ play.js:8
reset @ melonJS.js:13216
_switchState @ melonJS.js:13379
setTimeout (async)
Function.defer @ melonJS.js:237
me.state.api.change @ melonJS.js:13815
loaded @ game.js:55
(anonymous) @ melonJS.js:14104
setTimeout (async)
checkLoadStatus @ melonJS.js:14103
(anonymous) @ melonJS.js:14114
setTimeout (async)
checkLoadStatus @ melonJS.js:14113
me.loader.api.preload @ melonJS.js:14499
onload @ game.js:33
onReady @ (index):39
me.device.api._domReady @ melonJS.js:2366
```

**Comment by obiot** [comment]
Hi,

thank you very much for the report.  In the 5.x branche we slightly [changed](https://github.com/melonjs/melonJS/blob/master/CHANGELOG#L39-L40) (or shall I rather say fixed) the way renderable are drawn to correctly take in account their anchor point, and I think that the problem here is that the tutorial has not been updated to reflect it. 

Furthermore when using Tiled, and since Tiled uses top-left coordinates, the anchor point is manually forced to [0, 0], which does not help !

Therefore, if you add the following in your entity constructor, it should all be back to "normal"
```javascript
// set the renderable position to bottom center
this.anchorPoint.set(0.5, 1.0);
```
Note that this is what we do in the platformer [example](http://melonjs.github.io/melonJS/examples/platformer/) (source [here](https://github.com/melonjs/melonJS/blob/master/examples/platformer/js/entities/player.js))

**Comment by zosiakropka** [comment]
Thanks!

*The line you shared solved the problem!*

Previously I tried setting the `anchorPoint` on `renderable` associated with an entity, but I haven't tried setting `anchorPoint` on entity directly. Probably this is the reason that it was immediately overwritten with `0,0`.

Thanks again!

**Comment by obiot** [comment]
I'll take the point to update the tutorial and add this :)

**Comment by delphian** [comment]
Thank you so much for the fix! I've been trying to figure out what I'm doing wrong for the last few hours.
