### ISSUE TITLE
Please support for wx small game.

### ISSUE THREAD

**Issue by qichunren** [melonjs/melonJS#917]
I love beautiful & light weight melonJS.

Wx small game is running in embed custom js runtime. There is no DOM.  It use JavaScriptCore in iOS platform. and V8 in android.

There is only a custom canvas object for developer to render game objects.

Wx small game load game js files use CommonJS style:

Need use "module.exports" in melon js lib to export API.

Then in game.js  script:

require('./melonjs')

https://mp.weixin.qq.com/debug/wxagame/dev/index.html?t=2018115

**Comment by obiot** [comment]
Hi and thank you !

If I'm correct there are 2 requests here : 
1. support the wx api ;  for example they have a proprietary create canvas method
2. support modules, this is in the plan for the 6.0.0 branch (see as well #915)

am I correct?

**Comment by qichunren** [comment]
I test melonJS  v5.1.0 on WX small game platform v1.02.1801081 on MAC, currently, I failed to run a demo on it.

There are some problems currently I found in melonJS.

1. Property and functions from window object should not be used, there is no DOM in WX runtime. Such as 'scroll' and 'hash' I found currently.

2. Canvas init should invoke "wx.createCanvas()"

3.  

```
JSON.parse(localStorage.getItem("me.save")) || [];
```
failed when empty value.


3.  
```
accumulator += me.timer.getDelta();   
````
var accumulator will negative when it too big, this cause game objects not invoke update method.

After I fixed above problems, I still see no game stage created, it is just blank screen. There is no error in consle. But I think the game engine update cycleing is running OK, maybe some problem related about render.



I will later send PR later maybe.

**Comment by obiot** [comment]
@qichunren hi I saw you closed the PR, are you still working on it or you given up ?

**Comment by qichunren** [comment]
@obiot My PR currently based on master branch, I will later edit my PR to fork from 5.x.x after fixed game render working.

Currently I have fixed blank screen display on game stage. But there is some problem about  game rect height

**Comment by obiot** [comment]
Awesome ! 

That’s weird about the game rect, did you try to disable scaling to see if maybe this is related ?

**Comment by obiot** [comment]
@qichunren  any update ? I'm ok if you want to submit a partial support through a PR (on the 5.x branch), always good to have something in, and can be completed later (would be sad to lose all the effort you put into this so far)

**Comment by obiot** [comment]
https://medium.com/@yelin.qiu/a-complete-manual-on-wechat-mini-program-development-8fd28a85ee0d

**Comment by obiot** [comment]
@qichunren Hi, with the changes I reported here from your PR, and the use of the webapp-adapter for WeChat [here](https://github.com/loryxia/weapp-adapter), melonJS should now properly work with melonJS.

it would really be great and highly appreciated if you could take the time to test again on your side and confirm it :)

**Comment by obiot** [comment]
Forgot to mention that all changes are on the master branch now, due soon to release as the 6.0.0 version

**Comment by qichunren** [comment]
Still not work. Screen is black, nothing display. Here is a demo for testing. https://github.com/qichunren/wx-game-demo

**Comment by obiot** [comment]
oh ok.... going through your original PR, I just found out which one I forgot !

the one testing for `(image instanceof HTMLImageElement) || (image instanceof HTMLCanvasElement)`
https://github.com/melonjs/melonJS/pull/918/commits/a7da7a6c839e1b8d1bf12bd2816aad643040681b#diff-d7ffbb8623ab3acfee330c37574b7a33R700

**Comment by qichunren** [comment]
Still black screen with no error message in console.

**Comment by qichunren** [comment]
From doc [adapter](https://developers.weixin.qq.com/minigame/dev/tutorial/base/adapter.html), weapp-adapter will create a global Canvas object named 'canvas' when it required.
```
require('./weapp-adapter')
var context = canvas.getContext('2d')
context.fillStyle = 'red'
context.fillRect(0, 0, 100, 100)
```

So I changed code in melonjs.js, it work:

```
            // defined the 2d context
            // this.context = this.getContext2d(this.canvas, this.transparent);
            this.context = canvas.getContext('2d');
```

May this help you.

**Comment by obiot** [comment]
Definitely yes ! Probably i’ll check if a global canvas is available at that point :
https://github.com/melonjs/melonJS/blob/master/src/video/video.js
And do something like canvas = window.canvas, just to avoid touching the createCanvas function.

I’ll do another commit later with that.

**Comment by obiot** [comment]
@qichunren can I abused of your kindness and ask you to test with the latest change ?

also, would you mind testing with the `doubleBuffering` video setting set to `true` and `false` to see how it works as well ?

thank you very much !

**Comment by obiot** [comment]
ok, here is the state of the art concerning WeChat :
- JSON and other binary files require a full URL (relative path does not work, as WeChat throws a `invalid URL` error)
- there is no audio for now, see https://github.com/goldfire/howler.js/issues/983
- Canvas renderer is forced for now, as the WebGL is not properly working, see https://github.com/melonjs/melonJS/issues/933

but so basically, except for the audio, this is mostly working now after the two last commits from today !

**Comment by obiot** [comment]
I'm gonna close this "generic ticket", we can then manage left open points through the relevant tickets (basically the audio one).

**Comment by obiot** [comment]
Wiki updated :
https://github.com/melonjs/melonJS/wiki/How-to-deploy-WeChat-Mini-Games-with-melonJS

I also noticed that the official weapp-Adapter (https://github.com/finscn/weapp-adapter) had some improvements related to Audio, which means that Howler might just work now :)

**Comment by obiot** [comment]
@qichunren let me know if you are actually porting any melonJS games on WeChat :)

and again, thank you again for your help !
