### ISSUE TITLE
Broken link in tutotial http://melonjs.org/en/home/platformer

### ISSUE THREAD

**Issue by ensonic** [melonjs/melonJS#929]
Under 'Try it out' the link points to http://melonjs.org/en/home/tutorial_step2/index.html which yields:

    The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by ensonic** [comment]
Someone seems to have fixed it in the mean time. I came from the official tutorial

**Comment by obiot** [comment]
yes I did that, all made on purpose, transitioning to another hosting server.

**Comment by obiot** [comment]
> I went to
http://melonjs.org/#getting-started
http://melonjs.org/en/home/platformer
and there it fails. But going there from github works.

indeed through that path there are some issues, thanks !

**Comment by obiot** [comment]
closing this one, and opened it to the tutorial repo
