### ISSUE TITLE
proporsal logo for melonJS 

### ISSUE THREAD

**Issue by anablog** [melonjs/melonJS#938]
Hi a pleasure in greeting you, I wanted to introduce myself I am Ana Medina Graphic Web Designer, I am very interested in your new open source project for me it would be a pleasure to provide my services as a designer and collaborate without commitments, You require a new logo for your brand I can help him?

I will be pleased to collaborate with you.

**Comment by obiot** [comment]
hi, thanks for your proposition, but we are not interested for now.
