### ISSUE TITLE
Add search feature in the documentation

### ISSUE THREAD

**Issue by vibrantrida** [melonjs/melonJS#940]
Clicking around the documentation to find what you are looking for can get cumbersome especially if you already know what you are looking for but forgot which class or namespace it is under.

A client-side search functionality in the API documentation would be nice.

**Comment by papovslava** [comment]
use google and specify site
example
me.save site:melonjs.github.io/melonJS/docs

**Comment by obiot** [comment]
actually I wanted to switch to TUI JSDoc Template, that does provide a search box :

https://nhnent.github.io/tui.jsdoc-template/latest/

**Comment by obiot** [comment]
FYI, here is the new look&feel of the documentation, and that includes now a search feature !
![screenshot 2019-02-01 at 12 44 55 pm](https://user-images.githubusercontent.com/4033090/52103195-7cbb4480-261f-11e9-85c4-b5897b866c20.png)

still playing with/tweaking the colors, but so far I;m pretty happy with the result :)

**Comment by obiot** [comment]
this one is done and done :) closing this ticket !

**Comment by dwkrueger2** [comment]
Nice
