### ISSUE TITLE
What version of NodeJS is required to use melonJS or the Boilerplate?

### ISSUE THREAD

**Issue by ogrotten** [melonjs/melonJS#948]
If it's in the docs or elsewhere, a pointer would be enough and then I'll go read it, but I've not seen in the docs anywhere the minimum (or maximum) version of Node required for using Melon. 

Further, all the tutorials use the Boilerplate, which requires node, and the Boilerplate readme also doesn't give version specs. 

I'm not building a custom Melon, but I do plan on Android export.

**Comment by papovslava** [comment]
use current LTS version https://nodejs.org/en/download/. 
i'm using v8.10.0 from official ubuntu linux repo

**Comment by obiot** [comment]
you can either use node 8 or 10 (pretty sure previous versions are working as well, but at this point of time there is no point using them) 
https://github.com/melonjs/melonJS/blob/master/.travis.yml#L6-L8
