### ISSUE TITLE
Support for http/2 (h2, spdy)

### ISSUE THREAD

**Issue by geNAZt** [melonjs/melonJS#953]
It seems melonJS does not have support for h2 currently. Building in a "virtual" resource type like "h2package" would be nice since the server could push all resources needed in "one" request via h2 without the need of more requests through a h2 pipeline. This would reduce the load of the default example (isometric_rpg) from ~380ms to ~25ms. All further requests to the other resources would be loaded from the h2 push cache into the browser cache, thats why load times are improving so much.

I can also implement that feature if wanted, just wanted to ask if there is a feature for that already in the pipeline or not :)

Sources:
<img src="https://i.imgur.com/cyBUYbV.png" />

**Comment by obiot** [comment]
Hi, I'm not sure to understand what should be done on melonJS side to be honest... is it just not at th e end about how the server/backend is "serving" those assets ?

**Comment by geNAZt** [comment]
Yes, but a call to any 200 response would trigger a server push. So all it would need is a request with basicly no response (except a 200 http status)

This would result to this (i have configured a /resource/bundle/init "bundle" pushing the resources down):

<img src="https://i.imgur.com/sXWpvRF.png" />

**Comment by obiot** [comment]
@geNAZt Hi, this ticket is still open and I am still confused on what is missing to be honest, if you could you help better understand :)
