### ISSUE TITLE
TMXHexagonalRenderer - rendering issue with Staggered maps

### ISSUE THREAD

**Issue by digitalbreed** [melonjs/melonJS#966]
#### OS platform / Browser  
(irrelevant)
 
#### melonJS version 
6.0.0

#### Bug description  
`TMXHexagonalRenderer` does not honour `renderorder` property.
In Tiled (1.2.2), you can specify the "Tile Render Order" property, as certain tile-sets require rendering from bottom to top and/or from right to left.
Tiled screenshot:
<img width="303" alt="screenshot 2019-02-03 at 14 13 46" src="https://user-images.githubusercontent.com/826466/52177731-d8bfcd80-27c5-11e9-8c06-7df0e1257c24.png">
melonjs rendering screenshot:
<img width="306" alt="screenshot 2019-02-03 at 15 09 57" src="https://user-images.githubusercontent.com/826466/52177736-e83f1680-27c5-11e9-993f-14d197d5b289.png">

#### Steps to reproduce the bug
Create a map with "Left Up" tile render order, e.g. using CuddlyLover's excellent Fantasy Hex Tiles: https://cuddlyclover.itch.io/fantasy-hex-tiles - observe that tiles are rendered in the wrong order with melonjs.
Relevant code: https://github.com/melonjs/melonJS/blob/master/src/level/TMXRenderer.js#L693
Interestingly enough, the orthogonal renderer has support implemented: https://github.com/melonjs/melonJS/blob/master/src/level/TMXRenderer.js#L219

#### Console log Extract 
(irrelevant)

**Comment by obiot** [comment]
happy to fix it, but I'm confused though, as it's supposed to be only supported by orthogonal maps:  https://doc.mapeditor.org/en/stable/reference/tmx-map-format/?highlight=renderorder

and I do not see anything in the 1.2.2 changelog that this was changed...

**Comment by digitalbreed** [comment]
I guess the documentation is not up to date then:

<img width="1023" alt="screenshot 2019-02-04 at 10 30 15" src="https://user-images.githubusercontent.com/826466/52200057-03626280-2868-11e9-83c5-9da191347381.png">

From world.tmx:

```<?xml version="1.0" encoding="UTF-8"?>
<map version="1.2" tiledversion="1.2.2" orientation="hexagonal" renderorder="left-up" width="100" height="100" tilewidth="32" tileheight="28" infinite="0" hexsidelength="16" staggeraxis="x" staggerindex="odd" nextlayerid="2" nextobjectid="1">```

**Comment by obiot** [comment]
very interesting :)

looking at Tiled source code, I can see the render order being used in the Orthogonal renderer :
https://github.com/bjorn/tiled/blob/master/src/libtiled/orthogonalrenderer.cpp#L295

but not in the Hexagonal one :
https://github.com/bjorn/tiled/blob/master/src/libtiled/hexagonalrenderer.cpp#L269

but I'll look at it anyway :P 

any chance you can upload here a small zip with an small example demonstrating the order issue (it's just easier/faster to get started rather)

**Comment by obiot** [comment]
so finally looking closer at this one, I can confirm now that the issue is not linked to drawing order. 

I did actually add it, but that did not changed anything at all, and looking at the current code renderer and Tiled's (as a reference) I beleive the issue is related to staggered map, comparing both implementation, it's kind of obvious that we are missing something (see the if/else in Tiled) :
Tiled : https://github.com/bjorn/tiled/blob/master/src/libtiled/hexagonalrenderer.cpp#L190-L228
melonJS : https://github.com/melonjs/melonJS/blob/master/src/level/TMXRenderer.js#L667-L692

unfortunately I don't have the time right now to add proper support for it, but if you want to fix/add it, that would be great !

**Comment by obiot** [comment]
for reference here is the `drawTileLayer` modified to support drawing order (if you want to give it a try) :
````javascript
    /**
         * draw the tile map
         * @ignore
         */
        drawTileLayer : function (renderer, layer, rect) {
            var incX = 1, incY = 1;

            // get top-left and bottom-right tile position
            var start = this.pixelToTileCoords(
                rect.pos.x,
                rect.pos.y,
                me.pool.pull("me.Vector2d")
           ).floorSelf();

            var end = this.pixelToTileCoords(
                rect.pos.x + rect.width + this.tilewidth,
                rect.pos.y + rect.height + this.tileheight,
                me.pool.pull("me.Vector2d")
            ).ceilSelf();

            //ensure we are in the valid tile range
            start.x = start.x < 0 ? 0 : start.x;
            start.y = start.y < 0 ? 0 : start.y;
            end.x = end.x > this.cols ? this.cols : end.x;
            end.y = end.y > this.rows ? this.rows : end.y;

            switch (layer.renderorder) {
                case "right-up" :
                    // swapping start.y and end.y
                    end.y = start.y + (start.y = end.y) - end.y;
                    incY = -1;
                    break;
                case "left-down" :
                    // swapping start.x and end.x
                    end.x = start.x + (start.x = end.x) - end.x;
                    incX = -1;
                    break;
                case "left-up" :
                    // swapping start.x and end.x
                    end.x = start.x + (start.x = end.x) - end.x;
                    // swapping start.y and end.y
                    end.y = start.y + (start.y = end.y) - end.y;
                    incX = -1;
                    incY = -1;
                    break;
                default: // right-down
                    break;
            }

            // main drawing loop
            for (var y = start.y; y !== end.y; y+= incY) {
                for (var x = start.x; x !== end.x; x+= incX) {
                    var tmxTile = layer.layerData[x][y];
                    if (tmxTile) {
                        this.drawTile(renderer, x, y, tmxTile);
                    }
                }
            }

            me.pool.push(start);
            me.pool.push(end);
        }
    });
````

**Comment by obiot** [comment]
![Screenshot 2019-04-23 at 4 17 36 PM](https://user-images.githubusercontent.com/4033090/56565598-73f06400-65b9-11e9-8eb0-2968df1bc089.png)

Staggered hexagonal map are properly rendering now :) 

(will commits all the changes soon, the time to clean-up the code)

**Comment by obiot** [comment]
@digitalbreed here is a link to the latest wip build :
https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2532/build/
would be great if you could give it a try and confirm you are also happy about it :)

thanks !
