### ISSUE TITLE
Platformer tutorial page missing links

### ISSUE THREAD

**Issue by mwoguri** [melonjs/melonJS#972]
http://melonjs.org/#getting-started links to http://melonjs.org/en/home/platformer
Here's a screenshot of the link: 
![image](https://user-images.githubusercontent.com/15451347/53293217-99f9b380-3784-11e9-834a-f9017e2f2596.png)

========
http://melonjs.org/en/home/platformer does not have links. Here's a screenshot of this page, which leaves a new user confused about where to download the data files to be able follow the tutorial:
![image](https://user-images.githubusercontent.com/15451347/53293230-c281ad80-3784-11e9-81ac-d5d458d9b1d5.png)

========
http://melonjs.github.io/tutorial-platformer/ by contrast, does have links.  Could this page be linked to instead?
![image](https://user-images.githubusercontent.com/15451347/53293235-d88f6e00-3784-11e9-823e-61a34d6d1694.png)

**Comment by obiot** [comment]
thank you very much !  looks like indeed that the main page has its own link for the tutorial... and it should indeed link to http://melonjs.github.io/tutorial-platformer/

will look at fix it asap ! (Same applies for the space invaders tutorial by the way)

**Comment by obiot** [comment]
Fixed ! :)
