### ISSUE TITLE
Scaling Moves elements around incorrectly

### ISSUE THREAD

**Issue by dwkrueger2** [melonjs/melonJS#976]
[TowerDef2-2019-03-11.zip](https://github.com/melonjs/melonJS/files/2952740/TowerDef2-2019-03-11.zip)
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Chrome 72.0.3626.121 (Official Build) (64-bit)
 
#### melonJS version 
6.3.0

#### Bug description  
Scaling of screen seems to cause elements to displace disproportionately.  Specifically Noticed that when the CSS in style.css was setting the canvas element height different from the height me.video.init call that the calculated coordinates for the game were off.

You can see in appjs.js (our starting point) we tried to programatically change the height of the element but it seems that chrome was overwritting / giving precedence to the css file settings.

#### Steps to reproduce the bug
zip file provided.
style.css
``` #screen canvas { /* coppied from the exampes/platformer */
    width:1024px;
    height: 1024px;
    margin: auto; 
```

The portion in the 'onload' that initializes the canvas element
```  onload: function () {

        // init the video
        AppJS.contentWidth = 1024;
        AppJS.contentHeight = 1024;
        if (!me.video.init(AppJS.contentWidth, AppJS.contentHeight, {wrapper: "screen" ,doubleBuffering :false, scale: "auto", scaleMethod: "stretch" }))
        {
            alert("Your browser does not support HTML5 canvas.");
            return;
        }

     
        $('#screen').width( AppJS.contentWidth);
        $('#canvas').width  (AppJS.contentWidth);
        $('#screen').height(AppJS.contentHeight);
        $('#canvas').height(AppJS.contentHeight);
        $('#footer').width (AppJS.contentWidth);
        $('#content').width  (AppJS.contentWidth);```

**Comment by obiot** [comment]
@dwkrueger2 the zip is missing the data directory :)

**Comment by obiot** [comment]
so two things :
1. internally melonJS is also using css to resize the canvas ( https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L486-L493) so if you after also try to manually change the value, for sure there is some conflicts. is it not better instead to play with the parent div size ?
2. the latest 7.0 build should also help with canvas/viewport being embedded in a complex css layout, if you can give it a try ? https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2503/build/  there is no api change between 6.3 and 7.0 (so except maybe for the plugin it should work out of the box)

last but not least, in the 7.0 I added a `me.video.renderer.updateBounds()` function that you can call yourself (when programmatically manipulating things) and that will update the internal cache position on the parent container.

**Comment by obiot** [comment]
so, I'm closing this one, the latest changes does improve the situation (tested with my own page, since data is missing in the zip here), and for the rest as I was saying this is a matter of conflicts. Fee free to reopen it if anything further, but since there has been no further comments I assume this is ok
