### ISSUE TITLE
add arguments passing to setTimeout and SetInterval

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#977]
from
````javascript
var timeoutID = me.timer.setTimeout(function, delay[, pausable]);
var intervalID = me.timer.setInterval(function, delay[, pausable]);
````

to

````javascript
var timeoutID = me.timer.setTimeout(function, delay[, pausable, param1, param2, param 3, ...]);
var intervalID = me.timer.setInterval(function, delay[, pausable, param1, param2, param 3, ...]);
````

**Comment by parasyte** [comment]
pro-tip: Functions can be [curried](https://en.wikipedia.org/wiki/Currying) in vanilla JavaScript to achieve the same effect.

```javascript
function curry(fn, ...args) {
    return () => fn(...args);
}

me.timer.setTimeout(curry(fn, param1, param2), delay);
```

**Comment by obiot** [comment]
@parasyte nice to see you are still checking on the repo :):):)

As for you comment indeed, and this is what was done (http://www.html5gamedevs.com/topic/42410-passing-closed-arguments-lto-timer/), but extending the current implmentation to match the « standard » ones is still a nice and easy addition.
