### ISSUE TITLE
Support for Tiled properties with new lines

### ISSUE THREAD

**Issue by B0sh** [melonjs/melonJS#979]
#### OS platform / Browser  
Windows 10 / Firefox latest
 
#### melonJS version 
7.0.0

#### Bug description  
MelonJS does not load tiled files which have new lines in object properties. I was attempting to have long form NPC dialog stored directly in the tiled file.

Here's the quote from the TMX Map Format (https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#properties)

> When a string property contains newlines, the current version of Tiled will write out the value as characters contained inside the property element rather than as the value attribute. It is possible that a future version of the TMX format will switch to always saving property values inside the element rather than as an attribute.

#### Steps to reproduce the bug
In tiled create an object with a property that has a new line in it. Load TMX file with melonjs. Error received below.

#### Workaround
Put `<br>` tags in the text and don't use new lines, I guess... 

#### Console log Extract 

```
TypeError: properties[property] is undefined[Learn More] melonjs.js:27092:21
    applyTMXProperties https://localhost/maps_new/lib/melonjs.js:27092
    init https://localhost/maps_new/lib/melonjs.js:27439
    Class https://localhost/maps_new/lib/melonjs.js:193
    init https://localhost/maps_new/lib/melonjs.js:27190
    forEach self-hosted:262
    init https://localhost/maps_new/lib/melonjs.js:27189
    Class https://localhost/maps_new/lib/melonjs.js:193
    readObjectGroup https://localhost/maps_new/lib/melonjs.js:29103
    readMapObjects https://localhost/maps_new/lib/melonjs.js:29335
    forEach self-hosted:262
    readMapObjects https://localhost/maps_new/lib/melonjs.js:29323
    getLayers https://localhost/maps_new/lib/melonjs.js:29531
    addTo https://localhost/maps_new/lib/melonjs.js:29370
    loadTMXLevel https://localhost/maps_new/lib/melonjs.js:29629
    safeLoadLevel https://localhost/maps_new/lib/melonjs.js:29587
    loadLevel https://localhost/maps_new/lib/melonjs.js:29759
    onResetEvent https://localhost/maps_new/js/screens/play.js:13
    reset https://localhost/maps_new/lib/melonjs.js:13433
    _switchState https://localhost/maps_new/lib/melonjs.js:13595
    _switchState self-hosted:1016
```

##### How to enable/use the console log
* Webkit (Chrome, Safari) : https://developer.chrome.com/devtools
* Opera : http://www.opera.com/dragonfly/documentation/
* FireFox : http://getfirebug.com/enable
* MS (Edge) : https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/debugger

**Comment by obiot** [comment]
nice catch ! thanks :)

**Comment by obiot** [comment]
it should be fixed (tested on my side), here is a WIP build for you to try on your side while waiting for the official release :
https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2524/build/
