### ISSUE TITLE
Staggered isometric support

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#980]
Hi, when I created a TMXTileMap with orientation "staggered", I received an error, "staggered type TMX Tile Map not supported".

According to the documentation, staggered should be supported. Why I am receiving this error?

**Comment by obiot** [comment]
as for now, melonJS only support normal isometric map, would you share your staggered isometric map on this ticket ?

**Comment by obiot** [comment]
support of staggerred isometric map has been added, maybe needs some more testing with a "production" map, but as far as I could see it works with my testing map

**Comment by obiot** [comment]
@siauderman  here is a link to the latest wip build :
https://melonjs-builds.s3.amazonaws.com/index.html?prefix=artifacts/master/2532/build/
would be great if you could give it a try and confirm you are also happy about it :)

thanks !
