### ISSUE TITLE
Question: Rect Rotation around center

### ISSUE THREAD

**Issue by millerbennett** [melonjs/melonJS#985]
Firstly - thank you for making MelonJS! This is more of a question:

I'm attempting to rotate a sprite around it's anchor point; the center of the sprite. After placing it on the stage, and applying the rotation transform, I see the sprite is rotating roughly what appears to be around the (0,0) point of the stage. Am I applying the rotation transform correctly?

Relevant snippet and GIF with visual below.

![rotate](https://user-images.githubusercontent.com/2319831/73698910-67ed1300-46b0-11ea-98df-17aada10fe8d.gif)

```javascript
game.ShipSprite = me.Sprite.extend({
    init(x, y, settings) {
        this._super(me.Sprite, 'init', [x, y , settings]);
        this.body = new me.Body(this);
        this.body.addShape(new me.Rect(0, 0, this.width, this.height));
    },
    update(dt) {
        this.currentTransform.rotate(0.01);
    }
});

game.PlayScreen = me.Stage.extend({
    onResetEvent() {
        me.game.world.addChild(new me.ColorLayer('background', '#5E3F66'), 0);
        var physicEditorContainer = new me.Container();
        const ship = new game.ShipSprite(150, 150, { width: 40, height: 100, image: 'ship' })
        physicEditorContainer.addChild(ship, 1);
        me.game.world.addChild(physicEditorContainer, 1);
    }
});
```

**Comment by obiot** [comment]
hi @millerbennett indeed shapes are rotated around their origin point and not their center. A workaround would be to translate first to the middle of the shape, rotate it and then translate back to the origin point

so something like this :
````javascript
this.currentTransform.translate(this.width /2, this.height /2);
this.currentTransform.rotate(0.01);
this.currentTransform.translate(-this.width /2, -this.height /2);
````

also to be noted that here you are just rotating the sprite itself, and not the collision shape, definitely a missing feature here, as `me.Sprite` should definitely implement a "rotate" function that does all the heavy lifting

**Comment by obiot** [comment]
also looking at your code, you are missing something in the update function as you redecorate the function you should call the parent method :
````JavaScript
update(dt) {
        this.currentTransform.rotate(0.01);
        return this._super(me.Sprite, 'update', [dt]);
    }
````

**Comment by millerbennett** [comment]
Thank you for the responses. Makes sense, I gave this a try:

```javascript
update(dt) {
    this.translate(this.width / 2, this.height / 2);
    this.rotate(0.01);
    this.translate(-this.width / 2, -this.height / 2);
    this._super(me.Sprite, 'update', [dt]);
}
```

Though there was no effect, the rotation is the same as the earlier gif. I can see why this might make sense when I compare the rotation / translate functions which don't affect the same values:

```javascript
rotate: function rotate(angle) {
    if (angle !== 0) {
    var a = this.val,
        a00 = a[0],
        a01 = a[1],
        a02 = a[2],
        a10 = a[3],
        a11 = a[4],
        a12 = a[5],
        s = Math.sin(angle),
        c = Math.cos(angle);
    a[0] = c * a00 + s * a10;
    a[1] = c * a01 + s * a11;
    a[2] = c * a02 + s * a12;
    a[3] = c * a10 - s * a00;
    a[4] = c * a11 - s * a01;
    a[5] = c * a12 - s * a02;
    }

    return this;
},

translate: function translate(x, y) {
    var a = this.val;
    a[6] += a[0] * x + a[3] * y;
    a[7] += a[1] * x + a[4] * y;
    return this;
},
```

Where translate affects a[6] and a[7] and rotate affects a[0] through a[5]. I'm doing my own research into these as well to see if I can manipulate these methods to my desired effect, but I'm also happy to try any additional ideas.

**Comment by obiot** [comment]
I'll look into it as well and will try to add a rotate function at the sprite/entity level, thanks for the feedback !

**Comment by obiot** [comment]
Hi, so few changes I added :
- now all vectors and shapes object can be rotated around a given point, with their respective rotate() method now taking an additional vector object
- me.Body now also implement a proper rotate method that will rotate all the body shapes, either around the body bounding box center (by default) or around the given point (as for a basic shapes), see an example [here](https://github.com/melonjs/melonJS/commit/847801f2dae914e8d9fe2e249cc0d07db0d92c85)

for more details on the change you can look at the commit here above, and If you want to give it a try you can use the latest WIP build here : https://melonjs-builds.s3.amazonaws.com/artifacts/master/2581/build/melonjs.js

**Comment by obiot** [comment]
this one is done
