### ISSUE TITLE
proposal for new Renderable members; isFlippedX and isFlippedY

### ISSUE THREAD

**Issue by Hectate** [melonjs/melonJS#986]
I'd like to recommend a complementary members for ``Renderable.flipX`` and ``Renderable.flipY`` methods. Specifically, a simple Boolean for each that checks the current state and returns ``true`` or ``false`` for each. As it is, I have to track that separately myself if I'm going to do something else based on the current (flipped or not) state of the sprite.

A minor quality of life improvement, but it would be welcome. It seems odd to be able to set it without being able to then check it easily as well.

**Comment by obiot** [comment]
you can actually test using `flipX === true` but I guess it would be a nice addition indeed to have a isFlippedX/Y getter :)

I'm currently putting the final touch to some other changes, but I will add this one as soon as Im done

**Comment by Hectate** [comment]
That makes sense now that I've seen the way ``jumping`` is used in the tutorial as well, but yeah it didn't match my expectations on how I expected to use it. 😆 Thanks for the info!

**Comment by obiot** [comment]
thanks for the suggestion, it has been added to the master branch :)
