### ISSUE TITLE
Complete black screen after calling me.video.renderer.resize

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#989]
Hi, I am trying to make a game where I am using melonjs to render an isometric tilemap but there is a sidebar at the side rendered in HTML so my canvas does not take up the entire screen. When the orientation changes or the browser is resized, I want the canvas to be resized as well.

However, the moment I call me.video.renderer.resize in my window resize handler, the screen irrevocably turns completely black. Calling me.video.renderer.reset does not help. Neither does calling me.game.repaint nor me.game.viewport.resize. I have tried both the WebGL and Canvas renderers, to no avail.

Does anyone know of any way to fix this?

I am using melonjs 7.1.1.

**Comment by obiot** [comment]
this should work out of the box, if you provide the div element where the canvas should be and enable automatic scaling there is no even a reason to call the resize method manually as you did

How do you initialise the display ? see below for the scaling options 
http://melonjs.github.io/melonJS/docs/me.video.html#.init

else if you upload a quick example for the staggered map, just include this part so that I can look at both :)

**Comment by siauderman** [comment]
[dunes_of_terror.zip](https://github.com/melonjs/melonJS/files/4550598/dunes_of_terror.zip)
Hi, this is my project, it uses the Quasar framework. You will need to run npm install then run quasar dev in the folder. Thanks so much for reviewing!

For the staggered map bug, just change orientation:'isometric' to orientation:'staggered' and you will discover that the staggered renderer is trying to access an array with a rowTile that is a floating point number (which returns undefined).

**Comment by obiot** [comment]
hi, sorry, I must be missing something but I'm not able to install quasar and everything, and looking at your source code it seems that the map is actually manually generated, so I cannot just take the map file and use it separately. Could you maybe just build a minimum version of it that does not rely on any external dependency, that would be much more easy for me to debug, thanks!

**Comment by siauderman** [comment]
[melonjs_test.txt](https://github.com/melonjs/melonJS/files/4563190/melonjs_test.txt)
Please rename file extension to html.

It works in Chrome if the window is not resized. On Chrome, sometimes the screen turns black when resizing and sometimes the image remains there but becomes somewhat distorted and the scrolling stops working.

In Firefox, melonjs cannot load at all (I get an error "_context is null").

**Comment by obiot** [comment]
the link gives me a 404 error, this said I don't understand what you are doing here :
```javascript
	methods:{
		resize(){
			if(this.$refs.main.clientWidth>=this.$refs.main.clientHeight){
				this.screenWidth=Math.round(0.8*this.$refs.main.clientWidth);
				this.screenHeight=this.$refs.main.clientHeight;
				this.sidebarWidth=Math.round(0.2*this.$refs.main.clientWidth);
				this.sidebarHeight=this.$refs.main.clientHeight;
				this.flexDirection='row';
			}else{
				this.screenWidth=this.$refs.main.clientWidth;
				this.screenHeight=Math.round(0.8*this.$refs.main.clientHeight);
				this.sidebarWidth=this.$refs.main.clientWidth;
				this.sidebarHeight=Math.round(0.2*this.$refs.main.clientHeight);
				this.flexDirection='column';
			}
			this.$forceUpdate();
			melonjs.me.video.renderer.resize(this.screenWidth,this.screenHeight);
			melonjs.me.game.repaint();
		},
		loaded(){
			melonjs.me.state.set(melonjs.me.state.PLAY,new play_screen());
			melonjs.me.state.transition('fade','#000000',250);
			melonjs.me.state.change(melonjs.me.state.PLAY);
		}
	},
	mounted(){
		melonjs.me.boot();
		melonjs.me.video.init(1,1,{
			wrapper:'screen',
			scale:'auto',
			scaleMethod:'flex',
			useParentDOMSize:true
		});
		this.resize();
		window.removeEventListener('resize',this.resize);
		window.addEventListener('resize',this.resize);
		melonjs.me.loader.preload(this.resources,this.loaded.bind(this));
	}
```

why not are you not just do this first :
```javascript
if(this.$refs.main.clientWidth>=this.$refs.main.clientHeight){
				this.screenWidth=Math.round(0.8*this.$refs.main.clientWidth);
				this.screenHeight=this.$refs.main.clientHeight;
				this.sidebarWidth=Math.round(0.2*this.$refs.main.clientWidth);
				this.sidebarHeight=this.$refs.main.clientHeight;
				this.flexDirection='row';
			}else{
				this.screenWidth=this.$refs.main.clientWidth;
				this.screenHeight=Math.round(0.8*this.$refs.main.clientHeight);
				this.sidebarWidth=this.$refs.main.clientWidth;
				this.sidebarHeight=Math.round(0.2*this.$refs.main.clientHeight);
				this.flexDirection='column';
			}
```
and then call video.init using the calculated this.screenWidth and this.screenHeight ?

also if you specify a div element (`screen`) here, the library will automatically resize it accordingly with the rest of the page when resizing the window

**Comment by obiot** [comment]
also, I would not call me.boot, but rather use the following :

```javascript
melonjs..device.onReady(function () {
      melonjs.me.video.init(this.screenWidth, this.screenHeight, {
	        wrapper:'screen',
		scale:'auto',
		scaleMethod:'flex',
		useParentDOMSize:true
	});
        melonjs.me.loader.preload(this.resources,this.loaded.bind(this));
}
```

**Comment by siauderman** [comment]
I've tried your suggestions and the resize is still not working. I've tried calling video.init with the screenWidth and screenHeight, called resize before initing melonjs, and used me.device.onReady instead of calling boot().

I have put the html file in a zip file instead, maybe that will work.

There are also 4 screenshots.
Screenshot 1 shows what happens when the orientation is changed to staggered instead of isometric.
Screenshot 2 shows what is displayed when running the html file initially. I can scroll around using the mouse or cursor keys.
Screenshot 3 shows what happens when I resize the window. While the screen still displays something (albeit a bit skewed - I actually don't want my graphics to be scaled which is why I chose flex), it is totally not responsive at all and I cannot scroll around.
Screenshot 4 shows what happens when the window is maximised again. Now the graphics are only displayed in 1 corner, and I still cannot scroll.
[melonjs_test.zip](https://github.com/melonjs/melonJS/files/4564298/melonjs_test.zip)

**Comment by obiot** [comment]
got it ! but interestingly, trying with the latest 8.0 build, I'm not able to reproduce any of those issues, can you try on your side as well ? here below is the latest build
[melonjs-8.0.beta.zip](https://github.com/melonjs/melonJS/files/4566943/melonjs-8.0.beta.zip)

**Comment by siauderman** [comment]
I've just tried the 8.0 build and even worse, now I get a complete black screen on isometric right from the start!

![bildo](https://user-images.githubusercontent.com/14951259/80858680-691ce480-8c8d-11ea-91e3-a725a07dfa6a.png)

Interestingly enough staggered displays stuff but the camera cannot scroll, even though my scroll events (using arrow keys) are detected.

![bildo](https://user-images.githubusercontent.com/14951259/80858706-a08b9100-8c8d-11ea-8317-5f3815bfa5fd.png)

Did you manage to get my demo running completely (including the scrolling) on the 8.0 build? Did you do anything to get it working? Am I doing something wrong?

**Comment by siauderman** [comment]
Currently what I'm doing is that when the user goes into the Play screen, I lock the screen orientation on Android and ban resizing on Electron.

Not an ideal situation.

**Comment by obiot** [comment]
I did a few changes already to the whole scaling implementation and fixed a few issues including to pointer event detection (if you see my latest commits these last days), but I have not yet been able to get your demo (as such) running. I'm still not getting why you programmatically resize the whole thing instead of using css, which should fix the whole thing in my opinion, but I keep it under my todo list for now :)

**Comment by obiot** [comment]
this now works much better with the last changes we made too ;)

and using the new `setViewportBounds` argument seems to help as well here when resizing :
```javascript
tilemap.addTo(me.game.world, true, true);
```
