### ISSUE TITLE
Staggered map cannot render

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#990]
When rendering a staggered map, I receive this error

melonjs.js?22b4:30265 Uncaught TypeError: Cannot read property '19.515625' of undefined
    at Class.drawTileLayer (melonjs.js?22b4:30265)
    at Class.draw (melonjs.js?22b4:28907)
    at Class.draw (melonjs.js?22b4:12382)
    at Class.draw (melonjs.js?22b4:13068)
    at eval (melonjs.js?22b4:2249)
    at Map.forEach (<anonymous>)
    at Object.api.draw (melonjs.js?22b4:2247)
    at _renderFrame (melonjs.js?22b4:13555)

I suspect that this is due to the tile coordinates being returned as floats instead of integers.

**Comment by obiot** [comment]
interesting ! can you share your map here so that I can give it a try and track the issue ? When support was added we used the default example provided with Tiled and it was working just fine (not sure anyone did use it since then though)

**Comment by obiot** [comment]
(sorry closed it by mistakes)

**Comment by obiot** [comment]
@siauderman  actually forgot to fix this one too, which is done now, so one more thing for you to test this weekend :):):)

**Comment by siauderman** [comment]
[melonjs_test.txt](https://github.com/melonjs/melonJS/files/5045249/melonjs_test.txt)

Hooray! It works.
