### ISSUE TITLE
Random screen freezes

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#998]
Sometimes, from time to time, the entire screen stops updating and sprites stop moving / animating. However, click events on the sprites still work (I know this because other parts of my app which are rendered by DOM which depend on click events on the sprites are still working).

This normally happens when there are a lot of sprites on-screen. Is there some internal flag that stops all updates if there are too many sprites?

**Comment by obiot** [comment]
no, but there is a internal flag that prevents the screen from being refreshed/redrawn if none of the visible objects are returning true from their update function. How is the update function of your sprite object implemented ? 

this feature is quite nice especially on low end devices, as it allows to save from refreshing a few frame refresh here and there, but it has a few quirks :P

**Comment by obiot** [comment]
Closing as this is the normal behavior, and in the latest version, a display refresh is now forced when adding/removing child from a container or to the world, or when an animated sprite is switching to the next frame.
